import { Environment } from 'libs/environment/schema'

export const env: Environment = {
  ACCESSIBILITY_LINK: 'https://passculture.accessibility',
  ALGOLIA_APPLICATION_ID: 'algoliaAppId',
  ALGOLIA_ARTISTS_INDEX_NAME: 'algoliaArtistsIndexName',
  ALGOLIA_OFFERS_INDEX_NAME_B: 'algoliaOffersIndexNameB',
  ALGOLIA_OFFERS_INDEX_NAME: 'algoliaOffersIndexName',
  ALGOLIA_SEARCH_API_PUBLIC_KEY: 'algoliaApiKey',
  ALGOLIA_SUGGESTIONS_INDEX_NAME: 'algoliaSuggestionsIndexName',
  ALGOLIA_TOP_OFFERS_INDEX_NAME: 'algoliaTopOffersIndexName',
  ALGOLIA_VENUES_INDEX_NAME: 'algoliaVenuesIndexName',
  ALGOLIA_VENUES_INDEX_PLAYLIST_SEARCH_NEWEST: 'algoliaVenuesIndexPlaylistSearchNewest',
  ALGOLIA_VENUES_INDEX_PLAYLIST_SEARCH: 'algoliaVenuesIndexPlaylistSearch',
  ANDROID_APP_ID: 'app.android',
  API_BASE_URL: 'https://localhost',
  APPLE_STORE_URL: 'https://apps.apple.com/fr/app/pass-culture/id1557887412',
  APPS_FLYER_DEV_PUBLIC_KEY: 'appsFlyerDevKey',
  BOOKING_FEEDBACK_LINK: 'https://passculture.qualtrics.com/jfe/form/SV_dcmKZrtRwVABcA6',
  BOOKING_LIMIT_EXCEEDED_URL: 'https://aide.passculture.app/hc/fr/articles/4411991975825',
  CGU_LINK: 'https://passculture.cgu',
  COMMIT_HASH: '13371337',
  CONTENTFUL_ENVIRONMENT: 'environment',
  CONTENTFUL_PUBLIC_ACCESS_TOKEN: 'accessToken',
  CONTENTFUL_SPACE_ID: 'contentfulSpaceId',
  COOKIES_POLICY_LINK: 'https://passculture.cookies',
  CULTURAL_SURVEY_TYPEFORM_ID: 'TYPEFORM_FORM_ID',
  DATA_PRIVACY_CHART_LINK: 'https://passculture.data-privacy-chart',
  DMS_FOREIGN_CITIZEN_URL: 'https://dmsforeigncitizen',
  DMS_FRENCH_CITIZEN_URL: 'https://dmsfrenchcitizen',
  DOC_CGU_URL:
    'https//docs.passculture.app/textes-normatifs/mentions-legales-et-conditions-generales-dutilisation-de-lapplication-pass-culture',
  DOC_PERSONAL_DATA_URL:
    'https://docs.passculture.app/textes-normatifs/charte-des-donnees-personnelles',
  EDUCONNECT_ALLOWED_DOMAIN: 'https://educoco_alloweddodo',
  ENV: 'testing',
  FAQ_LINK_CREDIT_V3: 'https://passculture-credit-v3.faq',
  FAQ_LINK_CREDIT: 'https://passculture-credit.faq',
  FAQ_LINK_DELETE_ACCOUNT: 'https://passculture-delete-account.faq',
  FAQ_LINK_EDUCONNECT_URL: 'https://passculture-educonnect.faq',
  FAQ_LINK_PERSONAL_DATA:
    'https://aide.passculture.app/hc/fr/articles/7047585364380--Jeunes-Traitement-des-donn%C3%A9es-utilisateurs',
  FAQ_LINK_RESET_PASSORD_EMAIL_NOT_RECEIVED: 'https://passculture-reset-password.faq',
  FAQ_LINK_RIGHT_TO_ERASURE: 'https://passculture-right-to-erasure.faq',
  FAQ_LINK_SIGNUP_CONFIRMATION_EMAIL_NOT_RECEIVED: 'https://passculture-confirmation-email.faq',
  FAQ_LINK: 'https://passculture.faq',
  FEATURE_FLIPPING_ONLY_VISIBLE_ON_TESTING: true,
  FIREBASE_API_PUBLIC_KEY: 'FIREBASE_API_PUBLIC_KEY',
  FIREBASE_APPID: 'BATCH_VAPID_PUBLIC_KEY',
  FIREBASE_AUTHDOMAIN: 'FIREBASE_APPID',
  FIREBASE_DYNAMIC_LINK_DOMAIN: 'passcultureapptesting.page.link',
  FIREBASE_MESSAGINGSENDERID: 'FIREBASE_MESSAGINGSENDERID',
  FIREBASE_PROJECTID: 'FIREBASE_PROJECTID',
  FIREBASE_STORAGEBUCKET: 'FIREBASE_STORAGEBUCKET',
  FRAUD_EMAIL_ADDRESS: 'service.fraude@test.passculture.app',
  GCP_IMAGE_COULD_STORAGE_NAME: 'localhost-storage-v2',
  GOOGLE_CLIENT_ID: 'GOOGLE_CLIENT_ID',
  GOOGLE_IOS_CLIENT_ID: 'GOOGLE_IOS_CLIENT_ID',
  GOOGLE_IOS_REVERSED_CLIENT_ID: 'GOOGLE_IOS_REVERSED_CLIENT_ID',
  GOOGLE_PLAY_STORE_URL:
    'https://play.google.com/store/apps/details?id=app.passculture.webapp&hl=fr',
  HOT_UPDATER_FUNCTION_URL: 'https://hot-updater-5zhbbjibjq-ew.a.run.app',
  IOS_APP_ID: 'app.ios',
  IOS_APP_STORE_ID: '1557887412',
  PASSCULTURE_DOWNLOAD_APP_URL: 'https://pass.culture.fr/nosapplications/',
  PRIVACY_POLICY_LINK: 'https://passculture.privacy',
  PUBLIC_URL: 'https://web.example.com',
  RESIZE_IMAGE_ON_DEMAND_URL: 'https://image-resizing-dot-passculture-metier-ehp.ew.r.appspot.com',
  SENTRY_DSN: 'SENTRY_DSN',
  SENTRY_PROFILES_SAMPLE_RATE: '1.0',
  SENTRY_SAMPLE_RATE: '1.0',
  SENTRY_TRACES_SAMPLE_RATE: '1.0',
  SITE_PUBLIC_KEY: 'SITE_PUBLIC_KEY',
  SUPPORT_EMAIL_ADDRESS: 'support@test.passculture.app',
  URL_PREFIX: 'passculture',
  WEBAPP_V2_DOMAIN: 'webapp-v2.example.com',
}
