#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

DIR=$(git rev-parse --show-toplevel)

################
## SAFE-CHAIN ##
################

command -v "safe-chain" >/dev/null 2>&1 || { echo >&2 "❌ safe-chain is not installed on the system. Follow internal knowledge base to protect against supply chain attacks."; exit 1; }

####################
## END SAFE-CHAIN ##
####################

########################
## CHECK SECRET LEAKS ##
########################

cd "$DIR"

echo "Running gitleaks..."

output=$(gitleaks git --max-archive-depth=2 --max-decode-depth=2 --staged --verbose --exit-code 1 2>&1)
status=$?

if [ $status -ne 0 ]; then
    echo -e "❌ Secrets were detected by gitleaks"
    echo -e "$output"
    exit 1
fi

############################
## END CHECK SECRET LEAKS ##
############################

# return 0-exit code
exit 0