/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import { clamp } from './clamp'

describe('clamp', () => {
  it('should return min value when value is lower than 0', () => {
    expect(clamp(-10, 100)).toBe(0)
  })

  it('should return max value when value is higher than max', () => {
    expect(clamp(120, 100)).toBe(100)
  })

  it('should return value when value is between min and max', () => {
    expect(clamp(60, 100)).toBe(60)
  })
})
