/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import { computeProgressRatio } from './computeProgressRatio'

describe('computeProgressRatio', () => {
  it('should compute percentage progress ratio', () => {
    expect(computeProgressRatio(30, 100)).toBe(30)
  })

  it('should compute steps progress ratio', () => {
    expect(computeProgressRatio(3, 9)).toBe(33.33333333333333)
  })

  it('should return 0 when max is lower than or equal to 0', () => {
    expect(computeProgressRatio(3, 0)).toBe(0)
  })

  it('should clamp ratio to 0 when value is lower than 0', () => {
    expect(computeProgressRatio(-10, 100)).toBe(0)
  })

  it('should clamp ratio to 100 when value is higher than max', () => {
    expect(computeProgressRatio(120, 100)).toBe(100)
  })
})
