/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import { getProgressText } from './getProgressText'

describe('getProgressText', () => {
  it('should return percentage text', () => {
    expect(getProgressText('percentage', 60, 100)).toBe('60%')
  })

  it('should return steps text', () => {
    expect(getProgressText('steps', 3, 9)).toBe('3/9')
  })

  it('should clamp percentage text to min value', () => {
    expect(getProgressText('percentage', -10, 100)).toBe('0%')
  })

  it('should clamp percentage text to max value', () => {
    expect(getProgressText('percentage', 120, 100)).toBe('100%')
  })
})
