/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React from 'react'
import styled from 'styled-components/native'

import { AccessibilityRole } from 'libs/accessibilityRole/accessibilityRole'
import { ColorsType } from 'theme/types'
import { TouchableOpacity } from 'ui/components/TouchableOpacity'

import { ButtonBase } from './ButtonBase'
import { ButtonColorValue, ButtonNativeProps } from './types'

export const Button = (props: ButtonNativeProps) => {
  const { onPress, onLongPress } = props

  return (
    <ButtonBase
      {...props}
      defaultAccessibilityRole={AccessibilityRole.BUTTON}
      renderContainer={({ content, isDisabled, isLoading, ...containerProps }) => (
        <ButtonContainer
          {...containerProps}
          disabled={isDisabled}
          onPress={isDisabled || isLoading ? undefined : onPress}
          onLongPress={isDisabled || isLoading ? undefined : onLongPress}>
          {content}
        </ButtonContainer>
      )}
    />
  )
}

type ContainerStyleProps = {
  backgroundColor?: ButtonColorValue
  borderColor?: ColorsType
  borderWidth?: number
  fullWidth?: boolean
  paddingVertical: number
  paddingHorizontal: number
}

const ButtonContainer = styled(TouchableOpacity)<ContainerStyleProps>(
  ({
    theme,
    borderColor,
    borderWidth,
    backgroundColor,
    fullWidth,
    paddingVertical,
    paddingHorizontal,
  }) => ({
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: theme.designSystem.size.borderRadius.m,
    paddingTop: paddingVertical,
    paddingBottom: paddingVertical,
    paddingLeft: paddingHorizontal,
    paddingRight: paddingHorizontal,
    width: fullWidth ? '100%' : 'auto',
    alignSelf: fullWidth ? 'center' : undefined,
    borderStyle: borderColor ? 'solid' : undefined,
    borderColor: borderColor,
    borderWidth: borderColor ? borderWidth : 0,
    backgroundColor: backgroundColor,
  })
)
