/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React from 'react'
import { StyleProp, TextStyle } from 'react-native'

import { ColorsType } from 'theme/types'
import { AccessibleIcon } from 'ui/svg/icons/types'

import { ButtonColors, ButtonSize, ButtonVariant } from './types'

export const getInteractiveColors = (colors: ButtonColors, isHoverActive: boolean) => ({
  backgroundColor:
    isHoverActive && colors.hoverBackgroundColor
      ? colors.hoverBackgroundColor
      : colors.backgroundColor,
  borderColor:
    isHoverActive && colors.hoverBorderColor ? colors.hoverBorderColor : colors.borderColor,
  textColor: isHoverActive && colors.hoverTextColor ? colors.hoverTextColor : colors.textColor,
  iconColor: isHoverActive && colors.hoverIconColor ? colors.hoverIconColor : colors.iconColor,
})

export const getBorderWidth = (borderColor?: ColorsType) => (borderColor ? 1 : 0)

export const getPrimaryDisabledOpacity = (variant: ButtonVariant, isDisabled: boolean) =>
  variant === 'primary' && isDisabled ? 0.4 : 1

export const getLabelText = (iconButton: boolean, wording?: string) =>
  iconButton ? undefined : wording

export const getLabelStyle = (
  textColor: ColorsType,
  fullWidth?: boolean,
  isMultiline?: boolean
): StyleProp<TextStyle> => ({
  color: textColor,
  maxWidth: '100%',
  minWidth: 0,
  flexShrink: 1,
  flexGrow: fullWidth || isMultiline ? 1 : undefined,
  flexBasis: fullWidth || isMultiline ? 0 : undefined,
  textAlign: fullWidth ? 'center' : undefined,
})

export const getSpacingGap = (hasLabel: boolean, spacing: number) => (hasLabel ? spacing : 0)

export const getTypographyForSize = (size: ButtonSize) => (size === 'small' ? 'ButtonS' : 'Button')

export const getIconSizeKeyForButton = (size: ButtonSize) =>
  size === 'small' ? 'extraSmall' : 'smaller'

export const getIconElement = ({
  icon: Icon,
  color,
  size,
}: {
  icon?: React.FunctionComponent<AccessibleIcon>
  color: ColorsType | undefined
  size: number
}) => {
  if (!Icon) return null
  return <Icon color={color} size={size} />
}
