/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import { computedTheme } from 'tests/computedTheme'
import { theme } from 'theme'

import { getButtonColors } from './Button.colors'

describe('getButtonColors', () => {
  it('should returns primary default colors', () => {
    const result = getButtonColors({
      theme: computedTheme,
      variant: 'primary',
      color: 'brand',
      transparent: false,
      disabled: false,
    })

    expect(result).toEqual({
      backgroundColor: theme.designSystem.color.background.brandPrimary,
      borderColor: theme.designSystem.color.border.brandPrimary,
      textColor: theme.designSystem.color.text.inverted,
      iconColor: theme.designSystem.color.icon.inverted,
      hoverTextColor: undefined,
      hoverIconColor: undefined,
      hoverBackgroundColor: theme.designSystem.color.background.brandPrimaryHover,
      hoverBorderColor: theme.designSystem.color.border.brandPrimaryHover,
    })
  })

  it('should returns primary disabled colors', () => {
    const result = getButtonColors({
      theme: computedTheme,
      variant: 'primary',
      color: 'brand',
      transparent: false,
      disabled: true,
    })

    expect(result.backgroundColor).toBe(theme.designSystem.color.background.disabled)
    expect(result.borderColor).toBe(theme.designSystem.color.border.disabled)
    expect(result.textColor).toBe(theme.designSystem.color.text.disabled)
    expect(result.iconColor).toBe(theme.designSystem.color.icon.disabled)
    expect(result.hoverBackgroundColor).toBeUndefined()
    expect(result.hoverBorderColor).toBeUndefined()
  })

  it('should returns secondary transparent colors', () => {
    const result = getButtonColors({
      theme: computedTheme,
      variant: 'secondary',
      color: 'brand',
      transparent: true,
      disabled: false,
    })

    expect(result.backgroundColor).toBe('transparent')
    expect(result.hoverBackgroundColor).toBe('transparent')
  })

  it('should returns secondary neutral hover colors', () => {
    const result = getButtonColors({
      theme: computedTheme,
      variant: 'secondary',
      color: 'neutral',
      transparent: false,
      disabled: false,
    })

    expect(result.hoverTextColor).toBe(theme.designSystem.color.text.brandPrimaryHover)
    expect(result.hoverIconColor).toBe(theme.designSystem.color.icon.brandPrimaryHover)
    expect(result.hoverBorderColor).toBe(theme.designSystem.color.border.brandPrimaryHover)
  })

  it('should returns primary neutral colors with inverted background and border', () => {
    const result = getButtonColors({
      theme: computedTheme,
      variant: 'primary',
      color: 'neutral',
      transparent: false,
      disabled: false,
    })

    expect(result.backgroundColor).toBe(theme.designSystem.color.background.inverted)
    expect(result.borderColor).toBe(theme.designSystem.color.border.inverted)
  })
})
