/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import { computedTheme } from 'tests/computedTheme'
import { theme } from 'theme'

import { getButtonColors } from './Button.colors'

describe('getButtonColors', () => {
  it('should returns primary default colors', () => {
    const result = getButtonColors({
      theme: computedTheme,
      variant: 'primary',
      color: 'brand',
      transparent: false,
      disabled: false,
    })

    expect(result).toEqual({
      backgroundColor: theme.designSystem.color.background.brandPrimary,
      borderColor: theme.designSystem.color.border.brandPrimary,
      textColor: theme.designSystem.color.text.inverted,
      iconColor: theme.designSystem.color.icon.inverted,
      hoverTextColor: undefined,
      hoverIconColor: undefined,
      hoverBackgroundColor: theme.designSystem.color.background.brandPrimaryHover,
      hoverBorderColor: theme.designSystem.color.border.brandPrimaryHover,
    })
  })

  it('should returns primary disabled colors', () => {
    const result = getButtonColors({
      theme: computedTheme,
      variant: 'primary',
      color: 'brand',
      transparent: false,
      disabled: true,
    })

    expect(result.backgroundColor).toBe(theme.designSystem.color.background.disabled)
    expect(result.borderColor).toBe(theme.designSystem.color.border.disabled)
    expect(result.textColor).toBe(theme.designSystem.color.text.disabled)
    expect(result.iconColor).toBe(theme.designSystem.color.icon.disabled)
    expect(result.hoverBackgroundColor).toBeUndefined()
    expect(result.hoverBorderColor).toBeUndefined()
  })

  it('should returns secondary transparent colors', () => {
    const result = getButtonColors({
      theme: computedTheme,
      variant: 'secondary',
      color: 'brand',
      transparent: true,
      disabled: false,
    })

    expect(result.backgroundColor).toBe('transparent')
    expect(result.hoverBackgroundColor).toBe('transparent')
  })

  it('should returns secondary neutral hover colors', () => {
    const result = getButtonColors({
      theme: computedTheme,
      variant: 'secondary',
      color: 'neutral',
      transparent: false,
      disabled: false,
    })

    expect(result.hoverTextColor).toBe(theme.designSystem.color.text.brandPrimaryHover)
    expect(result.hoverIconColor).toBe(theme.designSystem.color.icon.brandPrimaryHover)
    expect(result.hoverBorderColor).toBe(theme.designSystem.color.border.brandPrimaryHover)
  })

  it('should returns primary neutral colors with inverted background and border', () => {
    const result = getButtonColors({
      theme: computedTheme,
      variant: 'primary',
      color: 'neutral',
      transparent: false,
      disabled: false,
    })

    expect(result.backgroundColor).toBe(theme.designSystem.color.background.inverted)
    expect(result.borderColor).toBe(theme.designSystem.color.border.inverted)
  })

  it('should returns danger colors from button tokens for all variants', () => {
    const primaryResult = getButtonColors({
      theme: computedTheme,
      variant: 'primary',
      color: 'danger',
      transparent: false,
      disabled: false,
    })
    const secondaryResult = getButtonColors({
      theme: computedTheme,
      variant: 'secondary',
      color: 'danger',
      transparent: false,
      disabled: false,
    })
    const tertiaryResult = getButtonColors({
      theme: computedTheme,
      variant: 'tertiary',
      color: 'danger',
      transparent: false,
      disabled: false,
    })

    expect(primaryResult.backgroundColor).toBe(theme.designSystem.color.background.danger)
    expect(primaryResult.borderColor).toBe(theme.designSystem.color.border.danger)
    expect(primaryResult.textColor).toBe(theme.designSystem.color.text.inverted)
    expect(primaryResult.iconColor).toBe(theme.designSystem.color.icon.inverted)
    expect(primaryResult.hoverBackgroundColor).toBe(theme.designSystem.color.background.dangerHover)
    expect(primaryResult.hoverBorderColor).toBe(theme.designSystem.color.border.dangerHover)
    expect(primaryResult.hoverTextColor).toBeUndefined()
    expect(primaryResult.hoverIconColor).toBeUndefined()

    expect(secondaryResult.backgroundColor).toBe(theme.designSystem.color.background.default)
    expect(secondaryResult.borderColor).toBe(theme.designSystem.color.border.danger)
    expect(secondaryResult.textColor).toBe(theme.designSystem.color.text.danger)
    expect(secondaryResult.iconColor).toBe(theme.designSystem.color.icon.danger)
    expect(secondaryResult.hoverBackgroundColor).toBeUndefined()
    expect(secondaryResult.hoverBorderColor).toBe(theme.designSystem.color.border.dangerHover)
    expect(secondaryResult.hoverTextColor).toBe(theme.designSystem.color.text.dangerHover)
    expect(secondaryResult.hoverIconColor).toBe(theme.designSystem.color.icon.dangerHover)

    expect(tertiaryResult.backgroundColor).toBe('transparent')
    expect(tertiaryResult.borderColor).toBeUndefined()
    expect(tertiaryResult.textColor).toBe(theme.designSystem.color.text.danger)
    expect(tertiaryResult.iconColor).toBe(theme.designSystem.color.icon.danger)
    expect(tertiaryResult.hoverBackgroundColor).toBeUndefined()
    expect(tertiaryResult.hoverBorderColor).toBeUndefined()
    expect(tertiaryResult.hoverTextColor).toBe(theme.designSystem.color.text.dangerHover)
    expect(tertiaryResult.hoverIconColor).toBe(theme.designSystem.color.icon.dangerHover)
  })
})
