module.exports = {
  entry: ['src/index.tsx'],
  project: ['src/**/*.{ts,tsx}'],
  ignore: [
    'src/**/*.ios.*',
    'src/**/*.android.*',
    'src/**/*.web.*',
    'src/api/gen/**',
    'src/**/fixtures/**',
    'src/**/__mocks__/**',
  ],
  ignoreDependencies: ['@sentry/vite-plugin'],
  skip: [
    'src/web/**',
    'src/**/*.stories.tsx',
    'src/ui/storybook/**',
    'src/libs/monitoring/sentry.ts',
    'src/libs/react-native-animatable/index.ts',
    'src/libs/react-native-batch/index.ts',
    'src/libs/react-native-share/index.tsx',
    'src/libs/react-native-web-fast-image/index.d.ts',
    'src/libs/react-native-web-fast-image/index.js',
    'jest/**',
    'src/tests/utils.tsx',
    'src/tests/utils/web.tsx',
    'src/**/__mocks__/**',
    'src/features/internal/cheatcodes/**',
    'src/ui/svg/icons/achievements/**',
  ],
  rules: {
    dependencies: 'off',
    binaries: 'off',
    unresolved: 'off',
    unlisted: 'off',
  },
}
