/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import { DefaultTheme } from 'styled-components'

import { BackgroundColorKey } from 'theme/types'
import { RadioStateObject } from 'ui/designSystem/RadioButton/RadioButtonDefault'
import { SelectableVariant } from 'ui/designSystem/types'

import { RadioPart, RadioState } from '../types'

type RadioBackgroundParams = {
  componentPart: RadioPart
  variant: SelectableVariant
  collapsed: boolean
}

type CollapsedKey = 'open' | 'collapsed'

export const getCollapsedKey = (part: RadioPart, collapsed: boolean): CollapsedKey =>
  part === 'container' && collapsed ? 'collapsed' : 'open'

const selectedBackgroundTokenByPart: Record<
  RadioPart,
  Record<SelectableVariant, Record<CollapsedKey, BackgroundColorKey>>
> = {
  round: {
    default: { open: 'brandPrimary', collapsed: 'brandPrimary' },
    detailed: { open: 'brandPrimary', collapsed: 'brandPrimary' },
  },
  container: {
    default: { open: 'brandPrimarySelected', collapsed: 'default' },
    detailed: { open: 'brandPrimarySelected', collapsed: 'default' },
  },
  circle: {
    default: { open: 'default', collapsed: 'default' },
    detailed: { open: 'brandPrimarySelected', collapsed: 'brandPrimarySelected' },
  },
}

export const backgroundColorForSelected = (
  theme: DefaultTheme,
  params: RadioBackgroundParams
): string => {
  const collapsedKey = getCollapsedKey(params.componentPart, params.collapsed)
  const token = selectedBackgroundTokenByPart[params.componentPart][params.variant][collapsedKey]
  return theme.designSystem.color.background[token]
}

export const backgroundColorForDisabledSelected = (
  theme: DefaultTheme,
  params: RadioBackgroundParams
): string =>
  params.componentPart === 'round'
    ? theme.designSystem.color.icon.disabled
    : theme.designSystem.color.background.disabled

export const backgroundColorForDisabled = (
  theme: DefaultTheme,
  params: RadioBackgroundParams
): string => {
  return params.variant === 'detailed'
    ? theme.designSystem.color.background.disabled
    : theme.designSystem.color.background.default
}

export const backgroundColorByState: Record<
  RadioState,
  (theme: DefaultTheme, params: RadioBackgroundParams) => string
> = {
  selected: backgroundColorForSelected,
  disabledSelected: backgroundColorForDisabledSelected,
  disabled: backgroundColorForDisabled,
  error: (theme: DefaultTheme): string => {
    return theme.designSystem.color.background.default
  },
  default: (theme: DefaultTheme): string => {
    return theme.designSystem.color.background.default
  },
}

export const getRadioBorderColor = (state: RadioStateObject, theme: DefaultTheme) => {
  if (state.disabled) return theme.designSystem.color.border.disabled
  if (state.error) return theme.designSystem.color.border.error
  return state.isSelected
    ? theme.designSystem.color.border.brandPrimary
    : theme.designSystem.color.border.default
}

type GetRadioColorsOptions = {
  componentPart?: RadioPart
  variant?: SelectableVariant
  collapsed?: boolean
}

export const getRadioColors = (
  state: RadioStateObject,
  theme: DefaultTheme,
  options?: GetRadioColorsOptions
) => {
  const params: RadioBackgroundParams = {
    componentPart: options?.componentPart ?? 'container',
    variant: options?.variant ?? 'default',
    collapsed: options?.collapsed ?? false,
  }
  let _state = 'default'
  if (state.disabled && state.isSelected) _state = 'disabledSelected'
  else if (state.disabled) _state = 'disabled'
  else if (state.error) _state = 'error'
  else if (state.isSelected) _state = 'selected'

  const borderColor = getRadioBorderColor(state, theme)
  const backgroundColor = backgroundColorByState[_state](theme, params)

  return { borderColor, backgroundColor }
}

export const getLabelColor = ({ disabled, theme }: { disabled: boolean; theme: DefaultTheme }) =>
  disabled ? theme.designSystem.color.text.disabled : theme.designSystem.color.text.default
