/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import { RadioDisplayOptions } from 'ui/designSystem/RadioButton/types'
import { SelectableSizing } from 'ui/designSystem/types'

export function getRadioDisplay(input: RadioDisplayOptions): SelectableSizing {
  if (input.variant === 'detailed' && input.collapsed) return 'fill'
  if (input.variant === 'detailed') return input.sizing ?? 'hug'
  return 'hug'
}
