/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import { DefaultTheme } from 'styled-components'

import { getHoverStyle } from 'ui/theme/getHoverStyle/getHoverStyle'

import { RadioState } from '../types'

import { isDisabledState } from './state'

export function getBorderHoverStyle({
  theme,
  radioState,
  isHover,
}: {
  theme: DefaultTheme
  radioState: RadioState
  isHover?: boolean
}) {
  if (isDisabledState(radioState) || radioState === 'error') return {}
  return getHoverStyle({ borderColor: theme.designSystem.color.border.brandPrimary, isHover })
}

export function getTextHoverStyle({
  theme,
  radioState,
  isHover,
}: {
  theme: DefaultTheme
  radioState: RadioState
  isHover?: boolean
}) {
  if (isDisabledState(radioState) || radioState === 'error') return {}
  return getHoverStyle({ textColor: theme.designSystem.color.text.brandPrimary, isHover })
}
