/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import { DefaultTheme } from 'styled-components'

import { RadioStateObject } from 'ui/designSystem/RadioButton/types'
import { getHoverStyle } from 'ui/theme/getHoverStyle/getHoverStyle'

export const getBorderHoverStyle = ({
  theme,
  radioState,
  isHover,
}: {
  theme: DefaultTheme
  radioState: RadioStateObject
  isHover?: boolean
}) =>
  radioState.disabled || radioState.error
    ? {}
    : getHoverStyle({ borderColor: theme.designSystem.color.border.brandPrimary, isHover })

export const getTextHoverStyle = ({
  theme,
  radioState,
  isHover,
}: {
  theme: DefaultTheme
  radioState: RadioStateObject
  isHover?: boolean
}) =>
  radioState.disabled || radioState.error
    ? {}
    : getHoverStyle({ textColor: theme.designSystem.color.text.brandPrimary, isHover })
