/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import { RadioState } from 'ui/designSystem/RadioButton/types'

export function getRadioState(
  isSelected: boolean,
  hasError?: boolean,
  isDisabled?: boolean
): RadioState {
  if (isDisabled && isSelected) return 'disabledSelected'
  if (isDisabled) return 'disabled'
  if (hasError) return 'error'
  if (isSelected) return 'selected'
  return 'default'
}

export function isDisabledState(state: RadioState) {
  return state === 'disabled' || state === 'disabledSelected'
}
