/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import type { Meta } from '@storybook/react-vite'
import React from 'react'

import { navigateToHomeConfig } from 'features/navigation/helpers/navigateToHome'
import { BannerType } from 'ui/designSystem/Banner/enums'
import { VariantsTemplate, type Variants, type VariantsStory } from 'ui/storybook/VariantsTemplate'
import { ClockFilled } from 'ui/svg/icons/ClockFilled'
import { EmailFilled } from 'ui/svg/icons/EmailFilled'
import { LENGTH_S } from 'ui/theme'

import { Banner } from './Banner'

const meta: Meta<typeof Banner> = {
  title: 'design system/Banner',
  component: Banner,
}
export default meta

const description =
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris mattis libero ultrices sem scelerisque gravida. Lorem ipsum dolor sit amet, consectetur adipiscing elit. '

const uri =
  'https://img-19.ccm2.net/8vUCl8TXZfwTt7zAOkBkuDRHiT8=/1240x/smart/b829396acc244fd484c5ddcdcb2b08f3/ccmcms-commentcamarche/20494859.jpg'

const variantConfig: Variants<typeof Banner> = [
  {
    label: 'Default',
    props: {
      label: 'Banner label',
    },
  },
  {
    label: 'Default with long label',
    props: {
      label: 'Banner label lorem ipsum dolor sit amet consectetur adipiscing elit',
      description,
    },
  },
  {
    label: 'Default with description',
    props: {
      label: 'Banner label',
      description,
    },
  },
  {
    label: 'Default with links',
    props: {
      label: 'Banner label',
      description,
      links: [
        {
          navigateTo: navigateToHomeConfig,
          wording: 'Internal link default',
        },
        {
          navigateTo: navigateToHomeConfig,
          wording: 'Internal link with custom icon',
          icon: ClockFilled,
        },
        {
          externalNav: { url: 'https://passculture.app/' },
          wording: 'External link default',
        },
        {
          externalNav: { url: 'https://passculture.app/' },
          wording: 'External link with custom icon',
          icon: EmailFilled,
        },
      ],
    },
  },
  {
    label: 'Default with default image',
    props: {
      label: 'Banner label',
      description,
      image: { uri },
    },
  },
  {
    label: 'Default with custom size image',
    props: {
      label: 'Banner label',
      description,
      image: { uri, size: LENGTH_S },
    },
  },
  {
    label: 'Default with close button',
    props: {
      label: 'Banner label',
      description,
      onClose: () => alert('Close button clicked'),
    },
  },
  {
    label: 'Default with all props',
    props: {
      label: 'Banner label',
      description,
      image: { uri, size: LENGTH_S },
      onClose: () => alert('Close button clicked'),
      links: [
        {
          navigateTo: { screen: 'TabNavigator', params: { screen: 'Home' } },
          wording: 'Internal link default',
        },
        {
          navigateTo: { screen: 'TabNavigator', params: { screen: 'Home' } },
          wording: 'Internal link with custom icon',
          icon: ClockFilled,
        },
        {
          externalNav: { url: 'https://passculture.app/' },
          wording: 'External link default',
        },
        {
          externalNav: { url: 'https://passculture.app/' },
          wording: 'External link with custom icon',
          icon: EmailFilled,
        },
      ],
    },
  },
  {
    label: 'Success with description',
    props: {
      label: 'Banner label',
      type: BannerType.SUCCESS,
      description,
    },
  },
  {
    label: 'Error with description',
    props: {
      label: 'Banner label',
      type: BannerType.ERROR,
      description,
    },
  },
  {
    label: 'Alert with description',
    props: {
      label: 'Banner label',
      type: BannerType.ALERT,
      description,
    },
  },
]

export const Template: VariantsStory<typeof Banner> = {
  name: 'Banner',
  render: (props) => (
    <VariantsTemplate variants={variantConfig} Component={Banner} defaultProps={props} />
  ),
}
