/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React, { FunctionComponent } from 'react'
import { Platform, useWindowDimensions } from 'react-native'
import styled from 'styled-components/native'

import {
  ModalSimpleContent,
  ModalSimpleProps,
} from 'ui/designSystem/ModalSimple/ModalSimpleContent'
import { ModalSimpleFooter } from 'ui/designSystem/ModalSimple/ModalSimpleFooter'
import { ModalSimpleHeader } from 'ui/designSystem/ModalSimple/ModalSimpleHeader'

export const ModalSimple: FunctionComponent<ModalSimpleProps> = (props) => {
  const { height } = useWindowDimensions()

  return (
    <ModalWrapper maxHeight={height}>
      <ModalSimpleHeader onClose={props.onClose} />

      <StyledScrollView bounces={false} showsVerticalScrollIndicator={false} nestedScrollEnabled>
        <ModalSimpleContent {...props} />
      </StyledScrollView>

      <ModalSimpleFooter {...props} />
    </ModalWrapper>
  )
}

const ModalWrapper = styled.View<{ maxHeight?: number }>(({ maxHeight }) => ({
  maxHeight,
  width: '100%',
}))

const StyledScrollView = styled.ScrollView({
  flexShrink: 1,
  maxHeight: '100%',
})
