/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import type { Meta, StoryObj } from '@storybook/react-vite'
import { action } from 'storybook/actions'

import { remoteIllustrationUrls } from 'shared/illustrations/remoteIllustrations'

import { ModalSimple } from './ModalSimple'

const meta: Meta<typeof ModalSimple> = {
  title: 'design system/ModalSimple',
  component: ModalSimple,
}
export default meta

type Story = StoryObj<typeof ModalSimple>

export const Default: Story = {
  args: {
    title: 'Titre de la modale',
    illustration: {
      backgroundColor: 'positive02',
      url: remoteIllustrationUrls.validStampMosaïcLarge,
    },
    description: 'Ceci est une description courte pour la modale simple.',
    onClose: action('onClose pressed'),
    primaryButton: {
      wording: 'Confirmer',
      accessibilityLabel: 'Confirmer',
      onPress: action('onPress primary button'),
    },
  },
}

export const FullContentWithScroll: Story = {
  args: {
    title: 'Titre très long nécessitant plusieurs lignes',
    description:
      'Description longue pour tester le comportement de la modale. Description longue pour tester le comportement de la modale. Description longue pour tester le comportement de la modale. Description longue pour tester le comportement de la modale. Description longue pour tester le comportement de la modale.',
    illustration: {
      backgroundColor: 'positive02',
      url: remoteIllustrationUrls.validStampMosaïcLarge,
    },
    onClose: action('onClose pressed'),
    primaryButton: {
      wording: 'Confirmer',
      accessibilityLabel: 'Bouton principal pour confirmer',
      onPress: action('onPress primary button'),
    },
    secondaryButton: {
      wording: 'Action secondaire',
      accessibilityLabel: 'Bouton pour une action secondaire',
      onPress: action('onPress secondary button'),
    },
    tertiaryButton: {
      wording: 'Annuler',
      accessibilityLabel: 'Bouton pour annuler',
      onPress: action('onPress tertiary button'),
    },
  },
}
