/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React, { FunctionComponent } from 'react'
import styled from 'styled-components/native'

import { RemoteIllustration, RemoteIllustrationProps } from 'ui/components/RemoteIllustration'
import { ViewGap } from 'ui/components/ViewGap/ViewGap'
import { Typo } from 'ui/theme'
import { setTextSemantic } from 'ui/theme/typographyAttrs/setTextSemantic'

export type ActionButtonProps = {
  wording: string
  accessibilityLabel: string
  onPress: () => void
}

export type BaseModalSimpleProps = {
  title: string
  illustration?: RemoteIllustrationProps
  description?: string
  onClose: () => void
}

export type ModalSimpleProps = BaseModalSimpleProps &
  (
    | {
        primaryButton: ActionButtonProps
        secondaryButton?: ActionButtonProps
        tertiaryButton?: ActionButtonProps
      }
    | {
        primaryButton?: ActionButtonProps
        secondaryButton: ActionButtonProps
        tertiaryButton?: ActionButtonProps
      }
    | {
        primaryButton?: ActionButtonProps
        secondaryButton?: ActionButtonProps
        tertiaryButton: ActionButtonProps
      }
  )

export const ModalSimpleContent: FunctionComponent<ModalSimpleProps> = ({
  title,
  illustration,
  description,
}) => {
  return (
    <ModalContainer gap={6}>
      <ContentContainer gap={6}>
        {illustration ? <RemoteIllustration {...illustration} size="s" /> : null}

        <TextsContainer gap={4}>
          <Title {...setTextSemantic('h1')}>{title}</Title>
          {description ? <Description>{description}</Description> : null}
        </TextsContainer>
      </ContentContainer>
    </ModalContainer>
  )
}

const ModalContainer = styled(ViewGap)(({ theme }) => ({
  width: '100%',
  backgroundColor: theme.designSystem.color.background.default,
  paddingHorizontal: theme.designSystem.size.spacing.xxl,
  paddingTop: theme.designSystem.size.spacing.xl,
}))

const ContentContainer = styled(ViewGap)({
  alignItems: 'center',
})

const TextsContainer = styled(ViewGap)({
  alignItems: 'center',
})

const Title = styled(Typo.Title4)(({ theme }) => ({
  color: theme.designSystem.color.text.default,
  textAlign: 'center',
}))

const Description = styled(Typo.Body)(({ theme }) => ({
  color: theme.designSystem.color.text.default,
  textAlign: 'center',
}))
