flows:
  - '*'
  - '**'
  - 'subFolder/*'
  - 'subFolder/tutorial/onboarding/*'
  - 'subFolder/auth/*'
  - 'subFolder/booking/*'
  - 'subFolder/cookies/*'
  - 'subFolder/home/*'
  - 'subFolder/profil/*'
  - 'subFolder/search/*'
  - 'subFolder/home/*'
  - 'subFolder/venue/*'
  - 'subFolder/analytics/*'

# TODO: En attente du fix dans la v1.39.0 de Maestro
# executionOrder:
#     flowsOrder:
#       - SearchAndBookCinemaOffer.yml
#       - SearchAndBookDuoOffer.yml
#       - SearchAndBookOffers.yml

notifications:
  email:
    enabled: true
    onSuccess: true
    recipients:
      - equipe-e2e-jeunes-aaaakntkqy3ta5ksdafyew6dae@passcultureteam.slack.com