/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import { StoryFn } from '@storybook/react-vite'
import React from 'react'

import {
  buildContentfulIllustrationUrl,
  contentfulIllustrationNames,
} from 'shared/illustrations/buildContentfulIllustrationUrl'
import {
  categoryButtonIllustrationNames,
  categoryButtonIllustrationUrls,
} from 'shared/illustrations/categoryButtonIllustrations'
import { AssetGridTemplate as Illustrations } from 'ui/storybook/AssetGridTemplate'
import { getSpacing } from 'ui/theme'

export default {
  title: 'design system/Category illustrations',
}

const getCategoryIllustrationAssetName = (url: string) => {
  const filename = url.split('/').pop() ?? url

  return filename.replace('%403x.png', '').replace('.png', '')
}

const categoryButtonImages = Object.fromEntries(
  categoryButtonIllustrationNames.map((name) => {
    const url = categoryButtonIllustrationUrls[name]

    return [getCategoryIllustrationAssetName(url), url]
  })
)

const contentfulHeaderImages = Object.fromEntries(
  contentfulIllustrationNames.map((name) => [name, buildContentfulIllustrationUrl(name)])
)

const Template: StoryFn = () => (
  <React.Fragment>
    <Illustrations title="Category illustrations" images={categoryButtonImages} isIllustration />
    <Illustrations
      title="Contentful header illustrations"
      images={contentfulHeaderImages}
      imageSize={getSpacing(40)}
      isIllustration
    />
  </React.Fragment>
)

export const AllIllustrations = {
  name: 'Illustrations',
  render: Template,
}
