import { AlgoliaHit } from 'libs/algolia'

// TODO(agarcia): once we are done mmocking the results in the front, move this file to the fixtures
export const algoliaHits: AlgoliaHit[] = [
  {
    offer: {
      author: 'Oda, Eiichiro',
      category: 'LIVRE',
      dateCreated: 1571211104.882934,
      dates: [],
      description:
        "Pour traverser la route de tous les périls, Luffy a sélectionné le meilleur équipage possible. Zorro ne fait pas exception : Luffy en est certain, son ami est le meilleur sabreur du monde ! Et ce n'est quand même pas Oeil de Faucon, ce mystérieux combattant, qui va mettre la réputation de Zorro en jeu ?!",
      id: 'XU8A',
      isbn: '9782017097679',
      isDigital: false,
      isDuo: false,
      isEvent: false,
      isThing: true,
      label: 'Livre ou carte lecture',
      musicSubType: null,
      musicType: null,
      name: 'One Piece T.6 ; la promesse de Zorro',
      performer: null,
      prices: [5],
      priceMin: 5,
      priceMax: 5,
      showSubType: null,
      showType: null,
      speaker: null,
      stageDirector: null,
      stocksDateCreated: [1571211104.906349],
      thumbUrl:
        'https://storage.gra.cloud.ovh.net/v1/AUTH_688df1e25bd84a48a3804e7fa8938085/storage-pc-staging/thumbs/products/FDUE2',
      tags: [],
      times: [],
      type: 'Lire',
      visa: null,
      withdrawalDetails: null,
    },
    offerer: {
      name: 'CHEMINANT S A',
    },
    venue: {
      city: 'VANNES',
      departementCode: '56',
      name: 'CHEMINANT S A',
      publicName: 'Librairie Cheminant à Vannes',
    },
    _geoloc: {
      lat: 47.65904,
      lng: -2.75922,
    },
    objectID: 'XU8A',
  },
  {
    offer: {
      author: 'Oda, Eiichiro',
      category: 'LIVRE',
      dateCreated: 1592844633.690835,
      dates: [],
      description:
        "Ça y est ! Luffy et Zorro sont prêts à embarquer sur la route de tous les périls. Mais avant ça, ils doivent trouver un navigateur digne de ce nom pour compléter leur équipage ! Mais ce n'est pas si facile de trouver la perle rare... Surtout que l'un des plus terribles capitaines pirates a juré de les arrêter !",
      id: 'EA964',
      isbn: '9782017071976',
      isDigital: false,
      isDuo: false,
      isEvent: false,
      isThing: true,
      label: 'Livre ou carte lecture',
      musicSubType: null,
      musicType: null,
      name: 'One Piece T.2 ; le capitaine Baggy',
      performer: null,
      prices: [5.5],
      priceMin: 5.5,
      priceMax: 5.5,
      showSubType: null,
      showType: null,
      speaker: null,
      stageDirector: null,
      stocksDateCreated: [1592844633.693503],
      thumbUrl:
        'https://storage.gra.cloud.ovh.net/v1/AUTH_688df1e25bd84a48a3804e7fa8938085/storage-pc-staging/thumbs/products/E25T6',
      tags: [],
      times: [],
      type: 'Lire',
      visa: null,
      withdrawalDetails: null,
    },
    offerer: {
      name: 'DIALOGUES MORLAIX',
    },
    venue: {
      city: 'MORLAIX',
      departementCode: '29',
      name: 'DIALOGUES MORLAIX',
      publicName: null,
    },
    _geoloc: {
      lat: 48.5764,
      lng: -3.82528,
    },
    objectID: 'EA964',
  },
  {
    offer: {
      author: 'Oda, Eiichiro',
      category: 'LIVRE',
      dateCreated: 1603180022.499456,
      dates: [],
      description:
        "Pipo ment comme il respire ! Du coup, lorsqu'il annonce aux habitants de son village que des pirates vont les attaquer, personne ne le prend au sérieux. Grave erreur ! L'attaque est réellement prévue, et elle va provenir de quelqu'un dont personne ne se serait méfié. Grâce à Luffy et ses amis, les villageois vont apprendre qu'il ne faut pas se fier aux apparences...",
      id: 'J64GK',
      isbn: '9782011183088',
      isDigital: false,
      isDuo: false,
      isEvent: false,
      isThing: true,
      label: 'Livre ou carte lecture',
      musicSubType: null,
      musicType: null,
      name: 'One Piece T.4 ; révélation',
      performer: null,
      prices: [5.51],
      priceMin: 5.51,
      priceMax: 5.51,
      showSubType: null,
      showType: null,
      speaker: null,
      stageDirector: null,
      stocksDateCreated: [1603180022.502248],
      thumbUrl:
        'https://storage.gra.cloud.ovh.net/v1/AUTH_688df1e25bd84a48a3804e7fa8938085/storage-pc-staging/thumbs/products/E7K2K',
      tags: [],
      times: [],
      type: 'Lire',
      visa: null,
      withdrawalDetails: null,
    },
    offerer: {
      name: 'RELAIS FNAC',
    },
    venue: {
      city: 'MONTPELLIER',
      departementCode: '34',
      name: 'Fnac Montpellier',
      publicName: null,
    },
    _geoloc: {
      lat: 43.60792,
      lng: 3.88565,
    },
    objectID: 'J64GK',
  },
]
