export { parseAlgoliaParameters } from './parseAlgoliaParameters'
export type { AlgoliaHit, Geoloc } from './algolia.d'
export { useFetchAlgolia } from './hooks/useFetchAlgolia'
export type { UseFetchAlgoliaInterface } from './hooks/useFetchAlgolia'
export * from './types'
