/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import type { Meta } from '@storybook/react-vite'
import React from 'react'

import { RadioButton } from 'ui/designSystem/RadioButton/RadioButton'
import { VariantsTemplate, type Variants, type VariantsStory } from 'ui/storybook/VariantsTemplate'

const meta: Meta<typeof RadioButton> = {
  title: 'design system/inputs/RadioButton',
  component: RadioButton,
}
export default meta

const variantConfig: Variants<typeof RadioButton> = [
  {
    label: 'RadioButton Default',
    props: {
      label: 'Label',
      value: null,
      setValue: () => {
        //
      },
      sizing: 'hug',
    },
  },
  {
    label: 'RadioButton Default selected',
    props: {
      label: 'Label',
      value: 'Label',
      setValue: () => {
        //
      },
      sizing: 'hug',
    },
  },
  {
    label: 'RadioButton Default disabled',
    props: {
      label: 'Label',
      disabled: true,
      value: null,
      setValue: () => {
        //
      },
      sizing: 'hug',
    },
  },
  {
    label: 'RadioButton Default disabled selected',
    props: {
      label: 'Label',
      disabled: true,
      value: 'Label',
      setValue: () => {
        //
      },
      sizing: 'hug',
    },
  },
  {
    label: 'RadioButton Default Has Error',
    props: {
      label: 'Label',
      error: true,
      value: null,
      setValue: () => {
        //
      },
      sizing: 'hug',
    },
  },
  {
    label: 'RadioButton Detailed with description',
    props: {
      label: 'RadioButton label',
      variant: 'detailed',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
  },
  {
    label: 'RadioButton Detailed with description selected',
    props: {
      label: 'Label',
      value: 'Label',
      setValue: () => {
        //
      },
      variant: 'detailed',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
  },
  /*  
  {
    label: 'RadioButton Detailed With Description',
    props: {
      label: 'RadioButton label',
      variant: 'detailed',
      isSelected: false,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
  },
  {
    label: 'RadioButton Detailed Hug',
    props: {
      label: 'RadioButton label',
      variant: 'detailed',
      isSelected: false,
      sizing: 'hug',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
  },
  {
    label: 'RadioButton Detailed Selected',
    props: {
      label: 'RadioButton label',
      variant: 'detailed',
      isSelected: true,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
  },
  {
    label: 'RadioButton Detailed Selected Disabled',
    props: {
      label: 'RadioButton label',
      variant: 'detailed',
      isSelected: true,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      disabled: true,
    },
  },
  {
    label: 'RadioButton Detailed Disabled',
    props: {
      label: 'RadioButton label',
      variant: 'detailed',
      isSelected: false,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      disabled: true,
    },
  },
  {
    label: 'RadioButton Detailed With Icon',
    props: {
      label: 'RadioButton label',
      variant: 'detailed',
      isSelected: false,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      asset: { variant: 'icon', Icon: Calendar },
    },
  },
  {
    label: 'RadioButton Detailed With Icon Disabled',
    props: {
      label: 'RadioButton label',
      variant: 'detailed',
      isSelected: false,
      disabled: true,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      asset: { variant: 'icon', Icon: Calendar },
    },
  },
  {
    label: 'RadioButton Detailed Has Error',
    props: {
      label: 'RadioButton label',
      variant: 'detailed',
      isSelected: false,
      hasError: true,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
  },
  {
    label: 'RadioButton Detailed With Text',
    props: {
      label: 'RadioButton label',
      variant: 'detailed',
      isSelected: false,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      asset: { variant: 'text', text: '32\u00a0€' },
    },
  },
  {
    label: 'RadioButton Detailed With Image',
    props: {
      label: 'RadioButton label',
      variant: 'detailed',
      isSelected: false,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      asset: {
        variant: 'image',
        src: 'https://storage.googleapis.com/passculture-metier-prod-production-assets-fine-grained/thumbs/mediations/9MPGW',
      },
    },
  },
  {
    label: 'RadioButton Detailed With Medium Image',
    props: {
      label: 'RadioButton label',
      variant: 'detailed',
      isSelected: false,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      asset: {
        variant: 'image',
        src: 'https://storage.googleapis.com/passculture-metier-prod-production-assets-fine-grained/thumbs/mediations/9MPGW',
        size: 'medium',
      },
    },
  },
  {
    label: 'RadioButton Detailed With Large Image',
    props: {
      label: 'RadioButton label',
      variant: 'detailed',
      isSelected: false,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      asset: {
        variant: 'image',
        src: 'https://storage.googleapis.com/passculture-metier-prod-production-assets-fine-grained/thumbs/mediations/9MPGW',
        size: 'large',
      },
    },
  },
  {
    label: 'RadioButton Detailed With Tag',
    props: {
      label: 'RadioButton label',
      variant: 'detailed',
      isSelected: false,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      asset: { variant: 'tag', tag: { label: 'Tag label', Icon: <Star size={16} /> } },
    },
  },
  {
    label: 'RadioButton Detailed With Collapsed Content',
    props: {
      label: 'RadioButton label',
      variant: 'detailed',
      isSelected: false,
      asset: { variant: 'icon', Icon: Calendar },
      collapsed: <Typo.Body>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</Typo.Body>,
    },
  },
  {
    label: 'RadioButton Detailed With Collapsed Content Selected',
    props: {
      label: 'RadioButton label',
      variant: 'detailed',
      isSelected: true,
      asset: { variant: 'icon', Icon: Calendar },
      collapsed: <Typo.Body>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</Typo.Body>,
    },
  },
  {
    label: 'RadioButton Detailed With Collapsed Content Disabled',
    props: {
      label: 'RadioButton label',
      variant: 'detailed',
      isSelected: false,
      disabled: true,
      asset: { variant: 'icon', Icon: Calendar },
      collapsed: <Typo.Body>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</Typo.Body>,
    },
  }, */
]

export const Template: VariantsStory<typeof RadioButton> = {
  name: 'RadioButton',
  render: (props) => (
    <VariantsTemplate variants={variantConfig} Component={RadioButton} defaultProps={props} />
  ),
}
