/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React, { FunctionComponent } from 'react'

import { RadioButtonDefault } from 'ui/designSystem/RadioButton/RadioButtonDefault'
import { RadioButtonDetailed } from 'ui/designSystem/RadioButton/RadioButtonDetailed'
import { BaseRadioProps } from 'ui/designSystem/RadioButton/types'

export const RadioButton: FunctionComponent<BaseRadioProps> = ({
  label,
  disabled,
  error,
  value,
  collapsed,
  description,
  asset,
  sizing,
  variant,
  setValue,
}) =>
  variant === 'detailed' ? (
    <RadioButtonDetailed
      label={label}
      disabled={!!disabled}
      error={error ?? false}
      value={value}
      setValue={setValue}
      sizing={collapsed ? 'fill' : (sizing ?? 'hug')}
      collapsed={collapsed}
      description={description ?? null}
      asset={asset ?? null}
      variant={variant}
    />
  ) : (
    <RadioButtonDefault
      label={label}
      disabled={!!disabled}
      error={error ?? false}
      value={value}
      setValue={setValue}
      variant={variant}
      sizing="hug"
    />
  )
