/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React, { FunctionComponent } from 'react'

import { RadioButtonDefault } from 'ui/designSystem/RadioButton/RadioButtonDefault'
import { RadioButtonDetailed } from 'ui/designSystem/RadioButton/RadioButtonDetailed'
import { DefaultRadioProps, DetailedRadioProps } from 'ui/designSystem/RadioButton/types'

export const RadioButton: FunctionComponent<DefaultRadioProps | DetailedRadioProps> = ({
  label,
  disabled,
  error,
  value,
  collapsed,
  description,
  asset,
  sizing,
  variant,
  setValue,
}) => {
  const detailedSizing = collapsed ? 'fill' : (sizing ?? 'hug')

  return variant === 'detailed' ? (
    <RadioButtonDetailed
      label={label}
      disabled={!!disabled}
      error={error ?? false}
      value={value}
      collapsed={collapsed}
      description={description ?? null}
      asset={asset ?? null}
      setValue={setValue}
      sizing={detailedSizing}
    />
  ) : (
    <RadioButtonDefault
      label={label}
      disabled={!!disabled}
      error={error ?? false}
      value={value}
      setValue={setValue}
      sizing="hug"
    />
  )
}
