/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import userEvent from '@testing-library/user-event'
import React, { ComponentProps } from 'react'

import { act, render, screen } from 'tests/utils/web'

import { RadioButton } from './RadioButton'

const setValueMock = jest.fn()
const labelText = 'I agree to disagree'

const baseProps: ComponentProps<typeof RadioButton> = {
  label: labelText,
  disabled: false,
  error: false,
  value: null,
  collapsed: null,
  description: null,
  asset: null,
  sizing: 'hug',
  setValue: setValueMock,
  isSelected: false,
  variant: 'default',
}

describe('<RadioButton />', () => {
  it('should render an accessible RadioButton', () => {
    render(<RadioButton {...baseProps} />)

    expect(screen.getByRole('radio')).toBeInTheDocument()
  })

  it('is linked to his label', () => {
    render(<RadioButton {...baseProps} />)

    expect(screen.getByLabelText(labelText)).toEqual(screen.getByRole('radio'))
  })

  it('can be checked with RadioButton', async () => {
    render(<RadioButton {...baseProps} />)

    await act(async () => {
      await userEvent.click(screen.getByLabelText(labelText))
    })

    expect(setValueMock).toHaveBeenCalledWith(labelText)
  })

  it('can be checked with label', async () => {
    render(<RadioButton {...baseProps} />)

    await act(async () => {
      await userEvent.click(screen.getByText(labelText))
    })

    expect(setValueMock).toHaveBeenCalledWith(labelText)
  })

  describe('toggle his state', () => {
    it('select radioButton when radioButton is unselected', async () => {
      render(<RadioButton {...baseProps} isSelected={false} />)

      await act(async () => {
        await userEvent.click(screen.getByRole('radio'))
      })

      expect(setValueMock).toHaveBeenCalledWith(labelText)
    })

    it('unselect radioButton when radioButton is selected', async () => {
      render(<RadioButton {...baseProps} isSelected />)

      await act(async () => {
        await userEvent.click(screen.getByRole('radio'))
      })

      expect(setValueMock).toHaveBeenCalledWith(labelText)
    })
  })

  describe('when pressing space', () => {
    it("doesn't change the checked state when doesn't having the focus", async () => {
      render(<RadioButton {...baseProps} />)

      await userEvent.keyboard('[Space]')

      expect(setValueMock).not.toHaveBeenCalled()
    })

    describe('when it has focus', () => {
      it('select the radio when is not selected', async () => {
        render(<RadioButton {...baseProps} isSelected={false} />)

        await act(async () => {
          await userEvent.tab()
        })

        await act(async () => {
          await userEvent.keyboard('[Space]')
        })

        expect(setValueMock).toHaveBeenCalledWith(labelText)
      })
    })
  })

  describe('have aria-checked attribute', () => {
    it('checked when RadioButton is checked', async () => {
      render(<RadioButton {...baseProps} isSelected />)

      expect(screen.getByRole('radio').getAttribute('aria-checked')).toBe('true')
    })

    it('not checked when RadioButton is unchecked', async () => {
      render(<RadioButton {...baseProps} isSelected={false} />)

      expect(screen.getByRole('radio').getAttribute('aria-checked')).toBe('false')
    })
  })
})
