/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React from 'react'

import { SelectableAssetProps, SelectableDisplay } from 'ui/designSystem/types'

export type RadioVariant = 'default' | 'detailed'
export type RadioPart = 'container' | 'circle' | 'round'
export type RadioState = 'selected' | 'disabledSelected' | 'disabled' | 'error' | 'default'

export type RadioDisplayOptions = {
  variant: RadioVariant
  collapsed?: React.ReactNode
  display?: SelectableDisplay
}

type BaseRadioProps = {
  label: string
  isSelected: boolean
  onSelect: (isSelected: boolean) => void
  disabled?: boolean
  hasError?: boolean
}

type DefaultRadioProps = BaseRadioProps & {
  variant: 'default'
  description?: never
  asset?: never
  collapsed?: never
  display?: never
}

type DetailedInlineRadioProps = BaseRadioProps & {
  variant: 'detailed'
  description?: string
  asset?: SelectableAssetProps
  collapsed?: never
  display?: SelectableDisplay
}

type DetailedCollapsedRadioProps = BaseRadioProps & {
  variant: 'detailed'
  collapsed: React.ReactNode
  description?: never
  asset?: Extract<SelectableAssetProps, { variant: 'icon' }>
  display?: Extract<SelectableDisplay, 'fill'>
}

export type RadioButtonProps =
  | DefaultRadioProps
  | DetailedInlineRadioProps
  | DetailedCollapsedRadioProps
