/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React from 'react'

import { SelectableAssetProps, SelectableSizing } from 'ui/designSystem/types'

export type RadioPart = 'container' | 'circle' | 'round'
export type Variant = 'default' | 'detailed'

export type RadioStateObject = {
  selected: boolean
  error: boolean
  disabled: boolean
}

export type BaseRadioProps = {
  label: string
  disabled: boolean
  error: boolean
  value: string | null
  setValue: React.Dispatch<React.SetStateAction<string>> | VoidFunction
  variant: Variant
  description?: string | null
  collapsed?: React.ReactNode | null
  asset?: SelectableAssetProps | null
  sizing?: SelectableSizing
  accessibilityLabel?: string
}

export type DefaultRadioProps = Omit<BaseRadioProps, 'description' | 'asset' | 'collapsed'> & {
  variant: 'default'
  sizing: 'hug'
}

export type DetailedRadioProps = BaseRadioProps & {
  variant: 'detailed'
}
