/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React from 'react'

import { render, screen } from 'tests/utils'

import { PasswordRules } from './PasswordRules'

const EMPTY_PASSWORD = ''
const VALID_PASSWORD = 'user@AZERTY123'
const INVALID_PASSWORD = 'user@azerty'

describe('<PasswordRules />', () => {
  it('should not display rules when visible is false', () => {
    render(<PasswordRules password={EMPTY_PASSWORD} visible={false} />)

    expect(
      screen.queryByText('12 caractères', { includeHiddenElements: true })
    ).not.toBeOnTheScreen()
  })

  it('should display password rules when visible is true', () => {
    render(<PasswordRules password="" visible />)

    expect(screen.getByText('12 caractères', { includeHiddenElements: true })).toBeOnTheScreen()
    expect(screen.getByText('1 majuscule', { includeHiddenElements: true })).toBeOnTheScreen()
    expect(screen.getByText('1 minuscule', { includeHiddenElements: true })).toBeOnTheScreen()
    expect(screen.getByText('1 chiffre', { includeHiddenElements: true })).toBeOnTheScreen()
    expect(
      screen.getByText('1 caractère spécial (!@#$%^&*...)', { includeHiddenElements: true })
    ).toBeOnTheScreen()
  })

  it('should expose default accessibility label when password is empty', () => {
    render(<PasswordRules password={EMPTY_PASSWORD} visible />)

    expect(
      screen.getByText(
        'Le mot de passe doit contenir au moins 12 caractères, 1 majuscule, 1 minuscule, 1 chiffre et 1 caractère spécial (!@#$%^&*...)',
        { includeHiddenElements: true }
      )
    ).toBeOnTheScreen()
  })

  it('should expose validation state in accessibility label when password is filled', () => {
    render(<PasswordRules password={VALID_PASSWORD} visible />)

    expect(
      screen.getByText(
        '12 caractères - critère validé, 1 majuscule - critère validé, 1 minuscule - critère validé, 1 chiffre - critère validé, 1 caractère spécial (!@#$%^&*...) - critère validé',
        { includeHiddenElements: true }
      )
    ).toBeOnTheScreen()
  })

  it('should expose invalidation state in accessibility label when password is filled', () => {
    render(<PasswordRules password={INVALID_PASSWORD} visible />)

    expect(
      screen.getByText(
        '12 caractères - au minimum, 1 majuscule - au minimum, 1 minuscule - critère validé, 1 chiffre - au minimum, 1 caractère spécial (!@#$%^&*...) - critère validé',
        { includeHiddenElements: true }
      )
    ).toBeOnTheScreen()
  })
})
