/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React, { FunctionComponent } from 'react'
import styled from 'styled-components/native'

import { hiddenFromScreenReader } from 'shared/accessibility/helpers/hiddenFromScreenReader'
import { HiddenAccessibleText } from 'ui/components/HiddenAccessibleText'
import { ViewGap } from 'ui/components/ViewGap/ViewGap'
import { PasswordRule } from 'ui/designSystem/PasswordInput/components/PasswordRule'
import {
  NUMBER_OF_CHARACTERS,
  NUMBER_OF_CAPITALS,
  NUMBER_OF_LOWERCASE,
  NUMBER_OF_NUMBERS,
  NUMBER_OF_SPECIAL_CHARACTERS,
  getPasswordRuleStatus,
  isLongEnough,
  containsCapital,
  containsLowercase,
  containsNumber,
  containsSpecialCharacter,
  getPasswordRulesAccessibilityLabel,
} from 'ui/designSystem/PasswordInput/helpers'

type Props = {
  password: string
  visible?: boolean
}

export const PasswordRules: FunctionComponent<Props> = ({ password, visible }) => {
  const getStatus = (rule: (password: string) => boolean) => getPasswordRuleStatus(password, rule)
  const hiddenAccessibleText = getPasswordRulesAccessibilityLabel(password)
  if (visible)
    return (
      <React.Fragment>
        <HiddenAccessibleText displayBlock>{hiddenAccessibleText}</HiddenAccessibleText>
        <RulesContainer {...hiddenFromScreenReader()} gap={1}>
          <PasswordRule title={NUMBER_OF_CHARACTERS} status={getStatus(isLongEnough)} />
          <PasswordRule title={NUMBER_OF_CAPITALS} status={getStatus(containsCapital)} />
          <PasswordRule title={NUMBER_OF_LOWERCASE} status={getStatus(containsLowercase)} />
          <PasswordRule title={NUMBER_OF_NUMBERS} status={getStatus(containsNumber)} />
          <PasswordRule
            title={NUMBER_OF_SPECIAL_CHARACTERS}
            status={getStatus(containsSpecialCharacter)}
          />
        </RulesContainer>
      </React.Fragment>
    )

  return null
}

const RulesContainer = styled(ViewGap)(({ theme }) => ({
  alignItems: 'flex-start',
  width: '100%',
  maxWidth: theme.forms.maxWidth,
  paddingTop: theme.designSystem.size.spacing.s,
}))
