/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React from 'react'

import { render, screen } from 'tests/utils/web'
import { PasswordRules } from 'ui/designSystem/PasswordInput/components/PasswordRules'

const renderPasswordRules = (password: string) =>
  render(<PasswordRules password={password} visible />)

// The web render helper mounts a SnackBarWrapper whose own live regions stay
// empty here, so joining every buffer only returns the password announcement.
const getAnnouncement = () =>
  screen
    .getAllByRole('status')
    .map((buffer) => buffer.textContent)
    .join('')

describe('<PasswordRules /> announcements', () => {
  it('should not announce anything when password is empty', () => {
    renderPasswordRules('')

    expect(getAnnouncement()).toEqual('')
  })

  it('should only announce the rules switching to a validated state', () => {
    const { rerender } = renderPasswordRules('')

    rerender(<PasswordRules password="azerty" visible />)

    expect(getAnnouncement()).toEqual('1 minuscule - critère validé')

    rerender(<PasswordRules password="azertyAZERTY" visible />)

    expect(getAnnouncement()).toEqual(
      '12 caractères - critère validé, 1 majuscule - critère validé'
    )
  })

  it('should not announce anything when no rule switches to a validated state', () => {
    const { rerender } = renderPasswordRules('')

    rerender(<PasswordRules password="az" visible />)
    rerender(<PasswordRules password="aze" visible />)

    expect(getAnnouncement()).toEqual('1 minuscule - critère validé')
  })
})
