/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

export type RequiredFormat = 'short' | 'long' | 'hidden'

export function getRequiredLabel(label?: RequiredFormat): string {
  const mapping: Record<RequiredFormat, string> = {
    short: '*',
    long: '\u00a0-\u00a0obligatoire',
    hidden: '',
  }

  return label ? mapping[label] : ''
}
