// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // introductionSidebar: [
  //   {
  //     type: 'doc',
  //     id: 'intro', // <-- J'utilise 'intro' qui est disponible
  //     label: 'Tutorial Intro', // Vous pouvez garder le label que vous voulez
  //   },
  //   {
  //     type: 'category',
  //     label: 'Tutorial Basics',
  //     items: [
  //       'tutorial-basics/create-a-document', // <-- Cet ID existe
  //       'tutorial-basics/create-a-blog-post', // <-- Cet ID existe
  //       // Ajoutez d'autres documents de base ici, en utilisant les IDs disponibles
  //       'tutorial-basics/congratulations',
  //       'tutorial-basics/create-a-page',
  //       'tutorial-basics/deploy-your-site',
  //       'tutorial-basics/markdown-features',
  //     ],
  //   },
  //   {
  //     type: 'category', // J'utilise une catégorie car vous avez plusieurs "tutorial-extras"
  //     label: 'Tutorial Extras',
  //     items: [
  //       'tutorial-extras/manage-docs-versions', // <-- Cet ID existe
  //       'tutorial-extras/translate-your-site', // <-- Cet ID existe
  //       // Si vous voulez inclure les "copy 2" ou "copy", ajustez les IDs ici aussi
  //       'tutorial-extras copy 2/manage-docs-versions',
  //       'tutorial-extras copy 2/translate-your-site',
  //     ],
  //   },
  // ],

  // testsSidebar: [
  //   // Ces IDs NE SONT PAS DANS VOTRE LISTE DES ID DISPONIBLES.
  //   // Vous devez créer les fichiers correspondants DANS votre dossier docs
  //   // (ex: docs/tests/e2e.md et docs/tests/unitaires.md)
  //   // AVANT de pouvoir les référencer ici.
  //   {
  //     type: 'doc',
  //     id: 'tests/e2e/e2e', // Cet ID n'existe PAS encore ! Créez le fichier docs/tests/e2e.md
  //     label: 'Tests E2E',
  //   },
  //   {
  //     type: 'doc',
  //     id: 'tests/unitaires/unitaires', // Cet ID n'existe PAS encore ! Créez le fichier docs/tests/unitaires.md
  //     label: 'Tests unitaires',
  //   },
  // ],
}
export default sidebars
