// This file is generated by scripts/generate_env_override_config.js — do not edit manually.
// Regenerate with: yarn generate:envOverrideConfig
import {
  EnvOverrideFirebaseConfig,
  EnvSwitchableConfig,
  SwitchableEnvironment,
} from 'libs/environment/envOverride/types'

export const ENV_OVERRIDE_CONFIG: Record<SwitchableEnvironment, EnvSwitchableConfig> = {
  testing: {
    API_BASE_URL: 'https://backend.testing.passculture.team',
    ALGOLIA_APPLICATION_ID: 'testingHXXTDUE7H0',
    ALGOLIA_SEARCH_API_PUBLIC_KEY: 'e6f3e382eaadae482499266cd9b6b6ac',
    ALGOLIA_ARTISTS_INDEX_NAME: 'testing-artists',
    ALGOLIA_CINE_CLUB_OFFERS_INDEX_NAME: 'cine club offers',
    ALGOLIA_MOST_LIKED_OFFERS_INDEX_NAME: 'most liked offers',
    ALGOLIA_OFFERS_INDEX_NAME: 'TESTING',
    ALGOLIA_OFFERS_INDEX_NAME_B: 'TESTING',
    ALGOLIA_SUGGESTIONS_INDEX_NAME: 'TESTING_query_suggestions',
    ALGOLIA_TOP_OFFERS_INDEX_NAME: 'TESTING',
    ALGOLIA_VENUES_INDEX_EXPERIMENTAL: 'venues-experimental',
    ALGOLIA_VENUES_INDEX_NAME: 'testing-venues',
    ALGOLIA_VENUES_INDEX_PLAYLIST_SEARCH: 'testing-venues',
    ALGOLIA_VENUES_INDEX_PLAYLIST_SEARCH_NEWEST: 'testing-venues',
    CONTENTFUL_SPACE_ID: '2bg01iqy0isv',
    CONTENTFUL_ENVIRONMENT: 'testing',
    CONTENTFUL_PUBLIC_ACCESS_TOKEN: 'NazW0Gl-T5S45ZDPRpbS_35KKIvgXrMG2DE3P2i-7fQ',
    GCP_IMAGE_COULD_STORAGE_NAME: 'passculture-metier-ehp-testing-assets-fine-grained',
    RESIZE_IMAGE_ON_DEMAND_URL: 'https://image-resizing.testing.passculture.team',
  },
  staging: {
    API_BASE_URL: 'https://backend.staging.passculture.team',
    ALGOLIA_APPLICATION_ID: 'testingHXXTDUE7H0',
    ALGOLIA_SEARCH_API_PUBLIC_KEY: 'e6f3e382eaadae482499266cd9b6b6ac',
    ALGOLIA_ARTISTS_INDEX_NAME: 'staging-artists',
    ALGOLIA_CINE_CLUB_OFFERS_INDEX_NAME: 'cine club offers',
    ALGOLIA_MOST_LIKED_OFFERS_INDEX_NAME: 'most liked offers',
    ALGOLIA_OFFERS_INDEX_NAME: 'STAGING',
    ALGOLIA_OFFERS_INDEX_NAME_B: 'PRODUCTION B',
    ALGOLIA_SUGGESTIONS_INDEX_NAME: 'STAGING_query_suggestions',
    ALGOLIA_TOP_OFFERS_INDEX_NAME: 'PRODUCTION Top offres',
    ALGOLIA_VENUES_INDEX_EXPERIMENTAL: 'venues-experimental',
    ALGOLIA_VENUES_INDEX_NAME: 'staging-venues',
    ALGOLIA_VENUES_INDEX_PLAYLIST_SEARCH: 'venues playlist search',
    ALGOLIA_VENUES_INDEX_PLAYLIST_SEARCH_NEWEST: 'venues playlist search newest',
    CONTENTFUL_SPACE_ID: '2bg01iqy0isv',
    CONTENTFUL_ENVIRONMENT: 'testing',
    CONTENTFUL_PUBLIC_ACCESS_TOKEN: 'NazW0Gl-T5S45ZDPRpbS_35KKIvgXrMG2DE3P2i-7fQ',
    GCP_IMAGE_COULD_STORAGE_NAME: 'passculture-metier-ehp-staging-assets-fine-grained',
    RESIZE_IMAGE_ON_DEMAND_URL: 'https://image-resizing.testing.passculture.team',
  },
  production: {
    API_BASE_URL: 'https://backend.passculture.app',
    ALGOLIA_APPLICATION_ID: 'E2IKXJ325N',
    ALGOLIA_SEARCH_API_PUBLIC_KEY: 'b451e96ac8d8323c321d8cc86e4a8b0a',
    ALGOLIA_ARTISTS_INDEX_NAME: 'artists',
    ALGOLIA_CINE_CLUB_OFFERS_INDEX_NAME: 'cine club offers',
    ALGOLIA_MOST_LIKED_OFFERS_INDEX_NAME: 'most liked offers',
    ALGOLIA_OFFERS_INDEX_NAME: 'PRODUCTION',
    ALGOLIA_OFFERS_INDEX_NAME_B: 'PRODUCTION B',
    ALGOLIA_SUGGESTIONS_INDEX_NAME: 'PRODUCTION_query_suggestions',
    ALGOLIA_TOP_OFFERS_INDEX_NAME: 'PRODUCTION Top offres',
    ALGOLIA_VENUES_INDEX_EXPERIMENTAL: 'venues-experimental',
    ALGOLIA_VENUES_INDEX_NAME: 'venues',
    ALGOLIA_VENUES_INDEX_PLAYLIST_SEARCH: 'venues playlist search',
    ALGOLIA_VENUES_INDEX_PLAYLIST_SEARCH_NEWEST: 'venues playlist search newest',
    CONTENTFUL_SPACE_ID: '2bg01iqy0isv',
    CONTENTFUL_ENVIRONMENT: 'master',
    CONTENTFUL_PUBLIC_ACCESS_TOKEN: 'oqkcaGmPpBLYASc-Tl2yTC1Jg6sK5_LviP0yrmUG8ug',
    GCP_IMAGE_COULD_STORAGE_NAME: 'passculture-metier-prod-production-assets-fine-grained',
    RESIZE_IMAGE_ON_DEMAND_URL: 'https://image-resizing.passculture.app',
  },
}

export const ENV_OVERRIDE_FIREBASE_CONFIG: Record<
  SwitchableEnvironment,
  EnvOverrideFirebaseConfig
> = {
  testing: {
    FIREBASE_PROJECTID: 'pc-native-testing',
    FIREBASE_API_PUBLIC_KEY: 'AIzaSyANVSEUDwZUt52X4kGlB6xDh5K7QdU3Nwc',
    FIREBASE_APPID: '1:557258398232:web:0a1cb6e123ac3d0b22816d',
  },
  staging: {
    FIREBASE_PROJECTID: 'pc-native-staging',
    FIREBASE_API_PUBLIC_KEY: 'AIzaSyDB4Vjg3_oxh4vSAeQYv9oSVh20kk6avn8',
    FIREBASE_APPID: '1:769039296481:web:495d2268d0b83a6cbe14a0',
  },
  production: {
    FIREBASE_PROJECTID: 'pc-native-production',
    FIREBASE_API_PUBLIC_KEY: 'AIzaSyCtHqbRqlMCFkeXEaidiOnrQ0xq_0gMXMc',
    FIREBASE_APPID: '1:378830896130:web:36273377e9720998307b1b',
  },
}
