import { Environment } from 'libs/environment/schema'

export const SWITCHABLE_ENVIRONMENTS = ['testing', 'staging', 'production'] as const

export type SwitchableEnvironment = (typeof SWITCHABLE_ENVIRONMENTS)[number]

export type EnvSwitchableConfig = Pick<
  Environment,
  | 'API_BASE_URL'
  | 'ALGOLIA_APPLICATION_ID'
  | 'ALGOLIA_SEARCH_API_PUBLIC_KEY'
  | 'ALGOLIA_ARTISTS_INDEX_NAME'
  | 'ALGOLIA_CINE_CLUB_OFFERS_INDEX_NAME'
  | 'ALGOLIA_MOST_LIKED_OFFERS_INDEX_NAME'
  | 'ALGOLIA_OFFERS_INDEX_NAME'
  | 'ALGOLIA_OFFERS_INDEX_NAME_B'
  | 'ALGOLIA_SUGGESTIONS_INDEX_NAME'
  | 'ALGOLIA_TOP_OFFERS_INDEX_NAME'
  | 'ALGOLIA_VENUES_INDEX_EXPERIMENTAL'
  | 'ALGOLIA_VENUES_INDEX_NAME'
  | 'ALGOLIA_VENUES_INDEX_PLAYLIST_SEARCH'
  | 'ALGOLIA_VENUES_INDEX_PLAYLIST_SEARCH_NEWEST'
  | 'CONTENTFUL_SPACE_ID'
  | 'CONTENTFUL_ENVIRONMENT'
  | 'CONTENTFUL_PUBLIC_ACCESS_TOKEN'
  | 'GCP_IMAGE_COULD_STORAGE_NAME'
  | 'RESIZE_IMAGE_ON_DEMAND_URL'
>

// Never applied to `env`: only used to target the remote config REST fetch.
export type EnvOverrideFirebaseConfig = Pick<
  Environment,
  'FIREBASE_PROJECTID' | 'FIREBASE_API_PUBLIC_KEY' | 'FIREBASE_APPID'
>

export const ENV_OVERRIDE_FIREBASE_CONFIG_KEYS = [
  'FIREBASE_PROJECTID',
  'FIREBASE_API_PUBLIC_KEY',
  'FIREBASE_APPID',
] as const satisfies readonly (keyof EnvOverrideFirebaseConfig)[]

export const ENV_SWITCHABLE_CONFIG_KEYS = [
  'API_BASE_URL',
  'ALGOLIA_APPLICATION_ID',
  'ALGOLIA_SEARCH_API_PUBLIC_KEY',
  'ALGOLIA_ARTISTS_INDEX_NAME',
  'ALGOLIA_CINE_CLUB_OFFERS_INDEX_NAME',
  'ALGOLIA_MOST_LIKED_OFFERS_INDEX_NAME',
  'ALGOLIA_OFFERS_INDEX_NAME',
  'ALGOLIA_OFFERS_INDEX_NAME_B',
  'ALGOLIA_SUGGESTIONS_INDEX_NAME',
  'ALGOLIA_TOP_OFFERS_INDEX_NAME',
  'ALGOLIA_VENUES_INDEX_EXPERIMENTAL',
  'ALGOLIA_VENUES_INDEX_NAME',
  'ALGOLIA_VENUES_INDEX_PLAYLIST_SEARCH',
  'ALGOLIA_VENUES_INDEX_PLAYLIST_SEARCH_NEWEST',
  'CONTENTFUL_SPACE_ID',
  'CONTENTFUL_ENVIRONMENT',
  'CONTENTFUL_PUBLIC_ACCESS_TOKEN',
  'GCP_IMAGE_COULD_STORAGE_NAME',
  'RESIZE_IMAGE_ON_DEMAND_URL',
] as const satisfies readonly (keyof EnvSwitchableConfig)[]
