/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React from 'react'

import { useHandleHover } from 'libs/hooks/useHandleHover'
import { InputTextContainerBase } from 'ui/designSystem/InputText/InputTextContainerBase'
import { InputTextContainerBaseProps } from 'ui/designSystem/InputText/types'

export const InputTextContainer: React.FC<InputTextContainerBaseProps> = (props) => {
  const hoverProps = useHandleHover()

  return <InputTextContainerBase {...props} {...hoverProps} isHover={hoverProps.isHover} />
}
