/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React from 'react'
import { View, ViewStyle } from 'react-native'
import styled, { DefaultTheme } from 'styled-components/native'

import { getSpacing, padding } from 'ui/theme'

type InputSize = 'small' | 'regular' | 'tall'

const SIZE_TO_HEIGHT = (theme: DefaultTheme) => ({
  small: theme.inputs.height.small,
  regular: theme.inputs.height.regular,
  tall: theme.inputs.height.tall,
})

type Props = {
  isError?: boolean
  isFocused?: boolean
  isDisabled?: boolean
  inputSize?: InputSize
  style?: ViewStyle
  children?: React.ReactNode
}

export const InputTextContainer: React.FC<Props> = ({
  children,
  inputSize = 'small',
  isDisabled = false,
  isError = false,
  isFocused = false,
  style,
}) => (
  <StyledView
    testID="styled-input-container"
    size={inputSize}
    isFocused={isFocused}
    isError={isError}
    isDisabled={isDisabled}
    style={style}>
    {children}
  </StyledView>
)

const getBorderColor = (
  theme: DefaultTheme,
  isFocused?: boolean,
  isDisabled?: boolean,
  isError?: boolean
) => {
  if (isDisabled) {
    return theme.designSystem.color.border.disabled
  }
  if (isFocused) {
    // maybe we need another semantic color.text.focused
    return theme.designSystem.color.outline.default
  }
  if (isError) {
    return theme.designSystem.color.border.error
  }
  return theme.designSystem.color.border.brandSecondary
}

const StyledView = styled(View)<{
  size: InputSize
  isFocused?: boolean
  isError?: boolean
  isDisabled?: boolean
}>(({ size, isFocused, isError, isDisabled, theme }) => {
  const heights = SIZE_TO_HEIGHT(theme)
  const horizontalPadding = 3

  return {
    height: heights[size],
    width: '100%',
    flexDirection: 'row',
    borderStyle: 'solid',
    borderWidth: getSpacing(0.25),
    borderColor: getBorderColor(theme, isFocused, isDisabled, isError),
    backgroundColor: isDisabled
      ? theme.designSystem.color.background.disabled
      : theme.designSystem.color.background.default,

    ...padding(0, horizontalPadding), // This assures that things don't move when the border width changes on focus
    alignItems: 'center',
    borderRadius: theme.designSystem.size.borderRadius.m,
    marginTop: theme.designSystem.size.spacing.xs,
  }
})
