/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

export { InputTextContainerBase as InputTextContainer } from './InputTextContainerBase'
