export type CheatcodesStackParamList = {
  // Menu
  CheatcodesMenu: undefined
  // Features
  CheatcodesNavigationAchievements: undefined
  CheatcodesNavigationBirthdayNotifications: undefined
  CheatcodesNavigationBookings: undefined
  CheatcodesNavigationBookOffer: undefined
  CheatcodesNavigationCulturalSurvey: undefined
  CheatcodesNavigationForceUpdate: undefined
  CheatcodesNavigationHome: undefined
  CheatcodesNavigationIdentityCheck: undefined
  CheatcodesNavigationInternal: undefined
  CheatcodesNavigationNewIdentificationFlow: undefined
  CheatcodesNavigationOnboarding: undefined
  CheatcodesNavigationProfile: undefined
  CheatcodesNavigationProfileTutorial: undefined
  CheatcodesNavigationShare: undefined
  CheatcodesNavigationSubscription: undefined
  CheatcodesNavigationTrustedDevice: undefined
  CheatcodesNavigationTutorial: undefined
  CheatcodesScreenBookingNotFound: undefined
  CheatcodesScreenCategoryThematicHomeHeader: undefined
  CheatcodesScreenDefaultThematicHomeHeader: undefined
  CheatcodesScreenHighlightThematicHomeHeader: undefined
  CheatcodesScreenMaintenance: undefined
  CheatcodesScreenNotEligibleEduConnect: undefined
  CheatcodesScreenRemoteBanners: undefined
  CheatcodesScreenTrustedDeviceInfos: undefined
  // Others
  CheatcodeScreenLoadingPage: undefined
  CheatcodesNavigationAccountManagement: undefined
  CheatcodesNavigationErrors: undefined
  CheatcodesNavigationGenericPages: undefined
  CheatcodesNavigationNotScreensPages: undefined
  CheatcodesNavigationSignUp: undefined
  CheatcodesScreenAccesLibre: undefined
  CheatcodesScreenLayoutExpiredLink: undefined
  CheatcodesScreenDebugInformations: undefined
  CheatcodesScreenFeatureFlags: undefined
  CheatcodesScreenGenericInfoPage: undefined
  CheatcodesScreenGenericErrorPage: undefined
  CheatcodesScreenSecondaryPageWithBlurHeader: undefined
  CheatcodesScreenGenericOfficialPage: undefined
  CheatcodesScreenPageWithHeader: undefined
  CheatcodesScreenNewCaledonia: undefined
  CheatcodesScreenRemoteConfig: undefined
}
