/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React from 'react'

import { AccessibilityRole } from 'libs/accessibilityRole/accessibilityRole'
import { render, screen } from 'tests/utils'
import { theme } from 'theme'
import { ProgressBar } from 'ui/designSystem/ProgressBar/ProgressBar'

describe('<ProgressBar />', () => {
  it('should render progressbar with accessible values', () => {
    render(<ProgressBar value={60} accessibilityLabel="Progression" />)

    expect(screen.getByLabelText('Progression')).toHaveProp(
      'accessibilityRole',
      AccessibilityRole.PROGRESSBAR
    )
    expect(screen.getByLabelText('Progression')).toHaveProp('accessibilityValue', {
      min: 0,
      max: 100,
      now: 60,
      text: '60%',
    })
  })

  it('should use design system tokens for track and progress', () => {
    render(<ProgressBar value={60} accessibilityLabel="Progression" />)

    expect(screen.getByTestId('progress-bar-track')).toHaveStyle({
      height: theme.designSystem.size.spacing.s,
      borderWidth: 1,
      borderColor: theme.designSystem.color.border.default,
      backgroundColor: theme.designSystem.color.background.subtle,
    })
    expect(screen.getByTestId('progress-bar-track').props.style).toEqual(
      expect.objectContaining({
        borderTopLeftRadius: theme.designSystem.size.borderRadius.pill,
        borderTopRightRadius: theme.designSystem.size.borderRadius.pill,
        borderBottomRightRadius: theme.designSystem.size.borderRadius.pill,
        borderBottomLeftRadius: theme.designSystem.size.borderRadius.pill,
      })
    )
    expect(screen.getByTestId('progress-bar-progress')).toHaveStyle({
      width: '60%',
      backgroundColor: theme.designSystem.color.background.brandPrimary,
    })
  })

  it('should compute percentage progress width', () => {
    render(<ProgressBar value={30} accessibilityLabel="Progression" />)

    expect(screen.getByTestId('progress-bar-progress')).toHaveStyle({ width: '30%' })
  })

  it('should compute steps progress width', () => {
    render(<ProgressBar type="steps" value={3} max={9} accessibilityLabel="Succès débloqués" />)

    expect(screen.getByTestId('progress-bar-progress')).toHaveStyle({ width: '33.33333333333333%' })
    expect(screen.getByLabelText('Succès débloqués')).toHaveProp('accessibilityValue', {
      min: 0,
      max: 9,
      now: 3,
      text: '3 sur 9',
    })
  })

  it('should clamp progress to min value', () => {
    render(<ProgressBar value={-10} labelPosition="right" accessibilityLabel="Progression" />)

    expect(screen.getByTestId('progress-bar-progress')).toHaveStyle({ width: '0%' })
    expect(screen.getByText('0%')).toBeOnTheScreen()
  })

  it('should clamp progress to max value', () => {
    render(<ProgressBar value={120} labelPosition="right" accessibilityLabel="Progression" />)

    expect(screen.getByTestId('progress-bar-progress')).toHaveStyle({ width: '100%' })
    expect(screen.getByText('100%')).toBeOnTheScreen()
  })

  it('should not display label by default', () => {
    render(<ProgressBar value={60} accessibilityLabel="Progression" />)

    expect(screen.queryByTestId('progress-bar-label')).not.toBeOnTheScreen()
  })

  it('should display label on right', () => {
    render(<ProgressBar value={60} labelPosition="right" accessibilityLabel="Progression" />)

    expect(screen.getByTestId('progress-bar-label')).toHaveTextContent('60%')
  })

  it('should display label on bottom', () => {
    render(<ProgressBar value={60} labelPosition="bottom" accessibilityLabel="Progression" />)

    expect(screen.getByTestId('progress-bar-label')).toHaveTextContent('60%')
  })

  it('should display steps label', () => {
    render(
      <ProgressBar
        type="steps"
        value={3}
        max={9}
        labelPosition="right"
        accessibilityLabel="Succès débloqués"
      />
    )

    expect(screen.getByTestId('progress-bar-label')).toHaveTextContent('3/9')
  })

  it('should use custom progress color', () => {
    render(
      <ProgressBar
        value={60}
        progressColor={theme.designSystem.color.background.danger}
        accessibilityLabel="Progression"
      />
    )

    expect(screen.getByTestId('progress-bar-progress')).toHaveStyle({
      backgroundColor: theme.designSystem.color.background.danger,
    })
  })
})
