/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import type { Meta } from '@storybook/react-vite'
import React from 'react'
import styled from 'styled-components/native'

import { ProgressBar } from 'ui/designSystem/ProgressBar/ProgressBar'
import { VariantsTemplate, type Variants, type VariantsStory } from 'ui/storybook/VariantsTemplate'

const meta: Meta<typeof ProgressBar> = {
  title: 'design system/ProgressBar',
  component: ProgressBar,
}
export default meta

const variantConfig: Variants<typeof ProgressBar> = [
  {
    label: 'Default',
    props: {
      value: 10,
      accessibilityLabel: 'Progression',
    },
  },
  ...[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100].map((value) => ({
    label: `Fill ${value}%`,
    props: {
      value,
      labelPosition: 'right' as const,
      accessibilityLabel: 'Progression',
    },
  })),
  {
    label: 'Label right',
    props: {
      value: 60,
      labelPosition: 'right',
      accessibilityLabel: 'Progression',
    },
  },
  {
    label: 'Label bottom',
    props: {
      value: 60,
      labelPosition: 'bottom',
      accessibilityLabel: 'Progression',
    },
  },
  {
    label: 'Steps',
    props: {
      type: 'steps',
      value: 3,
      max: 9,
      labelPosition: 'right',
      accessibilityLabel: 'Succès débloqués',
    },
  },
  {
    label: 'Clamped min',
    props: {
      value: -10,
      labelPosition: 'right',
      accessibilityLabel: 'Progression',
    },
  },
  {
    label: 'Clamped max',
    props: {
      value: 120,
      labelPosition: 'right',
      accessibilityLabel: 'Progression',
    },
  },
]

export const Template: VariantsStory<typeof ProgressBar> = {
  name: 'ProgressBar',
  render: (props) => (
    <ProgressBarContainer>
      <VariantsTemplate
        variants={variantConfig}
        Component={ProgressBar}
        defaultProps={{ ...props }}
      />
    </ProgressBarContainer>
  ),
}

const ProgressBarContainer = styled.View({
  width: 320,
})
