/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import { ViewProps } from 'react-native'

import { ColorsType } from 'theme/types'

export type ProgressBarType = 'percentage' | 'steps'

type ProgressBarLabelPosition = false | 'right' | 'bottom'

export type ProgressBarProps = ViewProps & {
  value: number
  max?: number
  type?: ProgressBarType
  labelPosition?: ProgressBarLabelPosition
  accessibilityLabel: string
  progressColor?: ColorsType
}
