/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React from 'react'
import { TextInput as RNTextInput } from 'react-native'

import { render, screen } from 'tests/utils'
import { TextInput } from 'ui/designSystem/TextInput/TextInput'
import { Search } from 'ui/svg/icons/Search'

describe('<TextInput />', () => {
  const myRef = React.createRef<RNTextInput>()

  it('should display label with asterisk when input required with symbol', () => {
    render(
      <TextInput onChangeText={jest.fn()} ref={myRef} label="E-mail" requiredIndicator="symbol" />
    )

    expect(screen.getByText('E-mail *', { hidden: true })).toBeOnTheScreen()
  })

  it('should display mandatory label when input required with text', () => {
    render(
      <TextInput onChangeText={jest.fn()} ref={myRef} label="E-mail" requiredIndicator="explicit" />
    )

    expect(screen.getByText('Obligatoire', { hidden: true })).toBeOnTheScreen()
  })

  it('should display format when defined', () => {
    render(
      <TextInput
        onChangeText={jest.fn()}
        ref={myRef}
        label="E-mail"
        description="Exemple : toto@email.com"
      />
    )

    expect(screen.getByText('Exemple : toto@email.com', { hidden: true })).toBeOnTheScreen()
  })

  it('should display left icon when defined', () => {
    render(
      <TextInput
        label="E-mail"
        onChangeText={jest.fn()}
        ref={myRef}
        leftComponent={<Search testID="leftIcon" />}
      />
    )

    expect(screen.getByTestId('leftIcon')).toBeOnTheScreen()
  })

  it('should display right button when defined', () => {
    render(
      <TextInput
        label="E-mail"
        onChangeText={jest.fn()}
        ref={myRef}
        rightButton={{ icon: Search, accessibilityLabel: 'My right button', onPress: jest.fn() }}
      />
    )

    expect(screen.getByLabelText('My right button')).toBeOnTheScreen()
  })

  it('should display error message when defined', () => {
    render(
      <TextInput label="E-mail" onChangeText={jest.fn()} ref={myRef} errorMessage="Error !!!" />
    )

    expect(screen.getByText('Error !!!')).toBeOnTheScreen()
  })

  it('should display character count when defined', () => {
    render(<TextInput label="E-mail" onChangeText={jest.fn()} ref={myRef} characterCount={10} />)

    expect(screen.getByText('0/10')).toBeOnTheScreen()
  })
})
