/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

export { TextInputContainerBase as TextInputContainer } from './TextInputContainerBase'
