/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import type { Meta } from '@storybook/react-vite'
import React from 'react'
import { styled } from 'styled-components/native'

import { VariantsTemplate, type Variants, type VariantsStory } from 'ui/storybook/VariantsTemplate'
import { Eye } from 'ui/svg/icons/Eye'
import { Search } from 'ui/svg/icons/Search'

import { TextInput } from './TextInput'

const meta: Meta<typeof TextInput> = {
  title: 'design system/inputs/TextInput',
  component: TextInput,
}
export default meta

const SearchIcon = styled(Search).attrs(({ theme }) => ({
  color: theme.designSystem.color.icon.subtle,
  size: theme.icons.sizes.smaller,
}))``

const baseProps = {
  label: 'Label',
  description: 'Format',
}

const variantConfig: Variants<typeof TextInput> = [
  {
    label: 'TextInput',
    props: { ...baseProps },
  },
  {
    label: 'TextInput with icon',
    props: { ...baseProps, leftComponent: <SearchIcon /> },
  },
  {
    label: 'Disabled TextInput',
    props: { ...baseProps, disabled: true },
  },
  {
    label: 'Required TextInput with symbol',
    props: { ...baseProps, requiredIndicator: 'symbol' },
  },
  {
    label: 'Required TextInput with text',
    props: { ...baseProps, requiredIndicator: 'explicit' },
  },
  {
    label: 'TextInput with error',
    props: { ...baseProps, errorMessage: 'Error message' },
  },
  {
    label: 'TextInput with long error',
    props: {
      ...baseProps,
      errorMessage:
        'L’e-mail renseigné est incorrect. Exemple de format attendu\u00a0: edith.piaf@email.fr',
    },
  },
  {
    label: 'TextInput with inside rightButton',
    props: {
      ...baseProps,
      rightButton: {
        icon: Eye,
        onPress: () => alert('Do nothing'),
        accessibilityLabel: 'Afficher le mot de passe',
      },
    },
  },
  {
    label: 'TextInput with character count',
    props: { ...baseProps, characterCount: 10 },
  },
  {
    label: 'TextInput with character count and error message',
    props: { ...baseProps, characterCount: 10, errorMessage: 'Error message' },
  },
  {
    label: 'TextInput with character count and long error message',
    props: {
      ...baseProps,
      characterCount: 10,
      errorMessage:
        'L’e-mail renseigné est incorrect. Exemple de format attendu\u00a0: edith.piaf@email.fr',
    },
  },
]

export const Template: VariantsStory<typeof TextInput> = {
  name: 'TextInput',
  render: (props) => (
    <VariantsTemplate variants={variantConfig} Component={TextInput} defaultProps={{ ...props }} />
  ),
}
