/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import { FunctionComponent, ReactElement } from 'react'

import { variantIcons } from 'ui/designSystem/Tag/Tag.variants'
import { TagVariant } from 'ui/designSystem/Tag/types'
import { AccessibleIcon } from 'ui/svg/icons/types'

export function getTagIcon(
  variant: TagVariant,
  icon?: FunctionComponent<AccessibleIcon> | ReactElement
): FunctionComponent<AccessibleIcon> | ReactElement {
  const forcedVariants = [
    TagVariant.BOOKCLUB,
    TagVariant.CINECLUB,
    TagVariant.HEADLINE,
    TagVariant.LIKE,
  ]
  return forcedVariants.includes(variant) ? variantIcons[variant] : icon
}
