/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import { getAfterTextParts } from 'ui/designSystem/TextWithLink/getAfterTextParts'

describe('getAfterTextParts', () => {
  it('should split first word when it should stay close to the link', () => {
    expect(
      getAfterTextParts({ keepFirstWordWithLink: true, text: 'version 1.386.1 du pass Culture.' })
    ).toEqual({
      firstWord: 'version',
      trailingText: '1.386.1 du pass Culture.',
    })
  })

  it('should return the full text as trailing text when first word should not stay close to the link', () => {
    expect(
      getAfterTextParts({ keepFirstWordWithLink: false, text: 'version 1.386.1 du pass Culture.' })
    ).toEqual({
      firstWord: undefined,
      trailingText: 'version 1.386.1 du pass Culture.',
    })
  })

  it('should trim text before splitting', () => {
    expect(getAfterTextParts({ keepFirstWordWithLink: true, text: '  version 1.386.1  ' })).toEqual(
      {
        firstWord: 'version',
        trailingText: '1.386.1',
      }
    )
  })

  it('should return only first word when text has a single word', () => {
    expect(getAfterTextParts({ keepFirstWordWithLink: true, text: 'version' })).toEqual({
      firstWord: 'version',
      trailingText: undefined,
    })
  })
})
