/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

export const getBeforeTextParts = ({
  keepLastWordWithLink,
  text,
}: {
  keepLastWordWithLink: boolean
  text: string
}) => {
  if (keepLastWordWithLink) return splitLastWord(text)

  return {
    leadingText: text.trim(),
    lastWord: undefined,
  }
}

const splitLastWord = (text: string) => {
  const trimmedText = text.trim()
  const lastSpaceIndex = trimmedText.lastIndexOf(' ')

  if (lastSpaceIndex === -1) return { leadingText: undefined, lastWord: trimmedText }

  return {
    leadingText: trimmedText.slice(0, lastSpaceIndex),
    lastWord: trimmedText.slice(lastSpaceIndex + 1),
  }
}
