/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import { getBeforeTextParts } from 'ui/designSystem/TextWithLink/getBeforeTextParts'

describe('getBeforeTextParts', () => {
  it('should split last word when it should stay close to the link', () => {
    expect(
      getBeforeTextParts({
        keepLastWordWithLink: true,
        text: 'Pour plus d’informations, nous t’invitons à consulter notre',
      })
    ).toEqual({
      leadingText: 'Pour plus d’informations, nous t’invitons à consulter',
      lastWord: 'notre',
    })
  })

  it('should return the full text as leading text when last word should not stay close to the link', () => {
    expect(
      getBeforeTextParts({
        keepLastWordWithLink: false,
        text: 'Pour plus d’informations, nous t’invitons à consulter notre',
      })
    ).toEqual({
      leadingText: 'Pour plus d’informations, nous t’invitons à consulter notre',
      lastWord: undefined,
    })
  })

  it('should trim text before splitting', () => {
    expect(getBeforeTextParts({ keepLastWordWithLink: true, text: '  consulter notre  ' })).toEqual(
      {
        leadingText: 'consulter',
        lastWord: 'notre',
      }
    )
  })

  it('should return only last word when text has a single word', () => {
    expect(getBeforeTextParts({ keepLastWordWithLink: true, text: 'notre' })).toEqual({
      leadingText: undefined,
      lastWord: 'notre',
    })
  })
})
