/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React from 'react'
import { StyleProp, ViewStyle } from 'react-native'
import styled from 'styled-components/native'

import { TextColorKey } from 'theme/types'
import { Link } from 'ui/designSystem/Link/Link'
import { LinkProps } from 'ui/designSystem/Link/types'
import { getAfterTextParts } from 'ui/designSystem/TextWithLink/getAfterTextParts'
import { getBeforeTextParts } from 'ui/designSystem/TextWithLink/getBeforeTextParts'
import { Typo } from 'ui/theme'

type TextWithLinkProps = {
  beforeText?: string
  text?: string
  linkLabel: string
  afterText?: string
  keepFirstWordWithLink?: boolean
  keepLastWordWithLink?: boolean
  surroundingTextColor?: TextColorKey
  typography?: keyof typeof Typo
  style?: StyleProp<ViewStyle>
  renderLink?: (props: Omit<LinkProps, 'label'> & { label: string }) => React.ReactNode
} & Omit<LinkProps, 'label'>

export function TextWithLink({
  beforeText,
  text,
  linkLabel,
  afterText,
  keepFirstWordWithLink = true,
  keepLastWordWithLink = false,
  surroundingTextColor = 'default',
  typography = 'Body',
  style,
  renderLink,
  ...linkProps
}: TextWithLinkProps) {
  const textBeforeLink = beforeText ?? text
  const beforeTextParts = textBeforeLink
    ? getBeforeTextParts({ keepLastWordWithLink, text: textBeforeLink })
    : undefined
  const afterTextParts = afterText
    ? getAfterTextParts({ keepFirstWordWithLink, text: afterText })
    : undefined
  const TextComponent = Typo[typography]
  const link = renderLink ? (
    renderLink({ label: linkLabel, ...linkProps })
  ) : (
    <Link label={linkLabel} {...linkProps} />
  )

  return (
    <Container style={style}>
      {beforeTextParts?.leadingText ? (
        <TextComponent color={surroundingTextColor}>{beforeTextParts.leadingText}</TextComponent>
      ) : null}
      {beforeTextParts?.lastWord ? (
        <LastWordWithLink>
          <TextComponent color={surroundingTextColor}>{beforeTextParts.lastWord}</TextComponent>
          {link}
        </LastWordWithLink>
      ) : (
        link
      )}
      {afterTextParts?.firstWord ? (
        <TextComponent color={surroundingTextColor}>{afterTextParts.firstWord}</TextComponent>
      ) : null}
      {afterTextParts?.trailingText ? (
        <TextComponent color={surroundingTextColor}>{afterTextParts.trailingText}</TextComponent>
      ) : null}
    </Container>
  )
}

const Container = styled.View(({ theme }) => ({
  alignItems: 'center',
  columnGap: theme.designSystem.size.spacing.xs,
  flexDirection: 'row',
  flexWrap: 'wrap',
  rowGap: 0,
}))

const LastWordWithLink = styled.View(({ theme }) => ({
  alignItems: 'center',
  columnGap: theme.designSystem.size.spacing.xs,
  flexDirection: 'row',
  flexShrink: 1,
}))
