import { PathConfigMap } from '@react-navigation/native/lib/typescript/src'

import { ProfileStackParamList } from 'features/navigation/ProfileStackNavigator/types'

export const profileStackNavigatorPathConfig: PathConfigMap<ProfileStackParamList> = {
  Accessibility: 'accessibilite',
  AccessibilityEngagement: 'accessibilite/engagements',
  AccessibilityActionPlan: 'accessibilite/plan-d-actions',
  AccessibilityDeclarationMobileAndroid: 'accessibilite/declaration-accessibilite-mobile-android',
  AccessibilityDeclarationMobileIOS: 'accessibilite/declaration-accessibilite-mobile-ios',
  AccessibilityDeclarationWeb: 'accessibilite/declaration-accessibilite-web',
  RecommendedPaths: 'accessibilite/parcours-recommandes',
  SiteMapScreen: 'accessibilite/plan-du-site',
  NotificationsSettings: 'profil/notifications',
  DeleteProfileReason: 'profil/suppression/raison',
  DeleteProfileContactSupport: 'profil/suppression/support',
  DeleteProfileEmailHacked: 'profil/suppression/email-pirate',
  DeleteProfileAccountHacked: 'profil/suppression/compte-pirate',
  DeleteProfileAccountNotDeletable: 'profil/suppression/information',
  DebugScreen: 'profil/debuggage',
  ConfirmDeleteProfile: 'profil/suppression',
  DeleteProfileConfirmation: 'profile/suppression/confirmation',
  DeleteProfileSuccess: 'profile/suppression/succes',
  DeactivateProfileSuccess: 'profile/desactivation/succes',
  SuspendAccountConfirmationWithoutAuthentication: 'profile/suppression/demande-confirmation',
  SuspendAccountConfirmation: 'suspension-compte/confirmation',
  ChangeStatus: 'profil/modification-statut',
  ChangeCity: 'profil/modification-ville',
  ChangeAddress: 'profil/modification-adresse',
  ChangeEmail: 'profil/modification-email',
  TrackEmailChange: 'profil/suivi-modification-email',
  LegalNotices: 'notices-legales',
  PersonalData: 'profil/donnees-personnelles',
  ValidateEmailChange: 'changement-email/validation',
  ChangePassword: 'profil/modification-mot-de-passe',
  FeedbackInApp: 'profil/formulaire-suggestion',
  DisplayPreference: 'profil/preference-affichage',
  ConsentSettings: 'profil/confidentialite',
  ConfirmChangeEmail: 'changement-email/confirmation',
  ChangeEmailSetPassword: 'profil/creation-mot-de-passe',
  NewEmailSelection: 'profil/nouvelle-adresse-email',
  ProfileTutorialAgeInformationCredit: 'profil/tutoriel',
  MandatoryUpdatePersonalData: 'profil/mise-a-jour-informations-personnelles',
  UpdatePersonalDataConfirmation: 'profil/confirmation-mise-a-jour-informations-personnelles',
  ProfileInformationValidationUpdate: 'profil/verification-informations-personnelles',
}
