export { Brush as ArtisticCourseIcon } from '../bicolor/Brush'
export { Bookstore as BookstoreIcon } from '../bicolor/Bookstore'
export { Micro as ConcertHallIcon } from '../bicolor/Micro'
export { Brush as CreativeArtsStoreIcon } from '../bicolor/Brush'
export { CulturalCentre as CulturalCentreIcon } from '../bicolor/CulturalCentre'
export { Digital as DigitalIcon } from '../bicolor/Digital'
export { Festival } from '../bicolor/Festival'
export { VideoGame as GamesIcon } from '../bicolor/VideoGame'
export { Book as LibraryIcon } from '../bicolor/Book'
export { Cinema as MovieIcon } from '../bicolor/Cinema'
export { Museum as MuseumIcon } from '../bicolor/Museum'
export { Piano as MusicalInstrumentStoreIcon } from '../bicolor/Piano'
export { All as OtherIcon } from '../bicolor/All'
export { Castle as PatrimonyTourismIcon } from '../bicolor/Castle'
export { PerformingArts } from '../bicolor/PerformingArts'
export { Turntable as RecordStoreIcon } from '../bicolor/Turntable'
export { ChemistryTools as ScientificCultureIcon } from '../bicolor/ChemistryTools'
export { Landscape as VisualArtIcon } from '../bicolor/Landscape'
