export const DEFAULT_FIFTEEN_YEARS_OLD_AMOUNT_V2 = 20_00
export const DEFAULT_FIFTEEN_YEARS_OLD_AMOUNT_V3 = 0

export const DEFAULT_SIXTEEN_YEARS_OLD_AMOUNT_V2 = 30_00
export const DEFAULT_SIXTEEN_YEARS_OLD_AMOUNT_V3 = 0

export const DEFAULT_SEVENTEEN_YEARS_OLD_AMOUNT_V2 = 30_00
export const DEFAULT_SEVENTEEN_YEARS_OLD_AMOUNT_V3 = 50_00

export const DEFAULT_EIGHTEEN_YEARS_OLD_AMOUNT_V2 = 300_00
export const DEFAULT_EIGHTEEN_YEARS_OLD_AMOUNT_V3 = 150_00

export const DEFAULT_EIGHTEEN_YEARS_OLD_DIGITAL_AMOUNT_V2 = 100_00
