export const DEFAULT_FIFTEEN_YEARS_OLD_AMOUNT = 20_00
export const DEFAULT_SIXTEEN_YEARS_OLD_AMOUNT = 30_00
export const DEFAULT_SEVENTEEN_YEARS_OLD_AMOUNT = 30_00
export const DEFAULT_EIGHTEEN_YEARS_OLD_AMOUNT = 300_00
export const DEFAULT_EIGHTEEN_YEARS_OLD_DIGITAL_AMOUNT = 100_00
