/**
 * Last update 2025
 * https://explore.data.gouv.fr/fr/datasets/58c984b088ee386cdb1261f3/#/resources/4cd91b1b-684b-44e0-af86-77b623fcb5f2
 * Converted with: https://www.convertcsv.com/csv-to-json.htm
 * Keep only 1 entry for each COG (keep the most recent one)
 */

type INSEE_COUNTRY = {
  COG: number
  CRPAY: number | null
  LIBCOG: string
  LIBENR: string
  DATE_DEBUT: string
  DATE_FIN: string
}

export const INSEE_COUNTRY_LIST: INSEE_COUNTRY[] = [
  {
    COG: 99100,
    CRPAY: null,
    LIBCOG: 'France',
    LIBENR: 'République française',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99101,
    CRPAY: null,
    LIBCOG: 'Danemark',
    LIBENR: 'Royaume du Danemark',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99102,
    CRPAY: null,
    LIBCOG: 'Islande',
    LIBENR: 'Islande',
    DATE_DEBUT: '2022-10-12',
    DATE_FIN: '',
  },
  {
    COG: 99103,
    CRPAY: null,
    LIBCOG: 'Norvège',
    LIBENR: 'Royaume de Norvège',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99104,
    CRPAY: null,
    LIBCOG: 'Suède',
    LIBENR: 'Royaume de Suède',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99105,
    CRPAY: null,
    LIBCOG: 'Finlande',
    LIBENR: 'République de Finlande',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99106,
    CRPAY: null,
    LIBCOG: 'Estonie',
    LIBENR: 'République d’Estonie',
    DATE_DEBUT: '1991-08-20',
    DATE_FIN: '',
  },
  {
    COG: 99107,
    CRPAY: null,
    LIBCOG: 'Lettonie',
    LIBENR: 'République de Lettonie',
    DATE_DEBUT: '1991-11-08',
    DATE_FIN: '',
  },
  {
    COG: 99108,
    CRPAY: null,
    LIBCOG: 'Lituanie',
    LIBENR: 'République de Lituanie',
    DATE_DEBUT: '1990-03-10',
    DATE_FIN: '',
  },
  {
    COG: 99109,
    CRPAY: null,
    LIBCOG: 'Allemagne',
    LIBENR: 'République fédérale d’Allemagne',
    DATE_DEBUT: '1990-10-03',
    DATE_FIN: '',
  },
  {
    COG: 99110,
    CRPAY: null,
    LIBCOG: 'Autriche',
    LIBENR: 'République d’Autriche',
    DATE_DEBUT: '1945-04-27',
    DATE_FIN: '',
  },
  {
    COG: 99111,
    CRPAY: null,
    LIBCOG: 'Bulgarie',
    LIBENR: 'République de Bulgarie',
    DATE_DEBUT: '1990-11-15',
    DATE_FIN: '',
  },
  {
    COG: 99112,
    CRPAY: null,
    LIBCOG: 'Hongrie',
    LIBENR: 'Hongrie',
    DATE_DEBUT: '2012-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99113,
    CRPAY: null,
    LIBCOG: 'Liechtenstein',
    LIBENR: 'Principauté du Liechtenstein',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99114,
    CRPAY: null,
    LIBCOG: 'Roumanie',
    LIBENR: 'Roumanie',
    DATE_DEBUT: '1989-12-22',
    DATE_FIN: '',
  },
  {
    COG: 99115,
    CRPAY: null,
    LIBCOG: 'Tchécoslovaquie',
    LIBENR: 'République fédérale tchèque et slovaque',
    DATE_DEBUT: '1990-04-23',
    DATE_FIN: '1993-01-01',
  },
  {
    COG: 99116,
    CRPAY: null,
    LIBCOG: 'Tchéquie',
    LIBENR: 'République tchèque',
    DATE_DEBUT: '2019-04-21',
    DATE_FIN: '',
  },
  {
    COG: 99117,
    CRPAY: null,
    LIBCOG: 'Slovaquie',
    LIBENR: 'République slovaque',
    DATE_DEBUT: '1993-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99118,
    CRPAY: null,
    LIBCOG: 'Bosnie-Herzégovine',
    LIBENR: 'Bosnie-Herzégovine',
    DATE_DEBUT: '1995-12-14',
    DATE_FIN: '',
  },
  {
    COG: 99119,
    CRPAY: null,
    LIBCOG: 'Croatie',
    LIBENR: 'République de Croatie',
    DATE_DEBUT: '1991-06-25',
    DATE_FIN: '',
  },
  {
    COG: 99120,
    CRPAY: null,
    LIBCOG: 'Monténégro',
    LIBENR: 'Monténégro',
    DATE_DEBUT: '2006-06-08',
    DATE_FIN: '',
  },
  {
    COG: 99121,
    CRPAY: null,
    LIBCOG: 'Serbie',
    LIBENR: 'République de Serbie',
    DATE_DEBUT: '2006-06-08',
    DATE_FIN: '',
  },
  {
    COG: 99122,
    CRPAY: null,
    LIBCOG: 'Pologne',
    LIBENR: 'République de Pologne',
    DATE_DEBUT: '1989-12-31',
    DATE_FIN: '',
  },
  {
    COG: 99123,
    CRPAY: null,
    LIBCOG: 'Russie',
    LIBENR: 'Fédération de Russie',
    DATE_DEBUT: '1991-12-25',
    DATE_FIN: '',
  },
  {
    COG: 99124,
    CRPAY: 99208,
    LIBCOG: 'Turquie d’Europe',
    LIBENR: 'Turquie d’Europe',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '1966-01-01',
  },
  {
    COG: 99125,
    CRPAY: null,
    LIBCOG: 'Albanie',
    LIBENR: 'République d’Albanie',
    DATE_DEBUT: '1991-04-29',
    DATE_FIN: '',
  },
  {
    COG: 99126,
    CRPAY: null,
    LIBCOG: 'Grèce',
    LIBENR: 'République hellénique',
    DATE_DEBUT: '1974-12-08',
    DATE_FIN: '',
  },
  {
    COG: 99127,
    CRPAY: null,
    LIBCOG: 'Italie',
    LIBENR: 'République italienne',
    DATE_DEBUT: '1946-06-02',
    DATE_FIN: '',
  },
  {
    COG: 99128,
    CRPAY: null,
    LIBCOG: 'Saint-Marin',
    LIBENR: 'République de Saint-Marin',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99129,
    CRPAY: null,
    LIBCOG: 'Vatican',
    LIBENR: 'Saint-Siège ou Vatican',
    DATE_DEBUT: '2019-04-21',
    DATE_FIN: '',
  },
  {
    COG: 99130,
    CRPAY: null,
    LIBCOG: 'Andorre',
    LIBENR: 'Principauté d’Andorre',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99131,
    CRPAY: null,
    LIBCOG: 'Belgique',
    LIBENR: 'Royaume de Belgique',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99132,
    CRPAY: null,
    LIBCOG: 'Royaume-Uni',
    LIBENR: 'Royaume-Uni de Grande-Bretagne et d’Irlande du Nord',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99133,
    CRPAY: 99132,
    LIBCOG: 'Territoires britanniques en Méditerranée',
    LIBENR: 'Gibraltar, Akrotiri et Dhekelia',
    DATE_DEBUT: '1964-09-21',
    DATE_FIN: '',
  },
  {
    COG: 99134,
    CRPAY: null,
    LIBCOG: 'Espagne',
    LIBENR: 'Royaume d’Espagne',
    DATE_DEBUT: '1975-11-22',
    DATE_FIN: '',
  },
  {
    COG: 99135,
    CRPAY: null,
    LIBCOG: 'Pays-Bas',
    LIBENR: 'Royaume des Pays-Bas',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99136,
    CRPAY: null,
    LIBCOG: 'Irlande',
    LIBENR: 'Irlande',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99137,
    CRPAY: null,
    LIBCOG: 'Luxembourg',
    LIBENR: 'Grand-Duché du Luxembourg',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99138,
    CRPAY: null,
    LIBCOG: 'Monaco',
    LIBENR: 'Principauté de Monaco',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99139,
    CRPAY: null,
    LIBCOG: 'Portugal',
    LIBENR: 'République portugaise',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99140,
    CRPAY: null,
    LIBCOG: 'Suisse',
    LIBENR: 'Confédération suisse',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99141,
    CRPAY: null,
    LIBCOG: 'Allemagne de l’Est',
    LIBENR: 'République démocratique allemande',
    DATE_DEBUT: '1949-05-23',
    DATE_FIN: '1990-10-03',
  },
  {
    COG: 99142,
    CRPAY: null,
    LIBCOG: 'Allemagne de l’Ouest',
    LIBENR: 'République fédérale d’Allemagne',
    DATE_DEBUT: '1949-05-23',
    DATE_FIN: '1990-10-03',
  },
  {
    COG: 99143,
    CRPAY: null,
    LIBCOG: 'Chypre',
    LIBENR: 'République de Chypre',
    DATE_DEBUT: '1960-10-01',
    DATE_FIN: '1994-01-01',
  },
  {
    COG: 99144,
    CRPAY: null,
    LIBCOG: 'Malte',
    LIBENR: 'République de Malte',
    DATE_DEBUT: '1974-12-13',
    DATE_FIN: '',
  },
  {
    COG: 99145,
    CRPAY: null,
    LIBCOG: 'Slovénie',
    LIBENR: 'République de Slovénie',
    DATE_DEBUT: '1991-06-25',
    DATE_FIN: '',
  },
  {
    COG: 99148,
    CRPAY: null,
    LIBCOG: 'Biélorussie',
    LIBENR: 'République de Biélorussie',
    DATE_DEBUT: '1991-08-25',
    DATE_FIN: '',
  },
  {
    COG: 99151,
    CRPAY: null,
    LIBCOG: 'Moldavie',
    LIBENR: 'République de Moldavie',
    DATE_DEBUT: '1991-08-27',
    DATE_FIN: '',
  },
  {
    COG: 99155,
    CRPAY: null,
    LIBCOG: 'Ukraine',
    LIBENR: 'Ukraine',
    DATE_DEBUT: '1991-08-24',
    DATE_FIN: '',
  },
  {
    COG: 99156,
    CRPAY: null,
    LIBCOG: 'Macédoine du Nord',
    LIBENR: 'République de Macédoine du Nord',
    DATE_DEBUT: '2019-02-12',
    DATE_FIN: '',
  },
  {
    COG: 99157,
    CRPAY: null,
    LIBCOG: 'Kosovo',
    LIBENR: 'République du Kosovo',
    DATE_DEBUT: '2007-02-08',
    DATE_FIN: '',
  },
  {
    COG: 99158,
    CRPAY: 99101,
    LIBCOG: 'Féroé',
    LIBENR: 'Îles Féroé',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99159,
    CRPAY: 99103,
    LIBCOG: 'Territoires norvégiens en Atlantique Nord',
    LIBENR: 'Île Jan-Mayen, Svalbard',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99160,
    CRPAY: 99105,
    LIBCOG: 'Åland',
    LIBENR: 'Îles Åland',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99161,
    CRPAY: 99132,
    LIBCOG: 'Dépendances de la Couronne britannique',
    LIBENR: 'Île de Man, Jersey, Guernesey',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99162,
    CRPAY: 99134,
    LIBCOG: 'Île des Faisans',
    LIBENR: 'Île des Faisans',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99201,
    CRPAY: null,
    LIBCOG: 'Arabie saoudite',
    LIBENR: 'Royaume d’Arabie saoudite',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99202,
    CRPAY: null,
    LIBCOG: 'Yémen du Nord',
    LIBENR: 'République arabe du Yémen',
    DATE_DEBUT: '1962-09-27',
    DATE_FIN: '1990-01-01',
  },
  {
    COG: 99203,
    CRPAY: null,
    LIBCOG: 'Irak',
    LIBENR: 'République d’Irak',
    DATE_DEBUT: '1958-07-14',
    DATE_FIN: '',
  },
  {
    COG: 99204,
    CRPAY: null,
    LIBCOG: 'Iran',
    LIBENR: 'République islamique d’Iran',
    DATE_DEBUT: '1979-04-01',
    DATE_FIN: '',
  },
  {
    COG: 99205,
    CRPAY: null,
    LIBCOG: 'Liban',
    LIBENR: 'République libanaise',
    DATE_DEBUT: '1943-11-22',
    DATE_FIN: '',
  },
  {
    COG: 99206,
    CRPAY: null,
    LIBCOG: 'Syrie',
    LIBENR: 'République arabe syrienne',
    DATE_DEBUT: '1961-09-28',
    DATE_FIN: '',
  },
  {
    COG: 99207,
    CRPAY: null,
    LIBCOG: 'Israël',
    LIBENR: 'État d’Israël',
    DATE_DEBUT: '1948-05-14',
    DATE_FIN: '',
  },
  {
    COG: 99208,
    CRPAY: null,
    LIBCOG: 'Turquie',
    LIBENR: 'République de Turquie',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99209,
    CRPAY: 99123,
    LIBCOG: 'Sibérie',
    LIBENR: 'Sibérie',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '1943-01-01',
  },
  {
    COG: 99210,
    CRPAY: 99123,
    LIBCOG: 'Turkestan russe',
    LIBENR: 'Turkestan russe',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '1943-01-01',
  },
  {
    COG: 99211,
    CRPAY: 99123,
    LIBCOG: 'Kamtchatcka',
    LIBENR: 'Kamtchatcka',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '1943-01-01',
  },
  {
    COG: 99212,
    CRPAY: null,
    LIBCOG: 'Afghanistan',
    LIBENR: 'République islamique d’Afghanistan',
    DATE_DEBUT: '2004-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99213,
    CRPAY: null,
    LIBCOG: 'Pakistan',
    LIBENR: 'République islamique du Pakistan',
    DATE_DEBUT: '1956-03-23',
    DATE_FIN: '',
  },
  {
    COG: 99214,
    CRPAY: null,
    LIBCOG: 'Bhoutan',
    LIBENR: 'Royaume du Bhoutan',
    DATE_DEBUT: '1949-08-08',
    DATE_FIN: '',
  },
  {
    COG: 99215,
    CRPAY: null,
    LIBCOG: 'Népal',
    LIBENR: 'Népal',
    DATE_DEBUT: '2020-12-14',
    DATE_FIN: '',
  },
  {
    COG: 99216,
    CRPAY: null,
    LIBCOG: 'Chine',
    LIBENR: 'République populaire de Chine',
    DATE_DEBUT: '1949-10-01',
    DATE_FIN: '',
  },
  {
    COG: 99217,
    CRPAY: null,
    LIBCOG: 'Japon',
    LIBENR: 'Japon',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99218,
    CRPAY: 99217,
    LIBCOG: 'Mandchoukouo',
    LIBENR: 'Mandchoukouo',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '1945-08-18',
  },
  {
    COG: 99219,
    CRPAY: null,
    LIBCOG: 'Thaïlande',
    LIBENR: 'Royaume de Thaïlande',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99220,
    CRPAY: null,
    LIBCOG: 'Philippines',
    LIBENR: 'République des Philippines',
    DATE_DEBUT: '1946-07-04',
    DATE_FIN: '',
  },
  {
    COG: 99221,
    CRPAY: 99132,
    LIBCOG: 'Territoires britanniques au Proche-Orient',
    LIBENR: 'États de la Trêve',
    DATE_DEBUT: '1971-09-03',
    DATE_FIN: '1971-12-02',
  },
  {
    COG: 99222,
    CRPAY: null,
    LIBCOG: 'Jordanie',
    LIBENR: 'Royaume hachémite de Jordanie',
    DATE_DEBUT: '1946-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99223,
    CRPAY: null,
    LIBCOG: 'Inde',
    LIBENR: 'République de l’Inde',
    DATE_DEBUT: '1950-01-26',
    DATE_FIN: '',
  },
  {
    COG: 99224,
    CRPAY: null,
    LIBCOG: 'Birmanie',
    LIBENR: 'République de l’Union de Birmanie',
    DATE_DEBUT: '2010-10-21',
    DATE_FIN: '',
  },
  {
    COG: 99225,
    CRPAY: null,
    LIBCOG: 'Brunei',
    LIBENR: 'Brunei Darussalam',
    DATE_DEBUT: '2019-04-21',
    DATE_FIN: '',
  },
  {
    COG: 99226,
    CRPAY: null,
    LIBCOG: 'Singapour',
    LIBENR: 'République de Singapour',
    DATE_DEBUT: '1965-08-09',
    DATE_FIN: '',
  },
  {
    COG: 99227,
    CRPAY: null,
    LIBCOG: 'Malaisie',
    LIBENR: 'Malaisie',
    DATE_DEBUT: '1963-09-16',
    DATE_FIN: '',
  },
  {
    COG: 99228,
    CRPAY: 99132,
    LIBCOG: 'États malais non fédérés',
    LIBENR: 'Johore, Kédah, Kélankan, Perles, Terenggannu',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '1946-04-01',
  },
  {
    COG: 99229,
    CRPAY: null,
    LIBCOG: 'Maldives',
    LIBENR: 'République des Maldives',
    DATE_DEBUT: '1965-07-26',
    DATE_FIN: '',
  },
  {
    COG: 99230,
    CRPAY: 99216,
    LIBCOG: 'Hong Kong',
    LIBENR: 'Hong Kong',
    DATE_DEBUT: '1997-07-01',
    DATE_FIN: '',
  },
  {
    COG: 99231,
    CRPAY: null,
    LIBCOG: 'Indonésie',
    LIBENR: 'République d’Indonésie',
    DATE_DEBUT: '1945-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99232,
    CRPAY: 99216,
    LIBCOG: 'Macao',
    LIBENR: 'Macao',
    DATE_DEBUT: '1999-12-20',
    DATE_FIN: '',
  },
  {
    COG: 99233,
    CRPAY: null,
    LIBCOG: 'Yémen du Sud',
    LIBENR: 'République démocratique populaire du Yémen',
    DATE_DEBUT: '1967-11-30',
    DATE_FIN: '1990-01-01',
  },
  {
    COG: 99234,
    CRPAY: null,
    LIBCOG: 'Cambodge',
    LIBENR: 'Royaume du Cambodge',
    DATE_DEBUT: '1953-11-09',
    DATE_FIN: '',
  },
  {
    COG: 99235,
    CRPAY: null,
    LIBCOG: 'Sri Lanka',
    LIBENR: 'République démocratique socialiste du Sri Lanka',
    DATE_DEBUT: '1975-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99236,
    CRPAY: null,
    LIBCOG: 'Taïwan',
    LIBENR: 'Taïwan',
    DATE_DEBUT: '1985-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99237,
    CRPAY: null,
    LIBCOG: 'Corée',
    LIBENR: 'Corée',
    DATE_DEBUT: '1945-08-18',
    DATE_FIN: '1953-01-01',
  },
  {
    COG: 99238,
    CRPAY: null,
    LIBCOG: 'Corée du Nord',
    LIBENR: 'République populaire démocratique de Corée',
    DATE_DEBUT: '1953-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99239,
    CRPAY: null,
    LIBCOG: 'Corée du Sud',
    LIBENR: 'République de Corée',
    DATE_DEBUT: '1953-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99240,
    CRPAY: null,
    LIBCOG: 'Koweït',
    LIBENR: 'État du Koweït',
    DATE_DEBUT: '1961-06-19',
    DATE_FIN: '',
  },
  {
    COG: 99241,
    CRPAY: null,
    LIBCOG: 'Laos',
    LIBENR: 'République démocratique populaire lao',
    DATE_DEBUT: '1975-12-02',
    DATE_FIN: '',
  },
  {
    COG: 99242,
    CRPAY: null,
    LIBCOG: 'Mongolie',
    LIBENR: 'Mongolie',
    DATE_DEBUT: '1992-02-12',
    DATE_FIN: '',
  },
  {
    COG: 99243,
    CRPAY: null,
    LIBCOG: 'Vietnam',
    LIBENR: 'République socialiste du Vietnam',
    DATE_DEBUT: '1976-07-02',
    DATE_FIN: '',
  },
  {
    COG: 99244,
    CRPAY: null,
    LIBCOG: 'Vietnam du Nord',
    LIBENR: 'République démocratique du Vietnam',
    DATE_DEBUT: '1954-07-20',
    DATE_FIN: '1976-07-02',
  },
  {
    COG: 99245,
    CRPAY: null,
    LIBCOG: 'Vietnam du Sud',
    LIBENR: 'République du Vietnam',
    DATE_DEBUT: '1954-07-20',
    DATE_FIN: '1976-07-02',
  },
  {
    COG: 99246,
    CRPAY: null,
    LIBCOG: 'Bangladesh',
    LIBENR: 'République populaire du Bangladesh',
    DATE_DEBUT: '1971-03-16',
    DATE_FIN: '',
  },
  {
    COG: 99247,
    CRPAY: null,
    LIBCOG: 'Émirats arabes unis',
    LIBENR: 'Émirats arabes unis',
    DATE_DEBUT: '1971-12-02',
    DATE_FIN: '',
  },
  {
    COG: 99248,
    CRPAY: null,
    LIBCOG: 'Qatar',
    LIBENR: 'État du Qatar',
    DATE_DEBUT: '1971-09-03',
    DATE_FIN: '',
  },
  {
    COG: 99249,
    CRPAY: null,
    LIBCOG: 'Bahreïn',
    LIBENR: 'Royaume de Bahreïn',
    DATE_DEBUT: '2002-02-14',
    DATE_FIN: '',
  },
  {
    COG: 99250,
    CRPAY: null,
    LIBCOG: 'Oman',
    LIBENR: 'Sultanat d’Oman',
    DATE_DEBUT: '1970-08-09',
    DATE_FIN: '',
  },
  {
    COG: 99251,
    CRPAY: null,
    LIBCOG: 'Yémen',
    LIBENR: 'République du Yémen',
    DATE_DEBUT: '1990-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99252,
    CRPAY: null,
    LIBCOG: 'Arménie',
    LIBENR: 'République d’Arménie',
    DATE_DEBUT: '1991-09-21',
    DATE_FIN: '',
  },
  {
    COG: 99253,
    CRPAY: null,
    LIBCOG: 'Azerbaïdjan',
    LIBENR: 'République d’Azerbaïdjan',
    DATE_DEBUT: '1991-08-30',
    DATE_FIN: '',
  },
  {
    COG: 99254,
    CRPAY: null,
    LIBCOG: 'Chypre',
    LIBENR: 'République de Chypre',
    DATE_DEBUT: '1994-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99255,
    CRPAY: null,
    LIBCOG: 'Géorgie',
    LIBENR: 'Géorgie',
    DATE_DEBUT: '1995-10-17',
    DATE_FIN: '',
  },
  {
    COG: 99256,
    CRPAY: null,
    LIBCOG: 'Kazakhstan',
    LIBENR: 'République du Kazakhstan',
    DATE_DEBUT: '1991-12-16',
    DATE_FIN: '',
  },
  {
    COG: 99257,
    CRPAY: null,
    LIBCOG: 'Kirghizstan',
    LIBENR: 'République kirghize',
    DATE_DEBUT: '1991-08-31',
    DATE_FIN: '',
  },
  {
    COG: 99258,
    CRPAY: null,
    LIBCOG: 'Ouzbékistan',
    LIBENR: 'République d’Ouzbékistan',
    DATE_DEBUT: '1991-08-31',
    DATE_FIN: '',
  },
  {
    COG: 99259,
    CRPAY: null,
    LIBCOG: 'Tadjikistan',
    LIBENR: 'République du Tadjikistan',
    DATE_DEBUT: '1991-09-09',
    DATE_FIN: '',
  },
  {
    COG: 99260,
    CRPAY: null,
    LIBCOG: 'Turkménistan',
    LIBENR: 'Turkménistan',
    DATE_DEBUT: '1991-10-27',
    DATE_FIN: '',
  },
  {
    COG: 99261,
    CRPAY: null,
    LIBCOG: 'Palestine',
    LIBENR: 'État de Palestine',
    DATE_DEBUT: '1988-11-15',
    DATE_FIN: '',
  },
  {
    COG: 99262,
    CRPAY: null,
    LIBCOG: 'Timor oriental',
    LIBENR: 'République démocratique du Timor oriental',
    DATE_DEBUT: '2002-05-20',
    DATE_FIN: '',
  },
  {
    COG: 99263,
    CRPAY: 99132,
    LIBCOG: 'Protectorat d’Arabie du Sud',
    LIBENR: 'Hadramaout, Socotra',
    DATE_DEBUT: '1962-04-04',
    DATE_FIN: '1967-11-30',
  },
  {
    COG: 99264,
    CRPAY: 99135,
    LIBCOG: 'Nouvelle-Guinée néerlandaise',
    LIBENR: 'Nouvelle-Guinée néerlandaise',
    DATE_DEBUT: '1962-01-01',
    DATE_FIN: '1963-05-01',
  },
  {
    COG: 99265,
    CRPAY: 99501,
    LIBCOG: 'Territoires australiens de l’océan Indien',
    LIBENR:
      'Îles Ashmore-et-Cartier, territoire antarctique australien, îles Heard-et-MacDonald, îles Cocos, île Christmas',
    DATE_DEBUT: '1958-10-01',
    DATE_FIN: '',
  },
  {
    COG: 99301,
    CRPAY: null,
    LIBCOG: 'Égypte',
    LIBENR: 'République arabe d’Égypte',
    DATE_DEBUT: '1971-09-02',
    DATE_FIN: '',
  },
  {
    COG: 99302,
    CRPAY: null,
    LIBCOG: 'Libéria',
    LIBENR: 'République du Libéria',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99303,
    CRPAY: null,
    LIBCOG: 'Afrique du Sud',
    LIBENR: 'République d’Afrique du Sud',
    DATE_DEBUT: '1966-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99304,
    CRPAY: null,
    LIBCOG: 'Gambie',
    LIBENR: 'République de Gambie',
    DATE_DEBUT: '1965-02-18',
    DATE_FIN: '',
  },
  {
    COG: 99305,
    CRPAY: 99132,
    LIBCOG: 'Cameroun britannique',
    LIBENR: 'Cameroun britannique',
    DATE_DEBUT: '1957-03-06',
    DATE_FIN: '1961-10-01',
  },
  {
    COG: 99306,
    CRPAY: 99132,
    LIBCOG: 'Territoires britanniques de l’océan Atlantique',
    LIBENR: 'Îles Sainte-Hélène, Ascension, Tristan-da-Cunha',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99307,
    CRPAY: 99132,
    LIBCOG: 'Kenya',
    LIBENR: 'Kenya',
    DATE_DEBUT: '1962-10-09',
    DATE_FIN: '1963-12-12',
  },
  {
    COG: 99308,
    CRPAY: 99132,
    LIBCOG: 'Territoire britannique de l’océan Indien',
    LIBENR: 'Îles Chagos',
    DATE_DEBUT: '1976-06-29',
    DATE_FIN: '',
  },
  {
    COG: 99309,
    CRPAY: null,
    LIBCOG: 'Tanzanie',
    LIBENR: 'République unie de Tanzanie',
    DATE_DEBUT: '1964-04-26',
    DATE_FIN: '',
  },
  {
    COG: 99310,
    CRPAY: null,
    LIBCOG: 'Zimbabwe',
    LIBENR: 'République du Zimbabwe',
    DATE_DEBUT: '1980-04-17',
    DATE_FIN: '',
  },
  {
    COG: 99311,
    CRPAY: null,
    LIBCOG: 'Namibie',
    LIBENR: 'République de Namibie',
    DATE_DEBUT: '1990-03-21',
    DATE_FIN: '',
  },
  {
    COG: 99312,
    CRPAY: null,
    LIBCOG: 'République démocratique du Congo',
    LIBENR: 'République démocratique du Congo',
    DATE_DEBUT: '1997-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99313,
    CRPAY: 99134,
    LIBCOG: 'Territoires espagnols en Afrique du Nord',
    LIBENR: 'Ceuta, Melilla, Présides, îles Canaries',
    DATE_DEBUT: '1976-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99314,
    CRPAY: null,
    LIBCOG: 'Guinée équatoriale',
    LIBENR: 'République de Guinée équatoriale',
    DATE_DEBUT: '1968-10-12',
    DATE_FIN: '',
  },
  {
    COG: 99315,
    CRPAY: null,
    LIBCOG: 'Éthiopie',
    LIBENR: 'République démocratique fédérale d’Éthiopie',
    DATE_DEBUT: '1995-08-22',
    DATE_FIN: '',
  },
  {
    COG: 99316,
    CRPAY: null,
    LIBCOG: 'Libye',
    LIBENR: 'État de Libye',
    DATE_DEBUT: '2011-10-23',
    DATE_FIN: '',
  },
  {
    COG: 99317,
    CRPAY: null,
    LIBCOG: 'Érythrée',
    LIBENR: 'État d’Érythrée',
    DATE_DEBUT: '1993-05-24',
    DATE_FIN: '',
  },
  {
    COG: 99318,
    CRPAY: null,
    LIBCOG: 'Somalie',
    LIBENR: 'République fédérale de Somalie',
    DATE_DEBUT: '2012-08-20',
    DATE_FIN: '',
  },
  {
    COG: 99319,
    CRPAY: 99139,
    LIBCOG: 'Territoires portugais de l’océan Atlantique',
    LIBENR: 'Açores, Madère',
    DATE_DEBUT: '1975-11-11',
    DATE_FIN: '',
  },
  {
    COG: 99320,
    CRPAY: 99139,
    LIBCOG: 'Mozambique',
    LIBENR: 'Mozambique',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '1975-06-25',
  },
  {
    COG: 99321,
    CRPAY: null,
    LIBCOG: 'Burundi',
    LIBENR: 'République du Burundi',
    DATE_DEBUT: '1966-11-29',
    DATE_FIN: '',
  },
  {
    COG: 99322,
    CRPAY: null,
    LIBCOG: 'Cameroun',
    LIBENR: 'République du Cameroun',
    DATE_DEBUT: '1961-10-01',
    DATE_FIN: '',
  },
  {
    COG: 99323,
    CRPAY: null,
    LIBCOG: 'Centrafrique',
    LIBENR: 'République centrafricaine',
    DATE_DEBUT: '1979-09-21',
    DATE_FIN: '',
  },
  {
    COG: 99324,
    CRPAY: null,
    LIBCOG: 'Congo',
    LIBENR: 'République du Congo',
    DATE_DEBUT: '1992-03-15',
    DATE_FIN: '',
  },
  {
    COG: 99325,
    CRPAY: null,
    LIBCOG: 'Tanger',
    LIBENR: 'Zone internationale de Tanger',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '1956-10-29',
  },
  {
    COG: 99326,
    CRPAY: null,
    LIBCOG: 'Côte d’Ivoire',
    LIBENR: 'République de Côte d’Ivoire',
    DATE_DEBUT: '1960-08-07',
    DATE_FIN: '',
  },
  {
    COG: 99327,
    CRPAY: null,
    LIBCOG: 'Bénin',
    LIBENR: 'République du Bénin',
    DATE_DEBUT: '1975-11-30',
    DATE_FIN: '',
  },
  {
    COG: 99328,
    CRPAY: null,
    LIBCOG: 'Gabon',
    LIBENR: 'République gabonaise',
    DATE_DEBUT: '1960-08-17',
    DATE_FIN: '',
  },
  {
    COG: 99329,
    CRPAY: null,
    LIBCOG: 'Ghana',
    LIBENR: 'République du Ghana',
    DATE_DEBUT: '1957-03-06',
    DATE_FIN: '',
  },
  {
    COG: 99330,
    CRPAY: null,
    LIBCOG: 'Guinée',
    LIBENR: 'République de Guinée',
    DATE_DEBUT: '1958-10-02',
    DATE_FIN: '',
  },
  {
    COG: 99331,
    CRPAY: null,
    LIBCOG: 'Burkina',
    LIBENR: 'Burkina Faso',
    DATE_DEBUT: '1984-08-04',
    DATE_FIN: '',
  },
  {
    COG: 99332,
    CRPAY: null,
    LIBCOG: 'Kenya',
    LIBENR: 'République du Kenya',
    DATE_DEBUT: '1963-12-12',
    DATE_FIN: '',
  },
  {
    COG: 99333,
    CRPAY: null,
    LIBCOG: 'Madagascar',
    LIBENR: 'République de Madagascar',
    DATE_DEBUT: '1960-06-26',
    DATE_FIN: '',
  },
  {
    COG: 99334,
    CRPAY: null,
    LIBCOG: 'Malawi',
    LIBENR: 'République du Malawi',
    DATE_DEBUT: '1964-07-06',
    DATE_FIN: '',
  },
  {
    COG: 99335,
    CRPAY: null,
    LIBCOG: 'Mali',
    LIBENR: 'République du Mali',
    DATE_DEBUT: '1960-09-22',
    DATE_FIN: '',
  },
  {
    COG: 99336,
    CRPAY: null,
    LIBCOG: 'Mauritanie',
    LIBENR: 'République islamique de Mauritanie',
    DATE_DEBUT: '1960-11-28',
    DATE_FIN: '',
  },
  {
    COG: 99337,
    CRPAY: null,
    LIBCOG: 'Niger',
    LIBENR: 'République du Niger',
    DATE_DEBUT: '1960-08-03',
    DATE_FIN: '',
  },
  {
    COG: 99338,
    CRPAY: null,
    LIBCOG: 'Nigéria',
    LIBENR: 'République fédérale du Nigéria',
    DATE_DEBUT: '1960-10-01',
    DATE_FIN: '',
  },
  {
    COG: 99339,
    CRPAY: null,
    LIBCOG: 'Ouganda',
    LIBENR: 'République d’Ouganda',
    DATE_DEBUT: '1962-10-09',
    DATE_FIN: '',
  },
  {
    COG: 99340,
    CRPAY: null,
    LIBCOG: 'Rwanda',
    LIBENR: 'République du Rwanda',
    DATE_DEBUT: '1962-07-01',
    DATE_FIN: '',
  },
  {
    COG: 99341,
    CRPAY: null,
    LIBCOG: 'Sénégal',
    LIBENR: 'République du Sénégal',
    DATE_DEBUT: '1960-08-20',
    DATE_FIN: '',
  },
  {
    COG: 99342,
    CRPAY: null,
    LIBCOG: 'Sierra Leone',
    LIBENR: 'République de Sierra Leone',
    DATE_DEBUT: '1961-04-27',
    DATE_FIN: '',
  },
  {
    COG: 99343,
    CRPAY: null,
    LIBCOG: 'Soudan',
    LIBENR: 'République du Soudan',
    DATE_DEBUT: '1956-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99344,
    CRPAY: null,
    LIBCOG: 'Tchad',
    LIBENR: 'République du Tchad',
    DATE_DEBUT: '1960-08-11',
    DATE_FIN: '',
  },
  {
    COG: 99345,
    CRPAY: null,
    LIBCOG: 'Togo',
    LIBENR: 'République togolaise',
    DATE_DEBUT: '1960-04-27',
    DATE_FIN: '',
  },
  {
    COG: 99346,
    CRPAY: null,
    LIBCOG: 'Zambie',
    LIBENR: 'République de Zambie',
    DATE_DEBUT: '1964-10-24',
    DATE_FIN: '',
  },
  {
    COG: 99347,
    CRPAY: null,
    LIBCOG: 'Botswana',
    LIBENR: 'République du Botswana',
    DATE_DEBUT: '1966-09-30',
    DATE_FIN: '',
  },
  {
    COG: 99348,
    CRPAY: null,
    LIBCOG: 'Lesotho',
    LIBENR: 'Royaume du Lesotho',
    DATE_DEBUT: '1966-10-04',
    DATE_FIN: '',
  },
  {
    COG: 99349,
    CRPAY: null,
    LIBCOG: 'Soudan du Sud',
    LIBENR: 'République du Soudan du Sud',
    DATE_DEBUT: '2011-07-09',
    DATE_FIN: '',
  },
  {
    COG: 99350,
    CRPAY: null,
    LIBCOG: 'Maroc',
    LIBENR: 'Royaume du Maroc',
    DATE_DEBUT: '1956-03-02',
    DATE_FIN: '',
  },
  {
    COG: 99351,
    CRPAY: null,
    LIBCOG: 'Tunisie',
    LIBENR: 'République tunisienne',
    DATE_DEBUT: '1956-03-20',
    DATE_FIN: '',
  },
  {
    COG: 99352,
    CRPAY: null,
    LIBCOG: 'Algérie',
    LIBENR: 'République algérienne démocratique et populaire',
    DATE_DEBUT: '1962-07-05',
    DATE_FIN: '',
  },
  {
    COG: 99362,
    CRPAY: null,
    LIBCOG: 'Zanzibar',
    LIBENR: 'République populaire de Zanzibar',
    DATE_DEBUT: '1963-12-10',
    DATE_FIN: '1964-04-26',
  },
  {
    COG: 99363,
    CRPAY: 99103,
    LIBCOG: 'Terres australes norvégiennes',
    LIBENR: 'Île Bouvet, île Pierre-Ier, terre de la Reine-Maud',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99389,
    CRPAY: null,
    LIBCOG: 'Sahara occidental',
    LIBENR: 'Sahara occidental',
    DATE_DEBUT: '1994-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99390,
    CRPAY: null,
    LIBCOG: 'Maurice',
    LIBENR: 'République de Maurice',
    DATE_DEBUT: '1968-03-12',
    DATE_FIN: '',
  },
  {
    COG: 99391,
    CRPAY: null,
    LIBCOG: 'Swaziland',
    LIBENR: 'Royaume du Swaziland',
    DATE_DEBUT: '1968-09-06',
    DATE_FIN: '',
  },
  {
    COG: 99392,
    CRPAY: null,
    LIBCOG: 'Guinée-Bissao',
    LIBENR: 'République de Guinée-Bissao',
    DATE_DEBUT: '1974-09-10',
    DATE_FIN: '',
  },
  {
    COG: 99393,
    CRPAY: null,
    LIBCOG: 'Mozambique',
    LIBENR: 'République du Mozambique',
    DATE_DEBUT: '1975-06-25',
    DATE_FIN: '',
  },
  {
    COG: 99394,
    CRPAY: null,
    LIBCOG: 'Sao Tomé-et-Principe',
    LIBENR: 'République démocratique de Sao Tomé-et-Principe',
    DATE_DEBUT: '1975-07-12',
    DATE_FIN: '',
  },
  {
    COG: 99395,
    CRPAY: null,
    LIBCOG: 'Angola',
    LIBENR: 'République d’Angola',
    DATE_DEBUT: '1992-08-26',
    DATE_FIN: '',
  },
  {
    COG: 99396,
    CRPAY: null,
    LIBCOG: 'Cap-Vert',
    LIBENR: 'République du Cap-Vert',
    DATE_DEBUT: '1975-07-05',
    DATE_FIN: '',
  },
  {
    COG: 99397,
    CRPAY: null,
    LIBCOG: 'Comores',
    LIBENR: 'Union des Comores',
    DATE_DEBUT: '2001-12-23',
    DATE_FIN: '',
  },
  {
    COG: 99398,
    CRPAY: null,
    LIBCOG: 'Seychelles',
    LIBENR: 'République des Seychelles',
    DATE_DEBUT: '1976-06-29',
    DATE_FIN: '',
  },
  {
    COG: 99399,
    CRPAY: null,
    LIBCOG: 'Djibouti',
    LIBENR: 'République de Djibouti',
    DATE_DEBUT: '1977-06-27',
    DATE_FIN: '',
  },
  {
    COG: 99401,
    CRPAY: null,
    LIBCOG: 'Canada',
    LIBENR: 'Canada',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99402,
    CRPAY: 99132,
    LIBCOG: 'Terre-Neuve',
    LIBENR: 'Terre-Neuve',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '1949-03-31',
  },
  {
    COG: 99403,
    CRPAY: 99132,
    LIBCOG: 'Labrador',
    LIBENR: 'Labrador',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '1949-03-31',
  },
  {
    COG: 99404,
    CRPAY: null,
    LIBCOG: 'États-Unis',
    LIBENR: 'États-Unis d’Amérique',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99405,
    CRPAY: null,
    LIBCOG: 'Mexique',
    LIBENR: 'États-Unis du Mexique',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99406,
    CRPAY: null,
    LIBCOG: 'Costa Rica',
    LIBENR: 'République du Costa Rica',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99407,
    CRPAY: null,
    LIBCOG: 'Cuba',
    LIBENR: 'République de Cuba',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99408,
    CRPAY: null,
    LIBCOG: 'République dominicaine',
    LIBENR: 'République dominicaine',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99409,
    CRPAY: null,
    LIBCOG: 'Guatémala',
    LIBENR: 'République du Guatémala',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99410,
    CRPAY: null,
    LIBCOG: 'Haïti',
    LIBENR: 'République d’Haïti',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99411,
    CRPAY: null,
    LIBCOG: 'Honduras',
    LIBENR: 'République du Honduras',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99412,
    CRPAY: null,
    LIBCOG: 'Nicaragua',
    LIBENR: 'République du Nicaragua',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99413,
    CRPAY: null,
    LIBCOG: 'Panama',
    LIBENR: 'République du Panama',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99414,
    CRPAY: null,
    LIBCOG: 'Salvador',
    LIBENR: 'République du Salvador',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99415,
    CRPAY: null,
    LIBCOG: 'Argentine',
    LIBENR: 'République argentine',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99416,
    CRPAY: null,
    LIBCOG: 'Brésil',
    LIBENR: 'République fédérative du Brésil',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99417,
    CRPAY: null,
    LIBCOG: 'Chili',
    LIBENR: 'République du Chili',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99418,
    CRPAY: null,
    LIBCOG: 'Bolivie',
    LIBENR: 'État plurinational de Bolivie',
    DATE_DEBUT: '2010-01-22',
    DATE_FIN: '',
  },
  {
    COG: 99419,
    CRPAY: null,
    LIBCOG: 'Colombie',
    LIBENR: 'République de Colombie',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99420,
    CRPAY: null,
    LIBCOG: 'Équateur',
    LIBENR: 'République d’Équateur',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99421,
    CRPAY: null,
    LIBCOG: 'Paraguay',
    LIBENR: 'République du Paraguay',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99422,
    CRPAY: null,
    LIBCOG: 'Pérou',
    LIBENR: 'République du Pérou',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99423,
    CRPAY: null,
    LIBCOG: 'Uruguay',
    LIBENR: 'République orientale de l’Uruguay',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99424,
    CRPAY: null,
    LIBCOG: 'Vénézuéla',
    LIBENR: 'République bolivarienne du Vénézuéla',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99425,
    CRPAY: 99132,
    LIBCOG: 'Territoires britanniques dans les Antilles et Bermudes',
    LIBENR:
      'Îles Turks-et-Caïcos, îles Caïmans, Montserrat, Anguilla, îles Vierges britanniques, Bermudes',
    DATE_DEBUT: '1983-09-19',
    DATE_FIN: '',
  },
  {
    COG: 99426,
    CRPAY: null,
    LIBCOG: 'Jamaïque',
    LIBENR: 'Jamaïque',
    DATE_DEBUT: '1962-08-31',
    DATE_FIN: '',
  },
  {
    COG: 99427,
    CRPAY: 99132,
    LIBCOG: 'Territoires britanniques dans l’océan Atlantique Sud',
    LIBENR:
      'Îles Malouines, territoire antarctique britannique, Géorgie-du-Sud-et-les-îles-Sandwich-du-Sud',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99428,
    CRPAY: null,
    LIBCOG: 'Guyana',
    LIBENR: 'République coopérative du Guyana',
    DATE_DEBUT: '1966-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99429,
    CRPAY: null,
    LIBCOG: 'Bélize',
    LIBENR: 'Bélize',
    DATE_DEBUT: '1981-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99430,
    CRPAY: 99101,
    LIBCOG: 'Groenland',
    LIBENR: 'Groenland',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99431,
    CRPAY: 99135,
    LIBCOG: 'Aruba',
    LIBENR: 'Aruba',
    DATE_DEBUT: '2010-10-10',
    DATE_FIN: '',
  },
  {
    COG: 99432,
    CRPAY: 99404,
    LIBCOG: 'Territoires des États-Unis en Amérique',
    LIBENR: 'Porto Rico, îles Vierges des États-Unis',
    DATE_DEBUT: '1999-12-31',
    DATE_FIN: '',
  },
  {
    COG: 99433,
    CRPAY: null,
    LIBCOG: 'Trinité-et-Tobago',
    LIBENR: 'République de Trinité-et-Tobago',
    DATE_DEBUT: '1962-08-31',
    DATE_FIN: '',
  },
  {
    COG: 99434,
    CRPAY: null,
    LIBCOG: 'Barbade',
    LIBENR: 'Barbade',
    DATE_DEBUT: '1966-11-30',
    DATE_FIN: '',
  },
  {
    COG: 99435,
    CRPAY: null,
    LIBCOG: 'Grenade',
    LIBENR: 'Grenade',
    DATE_DEBUT: '1974-02-07',
    DATE_FIN: '',
  },
  {
    COG: 99436,
    CRPAY: null,
    LIBCOG: 'Bahamas',
    LIBENR: 'Commonwealth des Bahamas',
    DATE_DEBUT: '1973-07-10',
    DATE_FIN: '',
  },
  {
    COG: 99437,
    CRPAY: null,
    LIBCOG: 'Suriname',
    LIBENR: 'République du Suriname',
    DATE_DEBUT: '1975-11-25',
    DATE_FIN: '',
  },
  {
    COG: 99438,
    CRPAY: null,
    LIBCOG: 'Dominique',
    LIBENR: 'Commonwealth de Dominique',
    DATE_DEBUT: '1978-11-03',
    DATE_FIN: '',
  },
  {
    COG: 99439,
    CRPAY: null,
    LIBCOG: 'Sainte-Lucie',
    LIBENR: 'Sainte-Lucie',
    DATE_DEBUT: '1979-02-22',
    DATE_FIN: '',
  },
  {
    COG: 99440,
    CRPAY: null,
    LIBCOG: 'Saint-Vincent-et-les-Grenadines',
    LIBENR: 'Saint-Vincent-et-les-Grenadines',
    DATE_DEBUT: '1979-10-27',
    DATE_FIN: '',
  },
  {
    COG: 99441,
    CRPAY: null,
    LIBCOG: 'Antigua-et-Barbuda',
    LIBENR: 'Antigua-et-Barbuda',
    DATE_DEBUT: '1981-11-01',
    DATE_FIN: '',
  },
  {
    COG: 99442,
    CRPAY: null,
    LIBCOG: 'Saint-Christophe-et-Niévès',
    LIBENR: 'Fédération de Saint-Christophe-et-Niévès',
    DATE_DEBUT: '1983-09-19',
    DATE_FIN: '',
  },
  {
    COG: 99443,
    CRPAY: 99135,
    LIBCOG: 'Bonaire, Saint-Eustache, Saba',
    LIBENR: 'Bonaire, Saint-Eustache, Saba',
    DATE_DEBUT: '2010-10-10',
    DATE_FIN: '',
  },
  {
    COG: 99444,
    CRPAY: 99135,
    LIBCOG: 'Curaçao',
    LIBENR: 'Curaçao',
    DATE_DEBUT: '2010-10-10',
    DATE_FIN: '',
  },
  {
    COG: 99445,
    CRPAY: 99135,
    LIBCOG: 'Saint-Martin (partie néerlandaise)',
    LIBENR: 'Saint-Martin (partie néerlandaise)',
    DATE_DEBUT: '2010-10-10',
    DATE_FIN: '',
  },
  {
    COG: 99446,
    CRPAY: 99415,
    LIBCOG: 'Territoire antarctique argentin',
    LIBENR: 'Territoire antarctique argentin',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99447,
    CRPAY: 99417,
    LIBCOG: 'Territoire antarctique chilien',
    LIBENR: 'Territoire antarctique chilien',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99501,
    CRPAY: null,
    LIBCOG: 'Australie',
    LIBENR: 'Commonwealth d’Australie',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99502,
    CRPAY: null,
    LIBCOG: 'Nouvelle-Zélande',
    LIBENR: 'Nouvelle-Zélande',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99503,
    CRPAY: 99132,
    LIBCOG: 'Pitcairn',
    LIBENR: 'Pitcairn',
    DATE_DEBUT: '1980-07-30',
    DATE_FIN: '',
  },
  {
    COG: 99504,
    CRPAY: 99404,
    LIBCOG: 'Îles Hawaï',
    LIBENR: 'Îles Hawaï',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '1959-08-21',
  },
  {
    COG: 99505,
    CRPAY: 99404,
    LIBCOG: 'Territoires des États-Unis en Océanie',
    LIBENR:
      'Îles Mariannes du Nord, Guam, îles Samoa américaines, îles mineures éloignées des États-Unis',
    DATE_DEBUT: '1994-10-01',
    DATE_FIN: '',
  },
  {
    COG: 99506,
    CRPAY: null,
    LIBCOG: 'Samoa',
    LIBENR: 'État indépendant des Samoa',
    DATE_DEBUT: '1997-07-04',
    DATE_FIN: '',
  },
  {
    COG: 99507,
    CRPAY: null,
    LIBCOG: 'Nauru',
    LIBENR: 'République de Nauru',
    DATE_DEBUT: '1968-01-31',
    DATE_FIN: '',
  },
  {
    COG: 99508,
    CRPAY: null,
    LIBCOG: 'Fidji',
    LIBENR: 'République des Fidji',
    DATE_DEBUT: '2019-04-21',
    DATE_FIN: '',
  },
  {
    COG: 99509,
    CRPAY: null,
    LIBCOG: 'Tonga',
    LIBENR: 'Royaume des Tonga',
    DATE_DEBUT: '1970-06-04',
    DATE_FIN: '',
  },
  {
    COG: 99510,
    CRPAY: null,
    LIBCOG: 'Papouasie-Nouvelle-Guinée',
    LIBENR: 'État indépendant de Papouasie-Nouvelle-Guinée',
    DATE_DEBUT: '2019-04-21',
    DATE_FIN: '',
  },
  {
    COG: 99511,
    CRPAY: null,
    LIBCOG: 'Tuvalu',
    LIBENR: 'Tuvalu',
    DATE_DEBUT: '1978-10-01',
    DATE_FIN: '',
  },
  {
    COG: 99512,
    CRPAY: null,
    LIBCOG: 'Salomon',
    LIBENR: 'Îles Salomon',
    DATE_DEBUT: '1978-07-07',
    DATE_FIN: '',
  },
  {
    COG: 99513,
    CRPAY: null,
    LIBCOG: 'Kiribati',
    LIBENR: 'République des Kiribati',
    DATE_DEBUT: '1979-07-12',
    DATE_FIN: '',
  },
  {
    COG: 99514,
    CRPAY: null,
    LIBCOG: 'Vanuatu',
    LIBENR: 'République du Vanuatu',
    DATE_DEBUT: '1980-07-30',
    DATE_FIN: '',
  },
  {
    COG: 99515,
    CRPAY: null,
    LIBCOG: 'Marshall',
    LIBENR: 'République des îles Marshall',
    DATE_DEBUT: '1990-12-22',
    DATE_FIN: '',
  },
  {
    COG: 99516,
    CRPAY: null,
    LIBCOG: 'Micronésie',
    LIBENR: 'États fédérés de Micronésie',
    DATE_DEBUT: '1990-12-22',
    DATE_FIN: '',
  },
  {
    COG: 99517,
    CRPAY: null,
    LIBCOG: 'Palaos',
    LIBENR: 'République des Palaos',
    DATE_DEBUT: '1994-10-01',
    DATE_FIN: '',
  },
  {
    COG: 99519,
    CRPAY: 99502,
    LIBCOG: 'Territoires de la Nouvelle-Zélande',
    LIBENR: 'Tokelau, dépendance de Ross',
    DATE_DEBUT: '1977-01-01',
    DATE_FIN: '',
  },
  {
    COG: 99520,
    CRPAY: 99502,
    LIBCOG: 'Cook',
    LIBENR: 'Îles Cook',
    DATE_DEBUT: '1965-08-04',
    DATE_FIN: '',
  },
  {
    COG: 99521,
    CRPAY: 99502,
    LIBCOG: 'Niue',
    LIBENR: 'Niue',
    DATE_DEBUT: '1974-10-19',
    DATE_FIN: '',
  },
  {
    COG: 99522,
    CRPAY: 99501,
    LIBCOG: 'Territoires de l’Australie en Océanie',
    LIBENR: 'Île Norfolk, îles de la mer de Corail',
    DATE_DEBUT: '1975-09-16',
    DATE_FIN: '',
  },
  {
    COG: 99699,
    CRPAY: null,
    LIBCOG: 'Antarctique',
    LIBENR: 'Antarctique',
    DATE_DEBUT: '1943-01-01',
    DATE_FIN: '',
  },
]
