/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React, { FunctionComponent } from 'react'
import { Platform } from 'react-native'
import styled, { useTheme } from 'styled-components/native'

import { getTagColors } from 'ui/designSystem/Tag/helper/getTagColors'
import { getTagIcon } from 'ui/designSystem/Tag/helper/getTagIcon'
import { renderTagIcon } from 'ui/designSystem/Tag/helper/renderTagIcon'
import { TagProps, TagVariant } from 'ui/designSystem/Tag/types'
import { Typo, getSpacing, getSpacingString } from 'ui/theme'

const PADDING_VERTICAL = getSpacing(1)
const NUMBER_OF_SPACES_LINE_HEIGHT = 4
const LINE_HEIGHT = getSpacing(NUMBER_OF_SPACES_LINE_HEIGHT)

export const TAG_HEIGHT = PADDING_VERTICAL + LINE_HEIGHT + PADDING_VERTICAL

export const Tag: FunctionComponent<TagProps> = ({
  label,
  variant = TagVariant.DEFAULT,
  Icon,
  withColor = true,
  ...props
}) => {
  const theme = useTheme()
  const { background, icon } = theme.designSystem.color

  const FinalIcon = getTagIcon(variant, Icon)

  const { backgroundColor, iconColor, labelColor, iconSize } = getTagColors({
    variant,
    background,
    icon,
    theme,
  })

  return (
    <Wrapper
      backgroundColor={withColor ? backgroundColor : theme.designSystem.color.background.default}
      withColor={withColor}
      testID="tagWrapper"
      {...props}>
      {FinalIcon ? (
        <IconContainer>
          {renderTagIcon(
            withColor ? iconColor : theme.designSystem.color.icon.default,
            iconSize,
            FinalIcon
          )}
        </IconContainer>
      ) : null}
      <LabelText color={labelColor}>{label}</LabelText>
    </Wrapper>
  )
}

const Wrapper = styled.View<{ backgroundColor: string; withColor?: boolean }>(
  ({ theme, backgroundColor, withColor }) => ({
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: theme.designSystem.size.borderRadius.s,
    backgroundColor,
    paddingVertical: PADDING_VERTICAL,
    ...(withColor ? { paddingHorizontal: getSpacing(2) } : undefined),
  })
)

const LabelText = styled(Typo.BodyAccentXs)({
  lineHeight: getSpacingString(NUMBER_OF_SPACES_LINE_HEIGHT),
  ...(Platform.OS === 'web' && { textWrap: 'nowrap' }),
})

const IconContainer = styled.View({
  marginRight: getSpacing(1),
})
