/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React, { FunctionComponent } from 'react'
import { Platform } from 'react-native'
import styled, { useTheme } from 'styled-components/native'

import { getTagColors } from 'ui/designSystem/Tag/helper/getTagColors'
import { getTagIcon } from 'ui/designSystem/Tag/helper/getTagIcon'
import { renderTagIcon } from 'ui/designSystem/Tag/helper/renderTagIcon'
import { TagProps, TagVariant } from 'ui/designSystem/Tag/types'
import { Typo, getSpacingString } from 'ui/theme'

const NUMBER_OF_SPACES_LINE_HEIGHT = 4

export const Tag: FunctionComponent<TagProps> = ({
  label,
  variant = TagVariant.DEFAULT,
  Icon,
  ...props
}) => {
  const theme = useTheme()
  const { background, icon } = theme.designSystem.color

  const FinalIcon = getTagIcon(variant, Icon)

  const { backgroundColor, iconColor, labelColor, iconSize } = getTagColors({
    variant,
    background,
    icon,
    theme,
  })

  return (
    <Wrapper backgroundColor={backgroundColor} testID="tagWrapper" {...props}>
      {FinalIcon ? (
        <IconContainer>{renderTagIcon(iconColor, iconSize, FinalIcon)}</IconContainer>
      ) : null}
      <LabelText color={labelColor}>{label}</LabelText>
    </Wrapper>
  )
}

const Wrapper = styled.View<{ backgroundColor: string }>(({ theme, backgroundColor }) => ({
  flexDirection: 'row',
  alignItems: 'center',
  alignSelf: 'flex-start',
  borderRadius: theme.designSystem.size.borderRadius.s,
  backgroundColor,
  paddingVertical: theme.designSystem.size.spacing.xs,
  paddingHorizontal: theme.designSystem.size.spacing.s,
}))

const LabelText = styled(Typo.BodyAccentXs)({
  lineHeight: getSpacingString(NUMBER_OF_SPACES_LINE_HEIGHT),
  ...(Platform.OS === 'web' && { textWrap: 'nowrap' }),
})

const IconContainer = styled.View(({ theme }) => ({
  marginRight: theme.designSystem.size.spacing.xs,
}))
