require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Override Firebase SDK Version
$FirebaseSDKVersion = '6.34.0'

platform :ios, '10.0'

target 'PassCulture' do
  config = use_native_modules!
  
  use_react_native!(:path => config["reactNativePath"])

  # Third party deps podspec link, to include if 0.60 autolinking not supported

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  post_install do |installer|
    flipper_post_install(installer)
  end
end
