export enum QueryKeys {
  ADDRESSES = 'addresses',
  ACCOUNT_SUSPENSION_DATE = 'accountSuspensionDate',
  ACCOUNT_SUSPENSION_STATUS = 'accountSuspensionStatus',
  BOOKINGS = 'bookings',
  CITIES = 'cities',
  CULTURAL_SURVEY_ANSWERS = 'culturalSurveyAnswers',
  CULTURAL_SURVEY_QUESTIONS = 'culturalSurveyQuestions',
  EMAIL_CHANGE_EXPIRATION_TIMESTAMP = 'emailChangeExpirationTimestamp',
  ERROR_ASYNC = 'errorAsync',
  FAVORITES = 'favorites',
  FAVORITES_COUNT = 'favoritesCount',
  FIRESTORE_UBBLE_ETA_MESSAGE = 'firestoreUbbleETAMessage',
  HOME_BANNER = 'homeBanner',
  HOME_MODULE = 'homeModule',
  HOME_VENUES_MODULE = 'homeVenuesModule',
  HOMEPAGE_MODULES = 'homepageModules',
  NEXT_SUBSCRIPTION_STEP = 'nextSubscriptionStep',
  OFFER = 'offer',
  PHONE_VALIDATION_CODE = 'phoneValidationCode',
  PHONE_VALIDATION_REMAINING_ATTEMPTS = 'phoneValidationRemainingAttempts',
  PLACES = 'places',
  RECOMMENDATION_HITS = 'recommendationHits',
  RECOMMENDATION_OFFER_IDS = 'recommendationOfferIds',
  REPORTED_OFFERS = 'reportedOffers',
  REPORT_OFFER_REASONS = 'reportOfferReasons',
  RESET_PASSWORD_EXPIRED_LINK = 'resetPasswordExpiredLink',
  STEPPER_INFO = 'stepperInfo',
  SCHOOL_TYPES = 'schoolTypes',
  SEARCH_RESULTS = 'searchResults',
  SETTINGS = 'settings',
  SIGNUP_CONFIRMATION_EXPIRED_LINK = 'signupConfirmationExpiredLink',
  SIMILAR_OFFERS = 'similarOffers',
  SUBCATEGORIES = 'subcategories',
  USER_PROFILE = 'userProfile',
  VENUE = 'venue',
  VENUES = 'venues',
  VENUE_OFFERS = 'venueOffers',
}

export enum MutationKeys {
  IDENTIFICATION_URL = 'identificationUrl',
}
