export enum QueryKeys {
  HOME_MODULE = 'homeModule',
  BOOKINGS = 'bookings',
  ERROR_ASYNC = 'errorAsync',
  FAVORITES = 'favorites',
  HOMEPAGE_MODULES = 'homepageModules',
  ID_CHECK_TOKEN = 'idCheckToken',
  OFFER = 'offer',
  PHONE_VALIDATION_CODE = 'phoneValidationCode',
  RECOMMENDATION_HITS = 'recommendationHits',
  RECOMMENDATION_OFFER_IDS = 'recommendationOfferIds',
  RESET_PASSWORD_EXPIRED_LINK = 'resetPasswordExpiredLink',
  SETTINGS = 'settings',
  SIGNUP_CONFIRMATION_EXPIRED_LINK = 'signupConfirmationExpiredLink',
  USER_PROFILE = 'userProfile',
}
