export enum QueryKeys {
  ADDRESSES = 'addresses',
  HOME_MODULE = 'homeModule',
  HOME_VENUES_MODULE = 'homeVenuesModule',
  BOOKINGS = 'bookings',
  CITIES = 'cities',
  ERROR_ASYNC = 'errorAsync',
  FAVORITES = 'favorites',
  FIRESTORE_UBBLE_LOAD = 'firestoreUbbleLoad',
  HOMEPAGE_MODULES = 'homepageModules',
  ID_CHECK_TOKEN = 'idCheckToken',
  OFFER = 'offer',
  PHONE_VALIDATION_CODE = 'phoneValidationCode',
  PLACES = 'places',
  RECOMMENDATION_HITS = 'recommendationHits',
  RECOMMENDATION_OFFER_IDS = 'recommendationOfferIds',
  REPORTED_OFFERS = 'reportedOffers',
  REPORT_OFFER_REASONS = 'reportOfferReasons',
  RESET_PASSWORD_EXPIRED_LINK = 'resetPasswordExpiredLink',
  SEARCH_RESULTS = 'searchResults',
  SETTINGS = 'settings',
  SIGNUP_CONFIRMATION_EXPIRED_LINK = 'signupConfirmationExpiredLink',
  SUBCATEGORIES = 'subcategories',
  USER_PROFILE = 'userProfile',
  VENUE = 'venue',
  VENUES = 'venues',
  VENUE_OFFERS = 'venueOffers',
}

export enum MutationKeys {
  IDENTIFICATION_URL = 'identificationUrl',
  PATCH_PROFILE = 'patchProfile',
}
