export const subcategoriesMappingSnap = {
  ABO_BIBLIOTHEQUE: {
    appLabel: 'Abonnement (bibliothèques, médiathèques...)',
    categoryId: 'LIVRE',
    homepageLabelName: 'LIVRE',
    isEvent: false,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'LIVRE',
  },
  ABO_CONCERT: {
    appLabel: 'Abonnement concert',
    categoryId: 'MUSIQUE_LIVE',
    homepageLabelName: 'MUSIQUE',
    isEvent: false,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'MUSIQUE',
  },
  ABO_JEU_VIDEO: {
    appLabel: 'Abonnement jeux vidéos',
    categoryId: 'JEU',
    homepageLabelName: 'JEU',
    isEvent: false,
    onlineOfflinePlatform: 'ONLINE',
    searchGroupName: 'JEU',
  },
  ABO_LIVRE_NUMERIQUE: {
    appLabel: 'Abonnement livres numériques',
    categoryId: 'LIVRE',
    homepageLabelName: 'LIVRE',
    isEvent: false,
    onlineOfflinePlatform: 'ONLINE',
    searchGroupName: 'LIVRE',
  },
  ABO_LUDOTHEQUE: {
    appLabel: 'Abonnement ludothèque',
    categoryId: 'JEU',
    homepageLabelName: 'JEU',
    isEvent: false,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'JEU',
  },
  ABO_MEDIATHEQUE: {
    appLabel: 'Abonnement médiathèque',
    categoryId: 'FILM',
    homepageLabelName: 'FILM',
    isEvent: false,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'FILM',
  },
  ABO_MUSEE: {
    appLabel: 'Entrée libre ou abonnement musée',
    categoryId: 'MUSEE',
    homepageLabelName: 'VISITE',
    isEvent: false,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'VISITE',
  },
  ABO_PLATEFORME_MUSIQUE: {
    appLabel: 'Abonnement plateforme musicale',
    categoryId: 'MUSIQUE_ENREGISTREE',
    homepageLabelName: 'MUSIQUE',
    isEvent: false,
    onlineOfflinePlatform: 'ONLINE',
    searchGroupName: 'MUSIQUE',
  },
  ABO_PLATEFORME_VIDEO: {
    appLabel: 'Abonnement plateforme streaming',
    categoryId: 'FILM',
    homepageLabelName: 'FILM',
    isEvent: false,
    onlineOfflinePlatform: 'ONLINE',
    searchGroupName: 'FILM',
  },
  ABO_PRATIQUE_ART: {
    appLabel: 'Abonnement pratique artistique',
    categoryId: 'PRATIQUE_ART',
    homepageLabelName: 'COURS',
    isEvent: false,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'COURS',
  },
  ABO_PRESSE_EN_LIGNE: {
    appLabel: 'Abonnement presse en ligne',
    categoryId: 'MEDIA',
    homepageLabelName: 'PRESSE',
    isEvent: false,
    onlineOfflinePlatform: 'ONLINE',
    searchGroupName: 'PRESSE',
  },
  ABO_SPECTACLE: {
    appLabel: 'Abonnement spectacle',
    categoryId: 'SPECTACLE',
    homepageLabelName: 'SPECTACLE',
    isEvent: false,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'SPECTACLE',
  },
  ACHAT_INSTRUMENT: {
    appLabel: 'Achat instrument',
    categoryId: 'INSTRUMENT',
    homepageLabelName: 'MUSIQUE',
    isEvent: false,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'INSTRUMENT',
  },
  ACTIVATION_EVENT: {
    appLabel: "Catégorie technique d'événement d'activation ",
    categoryId: 'TECHNIQUE',
    homepageLabelName: 'NONE',
    isEvent: true,
    onlineOfflinePlatform: 'ONLINE_OR_OFFLINE',
    searchGroupName: 'NONE',
  },
  ACTIVATION_THING: {
    appLabel: "Catégorie technique de thing d'activation",
    categoryId: 'TECHNIQUE',
    homepageLabelName: 'NONE',
    isEvent: false,
    onlineOfflinePlatform: 'ONLINE_OR_OFFLINE',
    searchGroupName: 'NONE',
  },
  APP_CULTURELLE: {
    appLabel: 'Application culturelle',
    categoryId: 'MEDIA',
    homepageLabelName: 'PRESSE',
    isEvent: false,
    onlineOfflinePlatform: 'ONLINE',
    searchGroupName: 'PRESSE',
  },
  ATELIER_PRATIQUE_ART: {
    appLabel: 'Atelier, stage de pratique artistique',
    categoryId: 'PRATIQUE_ART',
    homepageLabelName: 'COURS',
    isEvent: true,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'COURS',
  },
  AUTRE_SUPPORT_NUMERIQUE: {
    appLabel: 'Autre support numérique',
    categoryId: 'FILM',
    homepageLabelName: 'FILM',
    isEvent: false,
    onlineOfflinePlatform: 'ONLINE',
    searchGroupName: 'FILM',
  },
  BON_ACHAT_INSTRUMENT: {
    appLabel: "Bon d'achat instrument",
    categoryId: 'INSTRUMENT',
    homepageLabelName: 'MUSIQUE',
    isEvent: false,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'INSTRUMENT',
  },
  CAPTATION_MUSIQUE: {
    appLabel: 'Captation musicale',
    categoryId: 'MUSIQUE_ENREGISTREE',
    homepageLabelName: 'MUSIQUE',
    isEvent: false,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'MUSIQUE',
  },
  CARTE_CINE_ILLIMITE: {
    appLabel: 'Carte cinéma illimité',
    categoryId: 'CINEMA',
    homepageLabelName: 'CINEMA',
    isEvent: false,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'CINEMA',
  },
  CARTE_CINE_MULTISEANCES: {
    appLabel: 'Carte cinéma multi-séances',
    categoryId: 'CINEMA',
    homepageLabelName: 'CINEMA',
    isEvent: false,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'CINEMA',
  },
  CARTE_JEUNES: {
    appLabel: 'Carte jeunes',
    categoryId: 'CARTE_JEUNES',
    homepageLabelName: 'CARTE_JEUNES',
    isEvent: false,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'CARTE_JEUNES',
  },
  CARTE_MUSEE: {
    appLabel: 'Cartes musées, patrimoine...',
    categoryId: 'MUSEE',
    homepageLabelName: 'VISITE',
    isEvent: false,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'VISITE',
  },
  CINE_PLEIN_AIR: {
    appLabel: 'Cinéma plein air',
    categoryId: 'CINEMA',
    homepageLabelName: 'CINEMA',
    isEvent: true,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'CINEMA',
  },
  CINE_VENTE_DISTANCE: {
    appLabel: 'Cinéma',
    categoryId: 'CINEMA',
    homepageLabelName: 'CINEMA',
    isEvent: false,
    onlineOfflinePlatform: 'ONLINE',
    searchGroupName: 'CINEMA',
  },
  CONCERT: {
    appLabel: 'Concert',
    categoryId: 'MUSIQUE_LIVE',
    homepageLabelName: 'MUSIQUE',
    isEvent: true,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'MUSIQUE',
  },
  CONCOURS: {
    appLabel: 'Concours - jeux',
    categoryId: 'JEU',
    homepageLabelName: 'JEU',
    isEvent: true,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'JEU',
  },
  CONFERENCE: {
    appLabel: 'Conférence',
    categoryId: 'CONFERENCE',
    homepageLabelName: 'CONFERENCE',
    isEvent: true,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'CONFERENCE',
  },
  DECOUVERTE_METIERS: {
    appLabel: 'Découverte des métiers',
    categoryId: 'CONFERENCE',
    homepageLabelName: 'CONFERENCE',
    isEvent: true,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'CONFERENCE',
  },
  ESCAPE_GAME: {
    appLabel: 'Escape game',
    categoryId: 'JEU',
    homepageLabelName: 'JEU',
    isEvent: false,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'JEU',
  },
  EVENEMENT_CINE: {
    appLabel: 'Événement cinéma',
    categoryId: 'CINEMA',
    homepageLabelName: 'CINEMA',
    isEvent: true,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'CINEMA',
  },
  EVENEMENT_JEU: {
    appLabel: 'Événements - jeux',
    categoryId: 'JEU',
    homepageLabelName: 'JEU',
    isEvent: true,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'JEU',
  },
  EVENEMENT_MUSIQUE: {
    appLabel: "Autre type d'événement musical",
    categoryId: 'MUSIQUE_LIVE',
    homepageLabelName: 'MUSIQUE',
    isEvent: true,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'MUSIQUE',
  },
  EVENEMENT_PATRIMOINE: {
    appLabel: 'Événement et atelier patrimoine',
    categoryId: 'MUSEE',
    homepageLabelName: 'VISITE',
    isEvent: true,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'VISITE',
  },
  FESTIVAL_CINE: {
    appLabel: 'Festival de cinéma',
    categoryId: 'CINEMA',
    homepageLabelName: 'CINEMA',
    isEvent: true,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'CINEMA',
  },
  FESTIVAL_LIVRE: {
    appLabel: 'Festival et salon du livre',
    categoryId: 'LIVRE',
    homepageLabelName: 'LIVRE',
    isEvent: true,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'LIVRE',
  },
  FESTIVAL_MUSIQUE: {
    appLabel: 'Festival de musique',
    categoryId: 'MUSIQUE_LIVE',
    homepageLabelName: 'MUSIQUE',
    isEvent: true,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'MUSIQUE',
  },
  FESTIVAL_SPECTACLE: {
    appLabel: 'Festival',
    categoryId: 'SPECTACLE',
    homepageLabelName: 'SPECTACLE',
    isEvent: true,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'SPECTACLE',
  },
  JEU_EN_LIGNE: {
    appLabel: 'Jeux en ligne',
    categoryId: 'JEU',
    homepageLabelName: 'JEU',
    isEvent: false,
    onlineOfflinePlatform: 'ONLINE',
    searchGroupName: 'JEU',
  },
  JEU_SUPPORT_PHYSIQUE: {
    appLabel: 'Catégorie technique Jeu support physique',
    categoryId: 'TECHNIQUE',
    homepageLabelName: 'NONE',
    isEvent: false,
    onlineOfflinePlatform: 'ONLINE_OR_OFFLINE',
    searchGroupName: 'NONE',
  },
  LIVESTREAM_EVENEMENT: {
    appLabel: "Live stream d'événement",
    categoryId: 'SPECTACLE',
    homepageLabelName: 'SPECTACLE',
    isEvent: true,
    onlineOfflinePlatform: 'ONLINE',
    searchGroupName: 'SPECTACLE',
  },
  LIVESTREAM_MUSIQUE: {
    appLabel: 'Livestream musical',
    categoryId: 'MUSIQUE_LIVE',
    homepageLabelName: 'MUSIQUE',
    isEvent: true,
    onlineOfflinePlatform: 'ONLINE',
    searchGroupName: 'MUSIQUE',
  },
  LIVESTREAM_PRATIQUE_ARTISTIQUE: {
    appLabel: 'Pratique artistique - livestream',
    categoryId: 'PRATIQUE_ART',
    homepageLabelName: 'COURS',
    isEvent: true,
    onlineOfflinePlatform: 'ONLINE',
    searchGroupName: 'COURS',
  },
  LIVRE_AUDIO_PHYSIQUE: {
    appLabel: 'Livre audio sur support physique',
    categoryId: 'LIVRE',
    homepageLabelName: 'LIVRE',
    isEvent: false,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'LIVRE',
  },
  LIVRE_NUMERIQUE: {
    appLabel: 'Livre numérique, e-book',
    categoryId: 'LIVRE',
    homepageLabelName: 'LIVRE',
    isEvent: false,
    onlineOfflinePlatform: 'ONLINE',
    searchGroupName: 'LIVRE',
  },
  LIVRE_PAPIER: {
    appLabel: 'Livre',
    categoryId: 'LIVRE',
    homepageLabelName: 'LIVRE',
    isEvent: false,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'LIVRE',
  },
  LOCATION_INSTRUMENT: {
    appLabel: 'Location instrument',
    categoryId: 'INSTRUMENT',
    homepageLabelName: 'MUSIQUE',
    isEvent: false,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'INSTRUMENT',
  },
  MATERIEL_ART_CREATIF: {
    appLabel: 'Matériel arts créatifs',
    categoryId: 'BEAUX_ARTS',
    homepageLabelName: 'MATERIEL',
    isEvent: false,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'MATERIEL',
  },
  MUSEE_VENTE_DISTANCE: {
    appLabel: 'Musée vente à distance',
    categoryId: 'MUSEE',
    homepageLabelName: 'VISITE',
    isEvent: false,
    onlineOfflinePlatform: 'ONLINE',
    searchGroupName: 'VISITE',
  },
  OEUVRE_ART: {
    appLabel: "Catégorie technique d'oeuvre d'art",
    categoryId: 'TECHNIQUE',
    homepageLabelName: 'NONE',
    isEvent: false,
    onlineOfflinePlatform: 'ONLINE_OR_OFFLINE',
    searchGroupName: 'NONE',
  },
  PARTITION: {
    appLabel: 'Partition',
    categoryId: 'INSTRUMENT',
    homepageLabelName: 'MUSIQUE',
    isEvent: false,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'INSTRUMENT',
  },
  PLATEFORME_PRATIQUE_ARTISTIQUE: {
    appLabel: 'Plateforme de pratique artistique',
    categoryId: 'PRATIQUE_ART',
    homepageLabelName: 'COURS',
    isEvent: false,
    onlineOfflinePlatform: 'ONLINE',
    searchGroupName: 'COURS',
  },
  PODCAST: {
    appLabel: 'Podcast',
    categoryId: 'MEDIA',
    homepageLabelName: 'PRESSE',
    isEvent: false,
    onlineOfflinePlatform: 'ONLINE',
    searchGroupName: 'PRESSE',
  },
  PRATIQUE_ART_VENTE_DISTANCE: {
    appLabel: 'Pratique artistique - vente à distance',
    categoryId: 'PRATIQUE_ART',
    homepageLabelName: 'COURS',
    isEvent: false,
    onlineOfflinePlatform: 'ONLINE',
    searchGroupName: 'COURS',
  },
  RENCONTRE: {
    appLabel: 'Rencontre',
    categoryId: 'CONFERENCE',
    homepageLabelName: 'CONFERENCE',
    isEvent: true,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'CONFERENCE',
  },
  RENCONTRE_EN_LIGNE: {
    appLabel: 'Rencontre en ligne',
    categoryId: 'CONFERENCE',
    homepageLabelName: 'CONFERENCE',
    isEvent: true,
    onlineOfflinePlatform: 'ONLINE',
    searchGroupName: 'CONFERENCE',
  },
  RENCONTRE_JEU: {
    appLabel: 'Rencontres - jeux',
    categoryId: 'JEU',
    homepageLabelName: 'JEU',
    isEvent: true,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'JEU',
  },
  SALON: {
    appLabel: 'Salon, Convention',
    categoryId: 'CONFERENCE',
    homepageLabelName: 'CONFERENCE',
    isEvent: true,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'CONFERENCE',
  },
  SEANCE_CINE: {
    appLabel: 'Séance de cinéma',
    categoryId: 'CINEMA',
    homepageLabelName: 'CINEMA',
    isEvent: true,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'CINEMA',
  },
  SEANCE_ESSAI_PRATIQUE_ART: {
    appLabel: "Séance d'essai",
    categoryId: 'PRATIQUE_ART',
    homepageLabelName: 'COURS',
    isEvent: true,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'COURS',
  },
  SPECTACLE_ENREGISTRE: {
    appLabel: 'Spectacle enregistré',
    categoryId: 'SPECTACLE',
    homepageLabelName: 'SPECTACLE',
    isEvent: false,
    onlineOfflinePlatform: 'ONLINE',
    searchGroupName: 'SPECTACLE',
  },
  SPECTACLE_REPRESENTATION: {
    appLabel: 'Spectacle, représentation',
    categoryId: 'SPECTACLE',
    homepageLabelName: 'SPECTACLE',
    isEvent: true,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'SPECTACLE',
  },
  SPECTACLE_VENTE_DISTANCE: {
    appLabel: 'Spectacle vivant - vente à distance',
    categoryId: 'SPECTACLE',
    homepageLabelName: 'SPECTACLE',
    isEvent: false,
    onlineOfflinePlatform: 'ONLINE',
    searchGroupName: 'SPECTACLE',
  },
  SUPPORT_PHYSIQUE_FILM: {
    appLabel: 'Support physique (DVD, Blu-ray...)',
    categoryId: 'FILM',
    homepageLabelName: 'FILM',
    isEvent: false,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'FILM',
  },
  SUPPORT_PHYSIQUE_MUSIQUE: {
    appLabel: 'Support physique (CD, vinyle...)',
    categoryId: 'MUSIQUE_ENREGISTREE',
    homepageLabelName: 'MUSIQUE',
    isEvent: false,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'MUSIQUE',
  },
  TELECHARGEMENT_LIVRE_AUDIO: {
    appLabel: 'Livre audio à télécharger',
    categoryId: 'LIVRE',
    homepageLabelName: 'LIVRE',
    isEvent: false,
    onlineOfflinePlatform: 'ONLINE',
    searchGroupName: 'LIVRE',
  },
  TELECHARGEMENT_MUSIQUE: {
    appLabel: 'Téléchargement de musique',
    categoryId: 'MUSIQUE_ENREGISTREE',
    homepageLabelName: 'MUSIQUE',
    isEvent: false,
    onlineOfflinePlatform: 'ONLINE',
    searchGroupName: 'MUSIQUE',
  },
  VISITE: {
    appLabel: 'Visite',
    categoryId: 'MUSEE',
    homepageLabelName: 'VISITE',
    isEvent: true,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'VISITE',
  },
  VISITE_GUIDEE: {
    appLabel: 'Visite guidée',
    categoryId: 'MUSEE',
    homepageLabelName: 'VISITE',
    isEvent: true,
    onlineOfflinePlatform: 'OFFLINE',
    searchGroupName: 'VISITE',
  },
  VISITE_VIRTUELLE: {
    appLabel: 'Visite virtuelle',
    categoryId: 'MUSEE',
    homepageLabelName: 'VISITE',
    isEvent: false,
    onlineOfflinePlatform: 'ONLINE',
    searchGroupName: 'VISITE',
  },
  VOD: {
    appLabel: 'Vidéo à la demande',
    categoryId: 'FILM',
    homepageLabelName: 'FILM',
    isEvent: false,
    onlineOfflinePlatform: 'ONLINE',
    searchGroupName: 'FILM',
  },
}
