import { t } from '@lingui/macro'

import { Headers, NotAuthenticatedError } from 'libs/fetch'
import { _ } from 'libs/i18n'
import { getAccessToken } from 'libs/storage'

export async function getAuthenticationHeaders(options?: RequestInit): Promise<Headers> {
  const accessToken = await getAccessToken()
  const shouldAuthenticate = accessToken && (!options || options.credentials !== 'omit')
  if (shouldAuthenticate) {
    return { Authorization: `Bearer ${accessToken}` }
  }
  return {}
}

// In this case, the following `any` is not that much of a problem in the context of usage
// with the autogenerated files of swagger-codegen.
// !!! Not encouraging to use `any` anywhere else !!!
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function handleGeneratedApiResponse(response: Response): Promise<any | void> {
  if (response.status === 204) {
    return {}
  }

  if (response.status === 401) {
    throw new NotAuthenticatedError()
  }

  if (!response.ok) {
    throw new Error(_(t`Échec de la requête ${response.url}, code: ${response.status}`))
  }

  const json = await response.json()
  return json
}
