/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import type { Meta } from '@storybook/react-vite'
import React, { useState } from 'react'

import {
  CheckboxGroupOptionDetailed,
  CheckboxGroupOptionSimple,
} from 'ui/designSystem/CheckboxGroup/types'
import { VariantsTemplate, type Variants, type VariantsStory } from 'ui/storybook/VariantsTemplate'

import { CheckboxGroup } from './CheckboxGroup'

const meta: Meta<typeof CheckboxGroup> = {
  title: 'design system/inputs/CheckboxGroup',
  component: CheckboxGroup,
}
export default meta

const optionDefault: CheckboxGroupOptionSimple[] = ['option1', 'option2', 'option3'].map(
  (value, index) => ({ label: `Option ${index + 1}`, value })
)

const optionDefaultWithRequired: CheckboxGroupOptionSimple[] = [
  'option1',
  'option2',
  'option3',
].map((value, index) => ({ label: `Option ${index + 1}`, value, required: index === 1 }))

const optionsDetailed: CheckboxGroupOptionDetailed[] = ['option1', 'option2', 'option3'].map(
  (value, index) => ({
    label: `Detailed ${index + 1}`,
    description: `Detailed description ${index + 1}`,
    value,
    variant: 'detailed',
    asset: {
      variant: 'image',
      src: 'https://storage.googleapis.com/passculture-metier-prod-production-assets-fine-grained/thumbs/mediations/9MPGW',
    },
  })
)

const variantConfig: Variants<typeof CheckboxGroup> = [
  {
    label: 'CheckboxGroup Default Vertical',
    props: {
      label: 'Choose your options',
      variant: 'default',
      display: 'vertical',
      options: optionDefault,
    },
  },
  {
    label: 'CheckboxGroup Default Horizontal',
    props: {
      label: 'Choose your options',
      variant: 'default',
      display: 'horizontal',
      options: optionDefault,
    },
  },
  {
    label: 'CheckboxGroup Default with Description',
    props: {
      label: 'Choose your options',
      variant: 'default',
      description: 'You can select several options.',
      options: optionDefault,
    },
  },
  {
    label: 'CheckboxGroup Default with Error',
    props: {
      label: 'Choose your options',
      variant: 'default',
      error: 'You must select at least one option.',
      options: optionDefault,
    },
  },
  {
    label: 'CheckboxGroup Default with Description and Error',
    props: {
      label: 'Choose your options',
      variant: 'default',
      description: 'You can select several options.',
      error: 'You must select at least one option.',
      options: optionDefault,
    },
  },
  {
    label: 'CheckboxGroup Default and Disabled',
    props: {
      label: 'Choose your options',
      variant: 'default',
      description: 'You can select several options.',
      options: optionDefault,
      disabled: true,
    },
  },
  {
    label: 'CheckboxGroup Default with Default value',
    props: {
      label: 'Choose your options',
      variant: 'default',
      value: ['option2'],
      options: optionDefault,
    },
  },
  {
    label: 'CheckboxGroup Default with Required',
    props: {
      label: 'Choose your detailed options',
      display: 'vertical',
      options: optionDefaultWithRequired,
    },
  },
  {
    label: 'CheckboxGroup Detailed Vertical',
    props: {
      label: 'Choose your detailed options',
      variant: 'detailed',
      display: 'vertical',
      options: optionsDetailed,
    },
  },
  {
    label: 'CheckboxGroup Detailed Horizontal',
    props: {
      label: 'Choose your detailed options',
      variant: 'detailed',
      display: 'horizontal',
      options: optionsDetailed,
    },
  },
  {
    label: 'CheckboxGroup Detailed with Description',
    props: {
      label: 'Choose your detailed options',
      variant: 'detailed',
      display: 'vertical',
      options: optionsDetailed,
      description: 'You can select several options.',
    },
  },
  {
    label: 'CheckboxGroup Detailed with Heading Tag',
    props: {
      label: 'Choose your detailed options',
      variant: 'detailed',
      display: 'vertical',
      options: optionsDetailed,
      labelTag: 'h2',
      description: 'You can select several options.',
    },
  },
  {
    label: 'CheckboxGroup Detailed with Error',
    props: {
      label: 'Choose your detailed options',
      variant: 'detailed',
      display: 'vertical',
      options: optionsDetailed,
      error: 'You must select at least one option.',
    },
  },
  {
    label: 'CheckboxGroup Detailed with Description and Error',
    props: {
      label: 'Choose your detailed options',
      variant: 'detailed',
      display: 'vertical',
      options: optionsDetailed,
      description: 'You can select several options.',
      error: 'You must select at least one option.',
    },
  },
  {
    label: 'CheckboxGroup Detailed Disabled',
    props: {
      label: 'Choose your detailed options',
      variant: 'detailed',
      display: 'vertical',
      options: optionsDetailed,
      disabled: true,
    },
  },
  {
    label: 'CheckboxGroup Detailed with Default value',
    props: {
      label: 'Choose your detailed options',
      variant: 'detailed',
      display: 'vertical',
      value: ['option2'],
      options: optionsDetailed,
    },
  },
]

export const Template: VariantsStory<typeof CheckboxGroup> = {
  name: 'CheckboxGroup',
  render: (props) => {
    const [selected, setSelected] = useState(props.value ?? [])

    return (
      <VariantsTemplate
        variants={variantConfig}
        Component={CheckboxGroup}
        defaultProps={{ ...props, value: selected, onChange: setSelected }}
      />
    )
  },
}
