/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import { ElementType } from 'react'

import { CheckboxProps } from 'ui/designSystem/Checkbox/Checkbox'
import { SelectableVariant } from 'ui/designSystem/types'

export type CheckboxGroupOptionSimple<T = string> = Omit<
  CheckboxProps,
  'checked' | 'onChange' | 'hasError' | 'disabled' | 'variant' | 'asset' | 'onPress' | 'isChecked'
> & {
  label: string
  value: T
  variant?: 'default'
  asset?: never
}

export type CheckboxGroupOptionDetailed<T = string> = Omit<
  CheckboxProps,
  'checked' | 'onChange' | 'hasError' | 'disabled' | 'variant' | 'onPress' | 'isChecked'
> & {
  label: string
  value: T
  variant: 'detailed'
  asset?: CheckboxProps['asset']
}

export type CheckboxGroupOption<T = string> =
  | CheckboxGroupOptionSimple<T>
  | CheckboxGroupOptionDetailed<T>

export type CheckboxGroupDisplay = 'vertical' | 'horizontal'

export type CheckboxGroupProps<T = string> = {
  label: string
  labelTag?: ElementType
  description?: string
  error?: string
  options: CheckboxGroupOption<T>[]
  value: T[]
  onChange: (value: T[]) => void
  display?: CheckboxGroupDisplay
  variant?: SelectableVariant
  disabled?: boolean
}
