/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import type { Meta } from '@storybook/react-vite'
import React from 'react'

import { RadioButtonGroup } from 'ui/designSystem/RadioButtonGroup/RadioButtonGroup'
import { VariantsTemplate, type Variants, type VariantsStory } from 'ui/storybook/VariantsTemplate'

const meta: Meta<typeof RadioButtonGroup> = {
  title: 'design system/inputs/RadioButtonGroup',
  component: RadioButtonGroup,
}
export default meta

const variantConfig: Variants<typeof RadioButtonGroup> = [
  {
    label: 'RadioButtonGroup Default',
    props: {
      label: 'Label',
      options: [
        { label: 'RadioButton_1', variant: 'default' },
        { label: 'RadioButton_2', variant: 'default' },
      ],
    },
  },
  {
    label: 'RadioButtonGroup Detailed',
    props: {
      label: 'Label',
      options: [
        { label: 'RadioButton_1', variant: 'detailed' },
        { label: 'RadioButton_2', variant: 'detailed' },
      ],
    },
  },
  {
    label: 'RadioButtonGroup Disabled',
    props: {
      label: 'Label',
      options: [
        { label: 'RadioButton_1', variant: 'default', disabled: true },
        { label: 'RadioButton_2', variant: 'default', disabled: true },
      ],
    },
  },
  {
    label: 'RadioButtonGroup Error',
    props: {
      label: 'Label',
      options: [
        { label: 'RadioButton_1', variant: 'default', error: true },
        { label: 'RadioButton_2', variant: 'default', error: true },
      ],
    },
  },
]

export const Template: VariantsStory<typeof RadioButtonGroup> = {
  name: 'RadioButtonGroup',
  render: (props) => (
    <VariantsTemplate variants={variantConfig} Component={RadioButtonGroup} defaultProps={props} />
  ),
}
