/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React, { FunctionComponent, useCallback } from 'react'
import { FlatList, FlatListProps, ListRenderItemInfo } from 'react-native'
import styled from 'styled-components/native'

import { AccessibilityRole } from 'libs/accessibilityRole/accessibilityRole'
import { RadioButton } from 'ui/designSystem/RadioButton/RadioButton'
import { BaseRadioProps, Variant } from 'ui/designSystem/RadioButton/types'
import { SelectableSizing } from 'ui/designSystem/types'
import { ErrorFilled } from 'ui/svg/icons/ErrorFilled'
import { Typo } from 'ui/theme'

type RadioButtonGroupDisplay = 'horizontal' | 'vertical'

export type RadioButtonGroupOption = Omit<
  BaseRadioProps,
  'value' | 'setValue' | 'error' | 'variant' | 'disabled'
> & {
  key: string
}

type Props = {
  label: string
  description: string
  options: Array<RadioButtonGroupOption>
  value: string
  onValueChange: (value: string) => void
  errorText?: string
  error?: boolean
  variant?: Variant
  disabled?: boolean
  display?: RadioButtonGroupDisplay
  onEndReached?: () => void
  refreshing?: boolean
  onRefresh?: () => void
  onScroll?: FlatListProps<RadioButtonGroupOption>['onScroll']
  ListFooterComponent?: React.ReactElement
}

export const RadioButtonGroup: FunctionComponent<Props> = ({
  label,
  description,
  options,
  value,
  onValueChange,
  errorText,
  error = false,
  variant = 'default',
  disabled = false,
  display = 'vertical',
  onEndReached,
  refreshing,
  onRefresh,
  onScroll,
  ListFooterComponent,
}: Props) => {
  const keyExtractor = useCallback((item: RadioButtonGroupOption) => item.key, [])

  const setValue: React.Dispatch<React.SetStateAction<string>> = useCallback(
    (newValue) => {
      const resolvedValue = typeof newValue === 'function' ? newValue(value) : newValue
      onValueChange(resolvedValue)
    },
    [onValueChange, value]
  )

  const renderItem = useCallback(
    ({ item }: ListRenderItemInfo<RadioButtonGroupOption>) => (
      <RadioButtonItemWrapper variant={variant} display={display}>
        <RadioButton
          label={item.label}
          disabled={disabled}
          error={error}
          value={value}
          setValue={disabled || value === item.label ? () => undefined : setValue}
          variant={variant}
          description={item.description}
          collapsed={item.collapsed}
          asset={item.asset}
          sizing={computedRadioButtonSizing(item.sizing, display)}
        />
      </RadioButtonItemWrapper>
    ),
    [disabled, error, value, setValue, variant, display]
  )

  return (
    <RadioButtonGroupContainer accessibilityRole={AccessibilityRole.GROUP}>
      <TitleContainer>
        <Typo.Body>{label}</Typo.Body>
        <Description>{description}</Description>
        {error && errorText ? (
          <ErrorContainer>
            <ErrorIcon />
            <ErrorText>{errorText}</ErrorText>
          </ErrorContainer>
        ) : null}
      </TitleContainer>
      <StyledFlatList
        data={options}
        renderItem={renderItem}
        keyExtractor={keyExtractor}
        onEndReached={onEndReached}
        refreshing={refreshing}
        onRefresh={onRefresh}
        onScroll={onScroll}
        ListFooterComponent={ListFooterComponent}
        keyboardShouldPersistTaps="handled"
        keyboardDismissMode="on-drag"
      />
    </RadioButtonGroupContainer>
  )
}

const computedRadioButtonSizing = (
  sizing: SelectableSizing | undefined,
  display: RadioButtonGroupDisplay
) => {
  if (sizing) return sizing
  return display === 'horizontal' ? 'hug' : 'fill'
}

const RadioButtonGroupContainer = styled.View(({ theme }) => ({
  flex: 1,
  gap: theme.designSystem.size.spacing.s,
}))

const StyledFlatList = styled(FlatList)({
  flex: 1,
  overflow: 'scroll',
}) as typeof FlatList

const RadioButtonItemWrapper = styled.View<{
  variant: Variant
  display: RadioButtonGroupDisplay
}>(({ theme, variant, display }) => ({
  flexWrap: display === 'horizontal' ? 'wrap' : 'nowrap',
  flexDirection: display === 'vertical' ? 'column' : 'row',
  gap:
    variant == 'default' || display === 'horizontal'
      ? theme.designSystem.size.spacing.xl
      : theme.designSystem.size.spacing.s,
  paddingBottom:
    variant === 'default' || display === 'horizontal'
      ? theme.designSystem.size.spacing.xl
      : theme.designSystem.size.spacing.s,
}))

const ErrorContainer = styled.View(({ theme }) => ({
  display: 'flex',
  flexDirection: 'row',
  alignItems: 'center',
  gap: theme.designSystem.size.spacing.xs,
}))

const TitleContainer = styled.View(({ theme }) => ({
  gap: theme.designSystem.size.spacing.xs,
}))

const Description = styled(Typo.BodyXs)(({ theme }) => ({
  color: theme.designSystem.color.text.subtle,
}))

const ErrorText = styled(Typo.BodyXs)(({ theme }) => ({
  color: theme.designSystem.color.text.error,
}))

const ErrorIcon = styled(ErrorFilled).attrs(({ theme }) => ({
  size: theme.icons.sizes.extraSmall,
  color: theme.designSystem.color.icon.error,
}))``
