/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React, { ComponentProps, useState } from 'react'

import { render, screen, userEvent } from 'tests/utils'

import { RadioButtonGroup } from './RadioButtonGroup'

const label = 'RadioButtonGroup'
const description = 'A beautiful RadioButtonGroup'
const errorText = 'An Error in RadioButtonGroup'
const options = [{ label: 'RadioButton_1' }, { label: 'RadioButton_2' }]

const baseProps: ComponentProps<typeof RadioButtonGroup> = {
  label,
  description,
  errorText,
  error: false,
  variant: 'default',
  disabled: false,
  display: 'vertical',
  options,
  value: '',
  onValueChange: () => undefined,
}

const user = userEvent.setup()

const ControlledRadioButtonGroup = (
  props: Omit<ComponentProps<typeof RadioButtonGroup>, 'value' | 'onValueChange'>
) => {
  const [value, setValue] = useState('')
  return <RadioButtonGroup {...props} value={value} onValueChange={setValue} />
}

describe('<RadioButtonGroup />', () => {
  it('should render a RadioButtonGroup', () => {
    render(<RadioButtonGroup {...baseProps} />)

    expect(screen.getByText(label)).toBeOnTheScreen()
    expect(screen.getByText(description)).toBeOnTheScreen()
    expect(screen.getByLabelText('RadioButton_1')).toBeOnTheScreen()
    expect(screen.getByLabelText('RadioButton_2')).toBeOnTheScreen()
  })

  it('should check only one Radiobutton', async () => {
    render(<ControlledRadioButtonGroup {...baseProps} />)
    await user.press(screen.getByLabelText('RadioButton_1'))

    expect(screen.getByLabelText('RadioButton_1')).toBeChecked()
    expect(screen.getByLabelText('RadioButton_2')).not.toBeChecked()

    await user.press(screen.getByLabelText('RadioButton_2'))

    expect(screen.getByLabelText('RadioButton_2')).toBeChecked()
    expect(screen.getByLabelText('RadioButton_1')).not.toBeChecked()
  })

  it('should prevent RadioButton to be checked when disabled', async () => {
    render(<ControlledRadioButtonGroup {...baseProps} disabled />)
    await user.press(screen.getByLabelText('RadioButton_1'))

    expect(screen.getByLabelText('RadioButton_1')).not.toBeChecked()
    expect(screen.getByLabelText('RadioButton_2')).not.toBeChecked()
  })

  it('should prevent RadioButton to be unchecked when already selected', async () => {
    render(<ControlledRadioButtonGroup {...baseProps} disabled />)
    await user.press(screen.getByLabelText('RadioButton_1'))

    expect(screen.getByLabelText('RadioButton_1')).not.toBeChecked()
    expect(screen.getByLabelText('RadioButton_2')).not.toBeChecked()

    await user.press(screen.getByLabelText('RadioButton_1'))

    expect(screen.getByLabelText('RadioButton_1')).not.toBeChecked()
    expect(screen.getByLabelText('RadioButton_2')).not.toBeChecked()
  })

  it('should render Error text when RadioButtonGroup is in error', () => {
    render(<RadioButtonGroup {...baseProps} error />)

    expect(screen.getByText(label)).toBeOnTheScreen()
    expect(screen.getByText(description)).toBeOnTheScreen()
    expect(screen.getByText(errorText)).toBeOnTheScreen()
  })
})
