/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import type { Meta } from '@storybook/react-vite'
import React from 'react'

import {
  RadioButtonGroup,
  RadioButtonGroupOption,
} from 'ui/designSystem/RadioButtonGroup/RadioButtonGroup'
import { VariantsTemplate, type Variants, type VariantsStory } from 'ui/storybook/VariantsTemplate'

const meta: Meta<typeof RadioButtonGroup> = {
  title: 'design system/inputs/RadioButtonGroup',
  component: RadioButtonGroup,
}
export default meta

const optionsDetailed = (keyPrefix: string): Array<RadioButtonGroupOption> =>
  ['option1', 'option2', 'option3'].map((_, index) => ({
    key: `${keyPrefix}-${index + 1}`,
    label: `RadioButton Detailed ${index + 1}`,
    description: `Detailed description ${index + 1}`,
    collapsed: false,
    asset: {
      variant: 'image',
      src: 'https://storage.googleapis.com/passculture-metier-prod-production-assets-fine-grained/thumbs/mediations/9MPGW',
    },
  }))

const onValueChange = () => undefined

const variantConfig: Variants<typeof RadioButtonGroup> = [
  {
    label: 'RadioButtonGroup Default',
    minHeight: 150,
    props: {
      label: 'Label',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      value: '',
      onValueChange,
      options: [
        { label: 'RadioButton_1', sizing: 'fill', key: 'radio-button-default-1' },
        { label: 'RadioButton_2', sizing: 'fill', key: 'radio-button-default-2' },
      ],
    },
  },
  {
    label: 'RadioButtonGroup Disabled',
    minHeight: 150,
    props: {
      label: 'Label',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      value: '',
      onValueChange,
      disabled: true,
      options: [
        { label: 'RadioButton_1', sizing: 'fill', key: 'radio-button-disabled-1' },
        { label: 'RadioButton_2', sizing: 'fill', key: 'radio-button-disabled-2' },
      ],
    },
  },
  {
    label: 'RadioButtonGroup Error',
    minHeight: 170,
    props: {
      label: 'Label',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      value: '',
      onValueChange,
      error: true,
      errorText: 'Some error text',
      options: [
        { label: 'RadioButton_1', sizing: 'fill', key: 'radio-button-error-1' },
        { label: 'RadioButton_2', sizing: 'fill', key: 'radio-button-error-2' },
      ],
    },
  },
  {
    label: 'RadioButtonGroup Horizontal',
    minHeight: 150,
    props: {
      label: 'Label',
      display: 'horizontal',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      value: '',
      onValueChange,
      options: [
        { label: 'RadioButton_1', sizing: 'fill', key: 'radio-button-horizontal-1' },
        { label: 'RadioButton_2', sizing: 'fill', key: 'radio-button-horizontal-2' },
      ],
    },
  },
  {
    label: 'RadioButtonGroup Detailed',
    minHeight: 400,
    props: {
      label: 'Label',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      value: '',
      onValueChange,
      variant: 'detailed',
      options: optionsDetailed('radio-button-detailed'),
    },
  },
  {
    label: 'RadioButtonGroup Detailed Error',
    minHeight: 420,
    props: {
      label: 'Label',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      value: '',
      onValueChange,
      variant: 'detailed',
      error: true,
      errorText: 'Error mega',
      options: optionsDetailed('radio-button-detailed-error'),
    },
  },
  {
    label: 'RadioButtonGroup Detailed Disabled',
    minHeight: 400,
    props: {
      label: 'Label',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      value: '',
      onValueChange,
      variant: 'detailed',
      disabled: true,
      options: optionsDetailed('radio-button-detailed-disabled'),
    },
  },
  {
    label: 'RadioButtonGroup Detailed Horizontal',
    minHeight: 200,
    props: {
      label: 'Label',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      value: '',
      onValueChange,
      variant: 'detailed',
      display: 'horizontal',
      options: optionsDetailed('radio-button-detailed-horizontal'),
    },
  },
]

export const Template: VariantsStory<typeof RadioButtonGroup> = {
  name: 'RadioButtonGroup',
  render: (props) => (
    <VariantsTemplate variants={variantConfig} Component={RadioButtonGroup} defaultProps={props} />
  ),
}
