/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React, { ComponentProps, useState } from 'react'

import { render, screen, userEvent } from 'tests/utils'

import { RadioButtonGroup } from './RadioButtonGroup'

const label = 'RadioButtonGroup'
const description = 'A beautiful RadioButtonGroup'
const errorText = 'An Error in RadioButtonGroup'
const options = [
  { label: 'RadioButton_1', key: 'radio-button-1' },
  { label: 'RadioButton_2', key: 'radio-button-2' },
]

const baseProps: ComponentProps<typeof RadioButtonGroup> = {
  label,
  description,
  errorText,
  error: false,
  variant: 'default',
  disabled: false,
  display: 'vertical',
  options,
  value: '',
  onChange: () => undefined,
}

const user = userEvent.setup()

const ControlledRadioGroup = (props: Partial<ComponentProps<typeof RadioButtonGroup>>) => {
  const [value, setValue] = useState('')
  return <RadioButtonGroup {...baseProps} {...props} value={value} onChange={setValue} />
}

describe('<RadioButtonGroup />', () => {
  it('should render a RadioButtonGroup', () => {
    render(<ControlledRadioGroup />)

    expect(screen.getByText(label)).toBeOnTheScreen()
    expect(screen.getByText(description)).toBeOnTheScreen()
    expect(
      screen.getByLabelText(
        'RadioButtonGroup - Liste - Élément 1 sur 2 - RadioButton_1 - non sélectionné'
      )
    ).toBeOnTheScreen()
    expect(
      screen.getByLabelText(
        'RadioButtonGroup - Liste - Élément 2 sur 2 - RadioButton_2 - non sélectionné'
      )
    ).toBeOnTheScreen()
  })

  it('should check only one Radiobutton', async () => {
    render(<ControlledRadioGroup />)
    await user.press(
      screen.getByLabelText(
        'RadioButtonGroup - Liste - Élément 1 sur 2 - RadioButton_1 - non sélectionné'
      )
    )

    expect(
      screen.getByLabelText(
        'RadioButtonGroup - Liste - Élément 1 sur 2 - RadioButton_1 - sélectionné'
      )
    ).toBeChecked()
    expect(
      screen.getByLabelText(
        'RadioButtonGroup - Liste - Élément 2 sur 2 - RadioButton_2 - non sélectionné'
      )
    ).not.toBeChecked()

    await user.press(
      screen.getByLabelText(
        'RadioButtonGroup - Liste - Élément 2 sur 2 - RadioButton_2 - non sélectionné'
      )
    )

    expect(
      screen.getByLabelText(
        'RadioButtonGroup - Liste - Élément 2 sur 2 - RadioButton_2 - sélectionné'
      )
    ).toBeChecked()
    expect(
      screen.getByLabelText(
        'RadioButtonGroup - Liste - Élément 1 sur 2 - RadioButton_1 - non sélectionné'
      )
    ).not.toBeChecked()
  })

  it('should prevent RadioButton to be checked when disabled', async () => {
    render(<ControlledRadioGroup disabled />)
    await user.press(
      screen.getByLabelText(
        'RadioButtonGroup - Liste - Élément 1 sur 2 - RadioButton_1 - non sélectionné'
      )
    )

    expect(
      screen.getByLabelText(
        'RadioButtonGroup - Liste - Élément 1 sur 2 - RadioButton_1 - non sélectionné'
      )
    ).not.toBeChecked()
    expect(
      screen.getByLabelText(
        'RadioButtonGroup - Liste - Élément 2 sur 2 - RadioButton_2 - non sélectionné'
      )
    ).not.toBeChecked()
  })

  it('should prevent RadioButton to be unchecked when already selected', async () => {
    render(<ControlledRadioGroup disabled />)
    await user.press(
      screen.getByLabelText(
        'RadioButtonGroup - Liste - Élément 1 sur 2 - RadioButton_1 - non sélectionné'
      )
    )

    expect(
      screen.getByLabelText(
        'RadioButtonGroup - Liste - Élément 1 sur 2 - RadioButton_1 - non sélectionné'
      )
    ).not.toBeChecked()
    expect(
      screen.getByLabelText(
        'RadioButtonGroup - Liste - Élément 2 sur 2 - RadioButton_2 - non sélectionné'
      )
    ).not.toBeChecked()

    await user.press(
      screen.getByLabelText(
        'RadioButtonGroup - Liste - Élément 1 sur 2 - RadioButton_1 - non sélectionné'
      )
    )

    expect(
      screen.getByLabelText(
        'RadioButtonGroup - Liste - Élément 1 sur 2 - RadioButton_1 - non sélectionné'
      )
    ).not.toBeChecked()
    expect(
      screen.getByLabelText(
        'RadioButtonGroup - Liste - Élément 2 sur 2 - RadioButton_2 - non sélectionné'
      )
    ).not.toBeChecked()
  })

  it('should render Error text when RadioButtonGroup is in error', () => {
    render(<ControlledRadioGroup error />)

    expect(screen.getByText(label)).toBeOnTheScreen()
    expect(screen.getByText(description)).toBeOnTheScreen()
    expect(screen.getByText(errorText)).toBeOnTheScreen()
  })
})
