/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React, { FunctionComponent, useState } from 'react'
import { View } from 'react-native'

import { RadioButton } from 'ui/designSystem/RadioButton/RadioButton'
import { Variant } from 'ui/designSystem/RadioButton/types'

export type RadioButtonGroupOption = {
  variant: Variant
  label: string
  error?: boolean
  disabled?: boolean
}

type Props = {
  label: string
  options: Array<RadioButtonGroupOption>
}

export const RadioButtonGroup: FunctionComponent<Props> = ({ label: _label, options }: Props) => {
  const [value, setValue] = useState('')
  return (
    <View>
      {options.map((option) => (
        <RadioButton
          label={option.label}
          key={`rb-${option.label}`}
          disabled={option.disabled ?? false}
          error={option.error ?? false}
          value={value}
          setValue={setValue}
          variant={option.variant}
        />
      ))}
    </View>
  )
}
