/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React, { ComponentProps, useState } from 'react'

import { act, render, screen, userEvent } from 'tests/utils/web'

import { RadioButtonGroup } from './RadioButtonGroup'

const label = 'Sélectionne ta localisation'
const options = [
  { label: 'Autour de moi', key: 'around-me' },
  { label: 'Choisir une zone géographique', key: 'around-place' },
  { label: 'Partout', key: 'everywhere' },
]

const baseProps: ComponentProps<typeof RadioButtonGroup> = {
  label,
  options,
  value: '',
  onChange: () => undefined,
}

const user = userEvent.setup()

const ControlledRadioGroup = (props: Partial<ComponentProps<typeof RadioButtonGroup>>) => {
  const [value, setValue] = useState(props.value ?? '')
  return <RadioButtonGroup {...baseProps} {...props} value={value} onChange={setValue} />
}

describe('<RadioButtonGroup /> on web', () => {
  it('should expose a radiogroup labelled by the group title', () => {
    render(<ControlledRadioGroup />)

    expect(screen.getByRole('radiogroup', { name: label })).toBeInTheDocument()
  })

  it('should only make one radio reachable with Tab', () => {
    render(<ControlledRadioGroup value="Partout" />)

    const tabbableRadios = screen
      .getAllByRole('radio')
      .filter((radio) => radio.getAttribute('tabindex') === '0')

    expect(tabbableRadios).toHaveLength(1)
    expect(tabbableRadios[0]).toHaveAttribute('aria-checked', 'true')
  })

  it('should not expose the selection state in the accessibility label', () => {
    render(<ControlledRadioGroup />)

    expect(screen.getByRole('radio', { name: /Autour de moi/ })).not.toHaveAccessibleName(
      /sélectionné/
    )
  })

  describe('keyboard navigation', () => {
    it('should move both focus and selection to the next option on ArrowDown', async () => {
      render(<ControlledRadioGroup value="Autour de moi" />)
      const [firstRadio, secondRadio] = screen.getAllByRole('radio')

      await act(async () => {
        firstRadio?.focus()
        await user.keyboard('{ArrowDown}')
      })

      expect(secondRadio).toHaveFocus()
      expect(secondRadio).toHaveAttribute('aria-checked', 'true')
      expect(secondRadio).toHaveAttribute('tabindex', '0')
      expect(firstRadio).toHaveAttribute('tabindex', '-1')
    })

    it('should wrap around to the last option on ArrowUp from the first one', async () => {
      render(<ControlledRadioGroup value="Autour de moi" />)
      const radios = screen.getAllByRole('radio')

      await act(async () => {
        radios[0]?.focus()
        await user.keyboard('{ArrowUp}')
      })

      expect(radios[2]).toHaveFocus()
      expect(radios[2]).toHaveAttribute('aria-checked', 'true')
    })

    it('should jump to the first and last options with Home and End', async () => {
      render(<ControlledRadioGroup value="Choisir une zone géographique" />)
      const radios = screen.getAllByRole('radio')

      await act(async () => {
        radios[1]?.focus()
        await user.keyboard('{End}')
      })

      expect(radios[2]).toHaveFocus()

      await act(async () => {
        await user.keyboard('{Home}')
      })

      expect(radios[0]).toHaveFocus()
    })

    it('should skip disabled options', async () => {
      render(
        <ControlledRadioGroup
          value="Autour de moi"
          options={[
            options[0] as (typeof options)[number],
            { label: 'Choisir une zone géographique', key: 'around-place', disabled: true },
            options[2] as (typeof options)[number],
          ]}
        />
      )
      const radios = screen.getAllByRole('radio')

      await act(async () => {
        radios[0]?.focus()
        await user.keyboard('{ArrowDown}')
      })

      expect(radios[2]).toHaveFocus()
    })

    it('should select the first option when nothing is selected yet', async () => {
      render(<ControlledRadioGroup />)
      const radios = screen.getAllByRole('radio')

      await act(async () => {
        radios[0]?.focus()
        await user.keyboard('{ArrowDown}')
      })

      expect(radios[0]).toHaveFocus()
      expect(radios[0]).toHaveAttribute('aria-checked', 'true')
    })

    it('should ignore arrow keys coming from an input nested in the group', async () => {
      const value = 'Autour de moi'
      render(
        <ControlledRadioGroup
          variant="detailed"
          value={value}
          options={[
            {
              ...(options[0] as (typeof options)[number]),
              collapsed: <input aria-label="Recherche une ville, une adresse..." />,
            },
            options[1] as (typeof options)[number],
          ]}
        />
      )
      const nestedInput = screen.getByLabelText('Recherche une ville, une adresse...')

      await act(async () => {
        nestedInput.focus()
        await user.keyboard('{ArrowDown}')
      })

      expect(nestedInput).toHaveFocus()
      expect(screen.getByRole('radio', { name: new RegExp(value) })).toHaveAttribute(
        'aria-checked',
        'true'
      )
    })
  })
})
