/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import { RefObject } from 'react'
import { FlatList, FlatListProps, View } from 'react-native'

import { BaseRadioProps } from 'ui/designSystem/RadioButton/types'

export type LabelVariant = 'title2' | 'title3' | 'body'

export type RadioButtonGroupOption = Omit<
  BaseRadioProps,
  'value' | 'setValue' | 'error' | 'variant' | 'disabled' | 'id' | 'tabIndex'
> & {
  key: string
  disabled?: boolean
}

export type RadioButtonGroupNavigationParams = {
  containerRef: RefObject<View | null>
  listRef: RefObject<Pick<
    FlatList<RadioButtonGroupOption>,
    'scrollToIndex' | 'scrollToOffset'
  > | null>
  options: RadioButtonGroupOption[]
  value: string
  disabled: boolean
  onChange: (value: string) => void
  id: string
}

export type RadioButtonGroupNavigation = {
  getRadioProps: (key: string) => { id?: string; tabIndex?: 0 | -1 }
  onScrollToIndexFailed?: FlatListProps<RadioButtonGroupOption>['onScrollToIndexFailed']
}
