/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import { PasswordRuleStatus } from 'ui/designSystem/PasswordInput/enums'
import {
  containsCapital,
  containsLowercase,
  containsNumber,
  containsSpecialCharacter,
  getPasswordRuleStatus,
  getPasswordRulesAccessibilityLabel,
  isLongEnough,
  isPasswordCorrect,
} from 'ui/designSystem/PasswordInput/helpers'

describe('Password rules helpers', () => {
  describe('isLongEnough', () => {
    it('returns true when password has at least 12 characters', () => {
      expect(isLongEnough('Password123!')).toBe(true)
    })

    it('returns false when password has less than 12 characters', () => {
      expect(isLongEnough('Pass123!')).toBe(false)
    })
  })

  describe('containsCapital', () => {
    it('returns true when password contains an uppercase letter', () => {
      expect(containsCapital('passwordA')).toBe(true)
    })

    it('returns false when password does not contain an uppercase letter', () => {
      expect(containsCapital('password')).toBe(false)
    })
  })

  describe('containsLowercase', () => {
    it('returns true when password contains a lowercase letter', () => {
      expect(containsLowercase('PASSWORDa')).toBe(true)
    })

    it('returns false when password does not contain a lowercase letter', () => {
      expect(containsLowercase('PASSWORD')).toBe(false)
    })
  })

  describe('containsNumber', () => {
    it('returns true when password contains a number', () => {
      expect(containsNumber('Password1')).toBe(true)
    })

    it('returns false when password does not contain a number', () => {
      expect(containsNumber('Password')).toBe(false)
    })
  })

  describe('containsSpecialCharacter', () => {
    it('returns true when password contains a special character', () => {
      expect(containsSpecialCharacter('Password!')).toBe(true)
    })

    it('returns false when password does not contain a special character', () => {
      expect(containsSpecialCharacter('Password1')).toBe(false)
    })
  })

  describe('isPasswordCorrect', () => {
    it('returns true when password matches all security rules', () => {
      expect(isPasswordCorrect('Password123!')).toBe(true)
    })

    it('returns false when password misses one rule', () => {
      expect(isPasswordCorrect('password123!')).toBe(false)
      expect(isPasswordCorrect('PASSWORD123!')).toBe(false)
      expect(isPasswordCorrect('Password123')).toBe(false)
      expect(isPasswordCorrect('Password!')).toBe(false)
    })
  })

  describe('getPasswordRuleStatus', () => {
    it('returns Default when password is empty', () => {
      expect(getPasswordRuleStatus('', isLongEnough)).toBe(PasswordRuleStatus.Default)
    })

    it('returns Valid when rule is respected', () => {
      expect(getPasswordRuleStatus('Password123!', isLongEnough)).toBe(PasswordRuleStatus.Valid)
    })

    it('returns Invalid when rule is not respected', () => {
      expect(getPasswordRuleStatus('abc', isLongEnough)).toBe(PasswordRuleStatus.Invalid)
    })
  })

  describe('getPasswordRulesAccessibilityLabel', () => {
    it('returns all rules as invalid for an empty password', () => {
      expect(getPasswordRulesAccessibilityLabel('')).toBe(
        'Le mot de passe doit contenir au moins 12 caractères, 1 majuscule, 1 minuscule, 1 chiffre et 1 caractère spécial (!@#$%^&*...)'
      )
    })

    it('returns validated rules for a valid password', () => {
      expect(getPasswordRulesAccessibilityLabel('Password123!')).toBe(
        [
          '12 caractères - critère validé',
          '1 majuscule - critère validé',
          '1 minuscule - critère validé',
          '1 chiffre - critère validé',
          '1 caractère spécial (!@#$%^&*...) - critère validé',
        ].join(', ')
      )
    })

    it('returns mixed validation states', () => {
      expect(getPasswordRulesAccessibilityLabel('password')).toBe(
        [
          '12 caractères - au minimum',
          '1 majuscule - au minimum',
          '1 minuscule - critère validé',
          '1 chiffre - au minimum',
          '1 caractère spécial (!@#$%^&*...) - au minimum',
        ].join(', ')
      )
    })
  })
})
