/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import { PasswordRuleStatus } from 'ui/designSystem/PasswordInput/enums'

export const PASSWORD_MIN_LENGTH = 12
export const PASSWORD_MAX_LENGTH = 72
export const CAPITAL = /[A-Z]+/
export const LOWERCASE = /[a-z]+/
export const NUMBER = /[0-9]+/
export const SPECIAL = /[`!@#$%^&*()_+\-=[\]{};':"\\|,.<>/?~]/

export const isLongEnough = (password: string): boolean => password.length >= PASSWORD_MIN_LENGTH
export const containsCapital = (password: string): boolean => CAPITAL.test(password)
export const containsLowercase = (password: string): boolean => LOWERCASE.test(password)
export const containsNumber = (password: string): boolean => NUMBER.test(password)
export const containsSpecialCharacter = (password: string): boolean => SPECIAL.test(password)

export const isPasswordCorrect = (password: string) =>
  isLongEnough(password) &&
  containsCapital(password) &&
  containsLowercase(password) &&
  containsNumber(password) &&
  containsSpecialCharacter(password)

export const NUMBER_OF_CHARACTERS = '12 caractères'
export const NUMBER_OF_CAPITALS = '1 majuscule'
export const NUMBER_OF_LOWERCASE = '1 minuscule'
export const NUMBER_OF_NUMBERS = '1 chiffre'
export const NUMBER_OF_SPECIAL_CHARACTERS = '1 caractère spécial (!@#$%^&*...)'
const DEFAULT_PASSWORD_SECURITY_RULES_ACCESSIBILITY_LABEL = `Le mot de passe doit contenir au moins ${NUMBER_OF_CHARACTERS}, ${NUMBER_OF_CAPITALS}, ${NUMBER_OF_LOWERCASE}, ${NUMBER_OF_NUMBERS} et ${NUMBER_OF_SPECIAL_CHARACTERS}`

const getRuleLabel = (title: string, isValidated: boolean) =>
  `${title} ${isValidated ? '- critère validé' : '- au minimum'}`

export const getPasswordRulesAccessibilityLabel = (password: string): string => {
  if (password.length === 0) return DEFAULT_PASSWORD_SECURITY_RULES_ACCESSIBILITY_LABEL
  return [
    getRuleLabel(NUMBER_OF_CHARACTERS, isLongEnough(password)),
    getRuleLabel(NUMBER_OF_CAPITALS, containsCapital(password)),
    getRuleLabel(NUMBER_OF_LOWERCASE, containsLowercase(password)),
    getRuleLabel(NUMBER_OF_NUMBERS, containsNumber(password)),
    getRuleLabel(NUMBER_OF_SPECIAL_CHARACTERS, containsSpecialCharacter(password)),
  ].join(', ')
}

export const getPasswordRuleStatus = (
  password: string,
  isRuleValid: (password: string) => boolean
): PasswordRuleStatus => {
  if (password.length === 0) return PasswordRuleStatus.Default
  return isRuleValid(password) ? PasswordRuleStatus.Valid : PasswordRuleStatus.Invalid
}
