/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import type { Meta } from '@storybook/react-vite'
import React from 'react'

import { VariantsTemplate, type Variants, type VariantsStory } from 'ui/storybook/VariantsTemplate'

import { PasswordInput } from './PasswordInput'

const meta: Meta<typeof PasswordInput> = {
  title: 'design system/inputs/PasswordInput/PasswordInput',
  component: PasswordInput,
}
export default meta

const baseProps = {
  label: 'Label',
  value: 'Mot2Passe',
}

const variantConfig: Variants<typeof PasswordInput> = [
  {
    label: 'PasswordInput',
    props: { ...baseProps },
  },
  {
    label: 'PasswordInput with description',
    props: { ...baseProps, description: 'Format\u00a0: Exemple de format' },
  },
  {
    label: 'Disabled PasswordInput',
    props: { ...baseProps, disabled: true },
  },
  {
    label: 'Required PasswordInput with symbol',
    props: { ...baseProps, requiredIndicator: 'symbol' },
  },
  {
    label: 'Required PasswordInput with text',
    props: { ...baseProps, requiredIndicator: 'explicit' },
  },
  {
    label: 'PasswordInput with error',
    props: { ...baseProps, errorMessage: 'Message d’erreur' },
  },
  {
    label: 'PasswordInput with validation default',
    props: { ...baseProps, value: '', displayValidation: true },
  },
  {
    label: 'PasswordInput with validation',
    props: { ...baseProps, displayValidation: true },
  },
]

export const Template: VariantsStory<typeof PasswordInput> = {
  name: 'PasswordInput',
  render: (props) => (
    <VariantsTemplate
      variants={variantConfig}
      Component={PasswordInput}
      defaultProps={{ ...props }}
    />
  ),
}
