/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React, { useState } from 'react'

import { TextInputProps } from 'ui/components/inputs/types'
import { PasswordRules } from 'ui/designSystem/PasswordInput/components/PasswordRules'
import { RightButton } from 'ui/designSystem/PasswordInput/components/RightButton'
import { TextInput } from 'ui/designSystem/TextInput/TextInput'

type Props = Omit<TextInputProps, 'secureTextEntry' | 'rightButton'> & {
  value: string
  onChangeText: (value: string) => void
  autocomplete: 'new-password' | 'current-password'
  displayValidation?: boolean
}

export const PasswordInput = ({
  label,
  value,
  onChangeText,
  description,
  errorMessage,
  disabled,
  requiredIndicator,
  autocomplete,
  displayValidation,
  accessibilityHint,
}: Props) => {
  const [shouldHidePassword, setShouldHidePassword] = useState(true)

  return (
    <React.Fragment>
      <TextInput
        label={label}
        description={description}
        value={value}
        onChangeText={onChangeText}
        autoCapitalize="none"
        secureTextEntry={shouldHidePassword}
        errorMessage={errorMessage}
        disabled={disabled}
        autoComplete={autocomplete}
        requiredIndicator={requiredIndicator}
        rightButton={RightButton({ shouldHidePassword, setShouldHidePassword, disabled })}
        accessibilityHint={accessibilityHint}
        testID={label}
      />
      <PasswordRules visible={displayValidation} password={value} />
    </React.Fragment>
  )
}
