/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import { useEffect, useRef, useState } from 'react'

import { LiveRegionAnnouncement } from 'ui/components/accessibility/liveRegion.types'
import { DISPLAYED_PASSWORD_RULES, getRuleLabel } from 'ui/designSystem/PasswordInput/helpers'

// Announcing the whole rule list on every keystroke would be unusable, so only
// the rules switching to a validated state are sent to the live region.
export const usePasswordRulesAnnouncement = (
  password: string
): LiveRegionAnnouncement | undefined => {
  const [announcement, setAnnouncement] = useState<LiveRegionAnnouncement>()
  const validatedRuleKeys = useRef<string[]>([])

  useEffect(() => {
    const currentValidatedRuleKeys = DISPLAYED_PASSWORD_RULES.filter((rule) =>
      rule.test(password)
    ).map((rule) => rule.key)
    const newlyValidatedRules = DISPLAYED_PASSWORD_RULES.filter(
      (rule) =>
        currentValidatedRuleKeys.includes(rule.key) && !validatedRuleKeys.current.includes(rule.key)
    )
    validatedRuleKeys.current = currentValidatedRuleKeys

    if (newlyValidatedRules.length === 0) return

    setAnnouncement({
      id: currentValidatedRuleKeys.join('-'),
      message: newlyValidatedRules.map((rule) => getRuleLabel(rule.label, true)).join(', '),
    })
  }, [password])

  return announcement
}
