/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React from 'react'
import styled, { useTheme } from 'styled-components/native'

import { AccessibilityRole } from 'libs/accessibilityRole/accessibilityRole'
import { useHandleHover } from 'libs/hooks/useHandleHover'
import { getComputedAccessibilityLabel } from 'shared/accessibility/getComputedAccessibilityLabel'
import { ColorsType } from 'theme/types'
import { TouchableOpacity } from 'ui/components/TouchableOpacity'
import { ButtonLoadingIndicator } from 'ui/designSystem/ButtonDS/ButtonLoadingIndicator'
import { Typo } from 'ui/theme'

import { getButtonColors } from './Button.colors'
import {
  getBorderWidth,
  getIconElement,
  getInteractiveColors,
  getLabelStyle,
  getLabelText,
  getPrimaryDisabledOpacity,
  getSpacingGap,
  getTypographyForSize,
} from './Button.layout'
import { ButtonColorValue, ButtonNativeProps } from './types'

export const Button = ({
  variant = 'primary',
  size = 'default',
  hovered,
  color = 'brand',
  transparent = false,
  icon,
  disabled,
  iconPosition = 'left',
  iconButton = false,
  wording,
  accessibilityLabel,
  accessibilityHint,
  accessibilityRole,
  testID,
  fullWidth,
  onPress,
  onLongPress,
  isLoading,
}: ButtonNativeProps) => {
  const theme = useTheme()
  const hoverProps = useHandleHover()
  const isDisabled = disabled === true
  const isHover = hovered === undefined ? hoverProps.isHover : hovered
  const isHoverActive = isHover && !isDisabled

  const colors = getButtonColors({
    theme,
    variant,
    color,
    transparent,
    disabled: isDisabled,
  })

  const { backgroundColor, borderColor, textColor, iconColor } = getInteractiveColors(
    colors,
    isHoverActive
  )
  const borderWidth = getBorderWidth(borderColor)
  const opacity = getPrimaryDisabledOpacity(variant, isDisabled)

  const labelText = getLabelText(iconButton, wording)
  const computedA11yLabel = getComputedAccessibilityLabel(
    iconButton ? accessibilityLabel : (accessibilityLabel ?? wording ?? ''),
    accessibilityHint
  )
  const gap = getSpacingGap(!!labelText, theme.designSystem.size.spacing.s)
  const labelStyle = getLabelStyle(textColor, fullWidth)
  const typographyKey = getTypographyForSize(size)
  const LabelTypo = Typo[typographyKey]

  const iconSize = theme.icons.sizes.extraSmall
  const getPositionedIcon = (position: 'left' | 'right') =>
    iconPosition === position ? getIconElement({ icon, color: iconColor, size: iconSize }) : null

  const leftIcon = getPositionedIcon('left')
  const rightIcon = getPositionedIcon('right')

  const resolvedAccessibilityRole = accessibilityRole ?? AccessibilityRole.BUTTON

  return (
    <ButtonContainer
      accessibilityLabel={computedA11yLabel}
      accessibilityHint={accessibilityHint}
      accessibilityRole={resolvedAccessibilityRole}
      testID={testID}
      fullWidth={fullWidth}
      disabled={isDisabled}
      onPress={isDisabled || isLoading ? undefined : onPress}
      onLongPress={isDisabled || isLoading ? undefined : onLongPress}
      backgroundColor={backgroundColor}
      borderColor={borderColor}
      borderWidth={borderWidth}
      opacity={opacity}>
      <Content gap={gap}>
        {isLoading ? (
          <ButtonLoadingIndicator
            color={iconColor}
            size={theme.icons.sizes.extraSmall}
            testID="button-loading"
          />
        ) : (
          <React.Fragment>
            {leftIcon}
            {labelText ? <LabelTypo style={labelStyle}>{labelText}</LabelTypo> : null}
            {rightIcon}
          </React.Fragment>
        )}
      </Content>
    </ButtonContainer>
  )
}

type ContainerStyleProps = {
  backgroundColor?: ButtonColorValue
  borderColor?: ColorsType
  borderWidth?: number
  fullWidth?: boolean
  opacity?: number
}

const ButtonContainer = styled(TouchableOpacity)<ContainerStyleProps>(
  ({ theme, borderColor, borderWidth, backgroundColor, opacity, fullWidth }) => ({
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: theme.designSystem.size.borderRadius.m,
    paddingTop: theme.designSystem.size.spacing.s,
    paddingBottom: theme.designSystem.size.spacing.s,
    paddingLeft: theme.designSystem.size.spacing.m,
    paddingRight: theme.designSystem.size.spacing.m,
    width: fullWidth ? '100%' : 'auto',
    alignSelf: fullWidth ? 'center' : undefined,
    borderStyle: borderColor ? 'solid' : undefined,
    borderColor: borderColor,
    borderWidth: borderColor ? borderWidth : 0,
    backgroundColor: backgroundColor,
    opacity: opacity ?? 1,
  })
)

const Content = styled.View<{ gap: number }>(({ gap }) => ({
  flexDirection: 'row',
  alignItems: 'center',
  columnGap: gap,
}))
