/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React, { MouseEventHandler, useCallback } from 'react'
import styled, { CSSObject, DefaultTheme, useTheme } from 'styled-components'

import { accessibilityAndTestId } from 'libs/accessibilityAndTestId'
import { AccessibilityRole } from 'libs/accessibilityRole/accessibilityRole'
import { useHandleHover } from 'libs/hooks/useHandleHover'
import { getComputedAccessibilityLabel } from 'shared/accessibility/getComputedAccessibilityLabel'
import { ColorsType } from 'theme/types'
import { ButtonLoadingIndicator } from 'ui/designSystem/ButtonDS/ButtonLoadingIndicator'
import { Typo } from 'ui/theme'
import { customFocusOutline } from 'ui/theme/customFocusOutline/customFocusOutline'

import { getButtonColors } from './Button.colors'
import {
  getBorderWidth,
  getIconElement,
  getInteractiveColors,
  getLabelStyle,
  getLabelText,
  getPrimaryDisabledOpacity,
  getSpacingGap,
  getTypographyForSize,
} from './Button.layout'
import { ButtonColorValue, ButtonWebProps } from './types'

export const Button = ({
  variant = 'primary',
  size = 'default',
  hovered,
  color = 'brand',
  transparent = false,
  icon,
  disabled,
  iconPosition = 'left',
  iconButton = false,
  wording,
  accessibilityLabel,
  accessibilityHint,
  accessibilityRole,
  testID,
  fullWidth,
  onPress,
  onLongPress,
  isLoading,
  href,
  target,
  type = 'button',
}: ButtonWebProps) => {
  const theme = useTheme()
  const hoverProps = useHandleHover()
  const isDisabled = disabled === true
  const isHover = hovered === undefined ? hoverProps.isHover : hovered
  const isHoverActive = isHover && !isDisabled

  const colors = getButtonColors({
    theme,
    variant,
    color,
    transparent,
    disabled: isDisabled,
  })

  const { backgroundColor, borderColor, textColor, iconColor } = getInteractiveColors(
    colors,
    isHoverActive
  )
  const borderWidth = getBorderWidth(borderColor)
  const opacity = getPrimaryDisabledOpacity(variant, isDisabled)

  const labelText = getLabelText(iconButton, wording)
  const computedA11yLabel = getComputedAccessibilityLabel(
    iconButton ? accessibilityLabel : (accessibilityLabel ?? wording ?? ''),
    accessibilityHint
  )
  const gap = getSpacingGap(!!labelText, theme.designSystem.size.spacing.s)
  const labelStyle = getLabelStyle(textColor, fullWidth)
  const typographyKey = getTypographyForSize(size)
  const LabelTypo = Typo[typographyKey]

  const iconSize = theme.icons.sizes.extraSmall
  const getPositionedIcon = (position: 'left' | 'right') =>
    iconPosition === position ? getIconElement({ icon, color: iconColor, size: iconSize }) : null

  const leftIcon = getPositionedIcon('left')
  const rightIcon = getPositionedIcon('right')

  const pressHandler = disabled || isLoading ? undefined : onPress
  const longPressHandler = disabled || isLoading ? undefined : onLongPress

  const onClick: MouseEventHandler<HTMLButtonElement> = useCallback(
    (event) => {
      if (type === 'submit' && pressHandler) {
        event.preventDefault()
      }
      pressHandler?.(event)
    },
    [type, pressHandler]
  )

  const onDoubleClick: MouseEventHandler<HTMLButtonElement> = useCallback(
    (event) => {
      if (type === 'submit' && longPressHandler) {
        event.preventDefault()
      }
      longPressHandler?.(event)
    },
    [type, longPressHandler]
  )

  const ButtonComponent: React.ElementType = href ? Link : ButtonElement
  const resolvedAccessibilityRole =
    accessibilityRole ?? (href ? AccessibilityRole.LINK : AccessibilityRole.BUTTON)
  const buttonLinkProps = { href, target }

  return (
    <ButtonComponent
      {...accessibilityAndTestId(accessibilityLabel || wording, testID)}
      aria-label={computedA11yLabel}
      accessibilityRole={resolvedAccessibilityRole}
      accessibilityHint={accessibilityHint}
      fullWidth={fullWidth}
      disabled={isDisabled}
      onClick={onClick}
      onDoubleClick={onDoubleClick}
      onMouseEnter={hoverProps.onMouseEnter}
      onMouseLeave={hoverProps.onMouseLeave}
      backgroundColor={backgroundColor}
      borderColor={borderColor}
      borderWidth={borderWidth}
      opacity={opacity}
      type={href ? undefined : type}
      tabIndex={isDisabled || isLoading ? undefined : 0}
      {...buttonLinkProps}>
      <Content gap={gap}>
        {isLoading ? (
          <ButtonLoadingIndicator
            color={iconColor}
            size={theme.icons.sizes.extraSmall}
            testID="button-loading"
          />
        ) : (
          <React.Fragment>
            {leftIcon}
            {labelText ? <LabelTypo style={labelStyle}>{labelText}</LabelTypo> : null}
            {rightIcon}
          </React.Fragment>
        )}
      </Content>
    </ButtonComponent>
  )
}

type ContainerStyleProps = {
  backgroundColor?: ButtonColorValue
  borderColor?: ColorsType
  borderWidth?: number
  fullWidth?: boolean
  opacity?: number
}

const buttonContainerStyles = ({
  theme,
  borderColor,
  borderWidth,
  backgroundColor,
  opacity,
  fullWidth,
}: ContainerStyleProps & { theme: DefaultTheme }): CSSObject => ({
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'center',
  borderRadius: theme.designSystem.size.borderRadius.m,
  paddingTop: theme.designSystem.size.spacing.s,
  paddingBottom: theme.designSystem.size.spacing.s,
  paddingLeft: theme.designSystem.size.spacing.m,
  paddingRight: theme.designSystem.size.spacing.m,
  width: fullWidth ? '100%' : 'auto',
  alignSelf: fullWidth ? 'center' : undefined,
  borderStyle: borderColor ? 'solid' : undefined,
  borderColor: borderColor,
  borderWidth: borderColor ? borderWidth : 0,
  backgroundColor: backgroundColor,
  opacity: opacity ?? 1,
  cursor: 'pointer',
  outline: 'none',
  display: 'inline-flex',
  overflow: 'hidden',
  textDecoration: 'none',
  boxSizing: 'border-box',
  ['&:disabled']: {
    cursor: 'initial',
  },
  ...customFocusOutline({ theme }),
})

const ButtonElement = styled.button<ContainerStyleProps>(buttonContainerStyles)
const Link = styled.a<ContainerStyleProps>(buttonContainerStyles)

const Content = styled.div<{ gap: number }>(({ gap }) => ({
  display: 'flex',
  flexDirection: 'row',
  alignItems: 'center',
  columnGap: gap,
}))
