/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import { FunctionComponent } from 'react'
import { AccessibilityRole } from 'react-native'

import { BackgroundValue, ColorsType } from 'theme/types'
import { AppButtonEventNative, AppButtonEventWeb } from 'ui/components/buttons/AppButton/types'
import { AccessibleIcon } from 'ui/svg/icons/types'

export type ButtonVariant = 'primary' | 'secondary' | 'tertiary'
export type ButtonSize = 'default' | 'small'
export type ButtonColor = 'brand' | 'neutral'

export type ButtonColorValue = BackgroundValue | 'transparent'

export type ButtonColors = {
  backgroundColor?: ButtonColorValue
  borderColor?: ColorsType
  textColor: ColorsType
  iconColor: ColorsType
  hoverTextColor?: ColorsType
  hoverIconColor?: ColorsType
  hoverBackgroundColor?: ButtonColorValue
  hoverBorderColor?: ColorsType
}

type ButtonBaseProps = {
  disabled?: boolean
  isLoading?: boolean
  accessibilityLabel?: string
  accessibilityHint?: string
  accessibilityRole?: AccessibilityRole
  testID?: string
  fullWidth?: boolean
}

type ButtonVariantProps = {
  variant?: ButtonVariant
  size?: ButtonSize
  hovered?: boolean
  color?: ButtonColor
  transparent?: boolean
  iconPosition?: 'left' | 'right'
}

type IconButtonProps = ButtonBaseProps &
  ButtonVariantProps & {
    iconButton: true
    icon: FunctionComponent<AccessibleIcon>
    accessibilityLabel: string
    wording?: string
  }

type TextButtonProps = ButtonBaseProps &
  ButtonVariantProps & {
    iconButton?: false
    icon?: FunctionComponent<AccessibleIcon>
    wording?: string
  }

type ButtonNativeEvents = {
  onPress?: AppButtonEventNative
  onLongPress?: AppButtonEventNative
}

type ButtonWebEvents = {
  onPress?: AppButtonEventWeb
  onLongPress?: AppButtonEventWeb
  href?: string
  target?: string
  type?: 'button' | 'submit' | 'reset'
}

export type ButtonNativeProps = (IconButtonProps | TextButtonProps) & ButtonNativeEvents
export type ButtonWebProps = (IconButtonProps | TextButtonProps) & ButtonWebEvents
