/* eslint-disable no-console, @typescript-eslint/no-var-requires, import/no-extraneous-dependencies */
const fs = require('fs')
const path = require('path')

const { config } = require('dotenv')

const ENVIRONMENTS = ['testing', 'staging', 'production']

// Must stay in sync with the key lists in src/libs/environment/envOverride/types.ts
const SWITCHABLE_KEYS = [
  'API_BASE_URL',
  'ALGOLIA_APPLICATION_ID',
  'ALGOLIA_SEARCH_API_PUBLIC_KEY',
  'ALGOLIA_ARTISTS_INDEX_NAME',
  'ALGOLIA_CINE_CLUB_OFFERS_INDEX_NAME',
  'ALGOLIA_MOST_LIKED_OFFERS_INDEX_NAME',
  'ALGOLIA_OFFERS_INDEX_NAME',
  'ALGOLIA_OFFERS_INDEX_NAME_B',
  'ALGOLIA_SUGGESTIONS_INDEX_NAME',
  'ALGOLIA_TOP_OFFERS_INDEX_NAME',
  'ALGOLIA_VENUES_INDEX_EXPERIMENTAL',
  'ALGOLIA_VENUES_INDEX_NAME',
  'ALGOLIA_VENUES_INDEX_PLAYLIST_SEARCH',
  'ALGOLIA_VENUES_INDEX_PLAYLIST_SEARCH_NEWEST',
  'CONTENTFUL_SPACE_ID',
  'CONTENTFUL_ENVIRONMENT',
  'CONTENTFUL_PUBLIC_ACCESS_TOKEN',
  'GCP_IMAGE_COULD_STORAGE_NAME',
  'RESIZE_IMAGE_ON_DEMAND_URL',
]

const FIREBASE_FETCH_KEYS = ['FIREBASE_PROJECTID', 'FIREBASE_API_PUBLIC_KEY', 'FIREBASE_APPID']

const rootDir = path.join(__dirname, '..')
const outputPath = path.join(rootDir, 'src/libs/environment/envOverride/envOverrideConfig.ts')

function loadEnvFile(environment) {
  const filePath = path.join(rootDir, `.env.${environment}`)
  const { parsed, error } = config({ path: filePath, processEnv: {} })
  if (error) throw error
  if (!parsed) throw new Error(`No variables found in ${filePath}`)
  return parsed
}

function buildConfigEntry(environment, parsed, keys) {
  const lines = keys.map((key) => {
    const value = parsed[key]
    if (value === undefined) {
      throw new Error(`Missing variable ${key} in .env.${environment}`)
    }
    const escapedValue = value
      .replace(/\\/g, '\\\\')
      .replace(/'/g, "\\'")
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r')
    return `    ${key}: '${escapedValue}',`
  })
  return `  ${environment}: {\n${lines.join('\n')}\n  },`
}

const parsedByEnvironment = Object.fromEntries(
  ENVIRONMENTS.map((environment) => [environment, loadEnvFile(environment)])
)

function buildRecord(keys) {
  return ENVIRONMENTS.map((environment) =>
    buildConfigEntry(environment, parsedByEnvironment[environment], keys)
  ).join('\n')
}

const fileContent = `// This file is generated by scripts/generate_env_override_config.js — do not edit manually.
// Regenerate with: yarn generate:envOverrideConfig
import {
  EnvOverrideFirebaseConfig,
  EnvSwitchableConfig,
  SwitchableEnvironment,
} from 'libs/environment/envOverride/types'

export const ENV_OVERRIDE_CONFIG: Record<SwitchableEnvironment, EnvSwitchableConfig> = {
${buildRecord(SWITCHABLE_KEYS)}
}

export const ENV_OVERRIDE_FIREBASE_CONFIG: Record<
  SwitchableEnvironment,
  EnvOverrideFirebaseConfig
> = {
${buildRecord(FIREBASE_FETCH_KEYS)}
}
`

fs.writeFileSync(outputPath, fileContent)
console.log(`Generated ${path.relative(rootDir, outputPath)}`)
