import {
  CategoryIdEnum,
  SearchGroupNameEnumv2,
  HomepageLabelNameEnumv2,
  OnlineOfflinePlatformChoicesEnumv2,
  SubcategoriesResponseModelv2,
  SubcategoryIdEnumv2,
} from 'api/gen'

export const placeholderData: SubcategoriesResponseModelv2 = {
  subcategories: [
    {
      id: SubcategoryIdEnumv2.ABO_BIBLIOTHEQUE,
      categoryId: CategoryIdEnum.LIVRE,
      appLabel: 'Abonnement (bibliothèques, médiathèques...)',
      searchGroupName: SearchGroupNameEnumv2.BIBLIOTHEQUES_MEDIATHEQUE,
      homepageLabelName: HomepageLabelNameEnumv2.LIVRES,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.ABO_CONCERT,
      categoryId: CategoryIdEnum.MUSIQUE_LIVE,
      appLabel: 'Abonnement concert',
      searchGroupName: SearchGroupNameEnumv2.CONCERTS_FESTIVALS,
      homepageLabelName: HomepageLabelNameEnumv2.CONCERT,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.ABO_JEU_VIDEO,
      categoryId: CategoryIdEnum.JEU,
      appLabel: 'Abonnement jeux vidéos',
      searchGroupName: SearchGroupNameEnumv2.JEUX_JEUX_VIDEOS,
      homepageLabelName: HomepageLabelNameEnumv2.JEUX,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE,
    },
    {
      id: SubcategoryIdEnumv2.ABO_LIVRE_NUMERIQUE,
      categoryId: CategoryIdEnum.LIVRE,
      appLabel: 'Abonnement livres numériques',
      searchGroupName: SearchGroupNameEnumv2.LIVRES,
      homepageLabelName: HomepageLabelNameEnumv2.LIVRES,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE,
    },
    {
      id: SubcategoryIdEnumv2.ABO_LUDOTHEQUE,
      categoryId: CategoryIdEnum.JEU,
      appLabel: 'Abonnement ludothèque',
      searchGroupName: SearchGroupNameEnumv2.JEUX_JEUX_VIDEOS,
      homepageLabelName: HomepageLabelNameEnumv2.JEUX,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.ABO_MEDIATHEQUE,
      categoryId: CategoryIdEnum.FILM,
      appLabel: 'Abonnement médiathèque',
      searchGroupName: SearchGroupNameEnumv2.BIBLIOTHEQUES_MEDIATHEQUE,
      homepageLabelName: HomepageLabelNameEnumv2.FILMS,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.ABO_MUSEE,
      categoryId: CategoryIdEnum.MUSEE,
      appLabel: 'Entrée libre ou abonnement musée',
      searchGroupName: SearchGroupNameEnumv2.MUSEES_VISITES_CULTURELLES,
      homepageLabelName: HomepageLabelNameEnumv2.MUSEE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.ABO_PLATEFORME_MUSIQUE,
      categoryId: CategoryIdEnum.MUSIQUE_ENREGISTREE,
      appLabel: 'Abonnement plateforme musicale',
      searchGroupName: SearchGroupNameEnumv2.CD_VINYLE_MUSIQUE_EN_LIGNE,
      homepageLabelName: HomepageLabelNameEnumv2.MUSIQUE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE,
    },
    {
      id: SubcategoryIdEnumv2.ABO_PLATEFORME_VIDEO,
      categoryId: CategoryIdEnum.FILM,
      appLabel: 'Abonnement plateforme streaming',
      searchGroupName: SearchGroupNameEnumv2.FILMS_SERIES_CINEMA,
      homepageLabelName: HomepageLabelNameEnumv2.FILMS,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE,
    },
    {
      id: SubcategoryIdEnumv2.ABO_PRATIQUE_ART,
      categoryId: CategoryIdEnum.PRATIQUE_ART,
      appLabel: 'Abonnement pratique artistique',
      searchGroupName: SearchGroupNameEnumv2.ARTS_LOISIRS_CREATIFS,
      homepageLabelName: HomepageLabelNameEnumv2.BEAUX_ARTS,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.ABO_PRESSE_EN_LIGNE,
      categoryId: CategoryIdEnum.MEDIA,
      appLabel: 'Abonnement presse en ligne',
      searchGroupName: SearchGroupNameEnumv2.MEDIA_PRESSE,
      homepageLabelName: HomepageLabelNameEnumv2.MEDIAS,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE,
    },
    {
      id: SubcategoryIdEnumv2.ABO_SPECTACLE,
      categoryId: CategoryIdEnum.SPECTACLE,
      appLabel: 'Abonnement spectacle',
      searchGroupName: SearchGroupNameEnumv2.SPECTACLES,
      homepageLabelName: HomepageLabelNameEnumv2.SPECTACLES,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.ACHAT_INSTRUMENT,
      categoryId: CategoryIdEnum.INSTRUMENT,
      appLabel: 'Achat instrument',
      searchGroupName: SearchGroupNameEnumv2.INSTRUMENTS,
      homepageLabelName: HomepageLabelNameEnumv2.INSTRUMENT,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.ACTIVATION_EVENT,
      categoryId: CategoryIdEnum.TECHNIQUE,
      appLabel: "Catégorie technique d'évènement d'activation ",
      searchGroupName: SearchGroupNameEnumv2.NONE,
      homepageLabelName: HomepageLabelNameEnumv2.NONE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE_OR_OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.ACTIVATION_THING,
      categoryId: CategoryIdEnum.TECHNIQUE,
      appLabel: "Catégorie technique de thing d'activation",
      searchGroupName: SearchGroupNameEnumv2.NONE,
      homepageLabelName: HomepageLabelNameEnumv2.NONE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE_OR_OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.APP_CULTURELLE,
      categoryId: CategoryIdEnum.MEDIA,
      appLabel: 'Application culturelle',
      searchGroupName: SearchGroupNameEnumv2.MEDIA_PRESSE,
      homepageLabelName: HomepageLabelNameEnumv2.MEDIAS,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE,
    },
    {
      id: SubcategoryIdEnumv2.ATELIER_PRATIQUE_ART,
      categoryId: CategoryIdEnum.PRATIQUE_ART,
      appLabel: 'Atelier, stage de pratique artistique',
      searchGroupName: SearchGroupNameEnumv2.ARTS_LOISIRS_CREATIFS,
      homepageLabelName: HomepageLabelNameEnumv2.BEAUX_ARTS,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.AUTRE_SUPPORT_NUMERIQUE,
      categoryId: CategoryIdEnum.FILM,
      appLabel: 'Autre support numérique',
      searchGroupName: SearchGroupNameEnumv2.FILMS_SERIES_CINEMA,
      homepageLabelName: HomepageLabelNameEnumv2.FILMS,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE,
    },
    {
      id: SubcategoryIdEnumv2.BON_ACHAT_INSTRUMENT,
      categoryId: CategoryIdEnum.INSTRUMENT,
      appLabel: "Bon d'achat instrument",
      searchGroupName: SearchGroupNameEnumv2.INSTRUMENTS,
      homepageLabelName: HomepageLabelNameEnumv2.INSTRUMENT,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.CAPTATION_MUSIQUE,
      categoryId: CategoryIdEnum.MUSIQUE_ENREGISTREE,
      appLabel: 'Captation musicale',
      searchGroupName: SearchGroupNameEnumv2.CD_VINYLE_MUSIQUE_EN_LIGNE,
      homepageLabelName: HomepageLabelNameEnumv2.MUSIQUE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.CARTE_CINE_ILLIMITE,
      categoryId: CategoryIdEnum.CINEMA,
      appLabel: 'Carte cinéma illimité',
      searchGroupName: SearchGroupNameEnumv2.FILMS_SERIES_CINEMA,
      homepageLabelName: HomepageLabelNameEnumv2.CINEMA,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.CARTE_CINE_MULTISEANCES,
      categoryId: CategoryIdEnum.CINEMA,
      appLabel: 'Carte cinéma multi-séances',
      searchGroupName: SearchGroupNameEnumv2.FILMS_SERIES_CINEMA,
      homepageLabelName: HomepageLabelNameEnumv2.CINEMA,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.CARTE_JEUNES,
      categoryId: CategoryIdEnum.CARTE_JEUNES,
      appLabel: 'Carte jeunes',
      searchGroupName: SearchGroupNameEnumv2.CARTES_JEUNES,
      homepageLabelName: HomepageLabelNameEnumv2.CARTE_JEUNES,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.CARTE_MUSEE,
      categoryId: CategoryIdEnum.MUSEE,
      appLabel: 'Cartes musées, patrimoine...',
      searchGroupName: SearchGroupNameEnumv2.MUSEES_VISITES_CULTURELLES,
      homepageLabelName: HomepageLabelNameEnumv2.MUSEE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.CINE_PLEIN_AIR,
      categoryId: CategoryIdEnum.CINEMA,
      appLabel: 'Cinéma plein air',
      searchGroupName: SearchGroupNameEnumv2.FILMS_SERIES_CINEMA,
      homepageLabelName: HomepageLabelNameEnumv2.CINEMA,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.CINE_VENTE_DISTANCE,
      categoryId: CategoryIdEnum.CINEMA,
      appLabel: 'Cinéma',
      searchGroupName: SearchGroupNameEnumv2.FILMS_SERIES_CINEMA,
      homepageLabelName: HomepageLabelNameEnumv2.CINEMA,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE,
    },
    {
      id: SubcategoryIdEnumv2.CONCERT,
      categoryId: CategoryIdEnum.MUSIQUE_LIVE,
      appLabel: 'Concert',
      searchGroupName: SearchGroupNameEnumv2.CONCERTS_FESTIVALS,
      homepageLabelName: HomepageLabelNameEnumv2.CONCERT,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.CONCOURS,
      categoryId: CategoryIdEnum.JEU,
      appLabel: 'Concours - jeux',
      searchGroupName: SearchGroupNameEnumv2.JEUX_JEUX_VIDEOS,
      homepageLabelName: HomepageLabelNameEnumv2.JEUX,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.CONFERENCE,
      categoryId: CategoryIdEnum.CONFERENCE,
      appLabel: 'Conférence',
      searchGroupName: SearchGroupNameEnumv2.RENCONTRES_CONFERENCES,
      homepageLabelName: HomepageLabelNameEnumv2.RENCONTRES,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.DECOUVERTE_METIERS,
      categoryId: CategoryIdEnum.CONFERENCE,
      appLabel: 'Découverte des métiers',
      searchGroupName: SearchGroupNameEnumv2.RENCONTRES_CONFERENCES,
      homepageLabelName: HomepageLabelNameEnumv2.RENCONTRES,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.ESCAPE_GAME,
      categoryId: CategoryIdEnum.JEU,
      appLabel: 'Escape game',
      searchGroupName: SearchGroupNameEnumv2.JEUX_JEUX_VIDEOS,
      homepageLabelName: HomepageLabelNameEnumv2.JEUX,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.EVENEMENT_CINE,
      categoryId: CategoryIdEnum.CINEMA,
      appLabel: 'Évènement cinéma',
      searchGroupName: SearchGroupNameEnumv2.FILMS_SERIES_CINEMA,
      homepageLabelName: HomepageLabelNameEnumv2.CINEMA,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.EVENEMENT_JEU,
      categoryId: CategoryIdEnum.JEU,
      appLabel: 'Évènements - jeux',
      searchGroupName: SearchGroupNameEnumv2.JEUX_JEUX_VIDEOS,
      homepageLabelName: HomepageLabelNameEnumv2.JEUX,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.EVENEMENT_MUSIQUE,
      categoryId: CategoryIdEnum.MUSIQUE_LIVE,
      appLabel: "Autre type d'évènement musical",
      searchGroupName: SearchGroupNameEnumv2.CONCERTS_FESTIVALS,
      homepageLabelName: HomepageLabelNameEnumv2.CONCERT,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.EVENEMENT_PATRIMOINE,
      categoryId: CategoryIdEnum.MUSEE,
      appLabel: 'Évènement et atelier patrimoine',
      searchGroupName: SearchGroupNameEnumv2.MUSEES_VISITES_CULTURELLES,
      homepageLabelName: HomepageLabelNameEnumv2.VISITES,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.FESTIVAL_CINE,
      categoryId: CategoryIdEnum.CINEMA,
      appLabel: 'Festival de cinéma',
      searchGroupName: SearchGroupNameEnumv2.FILMS_SERIES_CINEMA,
      homepageLabelName: HomepageLabelNameEnumv2.CINEMA,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.FESTIVAL_LIVRE,
      categoryId: CategoryIdEnum.LIVRE,
      appLabel: 'Festival et salon du livre',
      searchGroupName: SearchGroupNameEnumv2.LIVRES,
      homepageLabelName: HomepageLabelNameEnumv2.LIVRES,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.FESTIVAL_MUSIQUE,
      categoryId: CategoryIdEnum.MUSIQUE_LIVE,
      appLabel: 'Festival de musique',
      searchGroupName: SearchGroupNameEnumv2.CONCERTS_FESTIVALS,
      homepageLabelName: HomepageLabelNameEnumv2.FESTIVAL,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.FESTIVAL_SPECTACLE,
      categoryId: CategoryIdEnum.SPECTACLE,
      appLabel: 'Festival',
      searchGroupName: SearchGroupNameEnumv2.SPECTACLES,
      homepageLabelName: HomepageLabelNameEnumv2.SPECTACLES,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.JEU_EN_LIGNE,
      categoryId: CategoryIdEnum.JEU,
      appLabel: 'Jeux en ligne',
      searchGroupName: SearchGroupNameEnumv2.JEUX_JEUX_VIDEOS,
      homepageLabelName: HomepageLabelNameEnumv2.JEUX,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE,
    },
    {
      id: SubcategoryIdEnumv2.JEU_SUPPORT_PHYSIQUE,
      categoryId: CategoryIdEnum.TECHNIQUE,
      appLabel: 'Catégorie technique Jeu support physique',
      searchGroupName: SearchGroupNameEnumv2.NONE,
      homepageLabelName: HomepageLabelNameEnumv2.NONE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE_OR_OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.LIVESTREAM_EVENEMENT,
      categoryId: CategoryIdEnum.SPECTACLE,
      appLabel: "Live stream d'évènement",
      searchGroupName: SearchGroupNameEnumv2.EVENEMENTS_EN_LIGNE,
      homepageLabelName: HomepageLabelNameEnumv2.SPECTACLES,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE,
    },
    {
      id: SubcategoryIdEnumv2.LIVESTREAM_MUSIQUE,
      categoryId: CategoryIdEnum.MUSIQUE_LIVE,
      appLabel: 'Livestream musical',
      searchGroupName: SearchGroupNameEnumv2.EVENEMENTS_EN_LIGNE,
      homepageLabelName: HomepageLabelNameEnumv2.MUSIQUE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE,
    },
    {
      id: SubcategoryIdEnumv2.LIVESTREAM_PRATIQUE_ARTISTIQUE,
      categoryId: CategoryIdEnum.PRATIQUE_ART,
      appLabel: 'Pratique artistique - livestream',
      searchGroupName: SearchGroupNameEnumv2.EVENEMENTS_EN_LIGNE,
      homepageLabelName: HomepageLabelNameEnumv2.COURS,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE,
    },
    {
      id: SubcategoryIdEnumv2.LIVRE_AUDIO_PHYSIQUE,
      categoryId: CategoryIdEnum.LIVRE,
      appLabel: 'Livre audio sur support physique',
      searchGroupName: SearchGroupNameEnumv2.LIVRES,
      homepageLabelName: HomepageLabelNameEnumv2.LIVRES,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.LIVRE_NUMERIQUE,
      categoryId: CategoryIdEnum.LIVRE,
      appLabel: 'Livre numérique, e-book',
      searchGroupName: SearchGroupNameEnumv2.LIVRES,
      homepageLabelName: HomepageLabelNameEnumv2.LIVRES,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE,
    },
    {
      id: SubcategoryIdEnumv2.LIVRE_PAPIER,
      categoryId: CategoryIdEnum.LIVRE,
      appLabel: 'Livre',
      searchGroupName: SearchGroupNameEnumv2.LIVRES,
      homepageLabelName: HomepageLabelNameEnumv2.LIVRES,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.LOCATION_INSTRUMENT,
      categoryId: CategoryIdEnum.INSTRUMENT,
      appLabel: 'Location instrument',
      searchGroupName: SearchGroupNameEnumv2.INSTRUMENTS,
      homepageLabelName: HomepageLabelNameEnumv2.INSTRUMENT,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.MATERIEL_ART_CREATIF,
      categoryId: CategoryIdEnum.BEAUX_ARTS,
      appLabel: 'Matériel arts créatifs',
      searchGroupName: SearchGroupNameEnumv2.ARTS_LOISIRS_CREATIFS,
      homepageLabelName: HomepageLabelNameEnumv2.BEAUX_ARTS,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.MUSEE_VENTE_DISTANCE,
      categoryId: CategoryIdEnum.MUSEE,
      appLabel: 'Musée vente à distance',
      searchGroupName: SearchGroupNameEnumv2.MUSEES_VISITES_CULTURELLES,
      homepageLabelName: HomepageLabelNameEnumv2.MUSEE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE,
    },
    {
      id: SubcategoryIdEnumv2.OEUVRE_ART,
      categoryId: CategoryIdEnum.TECHNIQUE,
      appLabel: "Catégorie technique d'oeuvre d'art",
      searchGroupName: SearchGroupNameEnumv2.ARTS_LOISIRS_CREATIFS,
      homepageLabelName: HomepageLabelNameEnumv2.NONE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE_OR_OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.PARTITION,
      categoryId: CategoryIdEnum.INSTRUMENT,
      appLabel: 'Partition',
      searchGroupName: SearchGroupNameEnumv2.INSTRUMENTS,
      homepageLabelName: HomepageLabelNameEnumv2.INSTRUMENT,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.PLATEFORME_PRATIQUE_ARTISTIQUE,
      categoryId: CategoryIdEnum.PRATIQUE_ART,
      appLabel: 'Plateforme de pratique artistique',
      searchGroupName: SearchGroupNameEnumv2.ARTS_LOISIRS_CREATIFS,
      homepageLabelName: HomepageLabelNameEnumv2.PLATEFORME,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE,
    },
    {
      id: SubcategoryIdEnumv2.PRATIQUE_ART_VENTE_DISTANCE,
      categoryId: CategoryIdEnum.PRATIQUE_ART,
      appLabel: 'Pratique artistique - vente à distance',
      searchGroupName: SearchGroupNameEnumv2.ARTS_LOISIRS_CREATIFS,
      homepageLabelName: HomepageLabelNameEnumv2.BEAUX_ARTS,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE,
    },
    {
      id: SubcategoryIdEnumv2.PODCAST,
      categoryId: CategoryIdEnum.MEDIA,
      appLabel: 'Podcast',
      searchGroupName: SearchGroupNameEnumv2.MEDIA_PRESSE,
      homepageLabelName: HomepageLabelNameEnumv2.MEDIAS,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE,
    },
    {
      id: SubcategoryIdEnumv2.RENCONTRE_EN_LIGNE,
      categoryId: CategoryIdEnum.CONFERENCE,
      appLabel: 'Rencontre en ligne',
      searchGroupName: SearchGroupNameEnumv2.RENCONTRES_CONFERENCES,
      homepageLabelName: HomepageLabelNameEnumv2.RENCONTRES,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE,
    },
    {
      id: SubcategoryIdEnumv2.RENCONTRE_JEU,
      categoryId: CategoryIdEnum.JEU,
      appLabel: 'Rencontres - jeux',
      searchGroupName: SearchGroupNameEnumv2.JEUX_JEUX_VIDEOS,
      homepageLabelName: HomepageLabelNameEnumv2.JEUX,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.RENCONTRE,
      categoryId: CategoryIdEnum.CONFERENCE,
      appLabel: 'Rencontre',
      searchGroupName: SearchGroupNameEnumv2.RENCONTRES_CONFERENCES,
      homepageLabelName: HomepageLabelNameEnumv2.RENCONTRES,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.SALON,
      categoryId: CategoryIdEnum.CONFERENCE,
      appLabel: 'Salon, Convention',
      searchGroupName: SearchGroupNameEnumv2.RENCONTRES_CONFERENCES,
      homepageLabelName: HomepageLabelNameEnumv2.RENCONTRES,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.SEANCE_CINE,
      categoryId: CategoryIdEnum.CINEMA,
      appLabel: 'Séance de cinéma',
      searchGroupName: SearchGroupNameEnumv2.FILMS_SERIES_CINEMA,
      homepageLabelName: HomepageLabelNameEnumv2.CINEMA,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.SEANCE_ESSAI_PRATIQUE_ART,
      categoryId: CategoryIdEnum.PRATIQUE_ART,
      appLabel: "Séance d'essai",
      searchGroupName: SearchGroupNameEnumv2.ARTS_LOISIRS_CREATIFS,
      homepageLabelName: HomepageLabelNameEnumv2.BEAUX_ARTS,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.SPECTACLE_ENREGISTRE,
      categoryId: CategoryIdEnum.SPECTACLE,
      appLabel: 'Spectacle enregistré',
      searchGroupName: SearchGroupNameEnumv2.SPECTACLES,
      homepageLabelName: HomepageLabelNameEnumv2.SPECTACLES,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE,
    },
    {
      id: SubcategoryIdEnumv2.SPECTACLE_REPRESENTATION,
      categoryId: CategoryIdEnum.SPECTACLE,
      appLabel: 'Spectacle, représentation',
      searchGroupName: SearchGroupNameEnumv2.SPECTACLES,
      homepageLabelName: HomepageLabelNameEnumv2.SPECTACLES,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.SPECTACLE_VENTE_DISTANCE,
      categoryId: CategoryIdEnum.SPECTACLE,
      appLabel: 'Spectacle vivant - vente à distance',
      searchGroupName: SearchGroupNameEnumv2.SPECTACLES,
      homepageLabelName: HomepageLabelNameEnumv2.SPECTACLES,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE,
    },
    {
      id: SubcategoryIdEnumv2.SUPPORT_PHYSIQUE_FILM,
      categoryId: CategoryIdEnum.FILM,
      appLabel: 'Support physique (DVD, Blu-ray...)',
      searchGroupName: SearchGroupNameEnumv2.FILMS_SERIES_CINEMA,
      homepageLabelName: HomepageLabelNameEnumv2.FILMS,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.SUPPORT_PHYSIQUE_MUSIQUE,
      categoryId: CategoryIdEnum.MUSIQUE_ENREGISTREE,
      appLabel: 'Support physique (CD, vinyle...)',
      searchGroupName: SearchGroupNameEnumv2.CD_VINYLE_MUSIQUE_EN_LIGNE,
      homepageLabelName: HomepageLabelNameEnumv2.MUSIQUE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.TELECHARGEMENT_LIVRE_AUDIO,
      categoryId: CategoryIdEnum.LIVRE,
      appLabel: 'Livre audio à télécharger',
      searchGroupName: SearchGroupNameEnumv2.PLATEFORMES_EN_LIGNE,
      homepageLabelName: HomepageLabelNameEnumv2.PLATEFORME,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE,
    },
    {
      id: SubcategoryIdEnumv2.TELECHARGEMENT_MUSIQUE,
      categoryId: CategoryIdEnum.MUSIQUE_ENREGISTREE,
      appLabel: 'Téléchargement de musique',
      searchGroupName: SearchGroupNameEnumv2.CD_VINYLE_MUSIQUE_EN_LIGNE,
      homepageLabelName: HomepageLabelNameEnumv2.MUSIQUE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE,
    },
    {
      id: SubcategoryIdEnumv2.VISITE_GUIDEE,
      categoryId: CategoryIdEnum.MUSEE,
      appLabel: 'Visite guidée',
      searchGroupName: SearchGroupNameEnumv2.MUSEES_VISITES_CULTURELLES,
      homepageLabelName: HomepageLabelNameEnumv2.VISITES,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.VISITE_VIRTUELLE,
      categoryId: CategoryIdEnum.MUSEE,
      appLabel: 'Visite virtuelle',
      searchGroupName: SearchGroupNameEnumv2.MUSEES_VISITES_CULTURELLES,
      homepageLabelName: HomepageLabelNameEnumv2.VISITES,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE,
    },
    {
      id: SubcategoryIdEnumv2.VISITE,
      categoryId: CategoryIdEnum.MUSEE,
      appLabel: 'Visite',
      searchGroupName: SearchGroupNameEnumv2.MUSEES_VISITES_CULTURELLES,
      homepageLabelName: HomepageLabelNameEnumv2.VISITES,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.OFFLINE,
    },
    {
      id: SubcategoryIdEnumv2.VOD,
      categoryId: CategoryIdEnum.FILM,
      appLabel: 'Vidéo à la demande',
      searchGroupName: SearchGroupNameEnumv2.FILMS_SERIES_CINEMA,
      homepageLabelName: HomepageLabelNameEnumv2.FILMS,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnumv2.ONLINE,
    },
  ],
  searchGroups: [
    { name: SearchGroupNameEnumv2.ARTS_LOISIRS_CREATIFS, value: 'Arts & loisirs créatifs' },
    { name: SearchGroupNameEnumv2.BIBLIOTHEQUES_MEDIATHEQUE, value: 'Bibliothèques, Médiathèques' },
    { name: SearchGroupNameEnumv2.CARTES_JEUNES, value: 'Cartes jeunes' },
    {
      name: SearchGroupNameEnumv2.CD_VINYLE_MUSIQUE_EN_LIGNE,
      value: 'CD, vinyles, musique en ligne',
    },
    { name: SearchGroupNameEnumv2.CONCERTS_FESTIVALS, value: 'Concerts & festivals' },
    { name: SearchGroupNameEnumv2.RENCONTRES_CONFERENCES, value: 'Conférences & rencontres' },
    { name: SearchGroupNameEnumv2.EVENEMENTS_EN_LIGNE, value: 'Évènements en ligne' },
    { name: SearchGroupNameEnumv2.FILMS_SERIES_CINEMA, value: 'Films, séries, cinéma' },
    { name: SearchGroupNameEnumv2.INSTRUMENTS, value: 'Instruments de musique' },
    { name: SearchGroupNameEnumv2.JEUX_JEUX_VIDEOS, value: 'Jeux & jeux vidéos' },
    { name: SearchGroupNameEnumv2.LIVRES, value: 'Livres' },
    { name: SearchGroupNameEnumv2.MEDIA_PRESSE, value: 'Médias & presse' },
    {
      name: SearchGroupNameEnumv2.MUSEES_VISITES_CULTURELLES,
      value: 'Musées & visites culturelles',
    },
    { name: SearchGroupNameEnumv2.PLATEFORMES_EN_LIGNE, value: 'Plateformes en ligne' },
    { name: SearchGroupNameEnumv2.SPECTACLES, value: 'Spectacles' },
    { name: SearchGroupNameEnumv2.NONE, value: null },
  ],
  homepageLabels: [
    { name: HomepageLabelNameEnumv2.BEAUX_ARTS, value: 'Beaux-Arts' },
    { name: HomepageLabelNameEnumv2.CARTE_JEUNES, value: 'Carte jeunes' },
    { name: HomepageLabelNameEnumv2.CINEMA, value: 'Cinéma' },
    { name: HomepageLabelNameEnumv2.CONCERT, value: 'Concert' },
    { name: HomepageLabelNameEnumv2.COURS, value: 'Cours' },
    { name: HomepageLabelNameEnumv2.FESTIVAL, value: 'Festival' },
    { name: HomepageLabelNameEnumv2.FILMS, value: 'Films' },
    { name: HomepageLabelNameEnumv2.INSTRUMENT, value: 'Instrument' },
    { name: HomepageLabelNameEnumv2.JEUX, value: 'Jeux' },
    { name: HomepageLabelNameEnumv2.LIVRES, value: 'Livre' },
    { name: HomepageLabelNameEnumv2.MEDIAS, value: 'Médias' },
    { name: HomepageLabelNameEnumv2.MUSEE, value: 'Musée' },
    { name: HomepageLabelNameEnumv2.MUSIQUE, value: 'Musique' },
    { name: HomepageLabelNameEnumv2.NONE, value: null },
    { name: HomepageLabelNameEnumv2.PLATEFORME, value: 'Plateforme' },
    { name: HomepageLabelNameEnumv2.RENCONTRES, value: 'Rencontres' },
    { name: HomepageLabelNameEnumv2.SPECTACLES, value: 'Spectacle' },
    { name: HomepageLabelNameEnumv2.VISITES, value: 'Visites' },
  ],
}
