import {
  CategoryIdEnum,
  HomepageLabelNameEnum,
  OnlineOfflinePlatformChoicesEnum,
  SearchGroupNameEnum,
  SubcategoryIdEnum,
  SubcategoriesResponseModel,
} from 'api/gen'

export const placeholderData: SubcategoriesResponseModel = {
  subcategories: [
    {
      id: SubcategoryIdEnum.ABO_BIBLIOTHEQUE,
      categoryId: CategoryIdEnum.LIVRE,
      appLabel: 'Abonnement (bibliothèques, médiathèques...)',
      searchGroupName: SearchGroupNameEnum.LIVRES,
      homepageLabelName: HomepageLabelNameEnum.LIVRES,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.ABO_CONCERT,
      categoryId: CategoryIdEnum.MUSIQUE_LIVE,
      appLabel: 'Abonnement concert',
      searchGroupName: SearchGroupNameEnum.CD_VINYLE_MUSIQUE_EN_LIGNE,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.ABO_JEU_VIDEO,
      categoryId: CategoryIdEnum.JEU,
      appLabel: 'Abonnement jeux vidéos',
      searchGroupName: SearchGroupNameEnum.JEUX_JEUX_VIDEOS,
      homepageLabelName: HomepageLabelNameEnum.JEUX,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.ABO_LIVRE_NUMERIQUE,
      categoryId: CategoryIdEnum.LIVRE,
      appLabel: 'Abonnement livres numériques',
      searchGroupName: SearchGroupNameEnum.LIVRES,
      homepageLabelName: HomepageLabelNameEnum.LIVRES,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.ABO_LUDOTHEQUE,
      categoryId: CategoryIdEnum.JEU,
      appLabel: 'Abonnement ludothèque',
      searchGroupName: SearchGroupNameEnum.JEUX_JEUX_VIDEOS,
      homepageLabelName: HomepageLabelNameEnum.JEUX,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.ABO_MEDIATHEQUE,
      categoryId: CategoryIdEnum.FILM,
      appLabel: 'Abonnement médiathèque',
      searchGroupName: SearchGroupNameEnum.FILMS_SERIES_CINEMA,
      homepageLabelName: HomepageLabelNameEnum.FILMS,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.ABO_MUSEE,
      categoryId: CategoryIdEnum.MUSEE,
      appLabel: 'Entrée libre ou abonnement musée',
      searchGroupName: SearchGroupNameEnum.MUSEES_VISITES_CULTURELLES,
      homepageLabelName: HomepageLabelNameEnum.VISITE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.ABO_PLATEFORME_MUSIQUE,
      categoryId: CategoryIdEnum.MUSIQUE_ENREGISTREE,
      appLabel: 'Abonnement plateforme musicale',
      searchGroupName: SearchGroupNameEnum.CD_VINYLE_MUSIQUE_EN_LIGNE,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.ABO_PLATEFORME_VIDEO,
      categoryId: CategoryIdEnum.FILM,
      appLabel: 'Abonnement plateforme streaming',
      searchGroupName: SearchGroupNameEnum.FILMS_SERIES_CINEMA,
      homepageLabelName: HomepageLabelNameEnum.FILMS,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.ABO_PRATIQUE_ART,
      categoryId: CategoryIdEnum.PRATIQUE_ART,
      appLabel: 'Abonnement pratique artistique',
      searchGroupName: SearchGroupNameEnum.ARTS_LOISIRS_CREATIFS,
      homepageLabelName: HomepageLabelNameEnum.COURS,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.ABO_PRESSE_EN_LIGNE,
      categoryId: CategoryIdEnum.MEDIA,
      appLabel: 'Abonnement presse en ligne',
      searchGroupName: SearchGroupNameEnum.MEDIA_PRESSE,
      homepageLabelName: HomepageLabelNameEnum.PRESSE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.ABO_SPECTACLE,
      categoryId: CategoryIdEnum.SPECTACLE,
      appLabel: 'Abonnement spectacle',
      searchGroupName: SearchGroupNameEnum.CONCERTS_FESTIVALS,
      homepageLabelName: HomepageLabelNameEnum.SPECTACLE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.ACHAT_INSTRUMENT,
      categoryId: CategoryIdEnum.INSTRUMENT,
      appLabel: 'Achat instrument',
      searchGroupName: SearchGroupNameEnum.INSTRUMENT,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.ACTIVATION_EVENT,
      categoryId: CategoryIdEnum.TECHNIQUE,
      appLabel: "Catégorie technique d'événement d'activation ",
      searchGroupName: SearchGroupNameEnum.NONE,
      homepageLabelName: HomepageLabelNameEnum.NONE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE_OR_OFFLINE,
    },
    {
      id: SubcategoryIdEnum.ACTIVATION_THING,
      categoryId: CategoryIdEnum.TECHNIQUE,
      appLabel: "Catégorie technique de thing d'activation",
      searchGroupName: SearchGroupNameEnum.NONE,
      homepageLabelName: HomepageLabelNameEnum.NONE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE_OR_OFFLINE,
    },
    {
      id: SubcategoryIdEnum.APP_CULTURELLE,
      categoryId: CategoryIdEnum.MEDIA,
      appLabel: 'Application culturelle',
      searchGroupName: SearchGroupNameEnum.MEDIA_PRESSE,
      homepageLabelName: HomepageLabelNameEnum.PRESSE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.ATELIER_PRATIQUE_ART,
      categoryId: CategoryIdEnum.PRATIQUE_ART,
      appLabel: 'Atelier, stage de pratique artistique',
      searchGroupName: SearchGroupNameEnum.ARTS_LOISIRS_CREATIFS,
      homepageLabelName: HomepageLabelNameEnum.COURS,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.AUTRE_SUPPORT_NUMERIQUE,
      categoryId: CategoryIdEnum.FILM,
      appLabel: 'Autre support numérique',
      searchGroupName: SearchGroupNameEnum.FILMS_SERIES_CINEMA,
      homepageLabelName: HomepageLabelNameEnum.FILMS,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.BON_ACHAT_INSTRUMENT,
      categoryId: CategoryIdEnum.INSTRUMENT,
      appLabel: "Bon d'achat instrument",
      searchGroupName: SearchGroupNameEnum.INSTRUMENT,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.CAPTATION_MUSIQUE,
      categoryId: CategoryIdEnum.MUSIQUE_ENREGISTREE,
      appLabel: 'Captation musicale',
      searchGroupName: SearchGroupNameEnum.CD_VINYLE_MUSIQUE_EN_LIGNE,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.CARTE_CINE_ILLIMITE,
      categoryId: CategoryIdEnum.CINEMA,
      appLabel: 'Carte cinéma illimité',
      searchGroupName: SearchGroupNameEnum.FILMS_SERIES_CINEMA,
      homepageLabelName: HomepageLabelNameEnum.CINEMA,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.CARTE_CINE_MULTISEANCES,
      categoryId: CategoryIdEnum.CINEMA,
      appLabel: 'Carte cinéma multi-séances',
      searchGroupName: SearchGroupNameEnum.FILMS_SERIES_CINEMA,
      homepageLabelName: HomepageLabelNameEnum.CINEMA,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.CARTE_JEUNES,
      categoryId: CategoryIdEnum.CARTE_JEUNES,
      appLabel: 'Carte jeunes',
      searchGroupName: SearchGroupNameEnum.CARTES_JEUNES,
      homepageLabelName: HomepageLabelNameEnum.CARTE_JEUNES,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.CARTE_MUSEE,
      categoryId: CategoryIdEnum.MUSEE,
      appLabel: 'Cartes musées, patrimoine...',
      searchGroupName: SearchGroupNameEnum.MUSEES_VISITES_CULTURELLES,
      homepageLabelName: HomepageLabelNameEnum.VISITE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.CINE_PLEIN_AIR,
      categoryId: CategoryIdEnum.CINEMA,
      appLabel: 'Cinéma plein air',
      searchGroupName: SearchGroupNameEnum.FILMS_SERIES_CINEMA,
      homepageLabelName: HomepageLabelNameEnum.CINEMA,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.CINE_VENTE_DISTANCE,
      categoryId: CategoryIdEnum.CINEMA,
      appLabel: 'Cinéma',
      searchGroupName: SearchGroupNameEnum.FILMS_SERIES_CINEMA,
      homepageLabelName: HomepageLabelNameEnum.CINEMA,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.CONCERT,
      categoryId: CategoryIdEnum.MUSIQUE_LIVE,
      appLabel: 'Concert',
      searchGroupName: SearchGroupNameEnum.CD_VINYLE_MUSIQUE_EN_LIGNE,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.CONCOURS,
      categoryId: CategoryIdEnum.JEU,
      appLabel: 'Concours - jeux',
      searchGroupName: SearchGroupNameEnum.JEUX_JEUX_VIDEOS,
      homepageLabelName: HomepageLabelNameEnum.JEUX,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.CONFERENCE,
      categoryId: CategoryIdEnum.CONFERENCE,
      appLabel: 'Conférence',
      searchGroupName: SearchGroupNameEnum.CONFERENCE,
      homepageLabelName: HomepageLabelNameEnum.CONFERENCE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.DECOUVERTE_METIERS,
      categoryId: CategoryIdEnum.CONFERENCE,
      appLabel: 'Découverte des métiers',
      searchGroupName: SearchGroupNameEnum.CONFERENCE,
      homepageLabelName: HomepageLabelNameEnum.CONFERENCE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.ESCAPE_GAME,
      categoryId: CategoryIdEnum.JEU,
      appLabel: 'Escape game',
      searchGroupName: SearchGroupNameEnum.JEUX_JEUX_VIDEOS,
      homepageLabelName: HomepageLabelNameEnum.JEUX,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.EVENEMENT_CINE,
      categoryId: CategoryIdEnum.CINEMA,
      appLabel: 'Événement cinéma',
      searchGroupName: SearchGroupNameEnum.FILMS_SERIES_CINEMA,
      homepageLabelName: HomepageLabelNameEnum.CINEMA,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.EVENEMENT_JEU,
      categoryId: CategoryIdEnum.JEU,
      appLabel: 'Événements - jeux',
      searchGroupName: SearchGroupNameEnum.JEUX_JEUX_VIDEOS,
      homepageLabelName: HomepageLabelNameEnum.JEUX,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.EVENEMENT_MUSIQUE,
      categoryId: CategoryIdEnum.MUSIQUE_LIVE,
      appLabel: "Autre type d'événement musical",
      searchGroupName: SearchGroupNameEnum.CD_VINYLE_MUSIQUE_EN_LIGNE,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.EVENEMENT_PATRIMOINE,
      categoryId: CategoryIdEnum.MUSEE,
      appLabel: 'Événement et atelier patrimoine',
      searchGroupName: SearchGroupNameEnum.MUSEES_VISITES_CULTURELLES,
      homepageLabelName: HomepageLabelNameEnum.VISITE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.FESTIVAL_CINE,
      categoryId: CategoryIdEnum.CINEMA,
      appLabel: 'Festival de cinéma',
      searchGroupName: SearchGroupNameEnum.FILMS_SERIES_CINEMA,
      homepageLabelName: HomepageLabelNameEnum.CINEMA,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.FESTIVAL_LIVRE,
      categoryId: CategoryIdEnum.LIVRE,
      appLabel: 'Festival et salon du livre',
      searchGroupName: SearchGroupNameEnum.LIVRES,
      homepageLabelName: HomepageLabelNameEnum.LIVRES,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.FESTIVAL_MUSIQUE,
      categoryId: CategoryIdEnum.MUSIQUE_LIVE,
      appLabel: 'Festival de musique',
      searchGroupName: SearchGroupNameEnum.CD_VINYLE_MUSIQUE_EN_LIGNE,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.FESTIVAL_SPECTACLE,
      categoryId: CategoryIdEnum.SPECTACLE,
      appLabel: 'Festival',
      searchGroupName: SearchGroupNameEnum.CONCERTS_FESTIVALS,
      homepageLabelName: HomepageLabelNameEnum.SPECTACLE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.JEU_EN_LIGNE,
      categoryId: CategoryIdEnum.JEU,
      appLabel: 'Jeux en ligne',
      searchGroupName: SearchGroupNameEnum.JEUX_JEUX_VIDEOS,
      homepageLabelName: HomepageLabelNameEnum.JEUX,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.JEU_SUPPORT_PHYSIQUE,
      categoryId: CategoryIdEnum.TECHNIQUE,
      appLabel: 'Catégorie technique Jeu support physique',
      searchGroupName: SearchGroupNameEnum.NONE,
      homepageLabelName: HomepageLabelNameEnum.NONE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE_OR_OFFLINE,
    },
    {
      id: SubcategoryIdEnum.LIVESTREAM_EVENEMENT,
      categoryId: CategoryIdEnum.SPECTACLE,
      appLabel: "Live stream d'événement",
      searchGroupName: SearchGroupNameEnum.CONCERTS_FESTIVALS,
      homepageLabelName: HomepageLabelNameEnum.SPECTACLE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.LIVESTREAM_MUSIQUE,
      categoryId: CategoryIdEnum.MUSIQUE_LIVE,
      appLabel: 'Livestream musical',
      searchGroupName: SearchGroupNameEnum.CD_VINYLE_MUSIQUE_EN_LIGNE,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.LIVESTREAM_PRATIQUE_ARTISTIQUE,
      categoryId: CategoryIdEnum.PRATIQUE_ART,
      appLabel: 'Pratique artistique - livestream',
      searchGroupName: SearchGroupNameEnum.ARTS_LOISIRS_CREATIFS,
      homepageLabelName: HomepageLabelNameEnum.COURS,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.LIVRE_AUDIO_PHYSIQUE,
      categoryId: CategoryIdEnum.LIVRE,
      appLabel: 'Livre audio sur support physique',
      searchGroupName: SearchGroupNameEnum.LIVRES,
      homepageLabelName: HomepageLabelNameEnum.LIVRES,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.LIVRE_NUMERIQUE,
      categoryId: CategoryIdEnum.LIVRE,
      appLabel: 'Livre numérique, e-book',
      searchGroupName: SearchGroupNameEnum.LIVRES,
      homepageLabelName: HomepageLabelNameEnum.LIVRES,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.LIVRE_PAPIER,
      categoryId: CategoryIdEnum.LIVRE,
      appLabel: 'Livre',
      searchGroupName: SearchGroupNameEnum.LIVRES,
      homepageLabelName: HomepageLabelNameEnum.LIVRES,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.LOCATION_INSTRUMENT,
      categoryId: CategoryIdEnum.INSTRUMENT,
      appLabel: 'Location instrument',
      searchGroupName: SearchGroupNameEnum.INSTRUMENT,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.MATERIEL_ART_CREATIF,
      categoryId: CategoryIdEnum.BEAUX_ARTS,
      appLabel: 'Matériel arts créatifs',
      searchGroupName: SearchGroupNameEnum.MATERIEL,
      homepageLabelName: HomepageLabelNameEnum.MATERIEL,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.MUSEE_VENTE_DISTANCE,
      categoryId: CategoryIdEnum.MUSEE,
      appLabel: 'Musée vente à distance',
      searchGroupName: SearchGroupNameEnum.MUSEES_VISITES_CULTURELLES,
      homepageLabelName: HomepageLabelNameEnum.VISITE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.OEUVRE_ART,
      categoryId: CategoryIdEnum.TECHNIQUE,
      appLabel: "Catégorie technique d'oeuvre d'art",
      searchGroupName: SearchGroupNameEnum.NONE,
      homepageLabelName: HomepageLabelNameEnum.NONE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE_OR_OFFLINE,
    },
    {
      id: SubcategoryIdEnum.PARTITION,
      categoryId: CategoryIdEnum.INSTRUMENT,
      appLabel: 'Partition',
      searchGroupName: SearchGroupNameEnum.INSTRUMENT,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.PLATEFORME_PRATIQUE_ARTISTIQUE,
      categoryId: CategoryIdEnum.PRATIQUE_ART,
      appLabel: 'Plateforme de pratique artistique',
      searchGroupName: SearchGroupNameEnum.ARTS_LOISIRS_CREATIFS,
      homepageLabelName: HomepageLabelNameEnum.COURS,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.PRATIQUE_ART_VENTE_DISTANCE,
      categoryId: CategoryIdEnum.PRATIQUE_ART,
      appLabel: 'Pratique artistique - vente à distance',
      searchGroupName: SearchGroupNameEnum.ARTS_LOISIRS_CREATIFS,
      homepageLabelName: HomepageLabelNameEnum.COURS,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.PODCAST,
      categoryId: CategoryIdEnum.MEDIA,
      appLabel: 'Podcast',
      searchGroupName: SearchGroupNameEnum.MEDIA_PRESSE,
      homepageLabelName: HomepageLabelNameEnum.PRESSE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.RENCONTRE_EN_LIGNE,
      categoryId: CategoryIdEnum.CONFERENCE,
      appLabel: 'Rencontre en ligne',
      searchGroupName: SearchGroupNameEnum.CONFERENCE,
      homepageLabelName: HomepageLabelNameEnum.CONFERENCE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.RENCONTRE_JEU,
      categoryId: CategoryIdEnum.JEU,
      appLabel: 'Rencontres - jeux',
      searchGroupName: SearchGroupNameEnum.JEUX_JEUX_VIDEOS,
      homepageLabelName: HomepageLabelNameEnum.JEUX,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.RENCONTRE,
      categoryId: CategoryIdEnum.CONFERENCE,
      appLabel: 'Rencontre',
      searchGroupName: SearchGroupNameEnum.CONFERENCE,
      homepageLabelName: HomepageLabelNameEnum.CONFERENCE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.SALON,
      categoryId: CategoryIdEnum.CONFERENCE,
      appLabel: 'Salon, Convention',
      searchGroupName: SearchGroupNameEnum.CONFERENCE,
      homepageLabelName: HomepageLabelNameEnum.CONFERENCE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.SEANCE_CINE,
      categoryId: CategoryIdEnum.CINEMA,
      appLabel: 'Séance de cinéma',
      searchGroupName: SearchGroupNameEnum.FILMS_SERIES_CINEMA,
      homepageLabelName: HomepageLabelNameEnum.CINEMA,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.SEANCE_ESSAI_PRATIQUE_ART,
      categoryId: CategoryIdEnum.PRATIQUE_ART,
      appLabel: "Séance d'essai",
      searchGroupName: SearchGroupNameEnum.ARTS_LOISIRS_CREATIFS,
      homepageLabelName: HomepageLabelNameEnum.COURS,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.SPECTACLE_ENREGISTRE,
      categoryId: CategoryIdEnum.SPECTACLE,
      appLabel: 'Spectacle enregistré',
      searchGroupName: SearchGroupNameEnum.CONCERTS_FESTIVALS,
      homepageLabelName: HomepageLabelNameEnum.SPECTACLE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.SPECTACLE_REPRESENTATION,
      categoryId: CategoryIdEnum.SPECTACLE,
      appLabel: 'Spectacle, représentation',
      searchGroupName: SearchGroupNameEnum.CONCERTS_FESTIVALS,
      homepageLabelName: HomepageLabelNameEnum.SPECTACLE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.SPECTACLE_VENTE_DISTANCE,
      categoryId: CategoryIdEnum.SPECTACLE,
      appLabel: 'Spectacle vivant - vente à distance',
      searchGroupName: SearchGroupNameEnum.CONCERTS_FESTIVALS,
      homepageLabelName: HomepageLabelNameEnum.SPECTACLE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.SUPPORT_PHYSIQUE_FILM,
      categoryId: CategoryIdEnum.FILM,
      appLabel: 'Support physique (DVD, Blu-ray...)',
      searchGroupName: SearchGroupNameEnum.FILMS_SERIES_CINEMA,
      homepageLabelName: HomepageLabelNameEnum.FILMS,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.SUPPORT_PHYSIQUE_MUSIQUE,
      categoryId: CategoryIdEnum.MUSIQUE_ENREGISTREE,
      appLabel: 'Support physique (CD, vinyle...)',
      searchGroupName: SearchGroupNameEnum.CD_VINYLE_MUSIQUE_EN_LIGNE,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.TELECHARGEMENT_LIVRE_AUDIO,
      categoryId: CategoryIdEnum.LIVRE,
      appLabel: 'Livre audio à télécharger',
      searchGroupName: SearchGroupNameEnum.LIVRES,
      homepageLabelName: HomepageLabelNameEnum.LIVRES,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.TELECHARGEMENT_MUSIQUE,
      categoryId: CategoryIdEnum.MUSIQUE_ENREGISTREE,
      appLabel: 'Téléchargement de musique',
      searchGroupName: SearchGroupNameEnum.CD_VINYLE_MUSIQUE_EN_LIGNE,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.VISITE_GUIDEE,
      categoryId: CategoryIdEnum.MUSEE,
      appLabel: 'Visite guidée',
      searchGroupName: SearchGroupNameEnum.MUSEES_VISITES_CULTURELLES,
      homepageLabelName: HomepageLabelNameEnum.VISITE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.VISITE_VIRTUELLE,
      categoryId: CategoryIdEnum.MUSEE,
      appLabel: 'Visite virtuelle',
      searchGroupName: SearchGroupNameEnum.MUSEES_VISITES_CULTURELLES,
      homepageLabelName: HomepageLabelNameEnum.VISITE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.VISITE,
      categoryId: CategoryIdEnum.MUSEE,
      appLabel: 'Visite',
      searchGroupName: SearchGroupNameEnum.MUSEES_VISITES_CULTURELLES,
      homepageLabelName: HomepageLabelNameEnum.VISITE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.VOD,
      categoryId: CategoryIdEnum.FILM,
      appLabel: 'Vidéo à la demande',
      searchGroupName: SearchGroupNameEnum.FILMS_SERIES_CINEMA,
      homepageLabelName: HomepageLabelNameEnum.FILMS,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
  ],
  searchGroups: [
    { name: SearchGroupNameEnum.CARTES_JEUNES, value: 'Carte jeunes' },
    { name: SearchGroupNameEnum.FILMS_SERIES_CINEMA, value: 'Films, séries, cinéma' },
    { name: SearchGroupNameEnum.CONFERENCE, value: 'Conférences, rencontres' },
    { name: SearchGroupNameEnum.JEUX_JEUX_VIDEOS, value: 'Jeux & jeux vidéos' },
    { name: SearchGroupNameEnum.LIVRES, value: 'Livres' },
    { name: SearchGroupNameEnum.MUSEES_VISITES_CULTURELLES, value: 'Musées & visites culturelles' },
    { name: SearchGroupNameEnum.CD_VINYLE_MUSIQUE_EN_LIGNE, value: 'CD, vinyle, musique en ligne' },
    { name: SearchGroupNameEnum.ARTS_LOISIRS_CREATIFS, value: 'Arts & loisirs créatifs' },
    { name: SearchGroupNameEnum.MEDIA_PRESSE, value: 'Médias & presse' },
    { name: SearchGroupNameEnum.CONCERTS_FESTIVALS, value: 'Concerts & festivals' },
    { name: SearchGroupNameEnum.INSTRUMENT, value: 'Instruments de musique' },
    { name: SearchGroupNameEnum.MATERIEL, value: 'Beaux-Arts' },
    { name: SearchGroupNameEnum.NONE, value: null },
  ],
  homepageLabels: [
    { name: HomepageLabelNameEnum.FILMS, value: 'Films' },
    { name: HomepageLabelNameEnum.CARTE_JEUNES, value: 'Carte jeunes' },
    { name: HomepageLabelNameEnum.CINEMA, value: 'Cinéma' },
    { name: HomepageLabelNameEnum.CONFERENCE, value: 'Rencontres' },
    { name: HomepageLabelNameEnum.JEUX, value: 'Jeux' },
    { name: HomepageLabelNameEnum.LIVRES, value: 'Livre' },
    { name: HomepageLabelNameEnum.VISITE, value: 'Visites' },
    { name: HomepageLabelNameEnum.MUSIQUE, value: 'Musique' },
    { name: HomepageLabelNameEnum.COURS, value: 'Cours' },
    { name: HomepageLabelNameEnum.PRESSE, value: 'Médias' },
    { name: HomepageLabelNameEnum.SPECTACLE, value: 'Spectacle' },
    { name: HomepageLabelNameEnum.MATERIEL, value: 'Beaux-Arts' },
    { name: HomepageLabelNameEnum.NONE, value: null },
  ],
}
