import {
  CategoryIdEnum,
  HomepageLabelNameEnum,
  OnlineOfflinePlatformChoicesEnum,
  SearchGroupNameEnum,
  SubcategoryIdEnum,
  SubcategoriesResponseModel,
} from 'api/gen'

export const placeholderData: SubcategoriesResponseModel = {
  subcategories: [
    {
      id: SubcategoryIdEnum.ABOBIBLIOTHEQUE,
      categoryId: CategoryIdEnum.LIVRE,
      appLabel: 'Abonnement (bibliothèques, médiathèques...)',
      searchGroupName: SearchGroupNameEnum.LIVRE,
      homepageLabelName: HomepageLabelNameEnum.LIVRE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.ABOCONCERT,
      categoryId: CategoryIdEnum.MUSIQUELIVE,
      appLabel: 'Abonnement concert',
      searchGroupName: SearchGroupNameEnum.MUSIQUE,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.ABOJEUVIDEO,
      categoryId: CategoryIdEnum.JEU,
      appLabel: 'Abonnement jeux vidéos',
      searchGroupName: SearchGroupNameEnum.JEU,
      homepageLabelName: HomepageLabelNameEnum.JEU,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.ABOLIVRENUMERIQUE,
      categoryId: CategoryIdEnum.LIVRE,
      appLabel: 'Abonnement livres numériques',
      searchGroupName: SearchGroupNameEnum.LIVRE,
      homepageLabelName: HomepageLabelNameEnum.LIVRE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.ABOLUDOTHEQUE,
      categoryId: CategoryIdEnum.JEU,
      appLabel: 'Abonnement ludothèque',
      searchGroupName: SearchGroupNameEnum.JEU,
      homepageLabelName: HomepageLabelNameEnum.JEU,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.ABOMEDIATHEQUE,
      categoryId: CategoryIdEnum.FILM,
      appLabel: 'Abonnement médiathèque',
      searchGroupName: SearchGroupNameEnum.FILM,
      homepageLabelName: HomepageLabelNameEnum.FILM,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.ABOMUSEE,
      categoryId: CategoryIdEnum.MUSEE,
      appLabel: 'Entrée libre ou abonnement musée',
      searchGroupName: SearchGroupNameEnum.VISITE,
      homepageLabelName: HomepageLabelNameEnum.VISITE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.ABOPLATEFORMEMUSIQUE,
      categoryId: CategoryIdEnum.MUSIQUEENREGISTREE,
      appLabel: 'Abonnement plateforme musicale',
      searchGroupName: SearchGroupNameEnum.MUSIQUE,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.ABOPLATEFORMEVIDEO,
      categoryId: CategoryIdEnum.FILM,
      appLabel: 'Abonnement plateforme streaming',
      searchGroupName: SearchGroupNameEnum.FILM,
      homepageLabelName: HomepageLabelNameEnum.FILM,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.ABOPRATIQUEART,
      categoryId: CategoryIdEnum.PRATIQUEART,
      appLabel: 'Abonnement pratique artistique',
      searchGroupName: SearchGroupNameEnum.COURS,
      homepageLabelName: HomepageLabelNameEnum.COURS,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.ABOPRESSEENLIGNE,
      categoryId: CategoryIdEnum.MEDIA,
      appLabel: 'Abonnement presse en ligne',
      searchGroupName: SearchGroupNameEnum.PRESSE,
      homepageLabelName: HomepageLabelNameEnum.PRESSE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.ABOSPECTACLE,
      categoryId: CategoryIdEnum.SPECTACLE,
      appLabel: 'Abonnement spectacle',
      searchGroupName: SearchGroupNameEnum.SPECTACLE,
      homepageLabelName: HomepageLabelNameEnum.SPECTACLE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.ACHATINSTRUMENT,
      categoryId: CategoryIdEnum.INSTRUMENT,
      appLabel: 'Achat instrument',
      searchGroupName: SearchGroupNameEnum.INSTRUMENT,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.ACTIVATIONEVENT,
      categoryId: CategoryIdEnum.TECHNIQUE,
      appLabel: "Catégorie technique d'événement d'activation ",
      searchGroupName: SearchGroupNameEnum.NONE,
      homepageLabelName: HomepageLabelNameEnum.NONE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINEOROFFLINE,
    },
    {
      id: SubcategoryIdEnum.ACTIVATIONTHING,
      categoryId: CategoryIdEnum.TECHNIQUE,
      appLabel: "Catégorie technique de thing d'activation",
      searchGroupName: SearchGroupNameEnum.NONE,
      homepageLabelName: HomepageLabelNameEnum.NONE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINEOROFFLINE,
    },
    {
      id: SubcategoryIdEnum.APPCULTURELLE,
      categoryId: CategoryIdEnum.MEDIA,
      appLabel: 'Application culturelle',
      searchGroupName: SearchGroupNameEnum.PRESSE,
      homepageLabelName: HomepageLabelNameEnum.PRESSE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.ATELIERPRATIQUEART,
      categoryId: CategoryIdEnum.PRATIQUEART,
      appLabel: 'Atelier, stage de pratique artistique',
      searchGroupName: SearchGroupNameEnum.COURS,
      homepageLabelName: HomepageLabelNameEnum.COURS,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.AUTRESUPPORTNUMERIQUE,
      categoryId: CategoryIdEnum.FILM,
      appLabel: 'Autre support numérique',
      searchGroupName: SearchGroupNameEnum.FILM,
      homepageLabelName: HomepageLabelNameEnum.FILM,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.BONACHATINSTRUMENT,
      categoryId: CategoryIdEnum.INSTRUMENT,
      appLabel: "Bon d'achat instrument",
      searchGroupName: SearchGroupNameEnum.INSTRUMENT,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.CAPTATIONMUSIQUE,
      categoryId: CategoryIdEnum.MUSIQUEENREGISTREE,
      appLabel: 'Captation musicale',
      searchGroupName: SearchGroupNameEnum.MUSIQUE,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.CARTECINEILLIMITE,
      categoryId: CategoryIdEnum.CINEMA,
      appLabel: 'Carte cinéma illimité',
      searchGroupName: SearchGroupNameEnum.CINEMA,
      homepageLabelName: HomepageLabelNameEnum.CINEMA,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.CARTECINEMULTISEANCES,
      categoryId: CategoryIdEnum.CINEMA,
      appLabel: 'Carte cinéma multi-séances',
      searchGroupName: SearchGroupNameEnum.CINEMA,
      homepageLabelName: HomepageLabelNameEnum.CINEMA,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.CARTEMUSEE,
      categoryId: CategoryIdEnum.MUSEE,
      appLabel: 'Cartes musées, patrimoine...',
      searchGroupName: SearchGroupNameEnum.VISITE,
      homepageLabelName: HomepageLabelNameEnum.VISITE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.CINEPLEINAIR,
      categoryId: CategoryIdEnum.CINEMA,
      appLabel: 'Cinéma plein air',
      searchGroupName: SearchGroupNameEnum.CINEMA,
      homepageLabelName: HomepageLabelNameEnum.CINEMA,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.CINEVENTEDISTANCE,
      categoryId: CategoryIdEnum.CINEMA,
      appLabel: 'Cinéma',
      searchGroupName: SearchGroupNameEnum.CINEMA,
      homepageLabelName: HomepageLabelNameEnum.CINEMA,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.CONCERT,
      categoryId: CategoryIdEnum.MUSIQUELIVE,
      appLabel: 'Concert',
      searchGroupName: SearchGroupNameEnum.MUSIQUE,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.CONCOURS,
      categoryId: CategoryIdEnum.JEU,
      appLabel: 'Concours - jeux',
      searchGroupName: SearchGroupNameEnum.JEU,
      homepageLabelName: HomepageLabelNameEnum.JEU,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.CONFERENCE,
      categoryId: CategoryIdEnum.CONFERENCE,
      appLabel: 'Conférence',
      searchGroupName: SearchGroupNameEnum.CONFERENCE,
      homepageLabelName: HomepageLabelNameEnum.CONFERENCE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.DECOUVERTEMETIERS,
      categoryId: CategoryIdEnum.CONFERENCE,
      appLabel: 'Découverte des métiers',
      searchGroupName: SearchGroupNameEnum.CONFERENCE,
      homepageLabelName: HomepageLabelNameEnum.CONFERENCE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.ESCAPEGAME,
      categoryId: CategoryIdEnum.JEU,
      appLabel: 'Escape game',
      searchGroupName: SearchGroupNameEnum.JEU,
      homepageLabelName: HomepageLabelNameEnum.JEU,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.EVENEMENTCINE,
      categoryId: CategoryIdEnum.CINEMA,
      appLabel: 'Événement cinéma',
      searchGroupName: SearchGroupNameEnum.CINEMA,
      homepageLabelName: HomepageLabelNameEnum.CINEMA,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.EVENEMENTJEU,
      categoryId: CategoryIdEnum.JEU,
      appLabel: 'Événements - jeux',
      searchGroupName: SearchGroupNameEnum.JEU,
      homepageLabelName: HomepageLabelNameEnum.JEU,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.EVENEMENTMUSIQUE,
      categoryId: CategoryIdEnum.MUSIQUELIVE,
      appLabel: "Autre type d'événement musical",
      searchGroupName: SearchGroupNameEnum.MUSIQUE,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.EVENEMENTPATRIMOINE,
      categoryId: CategoryIdEnum.MUSEE,
      appLabel: 'Événement et atelier patrimoine',
      searchGroupName: SearchGroupNameEnum.VISITE,
      homepageLabelName: HomepageLabelNameEnum.VISITE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.FESTIVALCINE,
      categoryId: CategoryIdEnum.CINEMA,
      appLabel: 'Festival de cinéma',
      searchGroupName: SearchGroupNameEnum.CINEMA,
      homepageLabelName: HomepageLabelNameEnum.CINEMA,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.FESTIVALLIVRE,
      categoryId: CategoryIdEnum.LIVRE,
      appLabel: 'Festival et salon du livre',
      searchGroupName: SearchGroupNameEnum.LIVRE,
      homepageLabelName: HomepageLabelNameEnum.LIVRE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.FESTIVALMUSIQUE,
      categoryId: CategoryIdEnum.MUSIQUELIVE,
      appLabel: 'Festival de musique',
      searchGroupName: SearchGroupNameEnum.MUSIQUE,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.FESTIVALSPECTACLE,
      categoryId: CategoryIdEnum.SPECTACLE,
      appLabel: 'Festival',
      searchGroupName: SearchGroupNameEnum.SPECTACLE,
      homepageLabelName: HomepageLabelNameEnum.SPECTACLE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.JEUENLIGNE,
      categoryId: CategoryIdEnum.JEU,
      appLabel: 'Jeux en ligne',
      searchGroupName: SearchGroupNameEnum.JEU,
      homepageLabelName: HomepageLabelNameEnum.JEU,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.JEUSUPPORTPHYSIQUE,
      categoryId: CategoryIdEnum.TECHNIQUE,
      appLabel: 'Catégorie technique Jeu support physique',
      searchGroupName: SearchGroupNameEnum.NONE,
      homepageLabelName: HomepageLabelNameEnum.NONE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINEOROFFLINE,
    },
    {
      id: SubcategoryIdEnum.LIVESTREAMEVENEMENT,
      categoryId: CategoryIdEnum.SPECTACLE,
      appLabel: "Live stream d'événement",
      searchGroupName: SearchGroupNameEnum.SPECTACLE,
      homepageLabelName: HomepageLabelNameEnum.SPECTACLE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.LIVESTREAMMUSIQUE,
      categoryId: CategoryIdEnum.MUSIQUELIVE,
      appLabel: 'Live stream musical',
      searchGroupName: SearchGroupNameEnum.MUSIQUE,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.LIVREAUDIOPHYSIQUE,
      categoryId: CategoryIdEnum.LIVRE,
      appLabel: 'Livre audio sur support physique',
      searchGroupName: SearchGroupNameEnum.LIVRE,
      homepageLabelName: HomepageLabelNameEnum.LIVRE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.LIVRENUMERIQUE,
      categoryId: CategoryIdEnum.LIVRE,
      appLabel: 'Livre numérique, e-book',
      searchGroupName: SearchGroupNameEnum.LIVRE,
      homepageLabelName: HomepageLabelNameEnum.LIVRE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.LIVREPAPIER,
      categoryId: CategoryIdEnum.LIVRE,
      appLabel: 'Livre',
      searchGroupName: SearchGroupNameEnum.LIVRE,
      homepageLabelName: HomepageLabelNameEnum.LIVRE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.LOCATIONINSTRUMENT,
      categoryId: CategoryIdEnum.INSTRUMENT,
      appLabel: 'Location instrument',
      searchGroupName: SearchGroupNameEnum.INSTRUMENT,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.MATERIELARTCREATIF,
      categoryId: CategoryIdEnum.BEAUXARTS,
      appLabel: 'Matériel arts créatifs',
      searchGroupName: SearchGroupNameEnum.MATERIEL,
      homepageLabelName: HomepageLabelNameEnum.MATERIEL,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.MUSEEVENTEDISTANCE,
      categoryId: CategoryIdEnum.MUSEE,
      appLabel: 'Musée vente à distance',
      searchGroupName: SearchGroupNameEnum.VISITE,
      homepageLabelName: HomepageLabelNameEnum.VISITE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.OEUVREART,
      categoryId: CategoryIdEnum.TECHNIQUE,
      appLabel: "Catégorie technique d'oeuvre d'art",
      searchGroupName: SearchGroupNameEnum.NONE,
      homepageLabelName: HomepageLabelNameEnum.NONE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINEOROFFLINE,
    },
    {
      id: SubcategoryIdEnum.PARTITION,
      categoryId: CategoryIdEnum.INSTRUMENT,
      appLabel: 'Partition',
      searchGroupName: SearchGroupNameEnum.INSTRUMENT,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.PODCAST,
      categoryId: CategoryIdEnum.MEDIA,
      appLabel: 'Podcast',
      searchGroupName: SearchGroupNameEnum.PRESSE,
      homepageLabelName: HomepageLabelNameEnum.PRESSE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.RENCONTREJEU,
      categoryId: CategoryIdEnum.JEU,
      appLabel: 'Rencontres - jeux',
      searchGroupName: SearchGroupNameEnum.JEU,
      homepageLabelName: HomepageLabelNameEnum.JEU,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.RENCONTRE,
      categoryId: CategoryIdEnum.CONFERENCE,
      appLabel: 'Rencontre',
      searchGroupName: SearchGroupNameEnum.CONFERENCE,
      homepageLabelName: HomepageLabelNameEnum.CONFERENCE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.SALON,
      categoryId: CategoryIdEnum.CONFERENCE,
      appLabel: 'Salon, Convention',
      searchGroupName: SearchGroupNameEnum.CONFERENCE,
      homepageLabelName: HomepageLabelNameEnum.CONFERENCE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.SEANCECINE,
      categoryId: CategoryIdEnum.CINEMA,
      appLabel: 'Séance de cinéma',
      searchGroupName: SearchGroupNameEnum.CINEMA,
      homepageLabelName: HomepageLabelNameEnum.CINEMA,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.SEANCEESSAIPRATIQUEART,
      categoryId: CategoryIdEnum.PRATIQUEART,
      appLabel: "Séance d'essai",
      searchGroupName: SearchGroupNameEnum.COURS,
      homepageLabelName: HomepageLabelNameEnum.COURS,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.SPECTACLEENREGISTRE,
      categoryId: CategoryIdEnum.SPECTACLE,
      appLabel: 'Spectacle enregistré',
      searchGroupName: SearchGroupNameEnum.SPECTACLE,
      homepageLabelName: HomepageLabelNameEnum.SPECTACLE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.SPECTACLEREPRESENTATION,
      categoryId: CategoryIdEnum.SPECTACLE,
      appLabel: 'Spectacle, représentation',
      searchGroupName: SearchGroupNameEnum.SPECTACLE,
      homepageLabelName: HomepageLabelNameEnum.SPECTACLE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.SUPPORTPHYSIQUEFILM,
      categoryId: CategoryIdEnum.FILM,
      appLabel: 'Support physique (DVD, Blu-ray...)',
      searchGroupName: SearchGroupNameEnum.FILM,
      homepageLabelName: HomepageLabelNameEnum.FILM,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.SUPPORTPHYSIQUEMUSIQUE,
      categoryId: CategoryIdEnum.MUSIQUEENREGISTREE,
      appLabel: 'Support physique (CD, vinyle...)',
      searchGroupName: SearchGroupNameEnum.MUSIQUE,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.TELECHARGEMENTLIVREAUDIO,
      categoryId: CategoryIdEnum.LIVRE,
      appLabel: 'Livre audio à télécharger',
      searchGroupName: SearchGroupNameEnum.LIVRE,
      homepageLabelName: HomepageLabelNameEnum.LIVRE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.TELECHARGEMENTMUSIQUE,
      categoryId: CategoryIdEnum.MUSIQUEENREGISTREE,
      appLabel: 'Téléchargement de musique',
      searchGroupName: SearchGroupNameEnum.MUSIQUE,
      homepageLabelName: HomepageLabelNameEnum.MUSIQUE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.VISITEGUIDEE,
      categoryId: CategoryIdEnum.MUSEE,
      appLabel: 'Visite guidée',
      searchGroupName: SearchGroupNameEnum.VISITE,
      homepageLabelName: HomepageLabelNameEnum.VISITE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.VISITEVIRTUELLE,
      categoryId: CategoryIdEnum.MUSEE,
      appLabel: 'Visite virtuelle',
      searchGroupName: SearchGroupNameEnum.VISITE,
      homepageLabelName: HomepageLabelNameEnum.VISITE,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
    {
      id: SubcategoryIdEnum.VISITE,
      categoryId: CategoryIdEnum.MUSEE,
      appLabel: 'Visite',
      searchGroupName: SearchGroupNameEnum.VISITE,
      homepageLabelName: HomepageLabelNameEnum.VISITE,
      isEvent: true,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.OFFLINE,
    },
    {
      id: SubcategoryIdEnum.VOD,
      categoryId: CategoryIdEnum.FILM,
      appLabel: 'Vidéo à la demande',
      searchGroupName: SearchGroupNameEnum.FILM,
      homepageLabelName: HomepageLabelNameEnum.FILM,
      isEvent: false,
      onlineOfflinePlatform: OnlineOfflinePlatformChoicesEnum.ONLINE,
    },
  ],
  searchGroups: [
    { name: SearchGroupNameEnum.FILM, value: 'Films, séries' },
    { name: SearchGroupNameEnum.CINEMA, value: 'Cinéma' },
    { name: SearchGroupNameEnum.CONFERENCE, value: 'Conférences, rencontres' },
    { name: SearchGroupNameEnum.JEU, value: 'Jeux' },
    { name: SearchGroupNameEnum.LIVRE, value: 'Livre' },
    { name: SearchGroupNameEnum.VISITE, value: 'Visite, exposition' },
    { name: SearchGroupNameEnum.MUSIQUE, value: 'Musique' },
    { name: SearchGroupNameEnum.COURS, value: 'Cours, ateliers' },
    { name: SearchGroupNameEnum.PRESSE, value: 'Presse, médias' },
    { name: SearchGroupNameEnum.SPECTACLE, value: 'Spectacles' },
    { name: SearchGroupNameEnum.INSTRUMENT, value: 'Instruments de musique' },
    { name: SearchGroupNameEnum.MATERIEL, value: 'Beaux-Arts' },
    { name: SearchGroupNameEnum.NONE, value: null },
  ],
  homepageLabels: [
    { name: HomepageLabelNameEnum.FILM, value: 'Films' },
    { name: HomepageLabelNameEnum.CINEMA, value: 'Cinéma' },
    { name: HomepageLabelNameEnum.CONFERENCE, value: 'Rencontres' },
    { name: HomepageLabelNameEnum.JEU, value: 'Jeux' },
    { name: HomepageLabelNameEnum.LIVRE, value: 'Livre' },
    { name: HomepageLabelNameEnum.VISITE, value: 'Visites' },
    { name: HomepageLabelNameEnum.MUSIQUE, value: 'Musique' },
    { name: HomepageLabelNameEnum.COURS, value: 'Cours' },
    { name: HomepageLabelNameEnum.PRESSE, value: 'Médias' },
    { name: HomepageLabelNameEnum.SPECTACLE, value: 'Spectacle' },
    { name: HomepageLabelNameEnum.MATERIEL, value: 'Beaux-Arts' },
    { name: HomepageLabelNameEnum.NONE, value: null },
  ],
}
