/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import { AccessibilityInfo } from 'react-native'

import {
  EXIT_THRESHOLD_IN_MS,
  LONG_TEXT_ANIMATION_DURATION_IN_MS,
  LONG_TEXT_CHARACTER_LENGTH,
  SHORT_TEXT_ANIMATION_DURATION_IN_MS,
  snackBarStore,
} from './snackBar.store'

jest.unmock('uuid')
jest.useFakeTimers()

const mockAnnounceForAccessibility = jest.spyOn(AccessibilityInfo, 'announceForAccessibility')

describe('SnackBarStore', () => {
  let snackbars: ReturnType<typeof snackBarStore.selectors.selectSnackbarProps>

  beforeEach(() => {
    jest.clearAllTimers()
    snackBarStore.actions.reset()
    snackbars = getSnackbars()
  })

  describe('open action', () => {
    it(`should add a snackbar with short text and animation duration of ${SHORT_TEXT_ANIMATION_DURATION_IN_MS}ms`, () => {
      snackBarStore.actions.open('Short message', 'success')
      snackbars = getSnackbars()

      expect(snackbars).toHaveLength(1)
      expect(snackbars[0]).toMatchObject({
        label: 'Short message',
        type: 'success',
        animationDuration: SHORT_TEXT_ANIMATION_DURATION_IN_MS,
      })
      expect(mockAnnounceForAccessibility).toHaveBeenCalledWith('Short message')
    })

    it(`should announce short text`, () => {
      snackBarStore.actions.open('Short message', 'success')
      snackbars = getSnackbars()

      expect(mockAnnounceForAccessibility).toHaveBeenCalledWith('Short message')
    })

    it(`should add a snackbar with long text and animation duration of ${LONG_TEXT_ANIMATION_DURATION_IN_MS}ms`, () => {
      const longText = 'a'.repeat(LONG_TEXT_CHARACTER_LENGTH + 1)
      snackBarStore.actions.open(longText, 'success')
      snackbars = getSnackbars()

      expect(snackbars).toHaveLength(1)
      expect(snackbars[0]).toMatchObject({
        label: longText,
        type: 'success',
        animationDuration: LONG_TEXT_ANIMATION_DURATION_IN_MS,
      })
    })

    it('should auto-close snackbar after animation duration', () => {
      snackBarStore.actions.open('Test', 'success')
      snackbars = getSnackbars()

      expect(snackbars).toHaveLength(1)

      jest.advanceTimersByTime(SHORT_TEXT_ANIMATION_DURATION_IN_MS + EXIT_THRESHOLD_IN_MS)

      expect(getSnackbars()).toHaveLength(0)
    })

    it('should support multiple snackbars', () => {
      snackBarStore.actions.open('First', 'success')
      snackBarStore.actions.open('Second', 'error')

      expect(getSnackbars()).toHaveLength(2)
    })
  })

  describe('close action', () => {
    it('should remove snackbar by id', () => {
      snackBarStore.actions.open('Message', 'success')

      getSnackbars()[0]?.onClose()

      expect(getSnackbars()).toHaveLength(0)
    })

    it('should not remove snackbar if id is not found', () => {
      snackBarStore.actions.open('Message', 'success')

      snackBarStore.actions.close('non-existent-id')

      expect(getSnackbars()).toHaveLength(1)
    })
  })

  describe('accessibility props', () => {
    it('should expose accessibility props in selectSnackbarProps', () => {
      snackBarStore.actions.open('Opération réussie', 'success')
      const snackbar = getSnackbars()[0]

      expect(snackbar).toMatchObject({
        accessibilityLabel: 'Opération réussie',
        accessibilityHint: 'Appuyer deux fois pour fermer',
        accessibilityActions: [{ name: 'activate', label: 'Fermer' }],
      })
      expect(snackbar?.onAccessibilityTap).toBeDefined()
      expect(snackbar?.onAccessibilityAction).toBeDefined()
    })

    it('should close snackbar when accessibility action is triggered', () => {
      snackBarStore.actions.open('Test', 'error')
      const snackbar = getSnackbars()[0]

      snackbar?.onAccessibilityAction({
        nativeEvent: { actionName: 'activate' },
      } as never)

      expect(getSnackbars()).toHaveLength(0)
    })
  })
})

const getSnackbars = () => snackBarStore.selectors.selectSnackbarProps()
