/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React, { FC } from 'react'
import { styled } from 'styled-components/native'

import { SnackBarDefault } from 'ui/designSystem/Snackbar/SnackBarDefault'
import { SnackBarLarge } from 'ui/designSystem/Snackbar/SnackBarLarge'
import { ErrorPlain } from 'ui/svg/icons/ErrorPlain'
import { Validate } from 'ui/svg/icons/Validate'

export type SnackBarProps = {
  id: string
  label: string
  type: SnackBarType
  onClose: () => void
  animationDuration: number
  variant?: 'default' | 'large'
}

export type SnackBarType = 'success' | 'error'

export const SnackBar: FC<SnackBarProps> = ({ variant = 'default', ...props }) => {
  const Icon = props.type === 'success' ? IconSuccess : IconError
  const SnackBarVariant = variant === 'default' ? SnackBarDefault : SnackBarLarge

  return <SnackBarVariant Icon={Icon} {...props} />
}

const IconSuccess = styled(Validate).attrs(({ theme }) => ({
  color: theme.designSystem.color.icon.success,
  color2: theme.designSystem.color.icon.inverted,
  size: theme.icons.sizes.smaller,
}))``

const IconError = styled(ErrorPlain).attrs(({ theme }) => ({
  color: theme.designSystem.color.icon.error,
  color2: theme.designSystem.color.icon.inverted,
  size: theme.icons.sizes.smaller,
}))``
