/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import type { Meta, StoryObj } from '@storybook/react-vite'
import React, { useState } from 'react'
import styled from 'styled-components/native'

import { ButtonPrimary } from 'ui/components/buttons/ButtonPrimary'
import { ViewGap } from 'ui/components/ViewGap/ViewGap'
import { RadioButtonGroup } from 'ui/designSystem/RadioButtonGroup/RadioButtonGroup'
import { SnackBar } from 'ui/designSystem/Snackbar/SnackBar'
import { snackBarActions } from 'ui/designSystem/Snackbar/SnackBarStore'
import { SnackBarWrapper } from 'ui/designSystem/Snackbar/SnackBarWrapper'
import { TextInput } from 'ui/designSystem/TextInput/TextInput'

const meta: Meta<typeof SnackBar> = {
  title: 'design system/SnackBar',
  component: SnackBar,
  args: {
    label: 'Texte de la snackbar',
    type: 'success',
    variant: 'default',
    animationDuration: 5000,
    id: 'storybook-snackbar',
    onClose: () => undefined,
  },
  argTypes: {
    label: {
      control: 'text',
      description: 'Le message affiché dans la snackbar',
    },
    type: {
      control: 'radio',
      options: ['success', 'error'],
      description: 'Type de snackbar (success ou error)',
    },
    variant: {
      control: 'radio',
      options: ['default', 'large'],
      description: 'Variante de la snackbar',
    },
    animationDuration: {
      control: { type: 'number', min: 1000, max: 10000, step: 1000 },
      description: 'Durée (animation) en ms',
    },
    id: { table: { disable: true } },
    onClose: { table: { disable: true } },
  },
}
export default meta

type Story = StoryObj<typeof SnackBar>

export const Playground: Story = {
  name: 'Snackbar',
  render: (args) => <SnackBar {...args} />,
}

const SNACKBAR_TYPE_OPTIONS = [
  { key: 'success', label: 'success' },
  { key: 'error', label: 'error' },
]

const SnackBarWrapperDemo = () => {
  const [message, setMessage] = useState('Votre message ici')
  const [snackbarType, setSnackbarType] = useState<'success' | 'error'>('success')

  const handleShowSnackbar = () => {
    snackBarActions.open(message, snackbarType)
  }

  return (
    <FullHeightContainer>
      <SnackBarWrapper>
        <ViewGap gap={4}>
          <TextInput label="Message de la snackbar" value={message} onChangeText={setMessage} />

          <RadioButtonGroup
            label="Type de snackbar"
            options={SNACKBAR_TYPE_OPTIONS}
            value={snackbarType}
            onChange={(value) => setSnackbarType(value as 'success' | 'error')}
            errorText=""
            display="horizontal"
          />

          <ButtonPrimary wording="Afficher la Snackbar" onPress={handleShowSnackbar} />
        </ViewGap>
      </SnackBarWrapper>
    </FullHeightContainer>
  )
}

const FullHeightContainer = styled.View({
  flex: 1,
  minHeight: '100vh',
})

export const WithWrapper: Story = {
  name: 'SnackBarWrapper',
  parameters: {
    layout: 'fullscreen',
  },
  render: () => <SnackBarWrapperDemo />,
}
