/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React from 'react'
import { View } from 'react-native'

import { act, render, screen } from 'tests/utils/web'
import {
  EXIT_THRESHOLD_IN_MS,
  SHORT_TEXT_ANIMATION_DURATION_IN_MS,
  snackBarActions,
  snackBarStore,
} from 'ui/designSystem/Snackbar/snackBar.store'

jest.unmock('uuid')

// The web render helper already mounts the SnackBarWrapper around every tree.
const renderSnackBarWrapper = () => render(<View />)

describe('<SnackBarWrapper />', () => {
  beforeEach(() => {
    jest.useFakeTimers()
    snackBarActions.reset()
  })

  afterEach(() => {
    jest.clearAllTimers()
    jest.useRealTimers()
  })

  it('should render the live regions before any snackbar is displayed', () => {
    renderSnackBarWrapper()

    expect(screen.getAllByRole('status')).toHaveLength(2)
    expect(screen.getAllByRole('alert')).toHaveLength(2)
    expect(screen.queryByTestId('snackbar-success')).not.toBeInTheDocument()
  })

  it('should announce a success message politely', () => {
    renderSnackBarWrapper()

    act(() => {
      snackBarActions.showSuccessSnackBar('Le lien a été copié dans le presse-papier !')
    })

    const [firstStatusBuffer] = screen.getAllByRole('status')

    expect(firstStatusBuffer).toHaveTextContent('Le lien a été copié dans le presse-papier')
    expect(screen.getAllByRole('alert')[0]).toHaveTextContent('')
  })

  it('should announce an error message assertively', () => {
    renderSnackBarWrapper()

    act(() => {
      snackBarActions.showErrorSnackBar(
        'Une erreur est survenue lors de la mise à jour de ton profil'
      )
    })

    const [firstAlertBuffer] = screen.getAllByRole('alert')

    expect(firstAlertBuffer).toHaveTextContent(
      'Une erreur est survenue lors de la mise à jour de ton profil'
    )
    expect(screen.getAllByRole('status')[0]).toHaveTextContent('')
  })

  it('should keep the announcement in the live region after the snackbar is closed', () => {
    renderSnackBarWrapper()

    act(() => {
      snackBarActions.showSuccessSnackBar('Message conservé')
    })

    expect(screen.getByTestId('snackbar-success')).toBeInTheDocument()

    act(() => {
      jest.advanceTimersByTime(SHORT_TEXT_ANIMATION_DURATION_IN_MS + EXIT_THRESHOLD_IN_MS)
    })

    expect(screen.queryByTestId('snackbar-success')).not.toBeInTheDocument()
    expect(screen.getAllByRole('status')[0]).toHaveTextContent('Message conservé')
  })

  it('should re-announce two consecutive identical messages', () => {
    renderSnackBarWrapper()

    act(() => {
      snackBarActions.showSuccessSnackBar('Message identique')
    })

    act(() => {
      snackBarStore.actions.close(
        Object.keys(snackBarStore.store.getState().snackbars)[0] as string
      )
      snackBarActions.showSuccessSnackBar('Message identique')
    })

    const statusBuffers = screen.getAllByRole('status')

    expect(statusBuffers[0]).toHaveTextContent('')
    expect(statusBuffers[1]).toHaveTextContent('Message identique')
  })
})
