/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React, { FC, PropsWithChildren } from 'react'
import { View } from 'react-native'
import { styled, useTheme } from 'styled-components/native'

import { SnackBar } from 'ui/designSystem/Snackbar/SnackBar'
import { useSnackbarProps } from 'ui/designSystem/Snackbar/snackBar.store'

export const SnackBarWrapper: FC<PropsWithChildren> = ({ children }) => {
  const { isDesktopViewport } = useTheme()
  const snackbarsProps = useSnackbarProps()

  return (
    <React.Fragment>
      {snackbarsProps.length > 0 ? (
        <Container>
          {snackbarsProps.map(({ onClose, label, animationDuration, type, id }, index) => (
            <View style={{ zIndex: 1000 - index }} key={id}>
              <SnackBar
                variant={isDesktopViewport ? 'large' : 'default'}
                id={id}
                onClose={onClose}
                label={label}
                animationDuration={animationDuration}
                type={type}
              />
            </View>
          ))}
        </Container>
      ) : null}
      {children}
    </React.Fragment>
  )
}

const Container = styled.View(({ theme }) => ({
  top: theme.isDesktopViewport ? undefined : theme.designSystem.size.spacing.xs,
  bottom: theme.isDesktopViewport ? theme.designSystem.size.spacing.xs : undefined,
  left: theme.isDesktopViewport ? undefined : theme.designSystem.size.spacing.xs,
  right: theme.designSystem.size.spacing.xs,
  position: 'absolute',
  zIndex: 1000,
}))
