// Feature entry point for debug performance module
export { DebugPerformanceProvider, useDebugPerformance } from './context/DebugPerformanceProvider'
export { useNetworkInterception } from './hooks/useNetworkInterception'
export { useRenderTracking } from './hooks/useRenderTracking'
export { RenderProfiler } from './components/RenderProfiler'
export { NetworkInterceptor } from './services/NetworkInterceptor'
export { NetworkStorage } from './services/NetworkStorage'
export { RenderTracker } from './services/RenderTracker'
export { MetricsCollector } from './services/MetricsCollector'
export { MetricsCalculator, StreamingMetrics } from './utils/metrics'
export { ComponentTreeUtils } from './utils/componentTree'
export { RequestCategorizer } from './utils/requestCategorization'
export { startNetworkInterception, stopNetworkInterception } from './utils/startNetworkInterception'
export { now, measure, Timer, getPlatformInfo } from './utils/performanceTiming'
export type { PerformanceSession, NetworkRequest, RenderEvent, ListPerformance } from './types'
export type { NetworkInterceptionConfig, NetworkMetrics } from './hooks/useNetworkInterception'
export type { CategoryInfo } from './utils/requestCategorization'
export type { TreeNode } from './services/RenderTracker'
export { default as ConsoleInterface } from './console/ConsoleInterface'
export { logger } from './utils/logger'
