export enum AccessibilityRole {
  BUTTON = 'button',
  CHECKBOX = 'checkbox',
  DIALOG = 'dialog',
  FOOTER = 'contentinfo',
  GROUP = 'group',
  HEADER = 'banner',
  IMAGE = 'image',
  LINK = 'link',
  MAIN = 'main',
  RADIO = 'radio',
  RADIOGROUP = 'radiogroup',
  SWITCH = 'switch',
  STATUS = 'status',
}
