export enum AccessibilityRole {
  BUTTON = 'button',
  CHECKBOX = 'checkbox',
  DIALOG = 'none',
  FOOTER = 'none',
  FORM = 'none',
  GROUP = 'none',
  HEADER = 'header',
  HEADING = 'none',
  IMAGE = 'image',
  LINK = 'link',
  LIST = 'list',
  LISTITEM = 'none',
  MAIN = 'none',
  NAVIGATION = 'none',
  RADIO = 'radio',
  RADIOGROUP = 'radiogroup',
  SWITCH = 'switch',
  STATUS = 'none',
  TOOLTIP = 'none',
}
