export enum AccessibilityRole {
  ALERT = 'alert',
  BUTTON = 'button',
  CHECKBOX = 'checkbox',
  DIALOG = 'none',
  FOOTER = 'none',
  FORM = 'none',
  GROUP = 'none',
  HEADER = 'header',
  HEADING = 'none',
  IMAGE = 'image',
  LINK = 'link',
  LIST = 'list',
  LISTITEM = 'none',
  MAIN = 'none',
  NAVIGATION = 'none',
  NONE = 'none',
  PROGRESSBAR = 'progressbar',
  RADIO = 'radio',
  RADIOGROUP = 'radiogroup',
  STATUS = 'none',
  SWITCH = 'switch',
  TAB = 'tab',
  TABLIST = 'tablist',
  TABPANEL = 'none',
  TEXT = 'text',
  TOOLTIP = 'none',
}
