output.wording = {
  common: {
    browserUpdate: "J’accède au pass Culture sans mettre à jour mon navigateur",
    ios: {
      permissionRegex: "Autorisez-vous.*",
      allow: "Autoriser",
    },
    back: "Revenir à l’étape précédente",
    backButton: "Revenir en arrière",
    createAccount: "Créer un compte",
    welcome: "Bienvenue !",
    noThanks: "Non merci",
    later: "Plus tard",
  },
  cookies: {
    consent: {
      title: "Respect de ta vie privée",
      acceptAll: "Tout accepter",
      refuseAll: "Tout refuser",
      choose: "Choisir les cookies",
    },
    settings: {
      title: "Réglages des cookies",
      subtitle: "Je choisis mes cookies",
      policyLink: ".*politique de gestion des cookies",
      save: "Enregistrer mes choix",
    },
    switches: {
      customization: {
        off: "Personnaliser ta navigation - Interrupteur à bascule - non coché",
        on: "Personnaliser ta navigation - Interrupteur à bascule - coché",
      },
      statistics: {
        off: "Enregistrer des statistiques de navigation - Interrupteur à bascule - non coché",
        on: "Enregistrer des statistiques de navigation - Interrupteur à bascule - coché",
      },
      marketing: {
        off: "Mesurer l’efficacité de nos publicités - Interrupteur à bascule - non coché",
        on: "Mesurer l’efficacité de nos publicités - Interrupteur à bascule - coché",
      },
      video: {
        off: "Lire les contenus vidéos - Interrupteur à bascule - non coché",
        on: "Lire les contenus vidéos - Interrupteur à bascule - coché",
      },
      all: {
        on: "Tout accepter - Interrupteur à bascule - coché",
      },
    },
  },
  onboarding: {
    welcome: {
      title: "Bienvenue sur le pass Culture",
      button: "C’est parti !",
    },
    discover: {
      title: "Découvre les offres près de chez toi",
      continue: "Continuer.*",
    },
    location: {
      allow: "Lorsque vous utilisez l'appli",
      deny: "Ne pas autoriser",
    },
    age: {
      question: "Pour commencer, peux-tu nous dire ton âge ?",
      options: {
        age16OrLess: "J’ai 16 ans ou moins",
        age17: "J’ai 17 ans",
        age18: "J’ai 18 ans",
        age19OrMore: "J’ai 19 ans ou plus",
      },
    },
    end: {
      patience: "Encore un peu de patience !",
      accessCatalogue: "Accéder au catalogue",
      enjoy17: "À 17 ans, profite de ton pass Culture !",
      enjoy18: "À 18 ans, profite de ton pass Culture !",
      explore: "Explore, découvre, profite",
    },
  },
  booking: {
    wording: "Réserver l’offre",
    detailsTitle: "Détails de la réservation",
    info: "Informations",
    location: "Lieu de retrait",
    cancelConditions: "Conditions d’annulation",
    useConditions: "Conditions d’utilisation",
    generalConditions: "Nos conditions générales d’utilisation",
    closeModal: "Fermer la modale",
    stickyButtonId: "sticky-booking-button",
  },
  auth: {
    login: {
      title: "Connecte-toi",
      button: "Se connecter",
      emailId: "Entrée pour l’email",
      passwordId: "Mot de passe",
      showPasswordId: "Afficher le mot de passe",
      wrongCredentialsError: ".*E-mail ou mot de passe incorrect.*",
    },
    logout: {
      button: "Déconnexion",
      footer: "République Française - Liberté Égalité Fraternité",
    },
    signup: {
      title: "Inscription",
    },
    modal: {
      share: "Partager l’appli",
      activationNews: ".*Bonne nouvelle.*",
      continue: ".*Continuer.*",
      takeMinute: "Prends 1 minute",
    },
  },
  profil: {
    settings: "Paramètres du compte",
    tabBar: {
      profil: "Mon profil.*",
      home: "Accueil.*",
    },
    helpCenter: {
      title: "Aide",
      searchInfo: "Nouvelle fenêtre : Chercher une info",
      unloggedFallback: "Utiliser l'appli sans compte",
      backToPass: "Revenir à pass Culture S",
    },
    chatbot: {
      askQuestion: "Poser une question",
      virtualAssistant: "Assistant virtuel du pass culture",
    },
    accessibility: {
      title: "Accessibilité",
      sitemap: "Plan du site",
      commitments: "Nouvelle fenêtre : Les engagements du pass Culture",
      passAccessibility: "L'accessibilité au pass Culture",
      multiannualScheme: "Nouvelle fenêtre : Schéma pluriannuel",
      multiannualSchemeTitle: "Schéma pluriannuel.*",
      introduction: "Introduction",
      declarationAndroid: "Déclaration d’accessibilité - Android",
      declarationIos: "Déclaration d’accessibilité - iOS",
      declarationWeb: "Déclaration d’accessibilité - web",
      declarationWebTitle: "Déclaration d’accessibilité web",
      recommendedPathsWeb: "Parcours recommandés - web",
      recommendedPathsWebTitle: "Parcours recommandés web",
    },
    legal: {
      share: "Partager le pass Culture",
      title: "Informations légales",
      cgu: "Conditions Générales d’Utilisation",
      privacyPolicy: "Charte des données personnelles",
      others: "Autres",
      welcomeGreeting: "Bonjour Test-e2e.*",
    },
    confidentiality: {
      title: "Confidentialité",
      settings: "Paramètres de confidentialité",
    },
    social: {
      version: "Version.*",
      instagram: "Instagram",
      x: "X",
      tiktok: "Tiktok",
      facebook: "Facebook",
      chromeAccept: "Accepter et continuer",
    },
    deletion: {
      personalInfo: "Informations personnelles",
      fullName: "Prénom et nom",
      email: "Adresse e-mail",
      phone: "Numéro de téléphone",
      password: "Mot de passe",
      deleteAccount: "Supprimer mon compte",
      deleteReasonQuestion: "Pourquoi souhaites-tu supprimer ton compte ?",
      reasonDifferentEmail: "J’aimerais créer un compte avec une adresse e-mail différente",
      modifyEmailInfo: "Modifie ton adresse e-mail sur ce compte",
      iUnderstand: "J’ai compris",
      modifyEmail: "Modifier mon e-mail",
      validateModifyEmail: "Valider la demande de modification de mon e-mail",
      noLongerUseApp: "Je n’utilise plus l’application",
      noCredit: "Je n’ai plus de crédit ou très peu de crédit restant",
      deletePersonalData: "Je souhaite supprimer mes données personnelles",
      other: "Autre",
      someoneElseAccess: "Je pense que quelqu’un d’autre a accès à mon compte",
      secureAccount: "Sécurise ton compte",
      suspendAccount: "Suspendre mon compte",
      dontSecureAccount: "Ne pas sécuriser mon compte",
      contactSupport: "Contacte le support",
      contactSupportButton: "Contacter le support",
      backToProfile: "Retourner au profil",
      notAllowedTitle: "Nous ne pouvons pas encore supprimer ton compte",
      backToProfileButton: "Retourner sur mon profil",
      disableNotifications: "Désactiver mes notifications",
    },
  },
  favorite: {
    title: "Mes favoris",
    tabBar: "Mes favoris.*",
    emptyButton: "Découvrir le catalogue",
    deleteButton: "Supprimer.*",
    sortButton: "Trier",
    sortTitle: "Trier par",
    sortRecentlyAdded: ".*Ajouté récemment.*",
    sortPriceAsc: ".*Prix croissant.*",
    sortProximity: ".*Proximité géographique.*",
    validate: "Valider",
    count: ".* favori.*",
    emptyText: "Retrouve toutes tes offres en un clin d’oeil",
    unloggedTitle: "Identifie-toi pour retrouver tes favoris",
    addFavoriteId: "Mettre en favori",
    removeFavoriteId: "Retirer des favoris",
    location: {
      activate: "Activer la géolocalisation",
      permissions: "Autorisations",
      position: "Position",
      allowWhileUsing: "Autoriser seulement si l'appli est utilisée",
    },
  },
  search: {
    title: "Rechercher",
    musicCategory: {
      ios: "Catégorie Musique.*",
      android: "MUSIQUE",
    },
    cds: "CDs",
    myPosition: "Ma position",
    franceEntire: "Localisation – Liste - Élément 3 sur 3 - France entière.*",
    offersTitle: "Les offres",
    cdType: "CD",
    cinemaTitle: "Cinéma",
  },
}
