import { Environment } from 'libs/environment/types'
export const env: Environment = {
  ACCESSIBILITY_LINK: 'https://passculture.accessibility',
  ALGOLIA_APPLICATION_ID: 'algoliaAppId',
  ALGOLIA_OFFERS_INDEX_NAME: 'algoliaOffersIndexName',
  ALGOLIA_SEARCH_API_KEY: 'algoliaApiKey',
  ALGOLIA_VENUES_INDEX_NAME: 'algoliaVenuesIndexName',
  ALGOLIA_SUGGESTIONS_INDEX_NAME: 'algoliaSuggestionsIndexName',
  AMPLITUDE_API_KEY: 'amplitudeApiKey',
  ANDROID_APP_ID: 'app.android',
  API_BASE_URL: 'https://localhost',
  APPLE_STORE_URL: 'https://apps.apple.com/fr/app/pass-culture/id1557887412',
  APPS_FLYER_DEV_KEY: 'appsFlyerDevKey',
  BOOKING_LIMIT_EXCEEDED_URL: 'https://aide.passculture.app/hc/fr/articles/4411991975825',
  CGU_LINK: 'https://passculture.cgu',
  CONTENTFUL_ACCESS_TOKEN: 'accessToken',
  CONTENTFUL_ENVIRONMENT: 'environment',
  CONTENTFUL_SPACE_ID: 'contentfulSpaceId',
  COOKIES_POLICY_LINK: 'https://passculture.cookies',
  CULTURAL_SURVEY_TYPEFORM_ID: 'TYPEFORM_FORM_ID',
  DATA_PRIVACY_CHART_LINK: 'https://passculture.data-privacy-chart',
  DOC_CGU_URL:
    'https//docs.passculture.app/textes-normatifs/mentions-legales-et-conditions-generales-dutilisation-de-lapplication-pass-culture',
  DOC_PERSONAL_DATA_URL:
    'https://docs.passculture.app/textes-normatifs/charte-des-donnees-personnelles',
  DSM_URL: 'https://www.demarches-simplifiees.fr/commencer/inscription-pass-culture',
  DMS_FRENCH_CITIZEN_URL: 'https://dmsfrenchcitizen',
  DMS_FOREIGN_CITIZEN_URL: 'https://dmsforeigncitizen',
  EDUCONNECT_ALLOWED_DOMAIN: 'https://educoco_alloweddodo',
  ENABLE_WHY_DID_YOU_RENDER: false,
  ENV: 'testing',
  FAQ_LINK: 'https://passculture.faq',
  FAQ_LINK_DELETE_ACCOUNT: 'https://passculture-delete-account.faq',
  FAQ_LINK_EDUCONNECT_URL: 'https://passculture-educonnect.faq',
  FAQ_LINK_RESET_PASSORD_EMAIL_NOT_RECEIVED: 'https://passculture-reset-password.faq',
  FAQ_LINK_SIGNUP_CONFIRMATION_EMAIL_NOT_RECEIVED: 'https://passculture-confirmation-email.faq',
  FEATURE_FLIPPING_ONLY_VISIBLE_ON_TESTING: true,
  FIREBASE_APIKEY: 'FIREBASE_APIKEY',
  FIREBASE_APPID: 'BATCH_VAPID_PUBLIC_KEY',
  FIREBASE_AUTHDOMAIN: 'FIREBASE_APPID',
  FIREBASE_DYNAMIC_LINK_DOMAIN: 'passcultureapptesting.page.link',
  FIREBASE_MESSAGINGSENDERID: 'FIREBASE_MESSAGINGSENDERID',
  FIREBASE_PROJECTID: 'FIREBASE_PROJECTID',
  FIREBASE_STORAGEBUCKET: 'FIREBASE_STORAGEBUCKET',
  GCP_IMAGE_COULD_STORAGE_NAME: 'localhost-storage-v2',
  GOOGLE_PLAY_STORE_URL:
    'https://play.google.com/store/apps/details?id=app.passculture.webapp&hl=fr',
  IOS_APP_ID: 'app.ios',
  IOS_APP_STORE_ID: '1557887412',
  PASSCULTURE_DOWNLOAD_APP_URL: 'https://pass.culture.fr/nosapplications/',
  PRIVACY_POLICY_LINK: 'https://passculture.privacy',
  PUBLIC_URL: 'https://web.example.com',
  RECOMMENDATION_ENDPOINT: 'https://recommmendation-endpoint',
  RECOMMENDATION_TOKEN: 'recommmendation-token',
  RESIZE_IMAGE_ON_DEMAND_URL: 'https://image-resizing-dot-passculture-metier-ehp.ew.r.appspot.com',
  SENTRY_DSN: 'SENTRY_DSN',
  SIGNIN_IDENTIFIER: '',
  SIGNIN_PASSWORD: '',
  SIGNUP_POSTAL_CODE: '',
  SITE_KEY: 'SITE_KEY',
  SUPPORT_EMAIL_ADDRESS: 'support@test.passculture.app',
  FRAUD_EMAIL_ADDRESS: 'service.fraude@test.passculture.app',
  TMX_FPSERVER: 'test.pc',
  TMX_ORGID: 'xyzt',
  URL_PREFIX: 'passculture',
  WEBAPP_V2_DOMAIN: 'webapp-v2.example.com',
  COMMIT_HASH: '13371337',
  BRANCH: 'master',
  LAST_COMMIT_DATETIME: '2022-02-18T18:29:01+01:00',
}
