/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import type { Meta, StoryObj } from '@storybook/react-vite'
import React from 'react'

import { illustrations } from 'ui/designSystem/illustrations'
import { AssetGridTemplate } from 'ui/storybook/AssetGridTemplate'

const meta: Meta = {
  title: 'Design System/Illustrations',
}

export default meta

type Story = StoryObj

export const Gallery: Story = {
  render: () => <AssetGridTemplate title="Illustrations" images={illustrations} isIllustration />,
}
