import { PathConfigMap } from '@react-navigation/native/lib/typescript/src'

import { SubscriptionStackParamList } from 'features/navigation/SubscriptionStackNavigator/types'

export const subscriptionStackNavigatorPathConfig: PathConfigMap<SubscriptionStackParamList> = {
  CulturalSurveyIntro: 'questionnaire-pratiques-initiales/introduction',
  CulturalSurveyQuestions: 'questionnaire-pratiques-initiales/questions',
  CulturalSurveyThanks: 'questionnaire-pratiques-initiales/merci',
  FAQWebview: 'questionnaire-pratiques-initiales/foire-aux-questions',
  Stepper: 'verification-identite',
  DisableActivation: 'creation-compte/desactivation',
  SetPhoneNumberWithoutValidation: 'creation-compte/telephone-sans-validation',
  SetPhoneNumber: 'creation-compte/telephone',
  SetPhoneValidationCode: 'creation-compte/code-de-validation-telephone',
  PhoneValidationTooManyAttempts: 'creation-compte/code-de-validation-trop-d-essais',
  PhoneValidationTooManySMSSent: 'creation-compte/code-de-validation-trop-de-sms',
  SetName: 'creation-profil/nom-prenom',
  SetCity: 'creation-profil/ville',
  SetAddress: 'creation-profil/adresse',
  SetStatus: 'verification-identite/profil/statut',
  SetProfileBookingError: 'verification-identite/profil/statut/erreur',
  ProfileInformationValidationCreate: 'verification-identite/profil/validation-informations',
  UbbleWebview: 'identification/verification-manuelle-piece-identite',
  EduConnectForm: 'educonnect-formulaire',
  EduConnectValidation: 'educonnect/validation',
  IdentityCheckEnd: 'verification-identite/fin',
  IdentityCheckUnavailable: 'verification-identite/verification-indisponible',
  IdentityCheckPending: 'verification-identite/demande-en-attente',
  IdentityCheckDMS: 'verification-identite/demarches-simplifiees',
  IdentificationFork: 'identification/fourche',
  IdentityCheckHonor: 'confirmation',
  BeneficiaryRequestSent: 'demande-beneficiaire-envoyee',
  BeneficiaryAccountCreated: 'creation-compte/confirmation-beneficiaire',
  EduConnectErrors: 'educonnect/erreur',
  DMSIntroduction: 'identification/redirection-demarches-simplifiees',
  ExpiredOrLostID: 'identification/document-identite-perdu-ou-expire',
  SelectIDOrigin: 'identification/origine-document-identite',
  SelectIDStatus: 'identification/statut-document-identite',
  SelectPhoneStatus: 'identification/statut-telephone',
  ComeBackLater: 'identification/reviens-plus-tard',
  BonificationIntroduction: 'bonification/introduction',
  BonificationNames: 'bonification/noms',
  BonificationTitle: 'bonification/civilite',
  BonificationBirthDate: 'bonification/date-de-naissance',
  BonificationBirthPlace: 'bonification/lieu-de-naissance',
  BonificationRecap: 'bonification/resume',
  BonificationError: 'bonification/erreur',
  BonificationGranted: 'bonification/accordee',
  BonificationRefused: 'bonification/refuse',
}
