/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import { DefaultTheme } from 'styled-components/native'

import { LinkSize } from './types'

const iconSizeByLinkSize = ({ theme }: { theme: DefaultTheme }): Record<LinkSize, number> => ({
  default: theme.icons.sizes.smaller,
  small: theme.icons.sizes.extraSmall,
  extraSmall: theme.icons.sizes.extraSmall,
})

export const getIconSize = ({ size, theme }: { size: LinkSize; theme: DefaultTheme }) =>
  iconSizeByLinkSize({ theme })[size]
