/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import { computedTheme } from 'tests/computedTheme'

import { getLinkIconColor } from './getLinkIconColor'

describe('getLinkIconColor', () => {
  it.each([
    ['brand', undefined, undefined, computedTheme.designSystem.color.icon.brandPrimary],
    ['neutral', undefined, undefined, computedTheme.designSystem.color.icon.default],
    ['brand', true, undefined, computedTheme.designSystem.color.icon.brandPrimaryHover],
    ['neutral', true, undefined, computedTheme.designSystem.color.icon.brandPrimaryHover],
    ['brand', undefined, true, computedTheme.designSystem.color.icon.brandSecondaryHover],
    ['neutral', undefined, true, computedTheme.designSystem.color.icon.brandSecondaryHover],
  ] as const)(
    'should return the expected icon color for color=%s, hovered=%s, visited=%s',
    (color, hovered, visited, expectedColor) => {
      expect(getLinkIconColor({ color, hovered, visited, theme: computedTheme })).toBe(
        expectedColor
      )
    }
  )
})
