/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React from 'react'
import webStyled, { CSSObject, DefaultTheme, useTheme } from 'styled-components'

import { ExternalSiteFilled } from 'ui/svg/icons/ExternalSiteFilled'

import { getIconSize } from './getIconSize'
import { getLinkGap } from './getLinkGap'
import { getLinkTextColor } from './getLinkTextColor'
import { getLinkTypography } from './getLinkTypography'
import { LinkAnchor } from './LinkAnchor.web'
import { LinkProps, LinkSize } from './types'

type LinkAnchorComponentProps = React.ComponentProps<typeof LinkAnchor> & {
  style?: unknown
}

export const Link = ({
  label,
  size = 'default',
  color = 'brand',
  icon,
  isExternal = false,
  textColor,
  testID,
  accessibilityLabel,
  ...props
}: LinkProps) => {
  const theme = useTheme()
  const Icon = icon ?? (isExternal ? ExternalSiteFilled : undefined)
  const iconSize = getIconSize({ size, theme })
  const iconColor = textColor ?? getLinkTextColor({ color, theme })
  const { href, style: _style, ...anchorProps } = props as unknown as LinkAnchorComponentProps

  return (
    <Container
      {...anchorProps}
      accessibilityLabel={accessibilityLabel ?? getAccessibilityLabel({ isExternal, label })}
      color={color}
      href={href ?? '#'}
      testID={testID}>
      <InlineContent size={size}>
        {Icon ? <Icon color={iconColor} size={iconSize} testID="link-icon" aria-hidden /> : null}
        <Text data-testid="link-label" size={size} color={color} textColor={textColor}>
          {label}
        </Text>
      </InlineContent>
    </Container>
  )
}

function getAccessibilityLabel({ isExternal, label }: { isExternal: boolean; label: string }) {
  return isExternal ? `Nouvelle fenêtre\u00a0: ${label}` : label
}

const getContainerStyle = ({
  theme,
  color,
}: {
  theme: DefaultTheme
  color: LinkProps['color']
}): CSSObject => ({
  alignItems: 'center',
  columnGap: theme.designSystem.size.spacing.s,
  display: 'inline-flex',
  flexDirection: 'row',
  width: 'fit-content',
  ['&:hover span']: {
    color: getLinkTextColor({ color: color ?? 'brand', hovered: true, theme }),
  },
  ['&:visited span']: {
    color: getLinkTextColor({ color: color ?? 'brand', visited: true, theme }),
  },
})

const Container = webStyled(LinkAnchor)<{
  color: LinkProps['color']
}>(getContainerStyle)

const InlineContent = webStyled.span<{ size: LinkSize }>(({ theme, size }) => ({
  alignItems: 'center',
  columnGap: getLinkGap({ size, theme }),
  display: 'inline-flex',
  flexDirection: 'row',
}))

const Text = webStyled.span<{
  size: LinkSize
  color: LinkProps['color']
  textColor?: LinkProps['textColor']
}>(({ theme, size, color = 'brand', textColor }) => ({
  color: textColor ?? getLinkTextColor({ color, theme }),
  textDecoration: 'underline',
  ...theme.designSystem.typography[getLinkTypography(size)],
}))
