/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import type { Meta } from '@storybook/react-vite'
import React from 'react'
import styled from 'styled-components/native'

import { VariantsTemplate, type Variants, type VariantsStory } from 'ui/storybook/VariantsTemplate'

import { Link } from './Link'

const meta: Meta<typeof Link> = {
  title: 'design system/Link',
  component: Link,
}
export default meta

const variantConfig: Variants<typeof Link> = [
  {
    label: 'Brand default',
    props: { label: 'Label explicite du lien', externalNav: { url: 'https://passculture.app' } },
  },
  {
    label: 'Brand small',
    props: {
      label: 'Label explicite du lien',
      externalNav: { url: 'https://passculture.app' },
      size: 'small',
    },
  },
  {
    label: 'Brand extraSmall',
    props: {
      label: 'Label explicite du lien',
      externalNav: { url: 'https://passculture.app' },
      size: 'extraSmall',
    },
  },
  {
    label: 'Neutral default',
    props: {
      label: 'Label explicite du lien',
      navigateTo: { screen: 'TabNavigator', params: { screen: 'Home' } },
      color: 'neutral',
    },
  },
  {
    label: 'Without icon',
    props: {
      label: 'Label explicite du lien',
      navigateTo: { screen: 'TabNavigator', params: { screen: 'Home' } },
      showIcon: false,
    },
  },
]

const AlignStart = styled.View({
  alignItems: 'flex-start',
})

const AlignedLink = (props: React.ComponentProps<typeof Link>) => (
  <AlignStart>
    <Link {...props} />
  </AlignStart>
)

export const Template: VariantsStory<typeof AlignedLink> = {
  name: 'Link',
  render: (props) => (
    <VariantsTemplate variants={variantConfig} Component={AlignedLink} defaultProps={props} />
  ),
}
