/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React from 'react'

import { openUrl } from 'features/navigation/helpers/openUrl'
import { AccessibilityRole } from 'libs/accessibilityRole/accessibilityRole'
import { render, screen, userEvent } from 'tests/utils'
import { theme } from 'theme'

import { Link } from './Link'

jest.mock('features/navigation/helpers/openUrl')

const user = userEvent.setup()
jest.useFakeTimers()

describe('<Link />', () => {
  it('should render an accessible link', () => {
    render(<Link label="Documentation" externalNav={{ url: 'https://example.com' }} />)

    expect(screen.getByRole(AccessibilityRole.LINK)).toBeOnTheScreen()
    expect(screen.getByLabelText('Nouvelle fenêtre\u00a0: Documentation')).toBeOnTheScreen()
  })

  it('should open href when pressed', async () => {
    render(<Link label="Documentation" externalNav={{ url: 'https://example.com' }} />)

    await user.press(screen.getByRole(AccessibilityRole.LINK))

    expect(openUrl).toHaveBeenCalledWith('https://example.com', undefined, true)
  })

  it('should use link small typography when size is small', () => {
    render(<Link label="Documentation" externalNav={{ url: 'https://example.com' }} size="small" />)

    expect(screen.getByTestId('link-label')).toHaveStyle({
      fontFamily: theme.designSystem.typography.linkS.fontFamily,
      fontSize: Number.parseFloat(theme.designSystem.typography.linkS.fontSize),
      lineHeight: Number.parseFloat(theme.designSystem.typography.linkS.lineHeight),
    })
  })

  it('should use link extra small typography when size is extraSmall', () => {
    render(
      <Link label="Documentation" externalNav={{ url: 'https://example.com' }} size="extraSmall" />
    )

    expect(screen.getByTestId('link-label')).toHaveStyle({
      fontFamily: theme.designSystem.typography.linkXs.fontFamily,
      fontSize: Number.parseFloat(theme.designSystem.typography.linkXs.fontSize),
      lineHeight: Number.parseFloat(theme.designSystem.typography.linkXs.lineHeight),
    })
  })

  it('should use neutral color when color is neutral', () => {
    render(
      <Link label="Documentation" externalNav={{ url: 'https://example.com' }} color="neutral" />
    )

    expect(screen.getByTestId('link-label')).toHaveStyle({
      color: theme.designSystem.color.text.default,
    })
  })

  it('should hide icon when showIcon is false and link does not open in a new tab', () => {
    render(
      <Link
        label="Documentation"
        navigateTo={{ screen: 'TabNavigator', params: { screen: 'Home' } }}
        showIcon={false}
      />
    )

    expect(screen.queryByTestId('link-icon')).not.toBeOnTheScreen()
  })
})
