/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import userEvent from '@testing-library/user-event'
import React from 'react'

import { render, screen } from 'tests/utils/web'
import { ExternalTouchableLink } from 'ui/components/touchableLink/ExternalTouchableLink'
import { InternalTouchableLink } from 'ui/components/touchableLink/InternalTouchableLink'
import { Profile } from 'ui/svg/icons/Profile'

import { Link } from './Link'

jest.mock('features/navigation/helpers/openUrl')

describe('<Link />', () => {
  it('should render an anchor with href', () => {
    render(
      <ExternalTouchableLink
        as={Link}
        label="Documentation"
        externalNav={{ url: 'https://example.com' }}
        isExternal
      />
    )

    expect(
      screen.getByRole('link', { name: 'Nouvelle fenêtre\u00a0: Documentation' })
    ).toHaveAttribute('href', 'https://example.com')
  })

  it('should open external href in a new tab', () => {
    render(
      <ExternalTouchableLink
        as={Link}
        label="Documentation"
        externalNav={{ url: 'https://example.com' }}
        isExternal
      />
    )

    const link = screen.getByRole('link')

    expect(link.closest('a')).toHaveAttribute('target', '_blank')
    expect(link).not.toHaveTextContent('ouvre un nouvel onglet')
    expect(screen.getByTestId('link-icon')).toBeInTheDocument()
  })

  it('should call onBeforeNavigate when clicked', async () => {
    const onBeforeNavigate = jest.fn()
    render(
      <ExternalTouchableLink
        as={Link}
        label="Documentation"
        externalNav={{ url: 'https://example.com' }}
        onBeforeNavigate={onBeforeNavigate}
      />
    )

    await userEvent.click(screen.getByRole('link'))

    expect(onBeforeNavigate).toHaveBeenCalledTimes(1)
  })

  it('should not open internal link in a new tab', () => {
    render(
      <InternalTouchableLink
        as={Link}
        label="Documentation"
        navigateTo={{ screen: 'TabNavigator', params: { screen: 'Home' } }}
      />
    )

    expect(screen.getByRole('link')).not.toHaveAttribute('target')
  })

  it('should render custom icon', () => {
    render(
      <InternalTouchableLink
        as={Link}
        label="Documentation"
        navigateTo={{ screen: 'TabNavigator', params: { screen: 'Home' } }}
        icon={Profile}
      />
    )

    expect(screen.getByTestId('link-icon')).toBeInTheDocument()
  })
})
