/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React from 'react'
import { PixelRatio } from 'react-native'

import { openUrl } from 'features/navigation/helpers/openUrl'
import { render, screen, userEvent } from 'tests/utils'
import { theme } from 'theme'
import { ExternalTouchableLink } from 'ui/components/touchableLink/ExternalTouchableLink'
import { InternalTouchableLink } from 'ui/components/touchableLink/InternalTouchableLink'
import { Connect } from 'ui/svg/icons/Connect'

import { Link } from './Link'

jest.mock('features/navigation/helpers/openUrl')

const user = userEvent.setup()
const getFontScaleSpy = jest.spyOn(PixelRatio, 'getFontScale')
jest.useFakeTimers()

describe('<Link />', () => {
  beforeEach(() => {
    getFontScaleSpy.mockReturnValue(1)
  })

  afterEach(() => {
    getFontScaleSpy.mockClear()
  })

  it('should render an accessible link', () => {
    render(
      <ExternalTouchableLink
        as={Link}
        label="Documentation"
        externalNav={{ url: 'https://example.com' }}
        isExternal
      />
    )

    expect(screen.getByLabelText('Nouvelle fenêtre\u00a0: Documentation')).toBeOnTheScreen()
  })

  it('should open href when pressed', async () => {
    render(
      <ExternalTouchableLink
        as={Link}
        label="Documentation"
        externalNav={{ url: 'https://example.com' }}
        isExternal
      />
    )

    await user.press(screen.getByText('Documentation'))

    expect(openUrl).toHaveBeenCalledWith('https://example.com', undefined, true)
  })

  it('should use link small typography when size is small', () => {
    render(<Link label="Documentation" size="small" />)

    expect(screen.getByTestId('link-label')).toHaveStyle({
      fontFamily: theme.designSystem.typography.linkS.fontFamily,
      fontSize: Number.parseFloat(theme.designSystem.typography.linkS.fontSize),
      lineHeight: Number.parseFloat(theme.designSystem.typography.linkS.lineHeight),
    })
  })

  it('should use link extra small typography when size is extraSmall', () => {
    render(<Link label="Documentation" size="extraSmall" />)

    expect(screen.getByTestId('link-label')).toHaveStyle({
      fontFamily: theme.designSystem.typography.linkXs.fontFamily,
      fontSize: Number.parseFloat(theme.designSystem.typography.linkXs.fontSize),
      lineHeight: Number.parseFloat(theme.designSystem.typography.linkXs.lineHeight),
    })
  })

  it('should use neutral color when color is neutral', () => {
    render(<Link label="Documentation" color="neutral" />)

    expect(screen.getByTestId('link-label')).toHaveStyle({
      color: theme.designSystem.color.text.default,
    })
  })

  it('should render default external icon', () => {
    render(<Link label="Documentation" isExternal />)

    expect(screen.getByTestId('link-icon')).toBeOnTheScreen()
  })

  it('should scale icon with font scale', () => {
    getFontScaleSpy.mockReturnValueOnce(2)

    render(<Link label="Documentation" isExternal />)

    const baseIconSize = theme.designSystem.size.icon.m

    expect(screen.getByTestId('link-icon')).toHaveProp('width', baseIconSize * 2)
    expect(screen.getByTestId('link-icon')).toHaveProp('height', baseIconSize * 2)
  })

  it('should align scaled icon with scaled line height', () => {
    getFontScaleSpy.mockReturnValueOnce(2)

    render(<Link label="Documentation" isExternal />)

    const iconSize = theme.designSystem.size.icon.m * 2
    const lineHeight = Number.parseFloat(theme.designSystem.typography.link.lineHeight) * 2

    expect(screen.getByTestId('link-icon-container')).toHaveStyle({
      paddingTop: (lineHeight - iconSize) / 2,
    })
  })

  it('should render custom icon', () => {
    render(
      <InternalTouchableLink
        as={Link}
        label="Documentation"
        navigateTo={{ screen: 'TabNavigator', params: { screen: 'Home' } }}
        icon={Connect}
      />
    )

    expect(screen.getByTestId('link-icon')).toBeOnTheScreen()
  })
})
