/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React from 'react'
import styled, { useTheme } from 'styled-components/native'

import { ColorsType } from 'theme/types'
import { ExternalTouchableLink } from 'ui/components/touchableLink/ExternalTouchableLink'
import { InternalTouchableLink } from 'ui/components/touchableLink/InternalTouchableLink'
import {
  ExternalTouchableLinkProps,
  InternalTouchableLinkProps,
} from 'ui/components/touchableLink/types'
import { ExternalSiteFilled } from 'ui/svg/icons/ExternalSiteFilled'

import { getIconSize } from './getIconSize'
import { getLinkTextColor } from './getLinkTextColor'
import { getLinkTypography } from './getLinkTypography'
import { LinkProps, LinkSize } from './types'

export function Link({
  label,
  size = 'default',
  color = 'brand',
  showIcon = true,
  accessibilityLabel,
  testID,
  ...navigationProps
}: LinkProps) {
  const theme = useTheme()
  const isExternal = 'externalNav' in navigationProps
  const textColor = getLinkTextColor({ color, theme })
  const iconSize = getIconSize({ size, theme })
  const computedAccessibilityLabel =
    accessibilityLabel ?? (isExternal ? `Nouvelle fenêtre\u00a0: ${label}` : label)
  const content = (
    <Content>
      {showIcon || isExternal ? (
        <Icon color={textColor} size={iconSize} testID="link-icon" />
      ) : null}
      <StyledText testID="link-label" size={size} textColor={textColor}>
        {label}
      </StyledText>
    </Content>
  )

  if (isExternal) {
    return (
      <StyledExternalTouchableLink
        {...(navigationProps as ExternalTouchableLinkProps)}
        accessibilityLabel={computedAccessibilityLabel}
        testID={testID}>
        {content}
      </StyledExternalTouchableLink>
    )
  }

  return (
    <StyledInternalTouchableLink
      {...(navigationProps as InternalTouchableLinkProps)}
      accessibilityLabel={computedAccessibilityLabel}
      testID={testID}>
      {content}
    </StyledInternalTouchableLink>
  )
}

const Content = styled.View(({ theme }) => ({
  flexDirection: 'row',
  alignItems: 'center',
  columnGap: theme.designSystem.size.spacing.s,
}))

const StyledText = styled.Text<{
  size: LinkSize
  textColor: ColorsType
}>(({ theme, size, textColor }) => ({
  ...theme.designSystem.typography[getLinkTypography(size)],
  color: textColor,
  textDecorationLine: 'underline',
}))

const Icon = styled(ExternalSiteFilled).attrs<{ color: ColorsType; size: number }>(
  ({ color, size }) => ({
    color,
    size,
  })
)``

const StyledExternalTouchableLink = styled(ExternalTouchableLink)({
  alignSelf: 'flex-start',
})

const StyledInternalTouchableLink = styled(InternalTouchableLink)({
  alignSelf: 'flex-start',
})
