/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React from 'react'
import { PixelRatio } from 'react-native'
import styled, { useTheme } from 'styled-components/native'

import { ColorsType } from 'theme/types'
import { TouchableOpacity } from 'ui/components/TouchableOpacity'

import { getIconSize } from './getIconSize'
import { getLinkGap } from './getLinkGap'
import { getLinkIconColor } from './getLinkIconColor'
import { getLinkTextColor } from './getLinkTextColor'
import { getLinkTypography } from './getLinkTypography'
import { LinkProps, LinkSize } from './types'

export function Link({
  label,
  wording,
  size = 'default',
  color = 'brand',
  icon,
  isExternal = false,
  isInsideText = false,
  textColor,
  accessibilityLabel,
  accessibilityRole,
  onPress,
  onLongPress,
  testID,
  ...props
}: LinkProps) {
  const computedLabel = label ?? wording ?? ''
  const theme = useTheme()
  const linkTextColor = textColor ?? getLinkTextColor({ color, theme })
  const linkIconColor = getLinkIconColor({ color, theme })
  const Icon = icon
  const fontScale = PixelRatio.getFontScale()
  const iconSize = getIconSize({ size, theme }) * fontScale
  const computedAccessibilityLabel =
    accessibilityLabel ?? getAccessibilityLabel({ isExternal, label: computedLabel })

  if (isInsideText) {
    return (
      <InlineText
        onPress={onPress}
        onLongPress={onLongPress}
        accessibilityRole={accessibilityRole}
        accessibilityLabel={
          accessibilityLabel ??
          getInsideTextAccessibilityLabel({
            accessibilityRole,
            isExternal,
            label: computedLabel,
          })
        }
        testID={testID}
        $size={size}
        $textColor={linkTextColor}>
        {computedLabel}
      </InlineText>
    )
  }

  return (
    <Container
      {...props}
      onPress={onPress}
      onLongPress={onLongPress}
      accessibilityRole={accessibilityRole}
      accessibilityLabel={computedAccessibilityLabel}
      testID={testID}>
      <Content size={size}>
        {Icon ? (
          <IconContainer
            fontScale={fontScale}
            iconSize={iconSize}
            size={size}
            testID="link-icon-container">
            <Icon color={linkIconColor} size={iconSize} testID="link-icon" />
          </IconContainer>
        ) : null}
        <StyledText testID="link-label" size={size} textColor={linkTextColor}>
          {computedLabel}
        </StyledText>
      </Content>
    </Container>
  )
}

function getAccessibilityLabel({ isExternal, label }: { isExternal: boolean; label: string }) {
  return isExternal ? `Nouvelle fenêtre\u00a0: ${label}` : label
}

function getInsideTextAccessibilityLabel({
  accessibilityRole,
  isExternal,
  label,
}: {
  accessibilityRole?: LinkProps['accessibilityRole']
  isExternal: boolean
  label: string
}) {
  return isExternal || accessibilityRole === 'link' ? `${label}, lien externe` : label
}

const Container = styled(TouchableOpacity)({
  flexShrink: 1,
  maxWidth: '100%',
  minWidth: 0,
})

const Content = styled.View<{ size: LinkSize }>(({ theme, size }) => ({
  flexDirection: 'row',
  alignItems: 'flex-start',
  columnGap: getLinkGap({ size, theme }),
  flexShrink: 1,
  maxWidth: '100%',
  minWidth: 0,
}))

const IconContainer = styled.View<{
  fontScale: number
  iconSize: number
  size: LinkSize
}>(({ theme, fontScale, iconSize, size }) => {
  const lineHeight = Number.parseFloat(
    theme.designSystem.typography[getLinkTypography(size)].lineHeight
  )
  const scaledLineHeight = lineHeight * fontScale

  return {
    paddingTop: Math.max((scaledLineHeight - iconSize) / 2, 0),
  }
})

const StyledText = styled.Text<{
  size: LinkSize
  textColor: ColorsType
}>(({ theme, size, textColor }) => ({
  ...theme.designSystem.typography[getLinkTypography(size)],
  color: textColor,
  flexShrink: 1,
  minWidth: 0,
  textDecorationLine: 'underline',
}))

const InlineText = styled.Text<{
  $size: LinkSize
  $textColor: ColorsType
}>(({ theme, $size, $textColor }) => ({
  ...theme.designSystem.typography[getLinkTypography($size)],
  color: $textColor,
  cursor: 'pointer',
  textDecorationLine: 'underline',
}))
