/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import React from 'react'
import styled, { useTheme } from 'styled-components/native'

import { ColorsType } from 'theme/types'
import { TouchableOpacity } from 'ui/components/TouchableOpacity'
import { ExternalSiteFilled } from 'ui/svg/icons/ExternalSiteFilled'

import { getIconSize } from './getIconSize'
import { getLinkGap } from './getLinkGap'
import { getLinkTextColor } from './getLinkTextColor'
import { getLinkTypography } from './getLinkTypography'
import { LinkProps, LinkSize } from './types'

export function Link({
  label,
  size = 'default',
  color = 'brand',
  icon,
  isExternal = false,
  textColor,
  accessibilityLabel,
  ...props
}: LinkProps) {
  const theme = useTheme()
  const linkTextColor = textColor ?? getLinkTextColor({ color, theme })
  const Icon = icon ?? (isExternal ? ExternalSiteFilled : undefined)
  const iconSize = getIconSize({ size, theme })

  return (
    <Container
      {...props}
      accessibilityLabel={accessibilityLabel ?? getAccessibilityLabel({ isExternal, label })}>
      <Content size={size}>
        {Icon ? (
          <IconContainer iconSize={iconSize} size={size}>
            <Icon color={linkTextColor} size={iconSize} testID="link-icon" />
          </IconContainer>
        ) : null}
        <StyledText testID="link-label" size={size} textColor={linkTextColor}>
          {label}
        </StyledText>
      </Content>
    </Container>
  )
}

function getAccessibilityLabel({ isExternal, label }: { isExternal: boolean; label: string }) {
  return isExternal ? `Nouvelle fenêtre\u00a0: ${label}` : label
}

const Container = styled(TouchableOpacity)({
  flexShrink: 1,
  maxWidth: '100%',
  minWidth: 0,
})

const Content = styled.View<{ size: LinkSize }>(({ theme, size }) => ({
  flexDirection: 'row',
  alignItems: 'flex-start',
  columnGap: getLinkGap({ size, theme }),
  flexShrink: 1,
  maxWidth: '100%',
  minWidth: 0,
}))

const IconContainer = styled.View<{
  iconSize: number
  size: LinkSize
}>(({ theme, iconSize, size }) => {
  const lineHeight = Number.parseFloat(
    theme.designSystem.typography[getLinkTypography(size)].lineHeight
  )

  return {
    paddingTop: Math.max((lineHeight - iconSize) / 2, 0),
  }
})

const StyledText = styled.Text<{
  size: LinkSize
  textColor: ColorsType
}>(({ theme, size, textColor }) => ({
  ...theme.designSystem.typography[getLinkTypography(size)],
  color: textColor,
  flexShrink: 1,
  minWidth: 0,
  textDecorationLine: 'underline',
}))
