/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import userEvent from '@testing-library/user-event'
import React from 'react'

import { render, screen } from 'tests/utils/web'
import { theme } from 'theme'

import { Link } from './Link'

jest.mock('features/navigation/helpers/openUrl')

describe('<Link />', () => {
  it('should render an anchor with href', () => {
    render(<Link label="Documentation" externalNav={{ url: 'https://example.com' }} />)

    expect(
      screen.getByRole('link', { name: 'Nouvelle fenêtre\u00a0: Documentation' })
    ).toHaveAttribute('href', 'https://example.com')
  })

  it('should open external href in a new tab', () => {
    render(<Link label="Documentation" externalNav={{ url: 'https://example.com' }} />)

    const link = screen.getByRole('link')

    expect(link.closest('a')).toHaveAttribute('target', '_blank')
    expect(link).not.toHaveTextContent('ouvre un nouvel onglet')
    expect(screen.getByTestId('link-icon')).toBeInTheDocument()
  })

  it('should not open internal link in a new tab', () => {
    render(
      <Link
        label="Documentation"
        navigateTo={{ screen: 'TabNavigator', params: { screen: 'Home' } }}
      />
    )

    expect(screen.getByRole('link')).not.toHaveAttribute('target')
  })

  it('should call onBeforeNavigate when clicked', async () => {
    const onBeforeNavigate = jest.fn()
    render(
      <Link
        label="Documentation"
        externalNav={{ url: 'https://example.com' }}
        onBeforeNavigate={onBeforeNavigate}
      />
    )

    await userEvent.click(screen.getByRole('link'))

    expect(onBeforeNavigate).toHaveBeenCalledTimes(1)
  })

  it('should use link extra small typography when size is extraSmall', () => {
    render(
      <Link label="Documentation" externalNav={{ url: 'https://example.com' }} size="extraSmall" />
    )

    expect(screen.getByTestId('link-label')).toHaveStyle({
      fontFamily: theme.designSystem.typography.linkXs.fontFamily,
      lineHeight: theme.designSystem.typography.linkXs.lineHeight,
    })
  })

  it('should use neutral color when color is neutral', () => {
    render(
      <Link label="Documentation" externalNav={{ url: 'https://example.com' }} color="neutral" />
    )

    expect(screen.getByTestId('link-label')).toHaveStyle({
      color: theme.designSystem.color.text.default,
    })
  })

  it('should hide icon when showIcon is false and link does not open in a new tab', () => {
    render(
      <Link
        label="Documentation"
        navigateTo={{ screen: 'TabNavigator', params: { screen: 'Home' } }}
        showIcon={false}
      />
    )

    expect(screen.queryByTestId('link-icon')).not.toBeInTheDocument()
  })
})
