/**
 ⚠️ Design System — Protected file
 Do not edit this file without prior approval from the Design System team.
 */

import {
  ExternalTouchableLinkProps,
  InternalTouchableLinkProps,
} from 'ui/components/touchableLink/types'

export type LinkSize = 'default' | 'small' | 'extraSmall'
export type LinkColor = 'brand' | 'neutral'

type LinkBaseProps = {
  label: string
  size?: LinkSize
  color?: LinkColor
  showIcon?: boolean
  accessibilityLabel?: string
  testID?: string
}

export type LinkProps = LinkBaseProps &
  (Omit<ExternalTouchableLinkProps, 'children'> | Omit<InternalTouchableLinkProps, 'children'>)
