import { SearchResponse } from '@algolia/client-search'
import { Offer } from 'shared/offer/types'

export const mockedFacets: SearchResponse<Offer> = {
  hits: [],
  page: 0,
  nbHits: 0,
  nbPages: 1,
  hitsPerPage: 25,
  processingTimeMS: 1,
  exhaustiveNbHits: true,
  query: '',
  params: '',
  facets: {
    'offer.musicType': {
      'Hip-Hop/Rap': 15,
      Rock: 12,
      Pop: 10,
      Jazz: 6,
      Classique: 3,
      Reggae: 3,
      Punk: 2,
      Autre: 1,
      'Chansons / Variétés': 1,
      Electro: 1,
      Metal: 1,
    },
    'offer.bookMacroSection': {
      Loisirs: 7,
      'Littérature française': 6,
      'Religions, spiritualitées': 5,
      Manga: 3,
      Policier: 3,
      'Sciences, vie & Nature': 3,
      'Bandes dessinées': 2,
      Histoire: 2,
      Jeunesse: 2,
      Droit: 1,
      'Gestion/entreprise': 1,
      Jeux: 1,
      'Marketing et audio-visuel': 1,
      'Poèsie, théâtre et spectacle': 1,
      'Scolaire & Parascolaire': 1,
      Sport: 1,
      Tourisme: 1,
    },
    'offer.nativeCategoryId': {
      LIVRES_PAPIER: 4494,
      CD_VINYLES: 78,
      ACHAT_LOCATION_INSTRUMENT: 64,
      ABONNEMENTS_MUSEE: 55,
      DVD_BLU_RAY: 54,
      PRATIQUES_ET_ATELIERS_ARTISTIQUES: 51,
      FILMS_SERIES_EN_LIGNE: 30,
      LIVRES_NUMERIQUE_ET_AUDIO: 23,
      JEUX_EN_LIGNE: 11,
      MUSIQUE_EN_LIGNE: 10,
      CARTES_CINEMA: 7,
      PRESSE_EN_LIGNE: 6,
      VISITES_CULTURELLES: 5,
      CONCERTS_EVENEMENTS: 3,
      DEPRECIEE: 1,
      PRATIQUE_ARTISTIQUE_EN_LIGNE: 1,
    },
  },
}
