name: '1 [on_pull_request] Deploy PR version to Firebase for preview'

on:
  pull_request:
    branches:
      - PC-*

permissions:
  contents: read
  id-token: write

jobs:
  deploy_on_firebase:
    name: Deploy PR version to Firebase
    uses: ./.github/workflows/on_workflow_pr_preview.yml
    with:
      ENV: 'testing'
      PUSH_RELEASE_TO_SENTRY: false
      CHANNEL: 'preview'
      REF: '${{ github.ref }}'
      CACHE_BUCKET_NAME: 'passculture-metier-ehp'
    secrets:
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
