name: '1 [on_pr] Deploy PR version to Firebase for preview'

on:
  pull_request:
    branches:
      - 'PC-*'
  label:
    types:
      - created
      - edited
      - deleted

permissions:
  contents: read
  id-token: write

jobs:
  deploy_on_firebase:
    if: ${{ github.event.label.name == 'preview' }}
    name: Deploy PR version to Firebase
    uses: ./.github/workflows/on_workflow_pr_preview.yml
    with:
      ENV: 'testing'
      PUSH_RELEASE_TO_SENTRY: false
      CHANNEL: 'preview'
      REF: '${{ github.ref }}'
      CACHE_BUCKET_NAME: 'passculture-metier-ehp'
    secrets:
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
