name: '[OPS] Test authentification'

on:
  push:
    branches:
      - chore/use-new-sa-and-github-envs

permissions:
  id-token: write
  contents: read

jobs:
  authenticate:
    runs-on: ubuntu-24.04
    environment:
      name: app-native-testing
    permissions:
      contents: read
      id-token: write  # required for OIDC

    steps:
      - name: Checkout ref
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Authentification to Google
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PRD }}
          service_account: ${{ vars.APP_NATIVE_CI_SERVICE_ACCOUNT_EMAIL }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1

      - name: Check authenticated account
        run: gcloud auth list

      - name: Show old SA and list its IAM roles
        run: |
          echo "Old SA: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}"
          gcloud projects get-iam-policy ${{ vars.PROJECT_ID }} \
            --flatten="bindings[].members" \
            --filter="bindings.members=serviceAccount:${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}" \
            --format="table(bindings.role)"

      - name: List secrets from Secret Manager
        run: gcloud secrets list --project ${{ vars.PROJECT_ID }}

      - name: Create service account key
        run: |
          gcloud iam service-accounts keys create temporary-sa-key.json \
            --iam-account=${{ vars.APP_NATIVE_CI_SERVICE_ACCOUNT_EMAIL }} \
            --project=${{ vars.PROJECT_ID }}

      - name: Authenticate with service account key
        run: |
          gcloud auth activate-service-account \
            --key-file=temporary-sa-key.json
          gcloud auth list

      - name: List secrets from Secret Manager (SA key)
        run: gcloud secrets list --project ${{ vars.PROJECT_ID }}

      - name: Delete service account key
        if: always()
        run: |
          KEY_ID=$(jq -r .private_key_id temporary-sa-key.json)
          gcloud iam service-accounts keys delete "$KEY_ID" \
            --iam-account=${{ vars.APP_NATIVE_CI_SERVICE_ACCOUNT_EMAIL }} \
            --project=${{ vars.PROJECT_ID }} \
            --quiet
          rm -f temporary-sa-key.json
