name: '[Nightly] Run E2E tests on Android'

on:
  schedule:
    # 6:00 AM Paris time in UTC (Monday to Friday)
    - cron: '0 6 * * 1-5'

permissions:
  contents: read
  id-token: write

jobs:
  e2e-tests-android:
    uses: ./.github/workflows/dev_on_workflow_call_e2e_android.yml
    secrets:
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
