name: '3 [on_pr] Check if missing variables in env files'

on:
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run script to check if missing variables in env files
        run: python3 ./scripts/check_missing_variables_in_env_files_diff.py
