name: '2 [pull/pr] Initiate workflow'

on:
  push:

permissions:
  contents: read
  id-token: write

jobs:
  deploy-web-testing:
    uses: ./.github/workflows/dev_on_workflow_web_deploy.yml
    with:
      ENV: perf
      BUCKET_NAME: passculture-metier-ehp-testing-decliweb
      CACHE_BUCKET_NAME: passculture-infra-prod-github-runner-cache
    secrets:
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
