name: "2 [pull/pr] Initiate workflow"

on:
  push:

permissions:
  contents: read
  id-token: write

jobs:
  yarn-install:
    uses: ./.github/workflows/dev_on_workflow_install.yml
    with:
      CACHE_BUCKET_NAME: passculture-infra-prod-github-runner-cache
    secrets:
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
  deploy-web-proxy-perf:
    needs: [yarn-install]
    uses: ./.github/workflows/dev_on_workflow_web_proxy_deploy.yml
    with:
      ENV: perf
      CACHE_BUCKET_NAME: passculture-infra-prod-github-runner-cache
    secrets:
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
