name: 'E2E Web SmokeTest'

on:
  push:

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  run_e2e_web:
    name: 'Smoke test Staging Web'
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.3
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e #v6.4.0
        with:
          node-version-file: '.nvmrc'
      - uses: pass-culture/common-workflows/actions/setup-safe-chain@5715b432e91814bc6ab6725ff10abf3b81d5f8d1 # safe-chain-setup/v1.3.3
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae #v5.0.5
        id: yarn-modules-cache
        with:
          path: |
            node_modules
            ~/.cache/yarn
          key: v1-yarn-dependency-cache-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            v1-yarn-dependency-cache-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn install
        run: yarn install

      - name: Authentification to Google
        uses: 'google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093' # v3.0.0
        with:
          workload_identity_provider: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}

      - name: Get secrets for Maestro
        id: maestro_secrets
        uses: google-github-actions/get-secretmanager-secrets@bc9c54b29fdffb8a47776820a7d26e77b379d262 #v3.0.0
        with:
          secrets: |-
            MAESTRO_PASSWORD:passculture-metier-ehp/passculture-app-native-e2e-maestro-password
            MAESTRO_CLOUD_API_KEY:passculture-metier-ehp/passculture-app-native-e2e-maestro-cloud-api-key
            MAESTRO_E2E_API_KEY:passculture-metier-ehp/pcapi-staging_e2e_api_key
            MAESTRO_E2E_ENDPOINT:passculture-metier-ehp/pcapi-staging-e2e-endpoint

      - name: Determine latest Maestro version
        run: |
          MAESTRO_VERSION="$(curl -s https://api.github.com/repos/mobile-dev-inc/maestro/releases/latest | grep tag_name | cut -d '"' -f4 | sed 's/^cli-//;s/^v//')"
          echo "MAESTRO_VERSION=$MAESTRO_VERSION" >> "$GITHUB_ENV"

      - name: Cleanup Maestro CLI
        run: |
          echo "Cleaning up any previous Maestro CLI installation..."
          rm -rf "$HOME/.maestro"

      - name: Install latest Maestro CLI
        run: |
          echo "Installing Maestro CLI version ${MAESTRO_VERSION}..."
          curl --location --silent "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> "$GITHUB_PATH"
          export PATH="$HOME/.maestro/bin:$PATH"
          maestro --version
        env:
          MAESTRO_VERSION: ${{ env.MAESTRO_VERSION }}

      - name: Start a web staging server
        run: yarn start:web:staging --host > /dev/null 2>&1 &

      - name: Run Maestro E2E Web Tests
        env:
          MAESTRO_PASSWORD: ${{ steps.maestro_secrets.outputs.MAESTRO_PASSWORD }}
          MAESTRO_CLOUD_API_KEY: ${{ steps.maestro_secrets.outputs.MAESTRO_CLOUD_API_KEY }}
          MAESTRO_E2E_API_KEY: ${{ steps.maestro_secrets.outputs.MAESTRO_E2E_API_KEY }}
          MAESTRO_E2E_ENDPOINT: ${{ steps.maestro_secrets.outputs.MAESTRO_E2E_ENDPOINT }}
          MAESTRO_VALID_IOS_EMAIL: dev-tests-e2e-ios@passculture.team
          MAESTRO_VALID_ANDROID_EMAIL: dev-tests-e2e-android@passculture.team
          MAESTRO_INVALID_EMAIL: dev-tests-e2e-invalid@passculture.team
          MAESTRO_UNREGISTERED_EMAIL: dev-tests-unregistered+e2e@passculture.team
          MAESTRO_RUN_TRACKING_TESTS: false
          MAESTRO_RUN_CLOUD_COMMANDS: false
          MAESTRO_DRIVER_STARTUP_TIMEOUT: 60000
        run: |
          echo "Running Maestro tests from your branch on web Staging build"
          export PATH="$HOME/.maestro/bin:$PATH"
          yarn test:e2e:web:staging --headless

  slack_notify:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    if: always()
    needs: run_e2e_web
    steps:
      - name: Connect to Secret Manager
        uses: 'google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093' # v3.0.0
        with:
          workload_identity_provider: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
      - name: Get secrets for Slack
        id: 'slack_secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@bc9c54b29fdffb8a47776820a7d26e77b379d262' #v3.0.0
        with:
          secrets: |-
            SLACK_BOT_TOKEN:passculture-metier-ehp/passculture-ci-slack-bot-token
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c #v3.0.3
        with:
          # channel #equipe-e2e-jeunes
          method: chat.postMessage
          token: ${{ steps.slack_secrets.outputs.SLACK_BOT_TOKEN }}
          payload: |
            channel: 'C05MH81G9LY'
            text: "Le smoke test Web sur la branche `${{ github.ref_name }}` a ${{ fromJSON('["réussi :rocket:", "échoué :boom:"]')[(needs.run_e2e_web.result == 'failure') && 1 || 0] }}"
            attachments: [
                  {
                      "mrkdwn_in": ["text"],
                      "color": "${{ fromJSON('["#36a64f", "#A30002"]')[(needs.run_e2e_web.result == 'failure') && 1 || 0] }}",
                      "author_name": "${{github.actor}}",
                      "author_link": "https://github.com/${{github.actor}}",
                      "author_icon": "https://github.com/${{github.actor}}.png",
                      "title": "SMOKETEST E2E-WEB",
                      "title_link": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
                  }
            ]
            unfurl_links: false
            unfurl_media: false
