name: '[Nightly] Run E2E tests on iOS'

on:
  schedule:
    # 11:00 PM Paris time in UTC (Monday to Friday)
    - cron: '0 23 * * 1-5'

permissions:
  contents: read
  id-token: write

jobs:
  e2e-tests-ios:
    uses: ./.github/workflows/dev_on_workflow_call_e2e_ios.yml
    secrets:
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
