name: Check proxy version

on:
  workflow_call:
    outputs:
      proxy_version:
        value: ${{ jobs.check-proxy-version.outputs.proxy_version }}


jobs:
  check-proxy-version:
    name: Check proxy version
    runs-on: [self-hosted, linux, x64]
    outputs:
      version: ${{ steps.proxy-version.outputs.version }}
    steps:
      - id: staging-proxy-version
        if: startsWith(github.ref, 'refs/tags/patch') || startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "proxy_env=staging" >> $GITHUB_OUTPUT
      - id: production-proxy-version
        if: startsWith(github.ref, 'refs/tags/prod-hard-deploy') || startsWith(github.ref, 'refs/tags/hotfix-production')
        run: |
          echo "proxy_env=production" >> $GITHUB_OUTPUT
      - id: proxy-version
        name: Get proxy version
        run: |
          if [[ ${{ steps.staging-proxy-version.outputs.proxy_env == 'staging' }} ]]; then
            echo proxy_version=$(curl -sS https://app.staging.passculture.team/version.txt) >> $GITHUB_OUTPUT
          elif [[ ${{ steps.production-proxy-version.outputs.proxy_env == 'production' }} ]]; then
            echo proxy_version=$(curl -sS https://passculture.app/version.txt) >> $GITHUB_OUTPUT
          else
            echo proxy_version='' >> $GITHUB_OUTPUT
          fi
