name: Build and deploy storybook to Github Pages

on:
  push:
    branches:
      - deploy-storybook-to-github-pages
      # - master

env:
  BUILD_DIR: /tmp/${{ github.sha }}

jobs:
  build-and-deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Build Storybook
        run: yarn build-storybook --output-dir $BUILD_DIR
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
      - name: Get Storybook URL
        run: echo "Storybook URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
