name: '4 [on_workflow] Deploy web proxy'

on:
  workflow_call:
    inputs:
      ENV:
        type: string
        required: true
      CACHE_BUCKET_NAME:
        type: string
        required: true
    secrets:
      GCP_EHP_SERVICE_ACCOUNT:
        required: true
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER:
        required: true

jobs:
  web_proxy_deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    environment:
      name: app-native-${{ inputs.ENV }}
    steps:
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.3
      - name: Set up Cloud SDK to get gsutils
        uses: 'google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db' #v3.1.0
        with:
          version: '>= 416.0.0'
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e #v6.4.0
        with:
          node-version-file: 'server/.nvmrc'
      - uses: pass-culture/common-workflows/actions/setup-safe-chain@5715b432e91814bc6ab6725ff10abf3b81d5f8d1 # safe-chain-setup/v1.3.3
      - id: gcloud-auth
        name: 'OpenID Connect Authentication'
        uses: 'google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093' # v3.0.0
        with:
          cleanup_credentials: false
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PRD }}
          service_account: ${{ vars.NATIVE_DEPLOYER_SERVICE_ACCOUNT }}
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db' #v3.1.0
      - name: Cache the proxy node_modules
        id: yarn-modules-cache-proxy
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae #v5.0.5
        with:
          path: |
            node_modules
            ~/.cache/yarn
          key: v1-yarn-proxy-dependency-cache-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            v1-yarn-proxy-dependency-cache-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install app dependencies
        run: yarn install
      - name: Install packages for proxy
        run: cd server && yarn install && cd ..
      - name: Get Secret
        id: 'secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@bc9c54b29fdffb8a47776820a7d26e77b379d262' #v3.0.0
        with:
          secrets: |-
            SENTRY_AUTH_TOKEN:passculture-metier-ehp/pcapi-native-sentry-saas-token
      #      - name: Switch to google prod account for prod
      #        if: ${{ inputs.ENV == 'production' }}
      #        uses: 'google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093' # v3.0.0
      #        with:
      #          workload_identity_provider: ${{ secrets.GCP_PROD_WORKLOAD_IDENTITY_PROVIDER }}
      #          service_account: ${{ secrets.GCP_PROD_SERVICE_ACCOUNT }}

      - name: Cleanup .yarn cache
        run: rm -rf server/.yarn/cache

      - name: Push proxy for input env
        env:
          ENV: ${{ inputs.ENV }}
          CLOUDSDK_CORE_PROJECT: ${{ vars.WEB_PROXY_GCP_PROJECT_ID }}
        run: cd server && yarn run "deploy:$ENV" && cd ..

      - name: Clear unused apps
        env:
          ENV: ${{ inputs.ENV }}
          CLOUDSDK_CORE_PROJECT: ${{ vars.WEB_PROXY_GCP_PROJECT_ID }}
        run: |
          gcloud app versions list --service="web-proxy-$ENV" --format="table[no-heading](id)" \
            | grep -v "$(gcloud app versions list --service="web-proxy-$ENV" --hide-no-traffic --format="table[no-heading](id)")" \
            | xargs gcloud app versions delete --service="web-proxy-$ENV"
  slack_notify:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    if: ${{ always() && (contains(needs.web_proxy_deploy.result, 'success') || contains(needs.web_proxy_deploy.result, 'failure'))}}
    needs: web_proxy_deploy
    steps:
      - name: Connect to Secret Manager
        uses: 'google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093' # v3.0.0
        with:
          workload_identity_provider: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
      - name: Get secrets for Slack
        id: 'slack_secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@bc9c54b29fdffb8a47776820a7d26e77b379d262' #v3.0.0
        with:
          secrets: |-
            SLACK_BOT_TOKEN:passculture-metier-ehp/passculture-ci-slack-bot-token
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c #v3.0.3
        with:
          # channel #alertes-deploiement-native
          method: chat.postMessage
          token: ${{ steps.slack_secrets.outputs.SLACK_BOT_TOKEN }}
          payload: |
            channel: 'C0309RP8K42'
            text: "Le déploiement Web proxy sur `${{ inputs.ENV }}` a ${{ fromJSON('["réussi :rocket:", "échoué :boom:"]')[(needs.web_proxy_deploy.result == 'failure') && 1 || 0] }}"
            attachments: [
              {
                "mrkdwn_in": ["text"],
                "color": "${{ fromJSON('["#36a64f", "#A30002"]')[(needs.web_proxy_deploy.result == 'failure') && 1 || 0] }}",
                "author_name": "${{github.actor}}",
                "author_link": "https://github.com/${{github.actor}}",
                "author_icon": "https://github.com/${{github.actor}}.png",
                "title": "PCAPPNATIVE Deployment",
                "title_link": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
              }
            ]
            unfurl_links: false
            unfurl_media: false
