name: '4 [on_workflow] Build, test and deploy storybook with Chromatic'

on:
  workflow_call:
    secrets:
      CHROMATIC_PROJECT_TOKEN:
        required: true

env:
  BUILD_DIR: /tmp/${{ github.sha }}

jobs:
  yarn_test_and_publish_storybook_with_chromatic:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.3
      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e #v6.4.0
        with:
          node-version-file: '.nvmrc'
      - uses: pass-culture/common-workflows/actions/setup-safe-chain@5715b432e91814bc6ab6725ff10abf3b81d5f8d1 # safe-chain-setup/v1.3.3
      - name: Restore git history for Chromatic
        run: |
          if git rev-parse --is-shallow-repository; then
            git fetch --unshallow
          fi
          git fetch --all
      - name: Install dependencies
        run: yarn install
      - name: Install Playwright Browsers
        run: npx playwright install chromium
      - name: Build Storybook 🔧
        run: yarn build-storybook --stats-json --output-dir "$BUILD_DIR"
      - name: Publish to Chromatic 🚀
        uses: chromaui/action@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: ${{ env.BUILD_DIR }}
          onlyChanged: true
      - name: Run axe storybook accessibility tests 🧪
        run: yarn axe-storybook --build-dir "$BUILD_DIR"
