name: '1 [on_pr] Deploy PR version to Firebase for preview'

on:
  pull_request:
    branches: [master]
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: read
  id-token: write

jobs:
  deploy_on_firebase:
    if: contains(github.event.pull_request.labels.*.name, 'preview')
    name: Deploy PR version to Firebase
    uses: ./.github/workflows/dev_on_workflow_pr_preview.yml
    with:
      ENV: 'testing'
      SOURCE_BRANCH: '${{ github.ref }}'
    secrets:
      PASSCULTURE_GITHUB_ACTION_APP_ID: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_ID }}
      PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY }}
