name: Tests e2e iOS Safari

on:
  workflow_dispatch:
    inputs:
      tbd:
        description: "tbd"
        required: false
        type: string


jobs:
  e2e-ios-safari:
    strategy:
      matrix:
        include:
          - osVersion: '15.2'
            os: 'iOS'
            model: 'iPhone 13'
    env:
      CI: true
      APPIUM_TEST_SERVER_PORT: 4723
      APPIUM_TEST_SERVER_HOST: 0.0.0.0
      APPIUM_STARTUP_TIMEOUT_SEC: 30
      _FORCE_LOGS: 1
    runs-on: dka-mac
    steps:
      - uses: actions/checkout@v3

      - name: Install Haxm on MacOS
        run: brew install --cask intel-haxm

      - name: Install ffmpeg session on MacOS
        run: brew install ffmpeg

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: futureware-tech/simulator-action@v2
        with:
          model: ${{ matrix.model }}
          os: ${{ matrix.os }}
          os_version: ${{ matrix.os_version }}
      - run: yarn install
      - run: |
          npm config set legacy-peer-deps true
          npm install -g appium@next
          npm install -g appium-doctor
        name: Install dev dependencies
      - run: |
          cwd=$(pwd)
          pushd "$cwd"
          cd ~
          appium driver install xcuitest
          appium driver install safari
          appium-doctor
          nohup appium server \
            --port=$APPIUM_TEST_SERVER_PORT \
            --address=$APPIUM_TEST_SERVER_HOST \
            --relaxed-security \
            2>&1 > "$cwd/appium.log" &
          popd
        name: Start Appium server
      - run: |
          seconds_started=$(date +%s)
          while ! nc -z $APPIUM_TEST_SERVER_HOST $APPIUM_TEST_SERVER_PORT; do
            sleep 0.1
            seconds_elapsed=$(( $(date +%s) - seconds_started ))
            if [[ $seconds_elapsed -gt $APPIUM_STARTUP_TIMEOUT_SEC ]]; then
              echo "Appium server was unable to start within $APPIUM_STARTUP_TIMEOUT_SEC seconds timeout"
              exit 1
            fi
          done
        name: Wait for Appium server startup
      - run: |
          xcrun xctrace list devices

      - run: IOS_DEVICE_NAME="iPhone 13" IOS_PLATFORM_VERSION=15.2 yarn ios.browser
        name: Run functional tests
      - name: Save server output
        if: ${{ always() }}
        uses: actions/upload-artifact@master
        with:
          name: appium.log
          path: appium.log
      - name: Show appium server output
        if: ${{ always() }}
        run: cat appium.log
