name: Tests e2e Desktop Chrome

on:
  workflow_dispatch:
    inputs:
      tbd:
        description: "tbd"
        required: false
        type: string

jobs:
  tbd:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World"
