name: Tests e2e Android Chrome

on:
  workflow_dispatch:
    inputs:
      tbd:
        description: "tbd"
        required: false
        type: string

jobs:
  e2e-android-chrome:
    strategy:
      matrix:
        include:
#          - chromedriverVersion: "74.0.3729.6"
#            apiLevel: 30
#            emuTag: google_apis
          - chromedriverVersion: "74.0.3729.6"
            apiLevel: 29
            emuTag: google_apis
    #          - chromedriverVersion: "2.44"
    #            apiLevel: 28
    #            emuTag: default
    #          - chromedriverVersion: "2.28"
    #            apiLevel: 25
    #            emuTag: default
    #          - chromedriverVersion: "2.20"
    #            apiLevel: 23
    #            emuTag: default

    env:
      CI: true
      ANDROID_AVD: Nexus6P
      APPIUM_TEST_SERVER_PORT: 4723
      APPIUM_TEST_SERVER_HOST: 0.0.0.0
      _FORCE_LOGS: 1
    # No hardware acceleration is available for emulators on Ubuntu:
    # https://github.com/marketplace/actions/android-emulator-runner#can-i-use-this-action-on-linux-vms
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: yarn install
      - run: |
          mkdir apps
          wget https://github.com/webdriverio/native-demo-app/releases/download/v0.4.0/Android-NativeDemoApp-0.4.0.apk -P apps
      - run: |
          npm config set legacy-peer-deps true
          npm install -g appium@next
          npm install --chromedriver_version="${{ matrix.chromedriverVersion }}"
          npm install --no-save mjpeg-consumer
        name: Install dev dependencies
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: |
          cwd=$(pwd)
          pushd "$cwd"
          cd ~
          appium driver install uiautomator2
          nohup appium server \
            --port=$APPIUM_TEST_SERVER_PORT \
            --address=$APPIUM_TEST_SERVER_HOST \
            --relaxed-security \
            2>&1 > "$cwd/appium.log" &
          popd
        name: Start Appium server
      - run: nohup adb logcat > logcat.log &
        name: Capture logcat
      - uses: reactivecircus/android-emulator-runner@v2
        name: e2e_api${{ matrix.apiLevel }}
        with:
          script: yarn android.browser
          avd-name: ${{ env.ANDROID_AVD }}
          sdcard-path-or-size: 1500M
          api-level: ${{ matrix.apiLevel }}
          disable-spellchecker: true
          target: ${{ matrix.emuTag }}
          arch: x86
          profile: Nexus 6P
      - name: Save logcat output
        if: ${{ always() }}
        uses: actions/upload-artifact@master
        with:
          name: logcat-api${{ matrix.apiLevel }}
          path: logcat.log
      - name: Save server output
        if: ${{ always() }}
        uses: actions/upload-artifact@master
        with:
          name: appium-api${{ matrix.apiLevel }}
          path: appium.log
