name: Check PR title format

on:
  pull_request:
    branches: [master]
    types:
      - opened
      - edited
      - synchronize

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: Slashgear/action-check-pr-title@v3.0.0
        with:
          regexp: '^(\(PC-[0-9]+\) )?(build|ci|docs|feat|fix|perf|refactor|test)\(\w+\): \w+'
