name: Overwrite some file

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      token:
        required: true
        type: string

env:
  GIT_CONFIG_EMAIL: PassCulture-SA@users.noreply.github.com
  GIT_CONFIG_NAME: ${{ github.actor }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout commit hash'
        uses: actions/checkout@v4
        with:
          ref: 'bsr-script-to-find-routes-used-in-code'
          token: ${{ github.event.inputs.token }}
      - name: 'Author'
        run: |
          git config --global user.email "$GIT_CONFIG_EMAIL"
          git config --global user.name "$GIT_CONFIG_NAME"

      - name: 'find used routes'
        run: |
          ./scripts/get_used_routes.sh ${{ github.event.inputs.version }}
      - name: 'Commit changes'
        run: |
          git add trace_routes.md
          git commit --message "Overwrite test.md file"
          git push
